### ISSUE TITLE
Error "Invalid tab index"

### ISSUE THREAD

**Issue by paulroho** [cyrus-and/chrome-remote-interface#100]
The script from the readme throws a "Invalid tab index" error in case developer tools are attached to the chrome instance:
Error: Invalid tab index
    at /Users/myuser/Projects/my-headless-chrome/node_modules/chrome-remote-interface/lib/chrome.js:178:28
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by cyrus-and** [comment]
Now we can argue about the effectiveness of the error message, but that's it, you just [cannot] connect to a tab which is already being inspected.

[cannot]: https://developer.chrome.com/devtools/docs/debugger-protocol#simultaneous

**Comment by paulroho** [comment]
Cool, thank you for the quick improvement!
