### ISSUE TITLE
Question: similar projects but focused on integration tests

### ISSUE THREAD

**Issue by enapupe** [cyrus-and/chrome-remote-interface#101]
Hi there. I'd like to know if you guys know of any similar projects (that talk to Chrome Debugging Protocol) but have a focus on writing integration tests (such as Phantom, WebDriverIO).
You project is really nice and currently my best option to set up a e2e environment. Phantom uses Phantom (doh) and WebDriverIO talks to Selenium.
I think the ideal scenario is a tool that just talks to CDP, no dependencies.
I appreciate any hints you can give me. Thanks

**Comment by christian-bromann** [comment]
> WebDriverIO talks to Selenium

No, WebdriverIO talks to the browser driver which uses CDP to automate Webdriver actions.

> I think the ideal scenario is a tool that just talks to CDP, no dependencies.

I doubt that. How would you automate other browser or mobile devices then? Not all of them support CDP. There will always be some sort of driver necessary that can run the Webdriver commands in the browser.

**Comment by enapupe** [comment]
You are right. I forgot about diversity. 
It's funny that you answered both my questions. Thanks a lot.

**Comment by cyrus-and** [comment]
> I think the ideal scenario is a tool that just talks to CDP, no dependencies.

Probably, but not for now at least. If the trend to support the CDP continues to spread, eventually all the major browser implementation will implement the protocol (or a subset of it) either natively or via *adapters*, e.g., [edge-diagnostics-adapter] or [ios-webkit-debug-proxy]. At that point one could use as-is tools originally written for Chrome with any other browser. And you could use this project to do that, in this way you can abstract the low-level WebSocket communication and have a nice JavaScript API available.

Being the CDP quite low-level it would allow to write reasonably powerful tools like for example [Google Lighthouse], in fact, DevTools itself uses the CDP to inspect and debug pages. In this hypothetical future it may make sense to build complex integration test tools on top of the CDP.

Said that, it really depends on your use case but if you really care about diversity in your tests, you should probably look for more mature solutions.

[edge-diagnostics-adapter]: https://github.com/Microsoft/edge-diagnostics-adapter
[ios-webkit-debug-proxy]: https://github.com/google/ios-webkit-debug-proxy
[Google Lighthouse]: https://github.com/GoogleChrome/lighthouse
