### ISSUE TITLE
Is there a way to get the frameId from a Target

### ISSUE THREAD

**Issue by torbs** [cyrus-and/chrome-remote-interface#102]
I understand I must use Target to create new tabs in headless mode. Is there a way to get the frameId from a target without using `Page.navigate`?
```
client.Target.createTarget({
  url: `http://localhost:${config.get('httpServerPort')}`,
  width: 1200,
  height: 800,
})
.then((target) => {
   // ... target doesn't contain a frameId
})
```

**Comment by cyrus-and** [comment]
> I understand I must use Target to create new tabs in headless mode.

Not if you use Chrome version 59+, the issues listed in the [README] have been fixed in that release. This is the suggested solution.

Otherwise, I'm afraid you need to use something like:

```js
const CDP = require('chrome-remote-interface');

async function inspectNewTarget(width, height) {
    const target = 'ws://localhost:9222/devtools/browser';
    const client = await CDP({target});
    const {targetId} = await client.Target.createTarget({
        url: 'about:blank',
        width, height
    });
    await client.close();
    return CDP({
        target: (targets) => {
            return targets.find((target) => target.id === targetId);
        }
    });
}

inspectNewTarget(800, 600).then(async (client) => {
    const {Page} = client;
    const url = `http://localhost:${config.get('httpServerPort')}`;
    const frameId = await Page.navigate({url});
    console.log(frameId);
    client.close();
}).catch((err) => {
    console.error(err);
});
```

[README]: https://github.com/cyrus-and/chrome-remote-interface#headless

**Comment by torbs** [comment]
Thank you for the quick and thorough reply @cyrus-and. I'll have a follow up question.
If I use the frameId and try to create a new stylesheet. I'll get `Error: No target stylesheet found`.
If I don't use target (and headless) to create a new tab I don't get the error. 
BTW I'm still on the stable channel. I haven't tested this with Chrome 59, but I'll follow your proposal and switch to 59.
```
inspectNewTarget(800, 600).then(async (client) => {
    const { Page } = client;
    const url = `http://localhost:${config.get('httpServerPort')}`;
    const frame = await Page.navigate({ url });
    const stylesheet = await client.CSS.createStyleSheet({ frameId: frame.frameId })
    return client;
}).catch((err) => {
    console.error(err);
});
```

**Comment by cyrus-and** [comment]
That's because you need to enable the `DOM` and the `CSS` domains first:

```js
await DOM.enable();
await CSS.enable();
```

Yeah, I know, the documentation isn't particularly helpful.

> I haven't tested this with Chrome 59, but I'll follow your proposal and switch to 59.

It's a good idea since it will save you from writing some boilerplate code. If you're using a Debian-based distro you can simply install the `google-chrome-unstable` package.

**Comment by torbs** [comment]
Thank you for your help
