### ISSUE TITLE
Runtime.evaluate({expression:'console.log('aaa')'})

### ISSUE THREAD

**Issue by fh1994** [cyrus-and/chrome-remote-interface#105]
I can't get the right result because the SyntaxError.

How can I link other .js files by evaluate() function?

If i just put the whole js to the string in evaluate(),
first, it's too long. Then, it will make some SyntaxError just like that.

Thank u!

**Comment by pthieu** [comment]
`Runtime.evaluate({expression:'console.log(\'aaa\')'}'`
Or use `console.log("aaa")`.

You're quotes are cutting your string off early.

**Comment by fh1994** [comment]
Is it possible that linking to a . js file instead of the expression?

**Comment by pthieu** [comment]
Not sure, I was following https://github.com/cyrus-and/chrome-remote-interface/issues/97 with the generating of expression. Seems like it's possible to inject JS from comments in that issue.

**Comment by cyrus-and** [comment]
> Is it possible that linking to a . js file instead of the expression?

Nope, but there shouldn't be any issues with the length of the expression once that you fix your quotes as @pthieu said.

Anyway you can simply perform multiple calls of `Runtime.evaluate` one per file.

**Comment by fh1994** [comment]
got it
Thanks a lot
