### ISSUE TITLE
Question: frame/window size change

### ISSUE THREAD

**Issue by pthieu** [cyrus-and/chrome-remote-interface#108]
I'm looking up the chrome debugging protocol docs and seems like there's not really a way to change the viewport size?

There's `Emulation.setVisibleSize` (https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-setVisibleSize) but seems like it's `experimental` and doesn't affect the frame's container.

Looking at a way to do something like "change the width of the browser", doesn't have to be dynamic, can be set before we do any Page navigations. I read on another issue that you wouldn't use CDP for something like this, but I believe that was more of dynamical resizing of the browser window size.

Maybe `Emulation.forceViewport` (https://chromedevtools.github.io/debugger-protocol-viewer/tot/Emulation/#method-forceViewport)?

I've also tried `Emulation.setDeviceMetricsOverride`, but didn't seem to work.

I'm verifying by capturing screenshots, so maybe CDP works like PhantomJS where the screenshot viewport is not the same as frame viewport?

**Comment by cyrus-and** [comment]
> but seems like it's experimental

Big chunks of the protocols are marked as experimental, you shouldn't care too much.


Anyway, for issues concerning the protocol itself the [Google Group] may be a better place to ask.

[Google Group]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by auchenberg** [comment]
Try to open your issue here, https://github.com/ChromeDevTools/devtools-protocol/issues

**Comment by pthieu** [comment]
`Emulation.setDeviceMetricsOverride` worked, but had to play with config. Didn't seem like it was 100% working but maybe I just don't understand the docs. Had to set the `fitWindow` property to `true` to get the entire page in my screenshot.

**Comment by SerafinDinges** [comment]
@pthieu did you manage to save screenshots with the correct size?
Would you mind sharing that bit of code? I'm currently stuck at the same problem and seem to only get 1x1 px screenshots.

**Comment by cyrus-and** [comment]
@SerafinDinges maybe your problem is the same as #115?

**Comment by SerafinDinges** [comment]
We are currently using Chrome Beta (59.0.3071.47) and screenshots work fine directly via command line using `chrome --headless --disable-gpu --screenshot --window-size=1280,1696 https://www.chromestatus.com/`. Hence I suspect I am using the node commands wrong.

Is it possible that it would work in the command line but not via node?

I tried a bunch of different combinations going from the wiki here, but so far have only produced empty pixels as screenshots.

Current implementation with all the learnings (still doesn't work):
```javascript
await client.Emulation.setDeviceMetricsOverride({width: 1920, height: 1080, fitWindow: true, deviceScaleFactor: 1, mobile: false});

// navigate to url stuff here

const {data} = await client.Page.captureScreenshot();
const fs = require("fs");
fs.writeFileSync('scrot.png', Buffer.from(data, 'base64'));
```

Any help is appreciated.

**Comment by cyrus-and** [comment]
@SerafinDinges

> So I don't think it is related to #115?

That issue should be about Chrome version 60 on macOS or Windows.

> I rather suspect I am using the node commands wrong. Is it possible that it would work in the command line but not via node?

Yes, I don't think the former uses the Chrome Debugging Protocol.

Which OS are you using?

**Comment by pthieu** [comment]
@SerafinDinges: I did not. The screenshots were just for me to debug what was happening, I didn't actually need it for production. It was hard to see what was happening with the default screenshot size but I made out what I could and inferred any missing information for what I wanted to do.
