### ISSUE TITLE
HTTP Status?

### ISSUE THREAD

**Issue by ccoffee** [cyrus-and/chrome-remote-interface#113]
I can't seem to find where I can reliably capture the HTTP status code of the page or individual resources. I also cannot find any function mentioning in Runtime or Page functions.

Is there a method which I am just not seeing?

This seems like such a basic requirement it should be documented in the most basic example.

**Comment by cyrus-and** [comment]
The main example shows how to log requests using [`Network.requestWillBeSent`] while using [`Network.responseReceived`] you can do what you ask. As you can see it's the same domain, i.e.,  [`Network`]:

```js
Network.responseReceived((params) => {
    const {status, url} = params.response;
    console.log(`${status}: ${url}`);
});
```

[`Network`]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/
[`Network.requestWillBeSent`]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#event-requestWillBeSent
[`Network.responseReceived`]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#event-responseReceived
