### ISSUE TITLE
Abort requests

### ISSUE THREAD

**Issue by AntouanK** [cyrus-and/chrome-remote-interface#12]
Is there a way to abort certain requests? ( based on the url for example )
So we can block unnecessary ads and images loading in a "headless" browser...

There is the `requestWillBeSent` hook, but I didn't figure out any way to abort the request.

Thanks.

**Comment by cyrus-and** [comment]
This module is as powerful as the [Remote Debugging Protocol](https://developer.chrome.com/devtools/docs/protocol/1.1/index) (for a complete list of commands see the file `/lib/protocol.json` or use the REPL interface) and AFAIK Chrome offers no way to achieve what you want.

Alternatives may be blocking specific URLs using a Chrome extension or blocking specific domains using for example `/etc/hosts`.

**Comment by AntouanK** [comment]
I see.
Thanks for the response.
I thought of installing an extension, like uBlock or ABP, but I guess without a graphical interface ( the way I use it ) it's going to be a nightmare.
Maybe I can install it once and then save the "profile" directory across every chrome instance I launch.

**Comment by cyrus-and** [comment]
> Maybe I can install it once and then save the "profile" directory across every chrome instance I launch.

Exactly this!

**Comment by AntouanK** [comment]
Do you know if extensions are saved in there?
I haven't used that directory for anything so far, I always point to an empty one.

**Comment by cyrus-and** [comment]
To my knowledge an instrumented instance of Chrome behaves exactly as any other instance, so preferences, bookmarks, extensions, etc. are preserved.

**Comment by AntouanK** [comment]
I'm using it inside docker containers. So I'm thinking if I do the extension setup while running Chrome on an OSX or Ubuntu environment, just copying the profile directory might not be enough for the container.
I'll give it a try though.
Thanks.
