### ISSUE TITLE
printToPDF response data identical and renders blank

### ISSUE THREAD

**Issue by JoeChapman** [cyrus-and/chrome-remote-interface#120]
As the title says, when I invoke `printToPDF` with either a path to a file or a html data uri the response data - which is formatted as a PDF stream - is always the same,with the same content-length (921) and always renders blank. 

Node Version: v6.10.0
Chrome: https://store.docker.com/community/images/yukinying/chrome-headless

Example:
```js
    const chrome = require('chrome-remote-interface');

    return chrome().then(client =>
      client.Page.printToPDF(this._prepare()).then(result => {
        client.close();
        return return Buffer.from(result.data, 'base64');
      })
    );
```

**Comment by cyrus-and** [comment]
[`Page.printToPDF`] doesn't take any parameters, if you want to load an URL you have to do it before. See a [similar example] in the wiki.

[`Page.printToPDF`]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
[similar example]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Take-page-screenshot

**Comment by JoeChapman** [comment]
Thank you @cyrus-and. Does the uri need to be a fqdn, cannot be an internal, local file path?
Ideally it would accept data uri, is that on the cards?

**Comment by cyrus-and** [comment]
AFAIK the `url` parameter can be any URL, so even local files (`file://`) and data URIs (`data:`).

**Comment by cyrus-and** [comment]
Also related: #95

**Comment by JoeChapman** [comment]
Thank you for your quick response, really appreciated

**Comment by cyrus-and** [comment]
You're welcome!
