### ISSUE TITLE
Cannot connect to browser: TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by jdfx** [cyrus-and/chrome-remote-interface#121]
I apologise if I am doing something daft..

I have a working scraper setup using CDP and Chrome Canary Headless on windows via a NodeJS script running from another Non-Canary Chrome browser with Cors disabled. Fine.

Now, I have packaged that same NodeJS script into a command-line application expecting it to function just the same, but I get the error in the title.

Am I doing something fundamentally wrong in trying to package it into a nodeJS command line script or is there likely just a daft error?

Thanks in advance.

**Comment by cyrus-and** [comment]
Can you show me the stack trace?

**Comment by jdfx** [comment]
Sure, though I am having difficulty getting Node to output source-mapped errors on the commandline so it's not very helpful:

```
$ alpha-scraper
getPageContents: Cannot connect to browser: TypeError: Cannot read property 'protocol' of undefined
    at Object.s.request (D:\Projects\Homestead\projectalphascraper\dist\build.js:33238:31761)
    at Object.s.get (D:\Projects\Homestead\projectalphascraper\dist\build.js:33239:9)
    at n (D:\Projects\Homestead\projectalphascraper\dist\build.js:33240:19736)
    at r (D:\Projects\Homestead\projectalphascraper\dist\build.js:33238:6187)
    at D:\Projects\Homestead\projectalphascraper\dist\build.js:33238:8795
    at D:\Projects\Homestead\projectalphascraper\dist\build.js:33238:6340
    at Object.List (D:\Projects\Homestead\projectalphascraper\dist\build.js:33238:6314)
    at D:\Projects\Homestead\projectalphascraper\dist\build.js:33247:18006
    at t.c (D:\Projects\Homestead\projectalphascraper\dist\build.js:33247:17750)
    at t.s (D:\Projects\Homestead\projectalphascraper\dist\build.js:33247:17374)
```

I get the same error regardless of Canary headless running or not, so it's not getting that far. Malformed http header would seem to be the culprit? The code works in the browser however.

**Comment by cyrus-and** [comment]
AFAICT your setup should work, but since it doesn't, I have to understand where the error happens, can't you just run the non-minified version?

The only thing that's different in browser usage is that you provide a `criRequest` function, with Node.js instead the connection to the HTTP endpoint happens directly, try double-checking your `options` object.

**Comment by jdfx** [comment]
I will see if I can generate some more useful errors.

I need to run the built version as webpack is transpiling some ES6 stuff that Node can't handle yet but perhaps I can prettify the output at least.

**Comment by jdfx** [comment]
The error is occuring on this line of chrome-remote-interface.js

`var o = e.location.protocol.search(/^https?:$/) === -1 ? "http:" : "", s = t.protocol || o, p = t.hostname || t.host, c = t.port, d = t.path || "/";`

Although I can't find which file that is being compiled from.

I triple checked that I am not getting the same error in the browser with the exact same project and can confirm it runs in Chrome.

**Comment by cyrus-and** [comment]
Hm, but are you using `chrome-remote-interface.js` with Node.js? You aren't supposed to, that's for browser usage only.

**Comment by jdfx** [comment]
I simply did 

`npm install chrome-remote-interface`

and then 

`import CDP from 'chrome-remote-interface'`

I am then wrapping the entire build.js file in a node command using a shebang of 

`#!/usr/bin/env node`

I guess what I am trying to do is incorrect and not possible? If so I will just run the scraper from the browser and have done with it.

**Comment by cyrus-and** [comment]
I'm afraid you can't run a bundle which has been web-packed for the browser with Node.js because it's using objects that don't exist in a Node.js context, e.g., `location`.

See what happens if I try to list the available targets using the `chrome-remote-interface.js` file which comes with this module:

```console
$ node
> const CDP = require('./chrome-remote-interface.js')
undefined
> CDP.List(function () { console.log(arguments); })
TypeError: Cannot read property 'protocol' of undefined
    at Object.s.request (/tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:31755)
    at Object.s.get (/tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:2:9)
    at n (/tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:3:19736)
    at r (/tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:6181)
    at /tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:8789
    at Function.<anonymous> (/tmp/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:6373)
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
```

So if you already have a JavaScript application that successfully uses chrome-remote-interface **and** that does not use any other browser-specific feature then you can simply `import CDP from 'chrome-remote-interface'` as you do but then **do not** web-pack the application.

If you need some JavaScript features that are not yet part of the Node.js runtime (e.g., `import`) then just use [Babel].

Hope this helps.

[Babel]: https://babeljs.io/

**Comment by jdfx** [comment]
Thank you for your help.

I have it working now by removing webpack from the equation and just using babel-cli.

**Comment by cyrus-and** [comment]
Great, you're welcome!

**Comment by marcostoduto** [comment]
Hi! I have the same problem inside of react, i just copy and pasted your code corcerning print to pdf but i get the same error you've described here, how can i fix that?
