### ISSUE TITLE
Detecting invalid HTTPS certs

### ISSUE THREAD

**Issue by akleiner2** [cyrus-and/chrome-remote-interface#125]
Hi there! I've been digging through the CDP docs and through the codebase, and am not sure if there's a way to go about detecting if a `Page.navigate` call goes through to a page without a signed certification 
![image](https://cloud.githubusercontent.com/assets/5349500/25830840/b47ca8ea-3414-11e7-9a66-a30ba066de08.png). Right now, the call to `Page.navigate` just hangs at the page above, so I was curious if there's either something I'm missing or if you know of any workarounds. Thanks again so much!

**Comment by akleiner2** [comment]
Nevermind, hooking into `Security.certificateError` seems to do the trick 👍 . Closing this!

**Comment by jeethsuresh** [comment]
Hey, I'm having trouble with this - mind pasting a snippet?

**Comment by cyrus-and** [comment]
@jeethsuresh I've added a [recipe][1] to the wiki.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Bypass-certificate-errors-(%22Your-connection-is-not-private%22)

**Comment by jeethsuresh** [comment]
Much appreciated, thanks!
