### ISSUE TITLE
how to manipulate with tabs?

### ISSUE THREAD

**Issue by hbakhtiyor** [cyrus-and/chrome-remote-interface#127]
how to open tab, navigate url and close tab?

**Comment by cyrus-and** [comment]
Using [`CDP.New()`][1], [`client.Page.navigate()`][2] and [`CDP.Close()`][3].

All together:

```js
const CDP = require('chrome-remote-interface');

async function navigateInANewTab(url) {
    const tab = await CDP.New();
    const client = await CDP({tab});
    const {Page} = client;
    await Page.enable();
    await Page.navigate({url});
    await Page.loadEventFired();
    await CDP.Close({id: tab.id});
}

navigateInANewTab('https://github.com');
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpnewoptions-callback
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate
[3]: https://github.com/cyrus-and/chrome-remote-interface#cdpcloseoptions-callback

**Comment by hbakhtiyor** [comment]
@cyrus-and thanks,

Error: Could not create new page, i think [not](https://bugs.chromium.org/p/chromium/issues/detail?id=699392) in stable chrome release? 


What's the differences between `CDP.Close` and `client.close`?

**Comment by cyrus-and** [comment]
> Error: Could not create new page, i think not in stable chrome release?

Maybe related to #124?

As you can see from the doc:

- `CDP.Close` closes the chosen tab (and implicitly detach the client from it, if that tab was inspected);

- `client.close` detach the client from a currently inspected tab.

**Comment by hbakhtiyor** [comment]
thanks, which better `CDP.New({url})` or `Page.navigate({url})`?

**Comment by cyrus-and** [comment]
Not better, different. With the former you cannot keep track of the page load, e.g., registering events as I did in the above example.

**Comment by hbakhtiyor** [comment]
btw, how to handle errors for `CDP.New();` and `CDP({tab});` in the above example?

**Comment by cyrus-and** [comment]
As you usually do in JavaScript. Since `navigateInANewTab` is an `async` function which uses `await` to handle the promises you can either use a `try`/`catch` inside that function or handle the errors from outside:

```js
navigateInANewTab('https://github.com').then(() => {
    console.log('OK');
}).catch((err) => {
    console.error('ERROR', err);
})
```

You can even call it within a `try`/`catch` inside another `async` function...

**Comment by pthieu** [comment]
@cyrus-and: getting some problems on attaching to chrome on a remote machine. Seems to hang when I do `CDP.Close({id: tab.id})`. I checked the the ID at `http://host:port/json` of my server, and the ID matches.

I then run the exact same code, but point it to a local instance of chrome (same machine as script) and it works.

```
var tab = await CDP.New({
  host: CHROME_FE_HOST || 'localhost',
  port: CHROME_FE_PORT || 9222,
});
```

This is the only thing that's different.

**Comment by hbakhtiyor** [comment]
@pthieu 

need also pass the option to `Close` method

e.g.

```js
const options = {
  host: CHROME_FE_HOST || 'localhost',
  port: CHROME_FE_PORT || 9222,
};

var tab = await CDP.New(options);
...
do some stuff
...
await CDP.Close(Object.assign(options, {
  id: tab.id
}));
```

**Comment by pthieu** [comment]
@hbakhtiyor: options were applied to the tab upon creation of it though. It works on localhost but not on remote host.

**Comment by hbakhtiyor** [comment]
because default options are `localhost` and `9222`, since you're connecting to remote host, need to pass host and port to another methods too

**Comment by pthieu** [comment]
@hbakhtiyor 
host and port are passed in here:
```
const options = {
  host: CHROME_FE_HOST || 'localhost',
  port: CHROME_FE_PORT || 9222,
};
```

**Comment by hbakhtiyor** [comment]
hmm, it was clear, if you want to connect to remote host, you need to pass the option to another methods too, check the docs

**Comment by cyrus-and** [comment]
@pthieu, @hbakhtiyor yes *DevTools methods* such as List, New, etc. require the HTTP endpoint information as it's specified in the doc.

> It works on localhost but not on remote host.

Chrome will always listen on localhost meaning that you cannot attach to a Chome instance running on another host without some *tricks* (e.g., SSH tunnel).

**Comment by bootrino** [comment]
Suggest your reply "how to open tab, navigate url and close tab?" be added to wiki thanks.

**Comment by cyrus-and** [comment]
@bootrino [Inspect a new tab](https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab).
