### ISSUE TITLE
Page.captureScreenshot returning 'Unable to capture screenshot'

### ISSUE THREAD

**Issue by Mic75** [cyrus-and/chrome-remote-interface#128]
Hi,

With Canary (60.0.3100) running headless, on Windows 10, calling Page.captureScreenshot() returns a rejecting promise with : `{ error: { code: -32000, message: 'Unable to capture screenshot' } }` .

Starting the same build but without the --headless flag and calling `Page.captureScreenshot()` returns `undefined`.

I was wondering if this was a known issue and if this is the right place to report it  ?

**Comment by cyrus-and** [comment]
Yeah, it seems a [known issue][1].

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=714058

**Comment by cyrus-and** [comment]
This also happens on macOS and using `Page.captureScreenshot({fromSurface: true})` seems to be a possible workaround for this issue, you can give it a try.

**Comment by Mic75** [comment]
@cyrus-and thanks ! Like you said, using fromSurface flag makes the capture working !

**Comment by cyrus-and** [comment]
Possible duplicate: #115
