### ISSUE TITLE
how to debug popups?

### ISSUE THREAD

**Issue by DavidXanatos** [cyrus-and/chrome-remote-interface#130]
How can I debug popup windows of the page i open in the debugger?

**Comment by cyrus-and** [comment]
Using [`Page.handleJavaScriptDialog`][1], for example:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Runtime, Page} = client;
    // handle popup opening
    Page.javascriptDialogOpening(({message, type}) => {
        try {
            Page.handleJavaScriptDialog({accept: true});
            console.log(`${type}: ${message} -> accepted!`);
        } catch (err) {
            console.error(err);
        }
    });
    // trigger an alert message
    try {
        await Page.enable();
        await Runtime.evaluate({
            expression: `alert('click me!');`
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-handleJavaScriptDialog

**Comment by cyrus-and** [comment]
Uhm or maybe you mean *popup windows* as in `window.open(...)`? In that case it's just another target that you can inspect.

**Comment by DavidXanatos** [comment]
Yes I mean "popup windows as in window.open(...)"

I tryed to do:

            Target.setDiscoverTargets({discover: true});

            Target.targetCreated((params) => {
                console.log("Target Created: " + params.targetInfo.url + " (" + params.targetInfo.type + ")");

                if(params.targetInfo.type != "other")
                    return;

                Target.attachToTarget({targetId: params.targetInfo.targetId}).then(()=>{
                    console.log("Target Attached");
                })
            });

            Target.targetDestroyed((params) => {
                console.log("Target Destroyed");
            });

but it does not work, Network.responseReceived is not triggered for teh stuf loaded by the popup

**Comment by cyrus-and** [comment]
Ops, sorry about that...

You need to create a new client for that new target in order to inspect it and since the debugging URL is not returned by Chrome you need to search among the available targets:

```js
Target.targetCreated((params) => {
    if (params.targetInfo.type !== 'other') {
        return;
    }

    //////////
    const {targetId} = params.targetInfo;
    const findTarget = (targets) => {
        return targets.find(target => target.id === targetId);
    };
    CDP({target: findTarget}, (popup) => {
        // ...
    });
    //////////
});
```

AFAIK `Target.attachToTarget` is only useful to send raw commands using [`Target.sendMessageToTarget`][1].

Please let me know if this solves your problem.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-sendMessageToTarget

**Comment by DavidXanatos** [comment]
thank you very much,
I will try it out tomorrow or so :)

**Comment by cyrus-and** [comment]
FYI since [v0.23.0][1] you can just write `CDP({target: targetId}, ...)` and avoid the callback.

[1]: https://github.com/cyrus-and/chrome-remote-interface/releases/tag/v0.23.0

**Comment by jvilla32** [comment]
@cyrus-and When I run the first script that you replied with, I get an unhandled promise error:

alert: click me! -> accepted!
(node:57975) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not handle JavaScript dialog
(node:57975) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Do you know which part is creating a promise?
On another note, if you remove the Runtime.evaluate line, do you know how to make the program block until an alert comes along?

Thanks.

**Comment by cyrus-and** [comment]
@jvilla32

> Do you know which part is creating a promise?

The error handling is wrong there, it should be:

```js
// handle popup opening
Page.javascriptDialogOpening(async ({message, type}) => {
    try {
        await Page.handleJavaScriptDialog({accept: true});
        console.log(`${type}: ${message} -> accepted!`);
    } catch (err) {
        console.error(err);
    }
});
```

Edited the comment. Besides, it used to work, let me dig into it...

> On another note, if you remove the Runtime.evaluate line, do you know how to make the program block until an alert comes along?

Awaiting for the event, something like:

```js
const {message, type} = await Page.javascriptDialogOpening();
```

**Comment by jvilla32** [comment]
@cyrus-and 

Thanks for looking into it, it now seems to be catching an error rather than accepting the alert.

As for the awaiting, should this be in a while true loop, until I receive the {message, type} pair that I'm expecting?

**Comment by cyrus-and** [comment]
> Besides, it used to work, let me dig into it...

Well it does work in normal mode, this is possibly a bug with Chrome.

> As for the awaiting, should this be in a while true loop, until I receive the {message, type} pair that I'm expecting?

If you plan to handle more than one alert messages, yes. It really depends on how you want to structure your code, the original version uses event handling which is more suitable IMHO but the program flow of the *main* function doesn't *block* in this case. Please note that the Node.js process still keeps running though, if that's your concern; just don't call `client.close()` until you're done.

**Comment by cyrus-and** [comment]
> Well it does work in normal mode, this is possibly a bug with Chrome.

OK, it looks like Chrome is handling the dialog itself in headless mode, you can see that by registering for the `Page.javascriptDialogClosed` event. Still a bug IMHO.

**Comment by cyrus-and** [comment]
> Still a bug IMHO.

[Yep, it is.](https://bugs.chromium.org/p/chromium/issues/detail?id=718235)

**Comment by jvilla32** [comment]
Thanks for the clarity, looks like I'll be injecting an element into the DOM for signal.

**Comment by ouven** [comment]
> OK, it looks like Chrome is handling the dialog itself in headless mode, you can see that by registering for the `Page.javascriptDialogClosed` event. Still a bug IMHO.

I managed to unregister chromes headless handler before registering my own. 
```javascript
Page.javascriptDialogClosed(null)
```

**Comment by cyrus-and** [comment]
> > Still a bug IMHO.
> 
> [Yep, it is.](https://bugs.chromium.org/p/chromium/issues/detail?id=718235)

FYI it has been fixed now.

> Page.javascriptDialogClosed(null)

@ouven hmm, that's not how it works... there's no default Chrome handler.

**Comment by cyrus-and** [comment]
> For me this behavior still occurs in headless mode. (I'm using https://github.com/getgauge/taiko, which uses cri with chromium 73).

The [above code][1] now works even in headless mode so it's possibly another bug, please file it against Chrome.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/130#issuecomment-302952122

> OH no, I pasted the wrong clipboard position. I did `page.javascriptDialogOpening(null)` before registering my own callback to the opening event.

It's the `null` part I was referring to, that code is equivalent to `page.javascriptDialogOpening()` and registers a one-shot handler by returning a Promise, see the [doc][2].

[2]: https://github.com/cyrus-and/chrome-remote-interface#clientdomaineventcallback

**Comment by ouven** [comment]
Thank you! I will (need to) do further investigation.
