### ISSUE TITLE
Inspecting new tab

### ISSUE THREAD

**Issue by cungminh2710** [cyrus-and/chrome-remote-interface#133]
I followed the example in Wiki page: Inspect new tab
```
const CDP = require('chrome-remote-interface');

CDP.New().then((tab) => {
    return CDP({tab: tab});
}).then((client) => {
    return client.Runtime.evaluate({
        expression: 'alert("Closing this tab...")'
    }).then(() => {
        const tab = client.chooseTab;
        return CDP.Close({id: tab.id});
    });
}).catch((err) => {
    console.error(err);
});
```
I received an error `TypeError: Cannot read property 'id' of undefined`. It seems chooseTab is undefined.

**Comment by cyrus-and** [comment]
Yeah, that example is wrong, the fix is to use `client.target` instead of `client.chooseTab`.
I changed the example to reflect the most recent version of the API, thanks for reporting.
