### ISSUE TITLE
Wait for element to be present

### ISSUE THREAD

**Issue by saurabh2590** [cyrus-and/chrome-remote-interface#134]
I am trying to wait for an element to be present before proceeding with taking the screenshot for the given element. 
As of now I do this 
```
setTimeout(async function() {
            const {root: {nodeId: documentNodeId}} = await DOM.getDocument();
            const {nodeId: bodyNodeId} = await DOM.querySelector({
                selector: '#login-submit',
                nodeId: documentNodeId,
            });
          const screenshot = await Page.captureScreenshot({format});
          ......
   }, delay);
```
And then I have to pass the delay explicitly and hence it adds the overhead. Is there some explicit api exposed where I can wait for the element to be present before going for captureScreenshot command.

**Comment by cyrus-and** [comment]
Maybe using the [`DOM.childNodeInserted`][1] event? Give it a try and let me know.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-childNodeInserted

**Comment by paulirish** [comment]
One could argue that using `childNodeInserted` probably carries the same perf overhead issues as mutation events. I would try to avoid using it.

A slightly more friendly way would be to [evaluate asynchronously](https://github.com/GoogleChrome/lighthouse/blob/79d55c564af8c66f02b0eb137e1a126bd33cbf72/lighthouse-core/gather/driver.js#L225-L274) in the page and use a [mutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) + querySelector inside of there.

But..... This is all pretty awkward and tricky.. so until there was a higher level API for you to consume, I'd probably recommend sticking with your polling solution. haha. :)
cc @aslushnikov

**Comment by saurabh2590** [comment]
Hi Guys, Seems there was no alternative solution to achieve this. So in the end, i end up writing something like this.
```
const getElementBySelectorWait = async (querySelector: string, DOM: any, parentNodeId: number, waitTime: number) => {
    let startTime = 0;
    let elementNodeId = await getElementBySelector(querySelector, DOM, parentNodeId);
    while (elementNodeId.nodeId === 0 && startTime < waitTime) {
        await sleep(10);
        startTime = startTime + 10;
        elementNodeId = await getElementBySelector(querySelector, DOM, parentNodeId);
    }
    return elementNodeId;
}

const getElementBySelector = async (querySelector: string, DOM: any, parentNodeId: number) => {
    try {
        return await DOM.querySelector({selector: querySelector, nodeId: parentNodeId});
    } catch (error) {
        console.log("Cannot find the element yet", error);
        return null;
    }
}
```
and calling these functions as 
```
const {nodeId: formNodeId} = await getElementBySelectorWait('.form', DOM, documentNodeId, 2000);
```
Some aspects are still not clear that when failing to find the node, shall I return `null` or shall I return the `{nodeId: 0}`.  As far as I can see, when I waiting for the element to appear, I get `{nodeId: 0}` so probably I will also return that instead of null.

**Comment by cyrus-and** [comment]
By following the advice of @paulirish, here's another attempt using a [`MutationObserver`][1]. You may want to tune it a bit but I think the general idea is pretty clear.

```js
const CDP = require('chrome-remote-interface');

async function nodeAppears(client, selector) {
    // browser code to register and parse mutations
    const browserCode = (selector) => {
        return new Promise((fulfill, reject) => {
            new MutationObserver((mutations, observer) => {
                // add all the new nodes
                const nodes = [];
                mutations.forEach((mutation) => {
                    nodes.push(...mutation.addedNodes);
                });
                // fulfills if at least one node matches the selector
                if (nodes.find((node) => node.matches(selector))) {
                    observer.disconnect();
                    fulfill();
                }
            }).observe(document.body, {
                childList: true
            });
        });
    };
    // inject the browser code
    const {Runtime} = client;
    await Runtime.evaluate({
        expression: `(${browserCode})(${JSON.stringify(selector)})`,
        awaitPromise: true
    });
}

function demo() {
    setTimeout(() => {
        const foo = document.createElement('div');
        foo.id = 'foo';
        foo.innerText = 'foo';
        document.body.appendChild(foo);
    }, 3000);
}

CDP(async (client) => {
    const {Runtime} = client;
    try {
        // will add div
        await Runtime.evaluate({
            expression: `(${demo})()`
        });
        // wait for the element to be present
        await nodeAppears(client, 'div#foo');
        console.log('OK');
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

[1]: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by cyrus-and** [comment]
@saurabh2590 I think I can close this as you now have a few alternatives approach.

**Comment by supersky07** [comment]
Obviously, it's a wrong example~

No matter what you specify the second parameter in the function nodeAppears, it will show ‘OK’ immediately

**Comment by cyrus-and** [comment]
@supersky07 I don't think so... care to elaborate? And if your code is different from the [above][1] please post it.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/134#issuecomment-303780773

**Comment by supersky07** [comment]
@cyrus-and  I just replace 'foo' with 'bar', it will show 'OK'. Well, I'll try again.

**Comment by cyrus-and** [comment]
@supersky07 if I replace `div#foo` with `div#bar`, the script just doesn't terminate, there must be another problem.

**Comment by supersky07** [comment]
@cyrus-and  thank you~ I will try again. And give you a feedback some time.

**Comment by supersky07** [comment]
@cyrus-and So sorry, entirely my problem. When I change to Canary, it turns out the right answer.

**Comment by vichajser** [comment]
there is error when I run the code like this:

`const CDP = require('chrome-remote-interface');
const argv = require('minimist')(process.argv.slice(2));
const file = require('mz/fs');
const timeout = require('delay');

async function nodeAppears(client, selector) {
    // browser code to register and parse mutations
    const browserCode = async (selector) => {
        const result = new Promise(async (fulfill, reject) => {
            const {DOM} = client;
            let startTime = 0;
            const {root: {nodeId: documentNodeId}} = await DOM.getDocument();
            const getElementBySelectorWait = async (querySelector, DOM, parentNodeId, waitTime) => {
                let startTime = 0;
                let elementNodeId = await getElementBySelector(querySelector, DOM, parentNodeId);
                console.log('0000000 elementNodeId', elementNodeId);
                while (elementNodeId.nodeId === 0 && startTime < waitTime) {
                    await timeout(10);
                    startTime = startTime + 10;
                    elementNodeId = await getElementBySelector(querySelector, DOM, parentNodeId);
                    console.log(startTime, 'elementNodeId', elementNodeId);
                }
                return elementNodeId;
            }
            const getElementBySelector = async (querySelector, DOM, parentNodeId) => {
                try {
                    console.log(querySelector, parentNodeId);
                    return await DOM.querySelector({selector: querySelector, nodeId: parentNodeId});
                } catch (error) {
                    console.log("Cannot find the element yet", error);
                    return null;
                }
            }

            const result = await getElementBySelectorWait(selector, DOM, documentNodeId, 5000);
            if (result.nodeId && result.nodeId !== 0) {
                console.log('find ', selector);
                fulfill();
            } else {
                console.log('not find ', selector);
                reject();
            }    
        });
        return result;
    };
    // inject the browser code
    const {Runtime} = client;
    try {
        await Runtime.evaluate({
            expression: `${browserCode(selector)}`,
            awaitPromise: true
        });
    } catch (err) {
        console.log('err', err);
    }
}

async function load(url) {
    console.log('load(url) called');
    const target = await CDP.New({port: '9222'});
    const client = await CDP({target});
    // const client = tab;
    const {Network, Page, DOM} = client;
    await Promise.all([Network.enable(), Page.enable(), DOM.enable()]);

    const obj = new Promise((resolve, reject) => {
        let failed = false;
        Network.loadingFailed(() => {
            failed = true;
            console.log('Load(url) Network.loadingFailed');
            reject(new Error('Load(url) unable to load remote URL: ' + url));
        });
        Page.navigate({url});
        Page.domContentEventFired();
        Page.loadEventFired(() => {
            if (!failed) {
                console.log('Load(url) resolved');
                resolve({client: client, target: target});
            }
        });
    });
    return obj;
};

async function getPdf(url, output) {
    const {client, target} = await load(url);
    const {Page} = client;

    console.log("targetID: " + target.id);
    try {
        await nodeAppears(client, '.question-item-dom');
    } catch (err) {
        console.log('err', err);
    }
    // https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#method-printToPDF
    const {data} = await Page.printToPDF({
        landscape: false,
        scale: 1,
        printBackground: false,
        marginTop: 0,
        marginBottom: 0,
        marginLeft: 0,
        marginRight: 0,
        paperWidth: 8.267716,
        paperHeight: 11.708335
    });

    await console.log('output is', output);
    await CDP.Close({port: 9222, id: target.id}); // here's you need to pass target id

    const buffer = new Buffer(data, 'base64');
    await file.writeFile(output, buffer, 'base64');
}`

throw err:
`load(url) called
Load(url) resolved
targetID: bb24b5f8-1fcd-4b74-83e1-548c4a864259
.question-item-dom 1
0000000 elementNodeId { nodeId: 0 }
.question-item-dom 1
10 'elementNodeId' { nodeId: 0 }
.question-item-dom 1
output is ./test.pdf
20 'elementNodeId' { nodeId: 0 }
.question-item-dom 1
Cannot find the element yet Error: not opened
    at WebSocket.send (/home/zxy-test/app/service/ZXY-wrong-topic/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/home/zxy-test/app/service/ZXY-wrong-topic/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /home/zxy-test/app/service/ZXY-wrong-topic/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at Chrome.send (/home/zxy-test/app/service/ZXY-wrong-topic/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as querySelector] (/home/zxy-test/app/service/ZXY-wrong-topic/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at getElementBySelector (/home/zxy-test/app/service/ZXY-wrong-topic/new.js:65:38)
    at getElementBySelectorWait (/home/zxy-test/app/service/ZXY-wrong-topic/new.js:56:43)
30 'elementNodeId' null
(node:19338) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'nodeId' of null
(node:19338) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Why is elementNodeId the null at the third run?  `Why is elementNodeId the null at the third run?`

**Comment by cyrus-and** [comment]
@vichajser [as you can see][1] "Error: not opened" is a quite common error that happens when a connection is used after close.

Anyway here you're mixing Node.js and browser code in `nodeAppears` which is obviously wrong, e.g., `DOM` doesn't belong to the browser context.

Also please try to avoid bumping old issues if you're not reporting something strictly related (you've completely rewritten `nodeAppears` here!) especially when several other people are subscribed to the updates; file a new issue instead.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues?utf8=%E2%9C%93&q=%22Error%3A%20not%20opened%22
