### ISSUE TITLE
Use the README.md example but always got "No inspectable targets"

### ISSUE THREAD

**Issue by hinablue** [cyrus-and/chrome-remote-interface#136]
I modified the `chrome.js` and print the targets, it show me this,

```
{ description: '',
  devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:9222/devtools/page/781998de-c9e7-4ef1-b5c4-f747092f92da',
  id: '781998de-c9e7-4ef1-b5c4-f747092f92da',
  title: '127.0.0.1',
  type: 'page',
  url: 'http://127.0.0.1/',
  webSocketDebuggerUrl: 'ws://localhost:9222/devtools/page/781998de-c9e7-4ef1-b5c4-f747092f92da' }
{ description: '',
  id: '781998de-c9e7-4ef1-b5c4-f747092f92da',
  title: 'https://hinablue.me/interns/ji-shu-xing-xiaoshang-ye-kai-fa-zhu-li',
  type: 'page',
  url: 'https://hinablue.me/interns/ji-shu-xing-xiaoshang-ye-kai-fa-zhu-li' }
```
The second object is my URL but `webSocketDebuggerUrl` does not exists.

How can I fix it?

My env,
Ubuntu 16.04 LTS
Google Chrome 58.0.3029.81

And Google Chrome run with headless,
`chrome --headless --disable-gpu --window-size=1366,768 --remote-debugging-port=9222 --user-data-dir=/mnt/tmp http://127.0.0.1`

**Comment by cyrus-and** [comment]
> I modified the chrome.js and print the targets

You can also use `chrome-remote-interface list` for that.

> How can I fix it?

Are you sure there isn't another `chrome-remote-interface` session (or any other CDP client) attached to that tab? If a tab is being inspected then the `webSocketDebuggerUrl` field is omitted as you cannot have simultaneous protocol clients.

**Comment by cyrus-and** [comment]
Did you go any further with this?

**Comment by popsail** [comment]
Happened to me as well.
It works when I connect, but if I close that connection and re-connect again later - that's the error i'm getting.

Maybe client.close() doesn't do what it's supposed to ?

**Comment by cyrus-and** [comment]
@popsail from a previous [comment][1]: are you sure there isn't another chrome-remote-interface session (or any other CDP client) attached to that tab? If a tab is being inspected then the webSocketDebuggerUrl field is omitted as you cannot have simultaneous protocol clients.

Show me the output of `chrome-remote-interface list` when that error happens.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/136#issuecomment-303961249

**Comment by zsxsoft** [comment]
@cyrus-and 
I also got this error, and I edited ``lib/chrome.js`` and added log like this:
![image](https://user-images.githubusercontent.com/2398785/28262948-9b7e6128-6b17-11e7-92b9-62a0a885b4ba.png)

Then I found:
![image](https://user-images.githubusercontent.com/2398785/28263002-cd586b4e-6b17-11e7-9244-42ec5b4977b0.png)

So I think it will be caused if CDP inspects the same target more than once.
