### ISSUE TITLE
New Fullpage Screenshot call

### ISSUE THREAD

**Issue by KartoffelToby** [cyrus-and/chrome-remote-interface#137]
In Chrome 59, they introduced the new Full page Screenshot function: [https://developers.google.com/web/updates/2017/04/headless-chrome](https://developers.google.com/web/updates/2017/04/headless-chrome)
[https://i.ytimg.com/vi/r_6_9eFPhxI/maxresdefault.jpg](https://i.ytimg.com/vi/r_6_9eFPhxI/maxresdefault.jpg)

How can we call this with the Remote Interface API?

**Comment by cyrus-and** [comment]
The [wiki][1] points to a blog [post][2], it should provide a full working example.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Take-page-screenshot
[2]: https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a
