### ISSUE TITLE
how to make click events on elements using css selectors or alike?

### ISSUE THREAD

**Issue by DavidXanatos** [cyrus-and/chrome-remote-interface#138]
I would like to issue click events on elements in the webpage I'm interacting with,
but i dont want to have to search for x,y coordinates, instead
i would like to just select a element in the dom tree of the page and than click on it ideally using css selectors or something similar.

what is the best way to do that?

**Comment by cyrus-and** [comment]
While obtaining the coordinates should be [fairly easy][1], I guess you can always inject some JavaScript code to do that:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    try {
        const {Runtime} = client;
        await Runtime.evaluate({
            expression: `document.querySelector('#myButton').click()`
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

[1]: https://groups.google.com/forum/#!topic/chrome-debugging-protocol/9rxkDBRZc24

**Comment by DavidXanatos** [comment]
Yea, there is an issue with that, which is that some click capture mechanisms are not triggered by that.
Like annoying ad popups 😄 and I want to trigger those.
So I will need to find the coordinates I think.
I will try the linked method thanks

**Comment by DavidXanatos** [comment]
nope now it works i guess i triggered enough adds, clearing cookies solved it

**Comment by CarmenLexa** [comment]
@DavidXanatos Can you share your code of how you got the click?
