### ISSUE TITLE
better way to manage tabs for less consuming memory/cpu

### ISSUE THREAD

**Issue by hbakhtiyor** [cyrus-and/chrome-remote-interface#140]
is it make sense to leave open tabs with `about:blank` and use it later? or after finishing, close it and open new tab again?

what's differ from `CDP().Target.createTarget` and `CDP().New`?

**Comment by cyrus-and** [comment]
> is it make sense to leave open tabs with about:blank and use it later? 

Probably not, a loaded page will surely consume memory, `about:blank` will not (*as much*), but I don't think you'll gain any benefit from reusing tabs. The code should be cleaner if you dispose unused tabs.

> what's differ from CDP().Target.createTarget and CDP().New?

They both create a new target, the former is a protocol method, meaning that it needs to be delivered to an existing target (e.g., `/devtools/browser`), the latter instead uses the HTTP endpoint of Chrome. Moreover, the former allows to use [browser contexts][1].

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget

**Comment by gwuhaolin** [comment]
@hbakhtiyor 
here is a open-source project may be what you are finding:
[chrome-pool](https://github.com/gwuhaolin/chrome-pool) Headless chrome tabs manage pool, concept come from database connection pool for reuse chrome tab improve performance.

chrome-pool has been used in:
- [chrome-render](https://github.com/gwuhaolin/chrome-render) general server render base on chrome.
- [koa-chrome-render](https://github.com/gwuhaolin/koa-chrome-render) chrome-render middleware for koa
- [koa-seo](https://github.com/gwuhaolin/koa-seo) koa SEO middleware
