### ISSUE TITLE
Console messages appear twice

### ISSUE THREAD

**Issue by hinzundcode** [cyrus-and/chrome-remote-interface#141]
When running my script the first time I get one log message, but as I run it again I get two messages, the old log and the new log. What am I doing wrong?

versions:
Google Chrome 59.0.3071.71 beta
chrome-remote-interface@0.23.0

my script:
```javascript
"use strict";
const chrome = require("chrome-remote-interface");

(async () => {
	chrome(async protocol => {
		const { Page, Console } = protocol;
		
		Console.messageAdded(({ message }) => {
			console.log(message);
		});
		
		await Promise.all([
			Page.enable(),
			Console.enable(),
		]);
		
		await Page.navigate({ url: "http://127.0.0.1:8081/index.html" });
		await Page.loadEventFired();
		
		protocol.close();
	}).on("error", e => console.log(e));
})().catch(e => console.log(e));
```

the example page:
```html
<!DOCTYPE html>
<script>console.log("hi")</script>
```

console output:
```
{ source: 'console-api',
  level: 'log',
  text: 'hi',
  url: 'http://127.0.0.1:8081/index.html',
  line: 2,
  column: 17 }
{ source: 'console-api',
  level: 'log',
  text: 'hi',
  url: 'http://127.0.0.1:8081/index.html',
  line: 2,
  column: 17 }
```

**Comment by cyrus-and** [comment]
OK this is a funny one, fact is that as soon as you enable the `Console` domain, events about the currently loaded page are delivered immediately, so the first time you probably attach to an empty page or one which doesn't have console messages, while for the others the console is already containing the messages from the previous page load.

Is this your case?

---

FYI you should probably use [`Runtime.consoleAPICalled`][1] as the `Console` domain seems to be deprecated:

> This domain is deprecated - use Runtime or Log instead.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled

**Comment by hinzundcode** [comment]
Thanks for your quick reply. I made some experiments:

I replaced `Console` with `Runtime.consoleAPICalled` but I still get everything twice:
```js
Runtime.consoleAPICalled(msg => console.log(msg));
await Promise.all([ Page.enable(), Runtime.enable(), ]);
await Page.navigate({ url: "http://127.0.0.1:8081/index.html" });
```

```
{ type: 'log',
  args: [ { type: 'string', value: 'hi' } ],
  executionContextId: 3,
  timestamp: 1496089559368.367,
  stackTrace: 
   { callFrames: 
      [ { functionName: '',
          scriptId: '25',
          url: 'http://127.0.0.1:8081/index.html',
          lineNumber: 1,
          columnNumber: 16 } ] } }
{ type: 'log',
  args: [ { type: 'string', value: 'hi' } ],
  executionContextId: 4,
  timestamp: 1496089595598.573,
  stackTrace: 
   { callFrames: 
      [ { functionName: '',
          scriptId: '25',
          url: 'http://127.0.0.1:8081/index.html',
          lineNumber: 1,
          columnNumber: 16 } ] } }
```

I also switched from `Console` to `Log`, but `Log` doesn't print anything at all.
```js
Log.entryAdded(msg => console.log(msg));
await Promise.all([ Page.enable(), Log.enable(), ]);
await Page.navigate({ url: "http://127.0.0.1:8081/index.html" });
```

At last I tried to call `Console.clearMessages` before `Page.navigate`, but I still get old messages.
```js
Console.messageAdded(msg => console.log(msg));
await Promise.all([ Page.enable(), Console.enable(), ]);
await Console.clearMessages();
await Page.navigate({ url: "http://127.0.0.1:8081/index.html" });
```

**Comment by cyrus-and** [comment]
> I replaced Console with Runtime.consoleAPICalled but I still get everything twice:

Yes, the behavior I described is the intended behavior, it's not broken in `Console`, it's probably deprecated for other reasons.

> I also switched from Console to Log, but Log doesn't print anything at all.

I think `Log` is used for other kind of messages, e.g., error messages from Chrome. Not sure though.

> At last I tried to call Console.clearMessages before Page.navigate, but I still get old messages.

That's because you need to clear the messages before enabling the `Console` domain.

**Comment by hinzundcode** [comment]
> That's because you need to clear the messages before enabling the Console domain.

Doesn't help either :/

```js
await Console.clearMessages();
Console.messageAdded(msg => console.log(msg));
await Promise.all([ Page.enable(), Console.enable(), ]);
await Page.navigate({ url: "http://127.0.0.1:8081/index.html" });
```

I'll try to parse the stdout of chrome instead, it contains all logs as well. Thank you for all the help!

**Comment by cyrus-and** [comment]
> That's because you need to clear the messages before enabling the Console domain.

That wasn't accurate sorry, you need to clear the messages before registering for the event, this works for me:

```js
const CDP = require('..');

CDP(async (client) => {
    const {Console, Page} = client;
    try {
        await Promise.all([Console.enable(), Page.enable()]);
        await Console.clearMessages();
        Console.messageAdded((params) => {
            console.log(params);
        });
        await Page.navigate({url: 'https://facebook.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by hinzundcode** [comment]
Awesome! Works for me, too. And also in combination with `Runtime.consoleAPICalled` (which I prefer because of the stack trace). Thank you very much!

**Comment by cyrus-and** [comment]
You're welcome!
