### ISSUE TITLE
How to properly detect submit event?

### ISSUE THREAD

**Issue by demian85** [cyrus-and/chrome-remote-interface#142]
Hi,

I need to click a button that submits a form, then interact with the next page, which is a totally different document from another URL.
I'm registering an event `Page.loadEventFired` before submitting form, but it does not seem to work.
Which is the proper way of doing that? I don't want to rely on setTimeout and explicitly redirect to that page, I need to detect a page load... after another page load.

Thanks for your help!

**Comment by cyrus-and** [comment]
I think this problem is already addressed in #106, see this [comment][1]. Otherwise show me what you have tried, as you can see registering for the `Page.loadEventFired ` event is the right approach.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/106#issuecomment-295753078

**Comment by demian85** [comment]
I've read that issue but still it does not seem to work. I'm figuring out how `Page.loadEventFired` method works, as not sure what happens when called with and without a callback.
Should I await? Should I send a callback and handle states using a switch? Can I register more than one `loadEventFired` event?
I'll post my code later and try again.
Thanks.

**Comment by cyrus-and** [comment]
If you provide a callback then it's called *every* time the event occurs, otherwise it returns a promise which is fulfilled as soon as the event triggers.

In the former case you just register your own callback and nothing is returned, in the latter since a promise is returned you must either `await` for it or chain it with `.then()`.

Basically it's the difference between `emitter.on('foo', ...)` and `emitter.once('foo', ...)`.

**Comment by cyrus-and** [comment]
To explicitly answer your questions.

> Should I await?

Yes, meaning that you don't pass a callback, I think it's the better solution in this case.

> Should I send a callback and handle states using a switch?

Nope, see above.

> Can I register more than one loadEventFired event?

Sure, you can do whatever Node.js allows you to do with [event emitters](https://nodejs.org/api/events.html).

**Comment by cyrus-and** [comment]
Did you have any luck with this?

**Comment by demian85** [comment]
Yes, sorry. The problem was on my side. There was a hidden redirect causing
a duplicate load event.
Thanks.
