### ISSUE TITLE
how to get the redirect url

### ISSUE THREAD

**Issue by fh1994** [cyrus-and/chrome-remote-interface#143]
is there a event called onNavigationRequested?
how to get the redirect url when the page jump to it?

**Comment by cyrus-and** [comment]
> is there a event called onNavigationRequested?

Nope.

> how to get the redirect url when the page jump to it?

There's a `redirectResponse` field among the parameters returned by the [`Network. requestWillBeSent`][1] event. 

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent
