### ISSUE TITLE
Runtime.evaluate({ expression: 'document.getElementById(a)' })

### ISSUE THREAD

**Issue by fh1994** [cyrus-and/chrome-remote-interface#144]
```
var a = ...
Runtime.evaluate({ expression: 'document.getElementBiId(a)' }).then(){}
```
a is a variable 
how to do that?

**Comment by paulirish** [comment]
```js
var a = 'someID';
// ...
Runtime.evaluate({ expression: `document.getElementById(${a})` }).then(
```

**Comment by fh1994** [comment]
That works!
But 
```
var a = 'someID';
Runtime.evaluate({ expression: 'document.getElementById(${a})' }).then((result) => {
                                            console.log( result.result.value);
                                        })
```
the result is undefine
how is that happen?

**Comment by cyrus-and** [comment]
@fh1994 two things:

- you have to use the backtick (`) for template literals (but you probably already are);
- you need to properly quote the value (e.g., using `JSON.stringify`) otherwise you'll end up passing the actual HTML object since for convenience HTML tags with `id=<x>` are stored as global variables `window.<x>`; this is why you get `null`.

So:

```js
Runtime.evaluate({
    expression: `document.getElementById(${JSON.stringify(a)})`
})
```

**Comment by pmurley** [comment]
Got a follow-up here. Say I have a nodeId (and objectId) for some element, and I want to get the selector for it. 

In other words, I want to be able to run:

```js
Runtime.evaluate({
    expression: `document.getElementById(${JSON.stringify(a)})`
})
```
but I don't have `a`; all I have is a nodeId and objectId. Is there an easy way to get the selector?

Thanks!

**Comment by santosh20290** [comment]
Runtime.evaluate({
    expression: `document.getElementById(${JSON.stringify(a)})`
})
this worked for me
thanks
