### ISSUE TITLE
client.Overlay is not defined

### ISSUE THREAD

**Issue by clujin** [cyrus-and/chrome-remote-interface#149]
Hi, I'm am trying to use the Overlay domain but it seems that this is currently not supported. When I run "client.Overlay.enable()", all I get is that Overlay is not defined. Is there any resolution or alternative work around available? Thanks.

**Comment by cyrus-and** [comment]
See the [Chrome Debugging Protocol versions][1] section of the README and the discussion thread of #129 for more info.

Anyway I've just updated the bundled version of `protocol.json` so it should just work now.

[1]: https://github.com/cyrus-and/chrome-remote-interface#chrome-debugging-protocol-versions
