### ISSUE TITLE
How to pass in parameter with `Runtime.evaluate()`?

### ISSUE THREAD

**Issue by pthieu** [cyrus-and/chrome-remote-interface#150]
I need to write some browser tests where I log in as different users in my app. I used to hardcode my username and password right in the login function, which worked, but would like to not commit code that has credentials inside. Seems like I can't pass in a variable in the below code:

```js
const USERID = 'userid';
const PASSWORD = 'password';

let res = await Runtime.evaluate({
  expression: `(${login})(${USERID}, ${PASSWORD})`,
  awaitPromise: true,
})

function login(userid, password) {
// this runs within browser context
}
```

Any other way to pass in parameters into function? seems like the expression is able to resolve the `${login}` part but not the two constants for some reason.

**Comment by cyrus-and** [comment]
The problem is that:

```js
`(${login})(${USERID}, ${PASSWORD})`
```

evaluates to:

```js
'(function login(userid, password) {\n// this runs within browser context\n})(userid, password)'
```

where `userid` and `password` are interpreted as JavaScript variables; you need to quote them. For example using JSON:

```js
`(${login}).apply(null, ${JSON.stringify([USERID, PASSWORD])})`
```

Also see [this comment][1] in #144.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/144#issuecomment-305445897

**Comment by pthieu** [comment]
@cyrus-and wow can't believe I missed that. Thanks.

Also, couldn't I also do something like this:
```
`(${login})('${USERID}', '${PASSWORD}')`
```

**Comment by cyrus-and** [comment]
Sure, it just won't work if variables contains `'`.

**Comment by pthieu** [comment]
That makes sense, I'll stick with the stringify method
