### ISSUE TITLE
Applying CSS to a website fails

### ISSUE THREAD

**Issue by dominikkukacka** [cyrus-and/chrome-remote-interface#153]
I am trying to apply a CSS to a website like so:

```
await Page.enable();
await DOM.enable();
await CSS.enable();
const frame = await Page.navigate({ url: 'https://google.com' });
const styleSheet = await CSS.createStyleSheet(frame)


const ruleText = 'body { background-color: red; }';
const location = {
  startLine: 0,
  endLine: 0, // should be split by \n if its multiline
  startColumn: 0,
  endColumn: 31, // guessing this has to be the length if it is a one liner? what about multi line? longest line?
};
await CSS.addRule(styleSheet, ruleText, location);
```

It fails with `Error: Invalid parameters` and `'ruleText: string value expected; location: object expected'`

Any idea what is happening? I can't find anything in the documentation

**Comment by cyrus-and** [comment]
Parameters are [passed][1] via a JavaScript object just like you're doing for `Page.navigate`. Incidentally, it works for `CSS.createStyleSheet` because `frame` is actually an object.

All in all you should do something like this:

```js
const {frameId} = await Page.navigate({url: 'https://google.com'});
const {styleSheetId} = await CSS.createStyleSheet({frameId});
await CSS.addRule({styleSheetId, ruleText, location});
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#clientsendmethod-params-callback

**Comment by dominikkukacka** [comment]
Ah, thank you very much.
And how should the location object look like?
How can I inject CSS which will override everything already specified?

My example (with endColumn: 31) results in `Specified range is out of bounds`
With endColumn: 0 it works, but no CSS change is visible.

**Comment by cyrus-and** [comment]
> And how should the location object look like?

It should work now, that error was about the parameters passing.

> How can I inject CSS which will override everything already specified?

As you normally would I guess, e.g., using `!important` or removing the other rules. Also take a look at this [comment][1] for a similar use case.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/52#issuecomment-251413880

**Comment by dominikkukacka** [comment]
I just can't get It to work.

```
const nodeId = getRootNodeId(...);
const css = await CSS.getMatchedStylesForNode({nodeId: nodeId});
const setcss = await CSS.setStyleSheetText({styleSheetId: css.inlineStyle.styleSheetId, text: 'background-color: red !important;'});
```
This does not work, also I want to apply multiple css statements to the DOM.
Isn't there an easy way to just apply multiple css statements (like written in a css file)?

**Comment by cyrus-and** [comment]
This works for me:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    try {
        const {CSS, DOM, Page} = client;
        // the CSS domain must be enabled
        await DOM.enable();
        await CSS.enable();
        await Page.enable();
        // load the URL and wait for the load event in order to alter the CSS
        const {frameId} = await Page.navigate({url: 'https://google.com'});
        await Page.loadEventFired();
        // create and populate a new stylesheet so there's no need to mess
        // with ranges which is quite annoying; no !important is needed now as
        // presumably this new stylesheet has the highest priority
        const {styleSheetId} = await CSS.createStyleSheet({frameId});
        await CSS.setStyleSheetText({
            styleSheetId,
            text: `body { background: red; }`
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by dominikkukacka** [comment]
works!

the difference is I did the modifications before the `await Page.loadEventFired();`
If I do them afterwards they work!

thank you!

**Comment by dominikkukacka** [comment]
One other thing:
If I apply two style sheets in a row only the last one gets used.

```
const {styleSheetId} = await CSS.createStyleSheet({frameId});
await CSS.setStyleSheetText({
    styleSheetId,
    text: `body { background-color: red; }`
});

const styleSheet2 = await CSS.createStyleSheet({frameId});
await CSS.setStyleSheetText({
    styleSheetId: styleSheet2.styleSheetId,
    text: `#hplogo { background-color: green; }`
});
```

any idea why?

**Comment by cyrus-and** [comment]
Apparently you can have at most one styles heet per frame because the returned `styleSheetId` is the same for the two calls. I don't know why is that but you can always put more than one rule in a single style sheet:

```js
await CSS.setStyleSheetText({
    styleSheetId,
    text: `body { background-color: red; }
           #hplogo { background-color: green; }`
});
```

**Comment by dominikkukacka** [comment]
Ah perfect.

Thank you very much for your support!!!
