### ISSUE TITLE
Websocket closed throwing unhandled promise rejection

### ISSUE THREAD

**Issue by cungminh2710** [cyrus-and/chrome-remote-interface#155]
When I open DevTools or when the tab is closed, i got this error message `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: not opened`

I added event: 'disconnect' which should be emitted when the instance closes the WebSocket connection. Yet, I still received the error message of unhandled promise rejection.
```javascript
let tab = await CDP.New();
let client = await CDP({ tab: tab });
client.on("disconnect", _ => console.log("disconnect"));
client.on("ready", _ => console.log("ready"));
```

**Comment by cyrus-and** [comment]
Hmm, this works fine for me:

```js
const CDP = require('chrome-remote-interface');

async function foo() {
    let tab = await CDP.New();
    let client = await CDP({ tab: tab });
    client.on("disconnect", _ => console.log("disconnect"));
    client.on("ready", _ => console.log("ready"));
}

foo();
```

**Comment by cyrus-and** [comment]
Do you experience the same error even with the above code?

**Comment by cungminh2710** [comment]
Hey sorry I was on holiday. 
The above code works fine for me. Probably the issue is in my end. 
Thanks Cyrus
