### ISSUE TITLE
Page.printToPDF size

### ISSUE THREAD

**Issue by Groarq** [cyrus-and/chrome-remote-interface#157]
Hello!
I wonder if I'm doing something wrong, or it is just working differently.
On Issue #120 you've wrote that "Page.printToPDF doesn't take any parameters". And indeed it seems to refuse all params.

However, according to this documentation:
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
It should take few arguments. 

```
{ layoutViewport: { pageX: 0, pageY: 0, clientWidth: 3750, clientHeight: 5550 },
  visualViewport:
   { offsetX: 0,
     offsetY: 0,
     pageX: 0,
     pageY: 0,
     clientWidth: 3750,
     clientHeight: 5550,
     scale: 1 },
  contentSize: { x: 0, y: 0, width: 3752, height: 88736 } }
```

My layoutViewport looks as it supposed, but printToPDF creates A4 page and without those `paperWidth` and `paperHeight` I cant see any possibility of changing this.

**Comment by cyrus-and** [comment]
> On Issue #120 you've wrote that "Page.printToPDF doesn't take any parameters". And indeed it seems to refuse all params.

Yes, it changed some time [ago][1], so it's possible that your version of Chrome doesn't support it yet. For example the current stable (59) doesn't:

```
$ chrome-remote-interface inspect -r
>>> Page.printToPDF
{ [Function: override]
  category: 'command',
  description: 'Print page as pdf.',
  returns:
   [ { name: 'data',
       type: 'string',
       description: 'Base64-encoded pdf data.' } ],
  experimental: true }
```

[1]: https://github.com/cyrus-and/chrome-remote-interface/commit/58bacb6c15ccb6e6a4f7fa809cd47d1b901ebdf0#diff-b76455f1e3fb9edcec4803a74d6a940fL924

**Comment by Groarq** [comment]
Thank you very much!! 
Indeed I have stable 59 version :)

**Comment by cyrus-and** [comment]
It's surely present on Canary (61), can't check about version 60 right now.
