### ISSUE TITLE
How do I save page source?

### ISSUE THREAD

**Issue by abhishekdubey1** [cyrus-and/chrome-remote-interface#159]
What is the best way to save the page  source?

Thanks,

**Comment by cyrus-and** [comment]
Take a look at [this comment][1] in #76, quoting below.

---

You can get the *first request's* HTML with [Network.getResponseBody]. To fetch the DOM once the page is loaded ([Page.loadEventFired] event) I'm afraid you'll have to walk all the nodes and build the string manually. Another option might be injecting ([Runtime.evaluate]) some JavaScript code, like:

```js
document.documentElement.outerHTML
```

In any case you might have problem with frames.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/76#issuecomment-271531236

[Network.getResponseBody]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-getResponseBody
[Page.loadEventFired]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#event-loadEventFired
[Runtime.evaluate]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate

**Comment by abhishekdubey1** [comment]
Thanks Andrea!
