### ISSUE TITLE
PDF weight

### ISSUE THREAD

**Issue by Groarq** [cyrus-and/chrome-remote-interface#160]
Hey, I really appreciate your will to help and all your work!
I have another problem which is killing me and I can't find a solution.
My PDFs weight is huge. Same thing rendered by phantomJS is 2.5x lighter than PDF from headless chrome. Its big PDF so 2.5times more is really big difference.
Do you know what might be the problem?

Chrome canary 61

```js
function onPageLoad(Page) {
  return Page.printToPDF({paperWidth: 12.5, paperHeight: 18.5}).then(response => {
    const buffer = new Buffer(response.data, 'base64');
    file.writeFile('chrome.pdf', buffer, 'base64', function(err) {
      if (err) {
        console.error(err);
      } else {
        console.log('PDF saved');
      }
    });
  });
}
```

**Comment by cyrus-and** [comment]
A quick test with Chrome 60 gave me 492K for Chrome and 705K for PhantomJS. Using your code in the former case and `phantomjs examples/rasterize.js 'https://github.com/' phantomjs.pdf` in the latter.

Anyway, taking a look at your generated PDFs might help.

You may also want to ask this question in the [Google Group][1].

[1]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by cyrus-and** [comment]
Did you get any further with this?

**Comment by Groarq** [comment]
I did the test.
I had large image resized with CSS to very small one. Originally this image weights 2.5mb.
PDF from chrome weight was 2.5mb.
PDF from phantomJS weight was 1mb.
Also, while using scale property size for phantomJS pdf drastically lows while chrome pdf stays the same.

So this leads me to some DPI setting problem. I have huge web page in px which should be 12.5inch x 18.5inch in 300 DPI. As I've read in headless chrome there is no option to change DPI so I thought scale property would work. Anyway this is different kind of problem :)

**Comment by cyrus-and** [comment]
I see, well I think this is a thing you should discuss with the Chromium team, you can even file a bug [here][1]. I'm closing this but feel free to add any details/updates if you want.

[1]: https://github.com/ChromeDevTools/devtools-protocol/issues
