### ISSUE TITLE
Page.printToPDF landscape mode not working

### ISSUE THREAD

**Issue by mansona** [cyrus-and/chrome-remote-interface#166]
Howdy 👋 

First of all: thanks for the awesome library 🎉  I'm trying to use it with Ember-FastBoot to build a server-side PDF render for an app (long story).

I'm trying to get it to print using landscape but it's not working: `const pdfData = await Page.printToPDF({ landscape: true });`

Here is the rest of my code (not that I think it's relevant): 

```
    const chrome = await chromeLauncher.launch({
      chromeFlags: [
        // I tried swapping these around but it didn't seem to do anything
        '--window-size=1440,1080',
        '--disable-gpu',
        '--headless',
      ],
    });

    const protocol = await cdp({ port: chrome.port });

    const { Page } = protocol;
    await Page.enable();

    const datauri = new DataURI();
    datauri.format('.html', html);

    await Page.navigate({ url: datauri.content });
    await Page.loadEventFired();
    const pdfData = await Page.printToPDF({ landscape: true });

    const pdfBuffer = new Buffer(pdfData.data, 'base64');

    await writeFilePromise('./test.pdf', pdfBuffer);
```

As you can see I took inspiration from another issue you solved with someone else re: the datauri navigation.

Is there anything I could try to debug the landscape issue?

**Comment by cyrus-and** [comment]
Hey, thanks! :)

What version of Chrome are you using? *Older* versions have a simpler (no parameters) `Page.printToPDF` method. See #157, maybe it's the same scenario.

**Comment by tamdao** [comment]
I have tried to use Chrome Canary v61. But I still can not print with params. Could you help me check it?

**Comment by cyrus-and** [comment]
@tamdao I created a wiki page for that: [Print page to PDF][1]. Does it work for you as is?

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Print-page-to-PDF

**Comment by mansona** [comment]
I can confirm that this is working with Chrome 61 (currently canary). 

I'm happy to close this issue but should I leave it open to track @tamdao 's issues?

**Comment by tamdao** [comment]
The issue from my css. Because I use @page css, the css change margin on page. @mansona you can close this issue. Thanks
