### ISSUE TITLE
How to detect React route navigation?

### ISSUE THREAD

**Issue by saurabh2590** [cyrus-and/chrome-remote-interface#167]
We are having a weird problem for Page.loadEvent being not fired while navigating on the applications only using front-end routers in a React Application.
For example, we have React app which has route 
`https://localhost:8100#/gizmo/MultipleChoiceSingleEditor`
and 
`https://localhost:8100/#/gizmo/MultipleChoiceSingleRenderer` 
where changing the last argument only loads the different route of the front-end application. As a result when doing,
```
    await Page.navigate({url: 'https://localhost:8100#/gizmo/MultipleChoiceSingleEditor'});
    await Page.loadEventFired();
    await Page.navigate({url: 'https://localhost:8100#/gizmo/MultipleChoiceSingleRenderer'});
    await Page.loadEventFired();
```
the second Page.loadEvent is not fired because as I understand that due to React's internal router, there is actually no new Page request and the only required component is mounted from the resources already loaded in the first attempt.

Is there a work around with this problem to always find when the navigation has actually happened even though it didn't trigger any page load?

**Comment by cyrus-and** [comment]
Exactly, this is not an issue, this is how React works, and the `Page` domain cannot be aware of the fact that a JavaScript framework is handling the actual navigation.

Moreover, the meaning of "navigation happened" is now up to React. I'm not a React developer so please take the following with a grain of salt. Anyway, if you are responsible of the application then you might explicitly do something to notify the finished page load, e.g., inside `componentDidMount()`. For example:

```js
if (window.notifier) notifier();
```

Then you simulate the load event with:

```js
await Page.navigate({url: '...'});
await Runtime.evaluate({
    awaitPromise: true,
    expression: `new Promise((fulfill, reject) => {
        notifier = fulfill;
    }).then(() => {
        notifier = null
    })`
});
```

While if you cannot change the application then you can maybe try a similar approach, but hooking to some React-native properties instead, something that gets updated when a route is navigated. Remember that [wiki][1] that shows how to wait for a specific DOM node to appear.

Now while this maybe works it's spectacularly ugly and I sincerely hope there are better ways, unfortunately I have zero React experience so I cannot go more into the detail. You may want to also ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

Hope it helps.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element

**Comment by tim-field** [comment]
@saurabh2590 in case this is useful.  I'm getting around this in my react projects by searching for an element in the DOM to know the page is ready ( as suggested above by @cyrus-and )

https://github.com/tim-field/urlToPdf/blob/master/url-to-pdf.js#L82
https://github.com/tim-field/urlToPdf/blob/master/url-to-pdf.js#L17

**Comment by saurabh2590** [comment]
Thank you, everyone, for the replies. I was just confirming that if there is any way to detect URL change success but eventually we also ended up implementing watching for just required DOM element to be present. And now it works consistently without worrying about the fact whether routes are managed by React app or real routes serviced by the backend server.
