### ISSUE TITLE
Listen for Client Side Events

### ISSUE THREAD

**Issue by westy92** [cyrus-and/chrome-remote-interface#169]
Is it possible to listen for client side events?  I'd like to listen for an event that was fired on a page inside my Chrome instance and react accordingly.

**Comment by cyrus-and** [comment]
See #167 and this [wiki][1] recipe. The general approach is to use [`Runtime.evaluate`][2] to wait for a promise:


```js
await Runtime.evaluate({
    awaitPromise: true,
    expression: `new Promise((fulfill, reject) => {
        document.body.addEventListener('click', fulfill, {
            once: true
        });
    })`
});
```

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by SkeLLLa** [comment]
@cyrus-and hello. I'm trying this code to wait for event and it always fails with message "Promise was collected" before event is fired.

```
Runtime.evaluate({
          awaitPromise: true,
          expression: `new Promise((fulfill, reject) => {
                        document.addEventListener('page_rendered', fulfill, {
                          once: true
                        });
                      })`
        }).then(() => {
          console.log('ok');
        }).catch((ex) => {
          console.log('fail', ex);
        });
```

**Comment by cyrus-and** [comment]
@SkeLLLa take a look at [this][1] FAQ entry. If that doesn't solve your problem please file a new issue with all the details (that piece of code alone is not enough to explain the behavior).

[1]: https://github.com/cyrus-and/chrome-remote-interface#using-runtimeevaluate-with-awaitpromise-true-i-sometimes-obtain-error-promise-was-collected

**Comment by superhos** [comment]
Same problem. Any suggestion?
