### ISSUE TITLE
Collaboration with RemoteDebug?

### ISSUE THREAD

**Issue by auchenberg** [cyrus-and/chrome-remote-interface#17]
Now that we have multiple adaptors, http://remotedebug.org/adaptors/, in place for RemoteDebug, which all use the chrome remote debugging protocol, I was considering writing a Promise-based node client, as the "official RemoteDebug client", ala [webdriver.io](http://webdriver.io)

Since you already did most of the work I'm thinking if you were interesting in collaborating? To me it's mostly a naming thing, as it doesn't make sense to use a "chrome client" when talking to IE11 via an adapter.

**Comment by cyrus-and** [comment]
So basically, if I understand your point, chrome-remote-interface could already be the "official RemoteDebug client" except that: 1. the name is not appropriate; 2. it is not Promise-based. Is it correct?

If that's the case, it could be easier to write a new module which uses chrome-remote-interface as a dependency rather that forking it and changing the API. Now, I don't know what you were thinking about, but such module would be a little more than a wrapper, I wonder whether it would be worth it or not. While changing name to chrome-remote-interface is probably not advisable at this point.

Anyway, this week is gonna be a very busy one for me, but if you want to provide me more details I'll be happy to contribute.

You can also ping me by email if you wish.

**Comment by auchenberg** [comment]
Yes, correct. 

In a "RemoteDebug" world where multiple runtimes (Firefox, IE, Edge, Safari, Node.js, Android, etc) is using the chrome remote debugging protocol, I imagine having an client that is named and decoupled from Chrome.

I imagine such client could be based upon your client, but would use code generation to generate a static build based upon ``protocol.json``, as it would make it easier to glance through the implementation to discover available areas and methods, and would use Promises to make async handling a bit easier.

Fair point. I'll get a new repo going, and then we can take it from here.
