### ISSUE TITLE
How to take screenshots after emulation.

### ISSUE THREAD

**Issue by sa91** [cyrus-and/chrome-remote-interface#172]
Hi,
I am using Emulation api to change viewport and size and take screenshots like this
      var callback=function(){
          //screenshot code.
      }
      Emulation.setVisibleSize({width: x , height: y},callback);
 But sometimes screenshots are incomplete as if page has not completed rendering. Is there someway to know if page has completed rendering on viewport to have a good screenshot of  the page.
Thanks in advance.

**Comment by cyrus-and** [comment]
Do you wait for the [`Page.loadEventFired`][1] event before taking the screenshot?

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-loadEventFired

**Comment by sa91** [comment]
Yes, I make sure both Page.domContentEventFired and  Page.loadEventFired were already fired after which I started Emulation. 
will Page.loadEventFired will be fired again after emulation (if it is so, its not happening as per what I observed)??

**Comment by cyrus-and** [comment]
> will Page.loadEventFired will be fired again after emulation

It shouldn't.

The following seems to work reliably for me, can you manage to reproduce your issue using it?

```js
const CDP = require('chrome-remote-interface');
const fs = require('fs');

CDP(async (client) => {
    const {Emulation, Page} = client;
    try {
        await Page.enable();
        await Page.navigate({url: 'https://reddit.com'});
        await Page.loadEventFired();
        await Emulation.setVisibleSize({
            width: 800,
            height: 600
        });
        const {data} = await Page.captureScreenshot();
        fs.writeFileSync('scrot.png', Buffer.from(data, 'base64'));
    } catch (err) {
        console.error(err);
    } finally {
        await client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by JeffreyArts** [comment]
Hi,

Similair issue here, using the above code sample it creates an empty picture. So I suppose that the problem is related to how I run Chrome, but haven't figures out yet what's going wrong.

Neither
`chrome --headless --disable-gpu --remote-debugging-port=9222` or `chrome --headless --remote-debugging-port=9222` works

**Comment by cyrus-and** [comment]
Bump.
