### ISSUE TITLE
Wiki for chrome debugging protocol

### ISSUE THREAD

**Issue by apusing** [cyrus-and/chrome-remote-interface#173]
Other than the [website](https://chromedevtools.github.io/debugger-protocol-viewer/tot/). I wasn't able to find any wiki to understand the API. For example I am not able to understand what Target API is and how it is different from using the Page API.

Can you please provide some links where I can find this info.

**Comment by cyrus-and** [comment]
I'm in no way responsible of the API of the Chrome debugging protocol so I cannot maintain a proper wiki about it. I can just add examples for the most common use cases. I'm going to add an example about the `Target` domain. In the meanwhile:

- `Target` manages *targets* (e.g., tabs) and provides a more advanced API with respect to `CDP.New()` and similar, for example, it allows to manage browser contexts that are like incognito tabs but you can have more than one session.

- `Page` instead, is about the actual wepage navigation, DOM access, printing/screenshotting and more.

**Comment by cyrus-and** [comment]
[Here][1] it is, hope it helps.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Load-a-URL-in-a-separate-context-(headless-mode-only)

**Comment by apusing** [comment]
Thanks for the info and thanks for creating chrome-remote-interface
