### ISSUE TITLE
Getting blank pages using --headless and --proxy-server

### ISSUE THREAD

**Issue by anthonymayfield111** [cyrus-and/chrome-remote-interface#175]
Hi,

I'm having a strange issue I'm hoping some can help with.  I'm navigating to a page but when I have certain chrome options set it doesn't return the page itself but a blank page with just the html, body and head.  If I remove either proxy settings or the headless options then the page will return as expected.

The other odd thing is that in the code you can see that I'm registering the Network events coming back and all that comes back is a cache event.  So far I have not been able to find a way to get the request of the navigation URL which I provide which would be really helpful if anyone knows how, perhaps it doesn't get to this stage because a cache hit is triggered?

Below is some of the arguments I am sending in and below the main chunk of code in use:

"--proxy-server={myProxyDetails}"
"--host-resolver-rules=\"MAP * 0.0.0.0 , EXCLUDE {myProxyDetails}\""
"--headless"

```js
await Page.navigate({url});
    
    if (config.debug) {
        Network.requestWillBeSent(async(params) => {
            ds.log("Request ready to be sent " + JSON.stringify(params));
          if (!ds.dsResources[params.requestId]) {
             ds.dsResources[params.requestId] = {};
          }
          ds.dsResources[params.requestId]["request"] = params.request;
          ds.dsResources[params.requestId]["dateStarted"] = new Date();
          ds.dsResources[params.requestId]["requestWillBeSent"] = new Date().getTime();
        });
        
        Network.dataReceived(async(params) => {
            ds.log("Data received " + JSON.stringify(params));
            if (!ds.dsResources[params.requestId]) {
                ds.dsResources[params.requestId] = {};
                ds.log("Data recieved resource not found for " + params.requestId);
            }
          ds.dsResources[params.requestId]["dataReceived"] = new Date().getTime();
        });
        
        Network.requestServedFromCache(async(params) => {
            if (!ds.dsResources[params.requestId]) {
              ds.dsResources[params.requestId] = {};
            }
            ds.log("Request served from cache " + JSON.stringify(params));
            ds.dsResources[params.requestId]["servedFromCache"] = true;
        });
    }
    
    Network.responseReceived(async(params) => {
        ds.log("Response received " + JSON.stringify(params));
      if (!ds.dsResources[params.requestId]) {
        ds.dsResources[params.requestId] = {};
      }
      ds.dsResources[params.requestId]["responseReceived"] = new Date().getTime();
      if(!ds.mainResponse) {
        ds.mainResponse = params.response;
      }                
    });
    
    // Wait for page load event to take screenshot
    Page.loadEventFired(async () => {
      ds.log("-- Page loaded: " + _getNextLapTimeStr(ds));
      await _capture(Page, DOM, ds);
    });
```

**Comment by cyrus-and** [comment]
> blank page with just the html

Possibly related to #174? Can you try again with the latest release?

> So far I have not been able to find a way to get the request of the navigation URL which I provide

I'm not sure I'm fully understanding your problem here, when a resource is fetched from the browser cache the events should be:

1. `Network.requestWillBeSent`
2. `Network.requestServedFromCache`
3. `Network.responseReceived`
4. `Network.dataReceived`
5. `Network.loadingFinished`

`Network.requestWillBeSent` should contain what you need, I guess.

**Comment by anthonymayfield111** [comment]
Thank you for your prompt feedback, unfortunately our network is having some issues so I'm unable to test your suggestion for now.  In regards to the second part it appears to somehow get to requestServedFromCache before requestWillBeSent, however I'll double check once I can successfully make requests again.

**Comment by cyrus-and** [comment]
OK, the order shouldn't really matter as long as you check to have received all the expected messages.

**Comment by cyrus-and** [comment]
Did you get any further with this?
