### ISSUE TITLE
Add a version flag to the CLI

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-remote-interface#177]
the browser isn't always running at localhost, when `chrome-remote-interface -t 172.17.0.2 list` works it talks to the other host where browser is running; but version subcommand still trying talk to localhost

```console
$ ./node_modules/.bin/chrome-remote-interface -t 172.17.0.2 version
Error: connect ECONNREFUSED 127.0.0.1:9222
$ ./node_modules/.bin/chrome-remote-interface version -t 172.17.0.2
Error: connect ECONNREFUSED 127.0.0.1:9222
```

BTW, is it better to have `-v` or `--version` to print its own version? otherwise I have to ask npm or grep to show the version

```console
$ ./node_modules/.bin/chrome-remote-interface -v

  error: unknown option `-v'

$ ./node_modules/.bin/chrome-remote-interface --version

  error: unknown option `--version'
```

```console
$ grep version ./node_modules/chrome-remote-interface/package.json
  "version": "0.15.1"
```

**Comment by c0b** [comment]
sorry I just realized my version is too old; the latest `0.23.3` works; I'm closing this, but the `-v` `--version` to show its own version is still valid;

```console
$ grep version ./tmp/node_modules/chrome-remote-interface/package.json
  "version": "0.23.3"
```

**Comment by cyrus-and** [comment]
Right, it's actually `-V/--version` because this is how [commander.js][1] works.

[1]: https://github.com/tj/commander.js
