### ISSUE TITLE
expose the client (or CDP) in the CLI?

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-remote-interface#178]
when calling the CLI for inspect session, I'm not sure which tab is under inspection? I would like to also have the [`client`](https://github.com/cyrus-and/chrome-remote-interface/blob/master/bin/client.js#L165) available in this session; would be convenient to do something like `client.List` `client.Activate` or attach to a different tab within the same session

```console
$ ./node_modules/.bin/chrome-remote-interface -t 172.17.0.2 inspect
>>> Object.keys(global)
[ 'global',
  'console',
  'process',
  'Buffer',
  'clearImmediate',
  'clearInterval',
  'clearTimeout',
  'setImmediate',
  'setInterval',
  'setTimeout',
  'module',
  'require',
  'Inspector',
  'Memory',
  'Page',
  ...
```

**Comment by cyrus-and** [comment]
While I agree about providing a way to figure out the current tab, I'm not sure about adding the other features for now. First of all it would complicate the CLI which is basically just for convenience, moreover that is a part that would greatly benefit from a full rewrite of the project using the most recent JavaScript features. Such rewrite is planned, I'd postpone the decision to then.

Back to the current tab, considering that it should work for all the [implementations][1], it's not trivial to decide what information provide. I think the only common denominator is the WebSocket URL, although not so informative. Thoughts?

[1]: https://github.com/cyrus-and/chrome-remote-interface#implementations

**Comment by c0b** [comment]
from the CLI list sub-command I can get a list of objects like this, I think this is most complete information about what is current tab under the inspect, so, would be preferred to have some way to print this from inspect shell

```json
    {
        "description": "",
        "devtoolsFrontendUrl": "/devtools/inspector.html?ws=172.17.0.2:9222/devtools/page/3f392077-bff7-4f47-8383-1b6e390a91fd",
        "faviconUrl": "https://www.google.com/favicon.ico",
        "id": "3f392077-bff7-4f47-8383-1b6e390a91fd",
        "title": "New Tab",
        "type": "page",
        "url": "chrome://newtab/",
        "webSocketDebuggerUrl": "ws://172.17.0.2:9222/devtools/page/3f392077-bff7-4f47-8383-1b6e390a91fd"
    }
```

**Comment by cyrus-and** [comment]
The problem is that there are many ways to specify the target: by id, by WebSocket, etc. and that object you mentioned is not always directly available. I couldn't fetch it from the list by using the WebSocket URL to do the lookup because when a target is being inspected the `webSocketDebuggerUrl` field is not present.

A possibility would be to extract the id from the WebSocket URL but the format is not documented anywhere, and in any case it's not consistent among all the implementations (e.g., Node.js).

**Comment by cyrus-and** [comment]
I'm inclined to add the `.target` special command that prints the current WebSocket URL:

```
>>> .target
ws://localhost:9222/devtools/page/ac252852-302f-4d94-9cda-8d2913c04a60
```
