### ISSUE TITLE
can you use this client side in a chrome debugger extension?

### ISSUE THREAD

**Issue by faceyspacey** [cyrus-and/chrome-remote-interface#18]

**Comment by cyrus-and** [comment]
I'm not sure to fully understand what you're asking. This module allows you to attach to any *tab* shown at `http://localhost:9222/json`, this list also includes the background pages of the currently available Chrome extensions.

For example the following snippet will fetch the console messages of a given extension:

```js
var Chrome = require('chrome-remote-interface');

var extensionId = '<<< EXTENSION ID HERE >>>';
var options = {
    'chooseTab': function (tabs) {
        for (var i = 0; i < tabs.length; i++) {
            if (tabs[i].url.startsWith('chrome-extension://' + extensionId + '/')) {
                return i;
            }
        }
    }
};

Chrome(options, function (chrome) {
    chrome.Console.enable();
    chrome.Console.messageAdded(function (event) {
        var text = event.message.parameters.map(function (parameter) {
            return parameter.value;
        }).join(' ');
        console.log(text);
    });
});
```

Please note that the usual rule apply: you cannot attach to a *tab* if there is already an instance of DevTools attached to it.

Please let me know if this is what you had in mind.

**Comment by faceyspacey** [comment]
Awesome. I assume that code is supposed to run in, say, an Electron app, but is there a way to get the same library into a chrome extension that is debugging other pages? Are all the feature available within a chrome extension or just debugging?

**Comment by cyrus-and** [comment]
This module is just a wrapper around the [Remote Debugging Protocol](https://developer.chrome.com/devtools/docs/protocol/1.1/index); quoting the documentation:

> You can either debug over the wire using the raw messages as they are described in the corresponding domain documentation, or use extension JavaScript API.

I think you want [the latter](https://developer.chrome.com/devtools/docs/debugger-protocol#extension), basically you can write a Chrome extension which uses the [`chrome.debugger`](https://developer.chrome.com/extensions/debugger) module. You should then be able to interact with the same protocol using `chrome.debugger.sendCommand` and the event system. I've never tried though...

**Comment by faceyspacey** [comment]
chrome extension api is slightly different though, so if you built around this sockets message api, you could then port your code from a chrome extension to electron or NW.

**Comment by cyrus-and** [comment]
I have no experience with Electron apps but for what concerns the Remote Debugging Protocol, its API is quite simple, it should not be a problem to port it to fit your needs. The point is that there are just two ways to use it:

1. WebSocket (chrome-remote-interface);
2. Chrome extension.

**Comment by faceyspacey** [comment]
cool. Do you know if Node-Inspector communicates to node by a similar protocol? Do you know of any attempts to create an interface that works for both the Remote Debugging Protocol and Node?

**Comment by cyrus-and** [comment]
AFAIK, there's no such thing. You might try to ping the guys at the [google-chrome-developer-tools](https://groups.google.com/forum/#!forum/google-chrome-developer-tools) group.
