### ISSUE TITLE
Scroll to specific area to perform mouse actions

### ISSUE THREAD

**Issue by saurabh2590** [cyrus-and/chrome-remote-interface#180]
Hi, 
We are successfully using Chrome Remote interface into our project for performing screenshot testing. 
We are also able to take "mouseHover" screenshots of specific elements on the page.  That is after dispatching the "mouseHoever" Input events, the state of the element on page changes and the screenshot is successful.
However, if  the element is outside the browser Viewport area, the input events are not dispatched.
Is there a specific way to handle that we can scroll to the specific element on the page and then dispatch 'mouseHover'?

**Comment by cyrus-and** [comment]
There's no need  to trigger a synthetic mouse event, you can just force CSS pseudo states just like DevTools does:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {CSS, DOM} = client;
    try {
        await DOM.enable();
        await CSS.enable();
        const {root} = await DOM.getDocument();
        const {nodeId} = await DOM.querySelector({
            nodeId: root.nodeId,
            selector: 'body'
        });
        await CSS.forcePseudoState({
            nodeId,
            forcedPseudoClasses: ['hover']
        });
        //////////////////////////////
        // take the screenshot here //
        //////////////////////////////
    } catch (err) {
        console.error(err);
    } finally {
        // pseudo state override reverts on disconnection
        // client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by saurabh2590** [comment]
Thank you for your quick response. It really helped me to move forward. However, I have to really dispatch some mouse actions below the visible viewport of the browser? Is there any way to scroll.
I was trying:
```
const {DOM, Emulation, Network, Page, Input, CSS, Target, Browser} = client;
const {targetInfos} = await Target.getTargets();
// Since I knew it's first arget.
const {targetId} = targetInfo[0];
const {windowId} = await Browser.getWindowForTarget({targetId});
Browser.setWindowBounds({targetId, bouds});
```
However, I am getting error `'Browser.getWindowForTarget' wasn't found`

**Comment by cyrus-and** [comment]
> However, I am getting error 'Browser.getWindowForTarget' wasn't found.

Looks like a Chrome bug, see #131.

About scrolling, you can always inject some JavaScript to do that, using [`Runtime.evaluate`][1], for example:

```js
await Runtime.evaluate({
    expression: `document.querySelector('#foo').scrollIntoView()`
});
```

You also may want to experiment with [`Emulation.forceViewport`][2].

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-forceViewport

**Comment by saurabh2590** [comment]
Thank you for your pointers. I did try `Emulation.forceViewport` but it works well when taking screenshots but it didn't work well with triggering `mouseEvents`. But I guess it  is because [Emulation.forceViewport](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-forceViewport) documentation says clearly that "the observable scroll position and page scale does not change".

**Comment by cyrus-and** [comment]
What about `scrollIntoView()`?

**Comment by saurabh2590** [comment]
Yup, Thank you for your pointer. I totally missed the fact that standard browser functions are still available using `Runtime`
