### ISSUE TITLE
Is it possible to ignore self signed certificates?

### ISSUE THREAD

**Issue by anzeznidarsic** [cyrus-and/chrome-remote-interface#183]
Hi,

great job on this repository. I'm making screenshots of an intranet system that is using self signed ssl certificate. I'm using your library with Chrome Stable headless mode on Ubuntu 16.04 server.

I can see that Chromium team added a way to ignore certificate errors https://bugs.chromium.org/p/chromium/issues/detail?id=659662
but I'm not familiar with the tooling enough to figure this out (how to use it with CRI).

Any help would be greatly appreciated. Thank you.

**Comment by cyrus-and** [comment]
Hey thanks! :)

Have you tried this [wiki recipe][1]?

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Bypass-certificate-errors-(%22Your-connection-is-not-private%22)

**Comment by jdat82** [comment]
Regarding this recipe (bypass certificates errors), is this supposed to work out of the box with Chrome 59 ? In CDPV documentation, the stable version (1.2) has no Security domain.

**Comment by cyrus-and** [comment]
@jdat82 yes it should, the stable version of the CDP doesn't correspond to the stable version of Chrome, it just means that things there won't change in the future.

**Comment by jdat82** [comment]
Sorry, I'm not following. It is my understanding that CDP 1.2 is the default when using CRI. Am I right? 

According to this [documentation](https://chromedevtools.github.io/devtools-protocol/1-2/), there is no security domain.

**Comment by jdat82** [comment]
OK, I understand now. Thanks.

**Comment by anzeznidarsic** [comment]
Thank you, it worked! Where can I send the beer? :)

**Comment by shunwen** [comment]
I was getting blank screenshot from my internal test site with bad certificates. The wiki recipe works for me!
