### ISSUE TITLE
Wait until page is fully loaded?

### ISSUE THREAD

**Issue by jvilla32** [cyrus-and/chrome-remote-interface#184]
I would like to wait for the graphs on my webpage to fully load before making a PDF, and "await Page.loadEventFired();" doesn't seem suitable for the job. 

Is there any API available for determining when a page is fully loaded, or do I need to wait for a specific element to appear in the DOM?

**Comment by cyrus-and** [comment]
Whether a page is *fully* loaded (besides `Page.loadEventFired`) is not  something that can be understood by Chrome. You'll need to implement your own check, e.g., an HTML element appears, a JavaScript object has a certain property, etc.

In any case everything boils down to start and await a promise in `Runtime.evaluate` which gets fulfilled when your custom event triggers.

```js
await Runtime.evaluate({
    expression: `new Promise((fulfill, reject) => {
        /*...*/
    })`,
    awaitPromise: true
});
```

See this [wiki recipe][1].

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element

**Comment by jvilla32** [comment]
Thank you

**Comment by jvilla32** [comment]
@cyrus-and Do you know if there is a way to listen for alerts rather than modify an element/object?

**Comment by cyrus-and** [comment]
Using [Page.handleJavaScriptDialog][1], see [this comment][2], in this case you don't need to inject JavaScript code with `Runtime.evaluate`.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-handleJavaScriptDialog
[2]: https://github.com/cyrus-and/chrome-remote-interface/issues/130#issuecomment-302952122
