### ISSUE TITLE
Multiple clients for one target [CDP + real dev tools]

### ISSUE THREAD

**Issue by Bnaya** [cyrus-and/chrome-remote-interface#186]
I want to use `CDP` and also to be able to connect the headless chrome with dev tools (via chrome://inspect or whatever)
is it a possible setup?

Thanks!

**Comment by cyrus-and** [comment]
Unfortunately that's not possible, see "Simultaneous protocol clients" [here][1].

[1]: https://chromedevtools.github.io/devtools-protocol/

**Comment by johnspackman** [comment]
@Bnaya I have a fix for this - please try https://github.com/johnspackman/chrome-remote-multiplex  I've just released to solve exactly this problem.

**Comment by cyrus-and** [comment]
@johnspackman awesome, thanks for sharing!

**Comment by Bnaya** [comment]
GRATE!! i will take a look
