### ISSUE TITLE
Any way to allow only whitelisted requests? Or correct way to use setRequestInterceptionEnabled?

### ISSUE THREAD

**Issue by darvydas** [cyrus-and/chrome-remote-interface#191]
The purpose is to allow only whitelisted HTTP requests. I'd like to pass any request to be made to a function and reject/stop any requested URLs that don't match a simple RegEx.

**CDP.version:**
```
{
   "Browser": "HeadlessChrome/59.0.3071.104",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/59.0.3071.104 Safari/537.36",
   "V8-Version": "5.9.211.35",
   "WebKit-Version": "537.36 (@1c037b7399035b4209e72455256615e8972493aa)"
}
```
**Chrome-remote-interface:** `"chrome-remote-interface": "^0.23.2"`

Have tried a couple of methods with dead ends:
1. Using `Network.setBlockedURLs({ urls: urlsList })` - good if you know blocking URLs in advance (not in my case).
2. Using `Network.requestWillBeSent`. Are there any way to block request at this stage? It can easily extract the request information that is needed, but I haven't found how I could stop the requests from continuing.
3. Using `Network.enableRequestInterception` from [chrome-remote-interface protocol file](https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/protocol.json) or `Network.setRequestInterceptionEnabled` from [Chrome DevTools Protocol Viewer - latest (tip-of-tree)](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setRequestInterceptionEnabled) with no success and the same errors:
`Error: 'NetworkAgent.enableRequestInterception' wasn't found`
`Error: 'Network.setRequestInterceptionEnabled' wasn't found`
Even tried sending the same command as a `client.send(method, [params], [callback])` from the [docs](https://github.com/cyrus-and/chrome-remote-interface#clientsendmethod-params-callback) with no luck.

I've stumbled upon [this Google Doc](https://docs.google.com/document/d/1nEN0SqC1jEpHgKuQPrppwSabC8JRAuJb7MSTGCe2Pzg/edit#) explaining that Interception are meant for Blocking and Modifying Network requests so probably the best way would be to use that one and I'm simply not aren't using it correctly.

Could you specify an example on _how to properly use request Interceptions_?

**Comment by darvydas** [comment]
Sorry for the issue. 

**Updating Chromium to latest Dev and chrome-remote-interface versions helped.**

Working part: 
```javascript 
Network.enableRequestInterception({ enabled: true });
```

_CDP.version:_
`{
   "Browser": "HeadlessChrome/61.0.3141.7",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/61.0.3141.7 Safari/537.36",
   "V8-Version": "6.1.266",
   "WebKit-Version": "537.36 (@d5df4ad8983872374dad86bee9d1fa31299114f7)"
}`

_Chrome-remote-interface:_ 
`"chrome-remote-interface": "^0.24.1"`

Anyway, I haven't found any documentation about Interception. Would be great to have an example on [Wiki page](https://github.com/cyrus-and/chrome-remote-interface/wiki).

**Comment by cyrus-and** [comment]
[Here it is][1], hope it helps.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL

**Comment by 525118978** [comment]
Can I intercept the Response ?

**Comment by cyrus-and** [comment]
@525118978 for what purpose? You can intercept the "request" at a different [stage][1] that is `HeadersReceived` so you can, for example, make decisions according to the response headers.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network#type-InterceptionStage

**Comment by 525118978** [comment]
Thank you. I just want to know if I can intercept response.

**Comment by paulirish** [comment]
The protocol makes this quite challenging, tbh. We've been discussing making it easier but so far it's just discussion.

**Comment by conanF** [comment]
When multiple processes manipulate the same tab of chrome, can we ensure that these processes do not interfere with each other by obtaining browser status.

**Comment by conanF** [comment]
How to add a lock to the browser？

**Comment by paambaati** [comment]
@paulirish Is there a public discussion that we can subscribe/bookmark/follow?
