### ISSUE TITLE
Load state not affecting PDF capture

### ISSUE THREAD

**Issue by jvilla32** [cyrus-and/chrome-remote-interface#192]
I'm running the [Wait for a specific element](https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element) recipe, where I take a PDF of the site after waiting between 3 and 60 seconds. However, the PDF looks nearly identical every time - a partially loaded progress bar, which I would typically take 2 seconds to load on a GUI browser.

The modified code is:

        await nodeAppears(client, 'div#foo');
        await Page.enable();
        await Page.navigate({url: 'https://nite-www.sumologic.net/ui/dashboard.html?k=cdyDcDAhNLYplEq7Ky8E7OMfAFV9oHeeU1f5J1gl4pwCFwumQLqT5PyUv1EW&t=r'});
        await Page.loadEventFired();

        const {data} = await Page.printToPDF({
            landscape: true,
            printBackground: true,
            marginTop: 0,
            marginBottom: 0,
            marginLeft: 0,
            marginRight: 0
        });
        fs.writeFileSync('test.pdf', Buffer.from(data, 'base64'));

I've confirmed that the PDF function is not called until after the set timeout in demo(). Does anyone know why this might happen?

**Comment by cyrus-and** [comment]
You should call `nodeAppears` after `await Page.loadEventFired()` otherwise the page load will invalidate (collect) the promise.

Anyway, it still doesn't work as is, it seems that the `MutationObserver` doesn't catch the modification, that's possibly because your case is more complex than that simple demo example, so you have to fiddle with the `MutationObserver`'s [options][1].

It's not about the PDF generation IMO, you can test it with a simple print:

```js
await Page.enable();
await Page.navigate({url: '...'});
await Page.domContentEventFired();
await nodeAppears(client, 'div.iris-content'); // you can pick another one
console.log('Triggered!');
```

[1]: https://developer.mozilla.org/en/docs/Web/API/MutationObserver#MutationObserverInit

**Comment by cyrus-and** [comment]
While the following seems to work, it kind of nullify the advantage of using a `MutationObserver` since it queries the whole DOM for each mutation:

```js
async function nodeAppears(client, selector) {
    // browser code to register and parse mutations
    const browserCode = (selector) => {
        return new Promise((fulfill, reject) => {
            // shortcut if already present
            if (document.documentElement.querySelector(selector)) {
                fulfill();
                return;
            }
            // setup the observer
            new MutationObserver((mutations, observer) => {
                // add all the new nodes
                const nodes = [];
                mutations.forEach((mutation) => {
                    nodes.push(...mutation.addedNodes);
                });
                // fulfills if at least one mutation contains the selector
                if (nodes.find((node) => {
                    return node.parentElement
                        && node.parentElement.querySelector
                        && node.parentElement.querySelector(selector);
                })) {
                    observer.disconnect();
                    fulfill();
                }
            }).observe(document.documentElement, {
                childList: true,
                subtree: true
            });
        });
    };
    // inject the browser code
    const {Runtime} = client;
    await Runtime.evaluate({
        expression: `(${browserCode})(${JSON.stringify(selector)})`,
        awaitPromise: true
    });
}
```

I suggest you to experiment with the `MutationObserver` API; if you follow the advice in my [previous comment][1] then it's just a matter of catching the proper mutation event.

You may also want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/192#issuecomment-314418965

**Comment by jvilla32** [comment]
Hey @cyrus-and, I'm not quite sure what you're doing differently in the second comment, but simply putting `nodeAppears` after `await Page.loadEventFired()` fixed the issue for me. Thanks for your help.

**Comment by cyrus-and** [comment]
> I'm not quite sure what you're doing differently in the second comment

`node.parentElement.querySelector(selector)` instead of `node.matches(selector)`

Great, you're welcome!

**Comment by vichajser** [comment]
Error:  `document ` and  `MutationObserver ` were undefined?

**Comment by cyrus-and** [comment]
@vichajser I don't what you're trying but that code is meant to be run in the browser, Node.js has no `document` or `MutationObserver`.

**Comment by vichajser** [comment]
I am trying to detect whether a page is loaded (including pictures, JS, I need the asynchronous resource) after all the resources request, do the operation of printPDF, and the DOM node of this page is dynamic rendering
So, how do I make sure that all the resources on the page are loaded fully to make sure that the PDF generated by printPDF is not missing?
Checking the DOM element node is just one way I'm trying

**Comment by cyrus-and** [comment]
@vichajser then you're on the right track and the mentioned [wiki][1] should be what you want. I just can't see how `document` can be undefined in the browser context.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element
