### ISSUE TITLE
Unstable Input.dispatchMouseEvent

### ISSUE THREAD

**Issue by clujin** [cyrus-and/chrome-remote-interface#193]
I'm currently trying to get a mouse click to work with the following params:

```
{
    button: 'left',
    clickCount: 1,
    type: 'mousePressed',
    x: 55,
    y: 55
}
```

For some reason, the headless chrome crashes (on both stable v59 and canary). I am using the latest remote interface '0.24.1'. The error report I got from OSX is as follows. Something about an unrecognized selector. I can provide the more verbose backtrace if needed. 

Also, on a side note, is there an option to restart Chrome if it crashes? It would be really useful for these situations. 

<pre>
Process:               Google Chrome [41632]
Path:                  /Users/USER/*/Google Chrome.app/Contents/MacOS/Google Chrome
Identifier:            com.google.Chrome
Version:               59.0.3071.115 (3071.115)
Code Type:             X86-64 (Native)
Parent Process:        node [41630]
Responsible:           Google Chrome [41632]
User ID:               502

Date/Time:             2017-07-10 21:58:23.024 -0700
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        EA02703F-27EB-D386-9BC9-F146A4BDA2C3

Sleep/Wake UUID:       CDBAC4BA-741C-4682-B203-8F62CF5EB756

Time Awake Since Boot: 79000 seconds
Time Since Wake:       8300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: -[HeadlessShellCrApplication setHandlingSendEvent:]: unrecognized selector sent to instance 0x7fec88f072d0
</pre>

**Comment by cyrus-and** [comment]
You should really file the issue [here][1], this is just a Node.js support library.

[1]: https://bugs.chromium.org/p/chromium/issues/
