### ISSUE TITLE
Command timeout

### ISSUE THREAD

**Issue by Janpot** [cyrus-and/chrome-remote-interface#194]
Under some circumstances I find devtool commands timing out. It'd be nice if this could be handled by the library. Now I have to wrap every command with timeout code.

**Comment by cyrus-and** [comment]
> Under some circumstances I find devtool commands timing out.

Can you provide an example scenario?

> It'd be nice if this could be handled by the library.

So, for instance, aborting the request if the [timeout][1] triggers?

[1]: https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback

**Comment by Janpot** [comment]
> Can you provide an example scenario?

Unfortunately I can't reproduce yet, I'm only seeing this behavior on production load. Right now I've wrapped some `send`s with a timeout and see those failing in the logs.

> So, for instance, aborting the request if the timeout triggers?

Exactly, rejecting the promise with an error

**Comment by cyrus-and** [comment]
> Right now I've wrapped some `send`s with a timeout and see those failing in the logs.

Are we talking about DevTools methods only (`CDP.*`) or even protocol methods (`client.*`)?

**Comment by Janpot** [comment]
I'm talking about protocol methods.

**Comment by cyrus-and** [comment]
I was asking because you mentioned `send`. d99f0394549607d82b85aeb72457094409afdc20 should do, you can test it with `nc -lp 9222` or similar.

**Comment by Janpot** [comment]
That's quick, very nice, thanks 👍

**Comment by Janpot** [comment]
@cyrus-and ah, wait, this is only for the Devtools methods (`CDP.*`)? I was actually talking about the client methods, when Chrome for some reason never responds the rpc call. Also, I'd make this doesn't create a promise that's never resolved. As far as I can see `.abort()` doesn't trigger an error.

**Comment by cyrus-and** [comment]
> ah, wait, this is only for the Devtools methods (CDP.*)? I was actually talking about the client methods, when Chrome for some reason never responds the rpc call.

Oh yes, misread sorry, I even asked you... :)

The situation is more complicated then, if Chrome fails to reply to a command it may be that the reply is not ready yet and that could, in principle, take an arbitrary amount of time to resolve, e.g., `Runtime.evaluate` with `awaitPromise` set to `true`. So I cannot just embed a timeout in the commands.

The question is, are we trying to handle the case in which Chrome fails to reply to a single command **but** others (for the same target) work as expected, or the case in which Chrome become unresponsive for one or more targets?

The former is impossible to handle reliably IMHO.

> As far as I can see .abort() doesn't trigger an error.

The promise is rejected as soon as the `abort()` is called. Try running the following after running `nc -lp 9222` (on Linux).

```js
const CDP = require('chrome-remote-interface');

CDP.List().then(() => {
    console.log('OK');
}).catch((err) => {
    console.error(err);
});
```

**Comment by Janpot** [comment]
I'm specifically trying to handle unresponsive targets

**Comment by cyrus-and** [comment]
Well even in that case it's not so easy, the timeout introduced in d99f0394549607d82b85aeb72457094409afdc20 works at socket level and it's reasonable because the DevTools (`/json/*` endpoints) interaction is supposed to be immediate, so inactivity for more than, say, 10 seconds is to be considered a server *failure*. (Please note that server crashes are handled anyway; server up but not responding is a more subtle scenario.)

The same doesn't apply for the WebSocket, I mean where should I put the timeout?

If a socket-level idle timeout is really what you need, you can do the following, it's not documented, but there's no reason for me to change the internals.

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    //////////////////////////////////////////////////
    client._ws._socket.setTimeout(5000, function () {
        this.destroy();
        // place additional logging/handling here
    });
    //////////////////////////////////////////////////
    try {
        // just something that keeps the session open...
        const {Runtime} = client;
        await Runtime.evaluate({
            expression: `new Promise((fulfill, reject) => setTimeout(fulfill, 10000))`,
            awaitPromise: true
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

What happens here is that when the idle timeout triggers, the underlying TCP socket is forcibly terminated and the Node.js process is terminated as there's nothing (sockets, timers, etc.) to keep it alive.

I don't feel like to officially support it the following via the API though.
