### ISSUE TITLE
Access scroll height with remote interface

### ISSUE THREAD

**Issue by jvilla32** [cyrus-and/chrome-remote-interface#195]
Does anyone know if it is possible to view the content in the DOM from the remote interface? As far as I can tell from spending a day with the DOM functions, they only return nodes, which do not show you the content in document.body. I'm specifically looking for the height of the web page, and believe accessing the DOM is the most straightforward way.

**Comment by paulirish** [comment]
Runtime.evaluate is probably the most direct route for that sort of thing. Just run some clientside script to get the value and and pass that back.

**Comment by jvilla32** [comment]
Getting the value client side seems like a good idea. Do you have a recommended method for passing the information back?

**Comment by cyrus-and** [comment]
@jvilla32 it should be quite straightforward once you use [`Runtime.evaluate`][1]:

```js
const {result: {value}} = await Runtime.evaluate({
    expression: 'document.body.scrollHeight'
});
console.log(value);
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate
