### ISSUE TITLE
Chrome unresponsive and error conditions handling

### ISSUE THREAD

**Issue by vnsrahul1304** [cyrus-and/chrome-remote-interface#196]
#Question
Is there any way to check if the chrome gets unresponsive?
And also we are interested in checking, if a url opens properly in a tab or throws any error like network error or proxy block error.
And what if a particular resource only throws error?
Any suggestion would be greatly appreciable.

**Comment by cyrus-and** [comment]
> Is there any way to check if the chrome gets unresponsive?

What would be the case? Error/bogus situations are unreliable by definition, you can't really count on it. A possibility would be to check some trivial HTTP endpoint/methods, e.g., `CDP.Version` or, say, `Target.getTargets` (possibly with a timeout).

Let's say that Chrome shouldn't become unresponsive, if that's the case then it's a bug that you should report to the Chromium team.

> And also we are interested in checking, if a url opens properly in a tab or throws any error like network error or proxy block error.

Any URL loaded is just a resource, so loading failure can be checked with [`Network.loadingFailed`][1] for the *original* URL, i.e., the first request after [`Page.navigate`][2].

> And what if a particular resource only throws error?

See above.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFailed
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-navigate

**Comment by kevinelliott** [comment]
@cyrus-and Any way we can detect the very original `Page.navigate` in `Network.loadingFailed`? I implemented a handler for `Network.loadingFailed` but some pages seem to either have embedded `IFRAME`s or perhaps redirects that are triggering it with type of `Document` too. Perhaps by storing the first `Page.navigate`'s `requestId`. Is this possible?

**Comment by cyrus-and** [comment]
> Perhaps by storing the first Page.navigate's requestId. Is this possible?

Yes I guess you have to keep track of the request id and manually make the association.
