### ISSUE TITLE
New target on another port

### ISSUE THREAD

**Issue by hgfdd** [cyrus-and/chrome-remote-interface#197]
Hello! I'm trying to make several parallel workers to request chrome for their own new targets. How can i make to work this example to the port different, than 9222:

```
const CDP = require('chrome-remote-interface');

CDP.New().then((target) => {
    return CDP({target});
}).then((client) => {
    return client.Runtime.evaluate({
        expression: 'alert("Closing this tab...")'
    }).then(() => {
        const id = client.target.id;
        return CDP.Close({id});
    });
}).catch((err) => {
    console.error(err);
});

```

Hope on your responce!

**Comment by cyrus-and** [comment]
By specifying the port in [`CDP.New({port})`][1] and [`CDP.Close({port, id})`][2].

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpnewoptions-callback
[2]: https://github.com/cyrus-and/chrome-remote-interface#cdpcloseoptions-callback
