### ISSUE TITLE
Network.setRequestInterceptionEnabled not available

### ISSUE THREAD

**Issue by fatfatson** [cyrus-and/chrome-remote-interface#198]
if use builtin protocol, get error "TypeError: Network.setRequestInterceptionEnabled is not a function",
if use the latest from officialsite, get error "Error: 'Network.setRequestInterceptionEnabled' wasn't found"

os:macos10.12
chrome:59.0.3071.115 64bit

**Comment by cyrus-and** [comment]
You need Chrome 61 in order to do that, see this [wiki][1].

(Make sure to update to the latest chrome-remote-interface version or you'll have to use `CDP({remote: true}, ...`)

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL
