### ISSUE TITLE
Unsure if commands are working?

### ISSUE THREAD

**Issue by thearegee** [cyrus-and/chrome-remote-interface#199]
Hello, 
I'm pretty new to DevTools protocol, I'm having some issues understanding if what I want to happen is happening. Just wondering if I could get some help: 

Below is a small code sample where I am trying to set the userAgent and throttle the CPU.

```Javascript
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

function launchChrome(headless = false) {
  return chromeLauncher.launch({
    chromeFlags: [
      '--disable-gpu',
      headless ? '--headless' : ''
    ]
  });
}

const NEXUS5X_USERAGENT = {
  userAgent: 'Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MRA58N) AppleWebKit/537.36' +
    '(KHTML, like Gecko) Chrome/61.0.3116.0 Mobile Safari/537.36'
};

async function init() {
  try {
    const chrome = await launchChrome();
    const client = await CDP({ port: chrome.port });
    const { Network, Emulation, Page } = client;

    Network.requestWillBeSent(params => {
      console.log(params.request.url);
    });
    
    Network.setUserAgentOverride(NEXUS5X_USERAGENT);
    Emulation.setCPUThrottlingRate({ rate: 4 });
    
    await Promise.all([Network.enable(), Page.enable()]);
    await Page.navigate({ url: 'http://localhost:3000' });
    await Page.loadEventFired();
    
    const version = await CDP.Version({ port: chrome.port });
    console.log(version);

    // chrome.kill();
  } catch (err) {
    console.error(err);
  }
}

init();
```
So when I log the version:

```Javascript
const version = await CDP.Version({ port: chrome.port });
```

It is never updated, and when I run:
```Javascript
 navigator.userAgent
```
Within the browser it also has not changed? The CPU throttling has also not been configured.

Am I doing something stupid?

Any help would be awesome, thanks.

**Comment by cyrus-and** [comment]
Hello! First thing first you should `await` all the methods returning a `Promise` in order to ensure the proper order and to catch errors:

```js
await Network.setUserAgentOverride(NEXUS5X_USERAGENT);
await Emulation.setCPUThrottlingRate({ rate: 4 });
```

The user agent override does work and you can check it with:

```js
await Runtime.evaluate({expression: 'navigator.userAgent'});
```

(Or even better by navigating to https://httpbin.org/user-agent.)

The override scope is the current session so you will not see the difference using `CDP.Version`, and for the same reason you don't see it changed when you manually evaluate `navigator.userAgent` in the console.

Hope it helps!

**Comment by thearegee** [comment]
Hey @cyrus-and this is awesome thanks, the scope point was super useful. I have this working now, one last question - sorry :)

If I have an async function running in my browser, is there anyway to get the Runtime evaluate to await that until it resolves? I assume not because I'm in a different scope, so would the best way to just be keep polling until complete?

Thanks

**Comment by cyrus-and** [comment]
> If I have an async function running in my browser, is there anyway to get the Runtime evaluate to await that until it resolves? I assume not because I'm in a different scope, so would the best way to just be keep polling until complete?

There is! And it's very useful actually (see [`Runtime.evaluate`][1]):

```js
await Runtime.evaluate({
    awaitPromise: true,
    expression: `new Promise((fulfill, reject) => {
        setTimeout(fulfill, 1000);
    })`
});
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by thearegee** [comment]
amazing! Thanks so much, I've got it all working 😄

**Comment by cyrus-and** [comment]
Great, you're welcome!
