### ISSUE TITLE
Dynamic port to profile

### ISSUE THREAD

**Issue by Xhings** [cyrus-and/chrome-remote-interface#20]
Hi there,

Not sure if this is a bug but anyways let me put forward what i am trying to do using the interface. Let me know if I am missing anything obvious.

I am trying to automate chrome using webdriver and webdriver opens chrome on any random port, which can not be forced as of now (a bug). I want to read the port it opens the chrome in and pass that to chrome-remote-interface every time. I tried changing the port in defaults.js with the new port after chrome opens but it did not work. Do you have any suggestions in make debugging port dynamic?

Thanks,
Xhings

**Comment by cyrus-and** [comment]
Hi, you can specify the port by setting the [`port` option][1]. For example:

```js
Chrome({'port': 12345}, function (chrome) {/*...*/});
```

Same goes for `host`.

Does this fix your issue?

[1]: https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback

**Comment by Xhings** [comment]
Thanks for the quick reply. Did help!!
