### ISSUE TITLE
Throw an error when CDP.Close({ id })

### ISSUE THREAD

**Issue by LichFaker** [cyrus-and/chrome-remote-interface#206]
The error message is ：
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }

But it is fine without `CDP.Close({ id })`

**Comment by LichFaker** [comment]
Solved this problem by:
```
const id = client.target.id;
Target.closeTarget({targetId: id});
```
And now I don't think the demo code in [Inspect-a-new-tab](https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab) will work fine. Maybe should replaced by `Target.closeTarget({targetId: id})`.

thx anyway :)

**Comment by cyrus-and** [comment]
That code snippet seems to work fine to me. `Target.closeTarget` may be equivalent but it's not the same, e.g., being a protocol command (as opposed to an HTTP method) it requires an established connection (`client`).

**Comment by LichFaker** [comment]
sorry, I forgot to set port when use `CDP.Close`. Btw, the demo code in wiki can't run directly on my mac. And the following code worked fine.
```
CDP.New({port: chrome.port}).then((target) => {
    return CDP({target});
}).then((client) => {
    return client.Runtime.evaluate({
        expression: 'alert("Closing this tab...")'
    }).then(() => {
        const id = client.target.id;
        return CDP.Close({id:id, port:chrome.port});
    });
}).catch((err) => {
    console.error(err);
});
```

**Comment by cyrus-and** [comment]
It doesn't because it assumes the default port to be used being a demo code in a wiki. This other [recipe][1] deals with nonstandard endpoints.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Connect-to-non-standard-endpoints
