### ISSUE TITLE
Page.printToPdf does not finish in Docker

### ISSUE THREAD

**Issue by VlVl** [cyrus-and/chrome-remote-interface#207]
| Component | Version
|-|-
| **Operating system**	   	| Ubuntu 16.04.2 LTS
| **Node.js**				| v7.10.0
| **Chrome/Chromium/...**	| Google Chrome 61.0.3135.4 dev
| **chrome-remote-interface**	| 0.23.2

Good evening. I use docker container with ubuntu, Google Chrome and node.js app to save webpages to pdf. It works fine, but i can not print [this page](https://vlvl.github.io/). `Page.printToPdf` does not finish - there is not any response or exception.

JS:

```js
await Page.navigate({ url });
await Page.loadEventFired();

const { data } = await Page.printToPDF({
  marginTop: 0,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  printBackground: true,
  displayHeaderFooter: false,
  landscape: true,
  // A4
  paperWidth: 8.27,
  paperHeight: 11.69,
 });
```

Dockerfile:

```dockerfile
FROM ubuntu:latest

RUN apt-get update --fix-missing && apt-get -y upgrade &&\
apt-get install -y sudo curl wget unzip git

RUN curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - &&\
sudo apt-get install -y nodejs

RUN npm --global install yarn

RUN set -xe \
    && curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
    && apt-get update \
    && apt-get install -y google-chrome-unstable \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by cyrus-and** [comment]
Hi, are you sure the program is blocked on the `Page.printToPdf`, i.e., the `Page.loadEventFired` triggers?

In my local Linux machine (not Docker) it works, it's quite slow though it takes me about 20 seconds to complete. Is it possible that it's just slow in your case? Try checking the CPU load.

BTW I'm using [this][1] code but using your URL and parameters.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Print-page-to-PDF

**Comment by VlVl** [comment]
Good day! Thanx for answer. 
This morning I tried to print this page in my local Linux machine (not docker) - and it works)
Could you give me a cue why it does not work in docker? Not enouth memory?

**Comment by cyrus-and** [comment]
> Could you give me a cue why it does not work in docker? Not enouth memory?

Yeah, definitely that can be a problem, see #147 (especially [from this comment][1]).

[This][2] is the upstream issue and [this][3] is a possible solution.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/147#issuecomment-306711167
[2]:https://bugs.chromium.org/p/chromium/issues/detail?id=730995
[3]: https://github.com/cyrus-and/chrome-remote-interface/issues/147#issuecomment-307025442

**Comment by VlVl** [comment]
Thanks a lot!
