### ISSUE TITLE
[Question]: accessing multiple instances of Chrome (reverse-)proxied by Nginx?

### ISSUE THREAD

**Issue by gyula-ny** [cyrus-and/chrome-remote-interface#208]
| Component | Version
|-|-
| **Operating system**	   	| Ubuntu 16.04
| **Node.js**				| 8.1.3
| **Chrome/Chromium/...**	| 60.0.3112.50-1
| **chrome-remote-interface**	| 0.24.0

I've currently got two containers (using LXC/LXD) each running a headless Chrome instance and their IPs defined (with port 9222) in an "upstream" block in Nginx config.

The host has Nginx listening on 127.0.0.1:9222 and proxy_pass'ing requests to this upstream of multiple instances. (The _name_ of the nginx upstream block is "lxd" - it should not be important, but it turns out it is. As for the nginx config I use one of the many online examples for websocket proxying by nginx)

When using the cli/bundled client I get:

```
$ chrome-remote-interface new http://github.com
{
    "description": "",
    "devtoolsFrontendUrl": "/devtools/inspector.html?ws=lxd/devtools/page/a862971f-b611-4f63-9aba-57fb4e597576",
    "id": "a862971f-b611-4f63-9aba-57fb4e597576",
    "title": "",
    "type": "page",
    "url": "http://github.com/",
    "webSocketDebuggerUrl": "ws://lxd/devtools/page/a862971f-b611-4f63-9aba-57fb4e597576"
}
```
The page opens in one of the containers as confirmed by looking at their logs and the returned JSON - but the ws URL has "lxd" in it (??!!) (which is the name of the upstream).

When instead I try to use one of the examples of the Wiki - https://github.com/cyrus-and/chrome-remote-interface/wiki/Async-await-example - I got a DNS resolution error thrown: cannot resolve "lxd".

```
{ Error: getaddrinfo ENOTFOUND lxd lxd:80
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'lxd',
  host: 'lxd',
  port: 80 }

```

(my Nginx config has this block:
```
upstream lxd {
         server 10.113.45.7:9222;
        server 10.113.45.6:9222;
 }

(..and..)
location / {
..
    proxy_pass http://lxd;
..
}
```
). 

Why would the _name_ of the upstream appear as a regular hostname - and why difference between the behaviour of the CLI (it _does_ open a page) and the node.js example script (it throws) - is beyond me.
I'd be very glad to receive any kind of comment or help or suggestion, otherwise please feel free to close this non-issue.

**Comment by cyrus-and** [comment]
```console
$ chrome-remote-interface new http://github.com
```

does not use a WebSocket while the example from the wiki does, not sure how this can triggers a `getaddrinfo ENOTFOUND` error but at least it's a difference.

You can try to manually connect to the WebSocket using [`wscat`][1]:

```console
$ wscat -c ws://lxd/devtools/page/a862971f-b611-4f63-9aba-57fb4e597576
connected (press CTRL+C to quit)
> {"id": 1, "method": "Target.getTargets"}
< {"id":1,"result":{...}}
```

[1]: https://github.com/websockets/wscat

**Comment by gyula-ny** [comment]
It turns out that this is an Nginx configuration issue... Sorry for spamming you, and thanks a lot for reminding me of wscat - it was very helpful

**Comment by cyrus-and** [comment]
No problem, you're welcome! :)

**Comment by hbakhtiyor** [comment]
@gyula-ny how did you configure load-balancing with nginx upstream?
