### ISSUE TITLE
Page.printToPDF and Page.captureScreenshot doesn't work

### ISSUE THREAD

**Issue by DengJianShen** [cyrus-and/chrome-remote-interface#209]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 14.04 and Ubuntu 16.04
| Node.js					| v8.1.2
| Chrome/Chromium/...		| 61.0.3112.50-2
| chrome-remote-interface	| 0.23.2

Hello. I'm currently using the Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-79-generic x86_64) and the Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-83-generic x86_64).I got a problem.I hope to get your help.

When I using the Ubuntu 14.04.5 Page.printToPDF and Page.captureScreenshot can work successfully and generate the right pictures or PDF.

When I using the Ubuntu 16.04.2 Page.printToPDF and Page.captureScreenshot,and localhost url  doesn't work, or the pictures are white backgrounds.

Can you help me? Thank you for your answer.

Here is my  Page.captureScreenshot code.

```js
router.post('/api/output/screen', (req, res, next) => {
    const screenOptions = req.body;
    const _url = screenOptions.url;
    const _type = screenOptions.type;
    const _devWidth = parseInt(screenOptions.devWidth) || 640;
    const _devHeight = parseInt(screenOptions.devHeight) || 900;
    const _scale = parseInt(screenOptions.scale) || 1;
    const _width = parseInt(screenOptions.width) * _scale;
    const _height = parseInt(screenOptions.height) * _scale;
    const _x = (_width - parseInt(screenOptions.width)) / 2;
    const md5 = crypto.createHash('md5');

    TargetApi.createTarget({
        url: _url,
        width: _devWidth,
        height: _devHeight,
    }).then((target) => {
        CDP({
            target: target.targetId
        }, async(client) => {
            const {
                Emulation,
                Page,
                DOM,
                CSS,
                Network,
                Target
            } = client;
            await Page.enable();
            await DOM.enable();
            await CSS.enable();
            await Network.enable();
            await Page.loadEventFired();
            await utils.sleep(1000)
            const image = await Page.captureScreenshot({
                format: _type == 0 ? 'jpeg' : 'png',
                fromSurface: true,
                clip:{
                    x:_x,
                    y:0,
                    width:_width,
                    height:_height,
                    scale:_scale
                },
                quality: 100
            });
            const buffer = Buffer.from(image.data, 'base64');
            const nowTime = Date.now();
            const typeSuffix = _type == 0 ? 'jpg' : 'png';
            const _id = (screenOptions.url.split('#/preview/'))[1];
            const md5Prefix = md5.update(image.data).digest('base64').replace(/\//g, '');
            const localFile = path.join(__dirname, '../../file_local/', `${md5Prefix}.${typeSuffix}`);
            fs.writeFile(localFile, buffer, 'base64',(err) => {
                TargetApi.closeTarget({
                    targetId: target.targetId
                }).then(() => {
                    res.send({
                        errcode: 0,
                        errmsg: 'ok',
                        filename: `http://nr.dytdc.com/img/${md5Prefix}.${typeSuffix}`
                    })
                })
            })
        })
    })
})
```

**Comment by cyrus-and** [comment]
The version of Chrome (61.0.3112.50-2) is the same for both the distros?

> and localhost url doesn't work

What error do you get exactly?

**Comment by DengJianShen** [comment]
I correct a mistake. My version of chrome is google-chrome-unstable_61.0.3159.5-1_amd64.deb.

According to the code above.For example,I use the Nginx agent localhost as http://xxx.com, and then I'm going to have the Page.captureScreenshot URL is http://xxx.com/index.html, which causes the following.

Sometimes it reminds UnhandledPromiseRejectionWarning that it can't continue to work. Sometimes the pictures are successfully generated, but the pictures are pure white. 

But when my URL is another domain name, it can finish work.

I'm sure my code is correct. Because I succeeded in running on Ubuntu 16.04.2, Ubuntu 16.04.5 and mac. I suspect the system version is a problem.When using Ubuntu 16.04, the page of localhost cannot be Page.captureScreenshot.

Thank you for your answer.

**Comment by cyrus-and** [comment]
Are you by any chance running Chrome in a Docker container or another otherwise memory-limited environment?

> Sometimes it reminds UnhandledPromiseRejectionWarning that it can't continue to work.

Show me the full stack of that errors, you can obtain it by running node with the `--trace-warnings` option.

**Comment by DengJianShen** [comment]
I just tried it again. It's no longer in the wrong. The main problem is that the picture is blank. For example, 'http://nr.dytdc.com/img/EljlY2yRld3Nf6cfkaKq0g==.jpg'.When my URL fill in other, it is normal picture.For example,'http://nr.dytdc.com/img/KdmxQflvcbWp0wx1R5PFw==.jpg'.

**Comment by cyrus-and** [comment]
(You deleted your comment, was it intentional?)
