### ISSUE TITLE
How to use Target.targetInfoChanged?

### ISSUE THREAD

**Issue by ChexWarrior** [cyrus-and/chrome-remote-interface#212]
Hi,

Am I properly using the `Target.targetInfoChanged` event?

In my script I click a link which calls `window.open` and the `Target.targetCreated` event registers this new target.  Upon creation the `TargetInfo` instance contains an empty url and title, however when I later call `Target.getTargets()` the target (same ID as before) now has a non-empty url and title, I thought that `Target.targetInfoChanged` would catch this change, but it never gets called.

The script:
```node
const CDP = require('chrome-remote-interface');
const path = require('path');

async function main() {
  let target;
  try {
    let htmlFilePath = path.resolve('./index.html');
    target = await CDP();
    const {Page, DOM, Runtime, Target} = target;

    Target.targetCreated((params) => {
      console.log('targetCreated', params);
    });

    Target.targetInfoChanged((params) => {
      console.log('targetInfoChanged', params);
    });
    
    await Page.enable();
    await DOM.enable();
    await Runtime.enable();
    await Page.navigate({url: `file://${htmlFilePath}`});
    await Page.loadEventFired();
    await Target.setDiscoverTargets({discover: true});
    await Runtime.evaluate({
      expression: 'document.getElementById("link").click();'
    });

    setTimeout(async () => {
      let targets = await Target.getTargets();
      console.log('targets', targets);
      if(target) await target.close();
    }, 3000);
   
  } catch(error) {
    console.log('error', error);
    if(target) await target.close();
  } 
}

main();
```

The index.html file:
```html
<!DOCTYPE html>
<html lang="en">  
<head>
  <meta charset="utf-8">
  <title>CDP Test</title>
</head>
<body>
  <a id="link" href="#">CLICK ME</a>
</body>
<script>
  let link = document.getElementById('link');
  link.addEventListener('click', (event) => {
    event.preventDefault();
    window.open('http://www.google.com','test popup');
  });
</script>
</html>
```

[A tarball containing the html and script files.](https://github.com/cyrus-and/chrome-remote-interface/files/1171658/test.tar.gz)

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04
| Node.js					| 8.2.1
| Chrome/Chromium/...		| Google Chrome 59.0.3071.115
| chrome-remote-interface	| 0.24.2

**Comment by cyrus-and** [comment]
Here's what I get in the above conditions:

```
targetCreated { targetInfo:
   { targetId: '13b8c7e7-813f-4be6-ad6b-75c45e3dc2fd',
     type: 'page',
     title: 'index.html',
     url: 'file:///path/to/index.html' } }
targets { targetInfos:
   [ { targetId: '13b8c7e7-813f-4be6-ad6b-75c45e3dc2fd',
       type: 'page',
       title: 'index.html',
       url: 'file:///path/to/index.html' }] }
```

That is, no empty URL and title in this case.

Yet, I'm able to reproduce it using the CLI (`$ chrome-remote-interface new` in another terminal):

```
$ chrome-remote-interface inspect
>>> Target.setDiscoverTargets({discover: true})
{ result: {} }
>>> Target.targetCreated()
{ 'Target.targetCreated': true }
{ 'Target.targetCreated':
   { targetInfo:
      { targetId: '7ba64d70-45b0-4ac6-a997-dded87c12a63',
        type: 'page',
        title: '',
        url: '' } } }
```

It also happens with Chrome 60 and 61, it's probably a bug you should file an upstream issue [here][1] or ask for clarification in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

[1]: https://bugs.chromium.org/p/chromium/issues/list

**Comment by ChexWarrior** [comment]
Okay will do, thanks!

**Comment by cyrus-and** [comment]
Feel free to post the link here so to help others, thanks.
