### ISSUE TITLE
No inspectable targets Error

### ISSUE THREAD

**Issue by vichajser** [cyrus-and/chrome-remote-interface#213]
> Exception while taking screenshot: Error: No inspectable targets

The error does not occur unless the chrome service is restarted

```js
async function nodeAppears(client, selector) {
    const browserCode = (selector) => {
        console.log('browserCode start');
        return new Promise((fulfill, reject) => {
            if (document.documentElement.querySelector(selector)) {
                fulfill();
                return;
            } else {
                reject();
            }
        });
    };
    // inject the browser code
    const {Runtime} = client;
    await Runtime.evaluate({
        expression: `(${browserCode})(${JSON.stringify(selector)})`,
        awaitPromise: true
    });
};
```

**Comment by cyrus-and** [comment]
That error says that there are no targets (tabs) to inspect, make sure you don't have DevTools open or another instance of chrome-remote-interface attached to you tab.

**Comment by vichajser** [comment]
There are two instances of chrome-remote-interface attached to my tab, there are two function functions at the same time call a node method of the situation, so how to solve the two methods at the same time call and solve the exception, I need your help!

**Comment by cyrus-and** [comment]
I assume this is unrelated with the above... The problem is that you cannot attach more than one chrome-remote-interface instance to a tab, this is a current limitation of Chrome, but nothing prevents you to call two methods at the *same time* (i.e., called asynchronously; no `await` or using `Promise.all`) from a single instance. Note that ultimately these invocations get serialized on the Chrome side.

**Comment by Tin-Nguyen** [comment]
any solution to fix the issue? The issue just happen when using the Docker Chrome instance on my server, not happen when using Docker Chrome instance on my local. Any suggestion to fix this issue?

**Comment by cyrus-and** [comment]
@Tin-Nguyen as the label says it's not an issue:

> That error says that there are no targets (tabs) to inspect, make sure you don't have DevTools open or another instance of chrome-remote-interface attached to you tab.
