### ISSUE TITLE
printPDF to return a stream

### ISSUE THREAD

**Issue by jifeon** [cyrus-and/chrome-remote-interface#216]
Currently `printToPDF` returns a `base64` encoded string. It works great in general, but we are generating a bit huge PDFs - min 40MBs, they include lot of pages with high resolution images. Keeping such big data in memory causes performance and memories issues with node. It would be nice to take PDF content as a stream, or as a file. 

Currently we are thinking about workaround with page per page printing. But it dramatically increases complexity of the service. So my question is: are there any plans to support streams for `printToPDF`?

**Comment by cyrus-and** [comment]
While I agree that it would be a nice thing to have, this feature request is off topic here. Ping the  [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), the [official protocol repo](https://github.com/ChromeDevTools/devtools-protocol/issues) or even file an [upstream issue](https://bugs.chromium.org/p/chromium/issues/list).

**Comment by jifeon** [comment]
@cyrus-and thx for quick response!

**Comment by cyrus-and** [comment]
@nyroDev something along the lines of:

```js
const CDP = require('chrome-remote-interface');
const fs = require('fs');

async function streamPdfToFile(url, file, chunkSize = undefined /* means auto */) {
    const client = await CDP();

    try {
        const {IO, Page} = client;

        console.log(`Navigating to ${url}`);

        await Page.enable();
        await Page.navigate({url});
        await Page.loadEventFired();

        console.log(`Page loaded, requesting the PDF stream`);

        const {stream: handle} = await Page.printToPDF({
            transferMode: 'ReturnAsStream'
        });

        let fileStream;
        while (true) {
            const {base64Encoded, data, eof} = await IO.read({
                handle,
                size: chunkSize
            });

            if (!fileStream) {
                fileStream = fs.createWriteStream(file, {
                    encoding: base64Encoded ? 'base64' : 'binary'
                });
            }

            if (eof) {
                console.log(`PDF stream finished, saved to ${file}`);

                await IO.close({handle});
                fileStream.close();
                break;
            }

            console.log(`Processing the next chunk of ${data.length} (decoded) bytes`);

            fileStream.write(data);
        }
    } finally {
        client.close();
    }
}

streamPdfToFile('https://nodejs.org/api/fs.html', '/tmp/out.pdf', 1 << 20);
```

**Comment by nyroDev** [comment]
@cyrus-and thank you so much for your quick and detailed response, it works perfectly!

**Comment by nyroDev** [comment]
@cyrus-and Please not that in some edges cases (particullary with large images), letting the chunkSize to undefined creates a truncated (corrupted) PDF file.

After reading [this comment](https://github.com/puppeteer/puppeteer/issues/7757#issuecomment-999470890), I updated the code below to set the default chunk size to `16384*2` and so far it's working great!
