### ISSUE TITLE
Using DevTools after injecting a script

### ISSUE THREAD

**Issue by trentmwillis** [cyrus-and/chrome-remote-interface#217]
I have a use case where I am using `chrome-remote-interface` with [`chrome-launcher`](https://www.npmjs.com/package/chrome-launcher) to inject a script into a page (using `Runtime.evaluate`). That works great!

However, I would like to be able to debug the injected script if needed, preferably via Chrome's built-in DevTools. I've tried using the `Debugger` API, which will allow me to properly "break" on a `debugger` statement, but upon opening the DevTools, it appears the `chrome-remote-interface` connection is broken.

Based on https://github.com/cyrus-and/chrome-remote-interface/issues/213#issuecomment-317695406, it sounds like you can't use both DevTools and `chrome-remote-interface` simultaneously. Is this accurate? And, if so, is there a recommend approach to debugging injected scripts?

Thanks in advance! This library is awesome 💯 

---

| Component | Version
|-|-
| Operating system	  	 	| macOS 10.12.3
| Node.js					| 8.2.1
| Chrome/Chromium/...		| 59.0.3071.115
| chrome-remote-interface	| 0.24.2

**Comment by cyrus-and** [comment]
Hey, thanks! :)

Correct, Chrome doesn't allow multiple connections to a single tab ([yet][1]? they're working on this apparently...), from the main [page][2]:

> We currently do not support multiple clients connected to the protocol simultaneously. This includes opening DevTools while another client is connected. [...] After disconnection, some apps have chosen to pause their state and offer a reconnect button.

There are a couple of workarounds to this:

- support *reconnection* on your side, something that after disconnection tries periodically to fetch the target info (`CDP.List`) for a given id and attempt a new connection if the `webSocketDebuggerUrl` field is present (when already inspected such field is omitted);

- use [chrome-remote-multiplex][3] by @johnspackman as suggested in #186. I'm not sure whether there could be problem with certain domains though, for example the DOM domain:

    > It is important that client receives DOM events only for the nodes that are known to the client. Backend keeps track of the nodes that were sent to the client and never sends the same node twice. It is client's responsibility to collect information about the nodes that were sent to the client.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=590878
[2]: https://chromedevtools.github.io/devtools-protocol/
[3]: https://github.com/johnspackman/chrome-remote-multiplex

**Comment by trentmwillis** [comment]
Thanks for the detailed response. Looks like chrome-remote-multiplex might be the approach I want for now!

**Comment by johnspackman** [comment]
https://github.com/johnspackman/chrome-remote-multiplex is built to only forward those domain events which are relevant and provide an emulation rather than just a verbatim copy ... however this is currently limited to the Runtime domain.  I'll add an issue for this and support for DOM event filtering shortly
