### ISSUE TITLE
addScriptToEvaluateOnLoad Doesn't Add a Script

### ISSUE THREAD

**Issue by shellscape** [cyrus-and/chrome-remote-interface#219]
I've been plugging at this all night, can't seem to land on a solution.

`Page.addScriptToEvaluateOnLoad` doesn't appear to add script to any page loads whatsoever. Upon opening dev tools on the chrome instance, none of the variables, methods, etc are accessible in the console. Given the documentation is sparse on this method and there isn't much instruction out there, so I might be doing something wrong or out of order. Here's what my implementation looks like:

```js
const CDP = require('chrome-remote-interface');
const fs = require('fs');
const path = require('path');

module.exports = async function connectClient (instance) {

  function fetch (fileName) {
    const filePath = path.join(__dirname, '../client', fileName);
    return fs.readFileSync(filePath, 'utf-8');
  }

  const client = await CDP({port: instance.port});
  const { DOM, Console, Network, Page, Runtime } = client;

  await Promise.all([
    DOM.enable(),
    Network.enable(),
    Page.enable(),
    Runtime.enable(),
    Console.enable()
  ]);

  console.log('CDP Client Connected');

  await Page.addScriptToEvaluateOnLoad({ scriptSource: fetch('event-bus.js') });
  await Page.addScriptToEvaluateOnLoad({ scriptSource: fetch('shim.js') });

  return { DOM, client, Console, Network, Page, Runtime };
};
```

I do realize that the method is deprecated in favor of `Page.addScriptToEvaluateOnNewDocument`, but using that method results in an error of `'Page.addScriptToEvaluateOnNewDocument' wasn't found` consistently, even though I've verified the method exists on `Page` using console.log.

Could these be bugs? If not, I would greatly appreciate any direction anyone might have.

| Component | Version
|-|-
| Operating system	  	 	| MacOS 10.12.5
| Node.js					| 7.8
| Chrome/Chromium/...		| 60 (just updated)
| chrome-remote-interface	| latest

**Comment by hbakhtiyor** [comment]
> using that method results in an error of 'Page.addScriptToEvaluateOnNewDocument' wasn't found 

because you use stable version of Chrome which not yet there,

try something simple first 

```js
await Page.addScriptToEvaluateOnLoad({ scriptSource: "console.log('INJECTED SCRIPT')" });
```
if it works, will output on console which you started headless chrome

where's your `Page.navigate`? did you use it?

**Comment by shellscape** [comment]
> where's your Page.navigate? did you use it?

Ah, I was using the `startingUrl` option. I'll try that instead and see what happens.

**Comment by shellscape** [comment]
I can confirm that using `Page.navigate` results in the scripts being loaded into the VM. 👍

**Comment by Treeeater** [comment]
@shellscape  I'm also having this problem, even with Page.navigate.

Where do you put the Page.navigate? before or after Page.addScriptToEvaluateOnNewDocument?

Can you share your working snippet?

Thanks!

**Comment by tsirolnik** [comment]
Having the same issue, Page.addScriptToEvaluateOnNewDocument not running even though I'm using Page.navigate
