### ISSUE TITLE
Multiple Chrome instances

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#22]
Now when I want to connect to multiple chromium instances in one file, only the last connect works, all other are returning 
Cannot connect to Chrome { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }

Is there a way to connect to multiple chromium instances at the same time?

**Comment by mato75** [comment]
Fixed the problem, running conf was changed.

**Comment by DorMitzafon** [comment]
@puppeteer701  how did you fixed the problem?
