### ISSUE TITLE
awaitPromise causing error on evaluating promise

### ISSUE THREAD

**Issue by AStoker** [cyrus-and/chrome-remote-interface#222]
| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 8.2.1
| Chrome/Chromium/...		| Version 62.0.3173.2 (Official Build) canary (64-bit)
| chrome-remote-interface	| 0.24.2

Is Chrome running in a container? NO

I have a node script I'm using to try and load up a form to be printed out as a PDF. This form requires headers and cookies to be set, as the user needs to be authorized. Additionally, once this form is "loaded", there is data that is fetched at runtime to fill in. Therefore, I have a flag on the window that is set once everything is finished loading.  
I'm attempting to use the `Runtime.evaluate` functionality with the `awaitPromise: true` option. However, here's where things break with a `Result of the evaluation is not a promise` error.  

First, if I don't set the cookie, then my script will execute and I won't the result error. However, since my form isn't actually loaded up (I end up at a forbidden page), this isn't desired.  
Once I set the cookie, I get my result error. Now, sometimes (I'm debugging with VSCode) when I sit paused for a second or two before I evaluate my code, everything runs as expected. So I think there's something to do with waiting for things to be loaded appropriately, but I can't find any help/documentation on how to get around my issue.   

Below is my script I'm using (certain parts stripped out for confidentiality). 

``` js
const fs = require('fs');
const { URL } = require('url');

const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');
const uuid = require('node-uuid');

const urlToLoad = new URL("https://site.com/form-to-show");
const csrfToken = uuid.v4();


async function readStdIn() {
    return new Promise((resolve) => {
        resolve("myAuthorizationToken"); //For testing purposes hard coded result
    });
}

async function launchChrome(headless = true) {
    return chromeLauncher.launch({
        chromeFlags: [
        '--disable-gpu',
        headless ? '--headless' : ''
        ]
    });
}

async function cbToPromise(cb) {
    return new Promise((resolve) => {
        cb((resp) => {
            resolve(resp);
        })
    });
};

const execute = async () => {
    return new Promise(async (resolve, reject) => {
        try {
            
            const authorizationToken = await readStdIn();

            const chrome = await launchChrome();
            const client = await CDP({port: chrome.port});

            const {Page, Runtime, Network, DOM} = client;

            await Page.enable();
            await Runtime.enable();
            await Network.enable();
            await DOM.enable();            

            const setHeaders = await Network.setExtraHTTPHeaders({'headers': {
                'Authorization': authorizationToken,
                'X-CSRF-Token': csrfToken
            }});
            const cookieSet = await Network.setCookie({url: urlToLoad.origin, name: 'CSRFToken', value: csrfToken});

            const navigated = await Page.navigate({url: urlToLoad.href});
            const loaded = await Page.loadEventFired();

            let js =  `
                new Promise((fulfill, reject) => {
                    setTimeout(() => {
                        fulfill('your result');
                    }, 1000); // simulate a long-running async operation
                })`;
            const result = await Runtime.evaluate({
                expression: js, //Just testing a simple promise at this point
                awaitPromise: true
            }); //Throws message: 'Result of the evaluation is not a promise'
            if (result.exceptionDetails && result.exceptionDetails.exception) {
                throw Error(result.exceptionDetails.exception.description); //Used for any invalid js execution
            }

            const pdf = await Page.printToPDF({});
            
            client.close().then(() => {
                chrome.kill().then(() => {
                    resolve(pdf.data);
                });
            });
        } catch (e) {
            reject(e);
        }
    });
}


execute().then(base64Data => {
    const buff = Buffer.from(base64Data, 'base64');
    fs.writeFileSync('test.pdf', buff);      

    process.exit(1);
}).catch(e => {
    console.error(e);
    process.exit(-1);
});
```

Am I missing something here? Seems broken...

**Comment by cyrus-and** [comment]
Well this is weird, the only reason I see for that error is that, as the message says, the return value is not a Promise and actually it's easily reproducible with:

```js
Runtime.evaluate({expression: `'not a promise'`, awaitPromise: true});
```

If I run your code (after replacing `https://site.com/form-to-show` with `https://example.com`) I correctly get the PDF and I see no errors.

I can't really imagine how this is a timing issue. The only explanation I can think of is that your page redefines what a promise is or maybe uses a third-party library. Silly example:

```js
Runtime.evaluate({expression: `class Promise {}; new Promise()`, awaitPromise: true});
```

**Comment by AStoker** [comment]
Actually, that makes sense. Our forms that we're loading up need to be backwards compatible with IE, so we polyfill the Promise library with BlueBird. 
Is there a way to work around this? Is it actually type checking the result as opposed to just seeing if it is "promise-like"?

**Comment by cyrus-and** [comment]
> Is it actually type checking the result as opposed to just seeing if it is "promise-like"?

I think it's the former as I'm assuming that a Bluebird promise is actually a promise-like object.

> Is there a way to work around this?

You can save the native Promise object before applying the polyfill, if any, and use it with `Runtime.evaluate`, for example:

```js
const NativePromise = Promise;
```

**Comment by AStoker** [comment]
Sounds good. We'll have to figure some way around this due to how early the Promise library needs to be loaded for us. But that ultimately answers the question. Not a bug, just different promises. Thanks for clarifying that.

**Comment by cyrus-and** [comment]
OK you might either like it or hate it but here's an hackish way to obtain the native Promise implementation even after the polyfill:

```js
const NativePromise = fetch().catch(_=>_).constructor;
```

**Comment by AStoker** [comment]
I would have never thought about that 😄 
I think I have a less hacky approach that we can use in our instance though, but I'll stick that in my back pocket for later. I appreciate it.

**Comment by ashumaher** [comment]
const NativePromise = ((async function () {})().constructor);
