### ISSUE TITLE
printToPDF Options

### ISSUE THREAD

**Issue by eljefe6a** [cyrus-and/chrome-remote-interface#223]
The [wiki says](https://github.com/cyrus-and/chrome-remote-interface/wiki/Print-page-to-PDF) that the `printToPDF` method will accept the options in Chrome 60. I'm using Chrome 60 and the options still aren't being used.

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 17.04
| Node.js					| 8.2.1
| Chrome		|  60.0.3112.78
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container?  NO

**Comment by cyrus-and** [comment]
Care to back this assertion with an example or a description of what went wrong? If a run that wiki snippet with Chrome 60.0.3112.78 on Linux I get a landscape PDF with no borders and with the background...

**Comment by eljefe6a** [comment]
Sure. Here are the options I used:
```
const {data} = await Page.printToPDF({
            printBackground: true,
            paperWidth: "12.60",
            paperHeight: "7.10",
            marginTop: 0,
            marginBottom: 0,
            marginLeft: 0,
            marginRight: 0,
            pageRanges: 1-2
        });
```

The `pageRanges` weren't ignored. The `paperWidth` and `paperHeight` options were ignored. I tried changing it to various sizes and it didn't change. I couldn't verify the margins specifically.

**Comment by eljefe6a** [comment]
I just figured it out. `paperWidth and `paperHeight` can't be passed in as strings.

**Comment by cyrus-and** [comment]
> I just figured it out. paperWidth and paperHeight can't be passed in as strings.

Yep, as you can see [here][1] a number is expected.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF
