### ISSUE TITLE
DOMSnapshot.getSnapshot not available

### ISSUE THREAD

**Issue by ilanc** [cyrus-and/chrome-remote-interface#224]
Hi there,
Many thanks for chrome-remote-interface

### Overview of issue
I'm trying to dump the DOM of a webpage using [DOMSnapshot.getSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/DOMSnapshot/#method-getSnapshot). I have confirmed that the function exists in the devtools protocols of 2 versions of chrome (see table below) using `chrome-remote-interface inspect`. However when I attempt to invoke the function I get:
```
{ error:
   { code: -32601,
     message: '\'DOMSnapshot.getSnapshot\' wasn\'t found' } }
```

Am I invoking it incorrectly? or is there something missing in chrome-remote-interface?

### inspect REPL output
```
>>> DOMSnapshot.getSnapshot
{ [Function: override]
  category: 'command',
  parameters:
   { computedStyleWhitelist:
      { type: 'array',
        items: { type: 'string' },
        description: 'Whitelist of computed styles to return.' } },
  returns:
   [ { name: 'domNodes',
       type: 'array',
       items: { '$ref': 'DOMNode' },
       description: 'The nodes in the DOM tree. The DOMNode at index 0 corresponds to the root document.' },
     { name: 'layoutTreeNodes',
       type: 'array',
       items: { '$ref': 'LayoutTreeNode' },
       description: 'The nodes in the layout tree.' },
     { name: 'computedStyles',
       type: 'array',
       items: { '$ref': 'ComputedStyle' },
       description: 'Whitelisted ComputedStyle properties for each node in the layout tree.' } ],
  description: 'Returns a document snapshot, including the full DOM tree of the root node (including iframes, template contents, and imported documents) in a flattened array, as well as layout and white-listed computed style information for the nodes. Shadow DOM in the returned DOM tree is flattened. ' }
>>> DOMSnapshot.getSnapshot()
{ error:
   { code: -32601,
     message: '\'DOMSnapshot.getSnapshot\' wasn\'t found' } }
>>> DOMSnapshot.getSnapshot({ computedStyleWhitelist: [] })
{ error:
   { code: -32601,
     message: '\'DOMSnapshot.getSnapshot\' wasn\'t found' } }
```

### Version info
I have run 2 tests:
1. launch chrome in windows10 and connect using `chrome-remote-interface interface` 
2. launch headless_shell inside a docker container (lambci/lambda:nodejs6.10) and connect from the host (windows10) using `chrome-remote-interface interface`

| Component | Version
|-|-
| Operating system	  	 	| windows 10
| Node.js					| 6.10.2 & 7.9.0
| Chrome/Chromium/...		| latest windows stable chrome (60.0.3112.78) and headless_shell (60.0.3112.24)
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container?
* no in test 1
* yes in test 2

**Comment by cyrus-and** [comment]
Thanks to you for your interest in this project! :)

This problem is addressed in [this FAQ entry][1]. In this particular case `DOMSnapshot.getSnapshot` requires Chrome 61.

`chrome-remote-interface inspect` uses the `protocol.json` file that is bundled with this repository by default, which is likely to contain bleeding-edge features (w.r.t. the currently stable version of Chrome). That command can be used to check this kind of things, just use the `-r`/`--remote` option to obtain the correct protocol version from Chrome.

[1]: https://github.com/cyrus-and/chrome-remote-interface#invoking-domainmethod-i-obtain-domainmethod-wasnt-found

**Comment by ilanc** [comment]
Thanks for the swift response Andrea
