### ISSUE TITLE
send data from loaded webpage(such as window.callPhantom in phantomjs)

### ISSUE THREAD

**Issue by vichajser** [cyrus-and/chrome-remote-interface#225]
Does chrome-remote-interface provide a method (such as window.callPhantom in phantomjs) to get the data of the rendered page?

`if (typeof window.callPhantom === 'function') {
    window.callPhantom({ data: 'RenderPDF' });
 }`

And in the phantomjs script:

`page.onCallback = function (data) {
   /* callback code */
};`

**Comment by cyrus-and** [comment]
Unfortunately not, see #218 for a somewhat comprensive discussion of possible workarounds.
