### ISSUE TITLE
Setting Debugger breakpoints after beautification

### ISSUE THREAD

**Issue by dpnishant** [cyrus-and/chrome-remote-interface#227]
| Component | Version
|-|-
| Operating system	  	 	| macOS 10.12.6
| Node.js					| 8.2.1
| Chrome/Chromium/...		| Chrome Canary 62.0
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container? NO

Is there a way to beautify script sources and then set the Debugger breakpoints, the way we can do in Devtools? Or least can we intercept the response of `.js` files (`text/javascript`) and then beautify it before it is scriptParsed? 

The idea is to make the breakpoint locations more meaningful in a compressed/minified javascript source.

--
Thanks

**Comment by cyrus-and** [comment]
I'm not entirely sure but if you [inspect the inspector][1] (see "Sniffing the protocol") you'll notice that breakpoints are set using the original (minified) lines and columns numbers, this means that DevTools keeps a map between minified and beautified source.

In other words this isn't something that the CDP seems to be aware of.

Still you may want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

[1]: https://chromedevtools.github.io/devtools-protocol/

**Comment by paulirish** [comment]
Aye, In DevTools frontend source, it keeps a mapping between the original network file and the reformatted one. It's done quite similar to sourcemaps.  

Some of the source: [devtools-frontend/ScriptFormatter.js](https://github.com/ChromeDevTools/devtools-frontend/blob/master/front_end/formatter/ScriptFormatter.js)
