### ISSUE TITLE
Http Status on 301 redirect

### ISSUE THREAD

**Issue by anthonymayfield111** [cyrus-and/chrome-remote-interface#229]
Hi,

I'm getting an issue while trying to retrieve a page.  It gets caught in a 301 redirect loop, the problem is is that the loadEventFired appears to be called before I get the responseReceived (which doesn't appear to come in).  Is there a way to stop this happening, or detect the 301 status code?

Many thanks,

Anthony.

**Comment by cyrus-and** [comment]
Can you show me the URL along with the code that reproduces this problem?

**Comment by anthonymayfield111** [comment]
The URL is http://www.tjoos.com/Coupon/103855/P.F.-Changs-Rock-n-Roll-Arizona-Index

The code is over a few files and hard to separate, but here's the main section:

`  renderPage: async function (client, ds) {
    await _prepareForNavigation(client, ds);
    ds.log("Rendering page");
    const viewportWidth = 1440;
    const viewportHeight = 2000;
    const delay = 0;
    var fullPage = null;
    var config = ds.config;

    const {DOM, Emulation, Network, Page, Runtime, Security} = await client;
    await Page.enable().catch(function(err){_resourceErrorHandler(ds, "Page enable: " + err)});
    await DOM.enable().catch(function(err){_resourceErrorHandler(ds, "DOM enable: " + err)});
    await Network.enable().catch(function(err){_resourceErrorHandler(ds, "Network enable: " + err)});

    await Security.enable();
    await Security.setOverrideCertificateErrors({override: true});
    
 // ignore all the certificate errors
    Security.certificateError(({eventId}) => {
        Security.handleCertificateError({
            eventId,
            action: 'continue'
        });
    });

    ds.dsResources = {};
    
    // Set up viewport resolution, etc.
    const deviceMetrics = {
      width: viewportWidth,
      height: viewportHeight,
      deviceScaleFactor: 0,
      mobile: false,
      fitWindow: false,
    };
    await Emulation.setDeviceMetricsOverride(deviceMetrics).catch(function(err){_resourceErrorHandler(ds, err)});
    await Emulation.setVisibleSize({width: viewportWidth, height: viewportHeight}).catch(function(err){_resourceErrorHandler(ds, err)});
  
    ds.currentUrl = config.url;
    url = config.url;
    ds.log(url);
    ds.log("-- Chrome ready " + _getNextLapTimeStr(ds));
    await Page.navigate({url});
    
    if (config.debug) {
        Network.requestWillBeSent(async(params) => {
          if (!ds.dsResources[params.requestId]) {
             ds.dsResources[params.requestId] = {};
          }

          ds.dsResources[params.requestId]["request"] = params.request;
          ds.dsResources[params.requestId]["dateStarted"] = new Date();
          ds.dsResources[params.requestId]["requestWillBeSent"] = new Date().getTime();
        });
        
        Network.dataReceived(async(params) => {
            if (!ds.dsResources[params.requestId]) {
                ds.dsResources[params.requestId] = {};
                ds.log("Data recieved resource not found for " + params.requestId);
            }
          ds.dsResources[params.requestId]["dataReceived"] = new Date().getTime();
        });
        
        Network.requestServedFromCache(async(params) => {
            if (!ds.dsResources[params.requestId]) {
              ds.dsResources[params.requestId] = {};
            }
            ds.dsResources[params.requestId]["servedFromCache"] = true;
        });
    }
    
    Network.responseReceived(async(params) => {
      if (!ds.dsResources[params.requestId]) {
        ds.dsResources[params.requestId] = {};
      }
      ds.dsResources[params.requestId]["responseReceived"] = new Date().getTime();
      if(!ds.mainResponse) {
        ds.mainResponse = params.response;
      }                
    });
    
    // Wait for page load event to take screenshot
    Page.loadEventFired(async () => {
      ds.log("-- Page loaded: " + _getNextLapTimeStr(ds));
      // If the `full` CLI option was passed, we need to measure the
      // height of
      // the rendered page and use Emulation.setVisibleSize
      if (fullPage) {
        const {root: {nodeId: documentNodeId}} = await DOM.getDocument();
        ds.log("Looking for full page using node id: " + documentNodeId);
        const {nodeId: bodyNodeId} = await DOM.querySelector( {
          selector: 'body',
          nodeId: documentNodeId,
        });
        const {model: {height}} = await DOM.getBoxModel({nodeId: bodyNodeId});
  
        await Emulation.setVisibleSize({width: viewportWidth, height: height});
        // This forceViewport call ensures that content outside the
        // viewport is
        // rendered, otherwise it shows up as grey. Possibly a bug?
        await Emulation.forceViewport({x: 0, y: 0, scale: 1});
        ds.log("-- View port read: " + _getNextLapTimeStr(ds));
      }
      
      await _capture(Page, DOM, Network, ds);
    });

    Page.domContentEventFired(async () => {
      ds.log("Dom content loaded");
      if (config.authRequiredText) {
        var document = await DOM.getDocument();
        ds.log("Looking for auth text using node id: " + document.root.nodeId);
        var outerHtml = await DOM.getOuterHTML({nodeId:document.root.nodeId});
        if (outerHtml.outerHTML.indexOf(config.authRequiredText) > -1) {
          ds.log("Auth required text found: " + config.authRequiredText);
          ds.log("Outer html: " + outerHtml.outerHTML);
          ds.payload.outcome = 'LOGGED_OUT';
          ds.payload.errorMessage = "Auth required text found: " + config.authRequiredText;
          Page.stopLoading();
          ds.complete();
        }
      }
    });
    
    if (config.timeoutMillis) {
        _createWatchdog(Page, DOM, Network, ds);
    }
  }
};`

**Comment by cyrus-and** [comment]
You should be able to catch such redirect loop error by listening for the [`Network.loadingFailed`][1] event and abort the page load accordingly.

A real world example can be found [here][2] in [chrome-har-capturer][3], where `info.firstRequestId` is the request id of the first [Network.requestWillBeSent][4] event.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFailed
[2]: https://github.com/cyrus-and/chrome-har-capturer/blob/f4c25d8ee88efebb39bd85f150fa4b890e0a84ef/lib/page.js#L214-L219
[3]: https://github.com/cyrus-and/chrome-har-capturer
[4]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

**Comment by anthonymayfield111** [comment]
Thanks Cyrus, that does look like it helps with my current scenario, there were another number of scenarios I wanted the status code for that don't seem to hit the responseReceived function.  It's strange because clearly a response has been made, is there now way of accessing the response?

**Comment by cyrus-and** [comment]
While the actual response is provided via the `Network.responseReceived` event, the redirect responses are provided via subsequent `Network.requestWillBeSent` events (optional `redirectResponse` field).

**Comment by anthonymayfield111** [comment]
Awesome, thank you :)

**Comment by cyrus-and** [comment]
You're welcome! I'm closing this for now, feel free to comment if you need more support.
