### ISSUE TITLE
net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED

### ISSUE THREAD

**Issue by Mustek** [cyrus-and/chrome-remote-interface#230]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04 / Centos7
| Node.js					| 8.x
| Chrome/Chromium/...		| Chrome-stable v60 (Headless)
| chrome-remote-interface	| Included with Chrome-har-capturer

Is Chrome running in a container? NO

Some sites trigger this exception, causing the rest of the code to fail.
Note that this error does not trigger on https://google.com. I can not provide the URL that it triggers on as it's that of a customer. Their website does load through standard headed Chrome & firefox without any SSL exceptions.

Tried to intercept the request with `Network.setRequestInterceptionEnabled`, but the error triggers before it can intercept it.

Stack Trace
```
Error: net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
    at Chrome.Network.loadingFailed (/home/mustek/WebstormProjects/chrome-speed/node_modules/chrome-har-capturer/lib/page.js:217:24)
    at emitOne (events.js:120:20)
    at Chrome.emit (events.js:210:7)
    at Chrome.handleMessage (/home/mustek/WebstormProjects/chrome-speed/node_modules/chrome-remote-interface/lib/chrome.js:303:16)
    at WebSocket.<anonymous> (/home/mustek/WebstormProjects/chrome-speed/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/home/mustek/WebstormProjects/chrome-speed/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/home/mustek/WebstormProjects/chrome-speed/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/home/mustek/WebstormProjects/chrome-speed/node_modules/ws/lib/Receiver.js:354:40)
```

Request returned by event `Network.LoadingFailed`
```
{ requestId: '18520.1',
  timestamp: 100208.766945,
  type: 'Document',
  errorText: 'net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED',
  canceled: false }
```

**Comment by Mustek** [comment]
Might be helpful, this is the prehook code I'm currently running, I have removed the request interception as it did not catch it.

```
preHook: function (url, client) {
                // User Agent
                client.Network.enable();
                client.Network.setUserAgentOverride({userAgent: 'StatusCake_Pagespeed_Indev'});


                client.Network.loadingFailed((data) => {
                    console.log(data);
                });



                client.Security.enable();
                client.Security.setOverrideCertificateErrors({override: true});

                // Security Override
                client.Security.certificateError(({eventId}) => {
                    client.Security.handleCertificateError({eventId, action: 'continue'});
                });
            }
```

**Comment by cyrus-and** [comment]
OK I'm able to reproduce it with:

    openssl req -x509 -newkey rsa:2048 -nodes -days 3650 -subj '/CN=localhost' -keyout key.pem -out cert.pem

and:

```js
var fs = require('fs');
var https = require('https');

https.createServer({
    key: fs.readFileSync('key.pem'),
    cert: fs.readFileSync('cert.pem'),
    requestCert: true,
    rejectUnauthorized: true
}, (req, res) => {
    res.end("hello world\n");
}).listen(8443);
```

and:

```console
$ chrome-har-capturer https://localhost:8443
- https://localhost:8443/ ✗
  net::ERR_SSL_CLIENT_AUTH_CERT_NEEDED
```

Let me look into this...

**Comment by cyrus-and** [comment]
Yep it looks like that this particular certificate error is not handled by `Security.setOverrideCertificateErrors` as opposed to a simple `net::ERR_INSECURE_RESPONSE` which you can trigger, for example, by loading `https://93.184.216.34` (example.com).

You should file an issue to the Chromium team [here][1] or ping the guys on the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol). Feel free to post the link here if you decide to do so, thanks!

[1]: https://crbug.com/

**Comment by Mustek** [comment]
I was fearing that response, will report it to them.

**Comment by cyrus-and** [comment]
As a side note, hooks should return a promise, in particular I suggest to change your `preHook` to something like this to be sure that the override is set before continuing with the page load:

```js
async function (url, client) {
    // User Agent
    await client.Network.enable();
    await client.Network.setUserAgentOverride({userAgent: 'StatusCake_Pagespeed_Indev'});

    client.Network.loadingFailed((data) => {
        console.log(data);
    });

    await client.Security.enable();
    await client.Security.setOverrideCertificateErrors({override: true});

    // Security Override
    client.Security.certificateError(({eventId}) => {
        client.Security.handleCertificateError({eventId, action: 'continue'});
    });
}
```

**Comment by Mustek** [comment]
Opened issue over at Chromium, found some similar related ones, but none that describe this issue.

Link is https://bugs.chromium.org/p/chromium/issues/detail?id=754210
