### ISSUE TITLE
Getting headers before response is completed

### ISSUE THREAD

**Issue by anthonymayfield111** [cyrus-and/chrome-remote-interface#232]
I was using phantomJs before and phantom would fail quickly if it found out the resource was a PDF file.  I'm trying to recreate the same using the chrome remote interface but I need to get to the headers before the responseReceived is called.  I was hoping that the Network.webSocketHandshakeResponseReceived was the method I was looking for but it doesn't look like it is fired.  Do you know if this is just a versioning issue?  and if I can get it working do you know if this will help me to get the headers before the content is downloaded?

**Comment by cyrus-and** [comment]
> I was hoping that the Network.webSocketHandshakeResponseReceived was the method I was looking for but it doesn't look like it is fired.

I don't think the PDF is being served via WebSocket.

If you want to abort a request then you have to intercept it, take a look at [this wiki recipe][1]. There you can access the request (URL, headers, etc.) via the `request` field of the [Network.requestIntercepted][2] event.

Hope it helps.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestIntercepted

**Comment by anthonymayfield111** [comment]
Thanks, actually I have already tried this but it doesn't appear to work although I'd already followed this example.  I'm guessing it's a version issue, I'm on 59.0.3071.115, I'll try chrome beta and hopefully get some more luck, I already have the latest version of chrome-remote-interface 0.24.2

**Comment by cyrus-and** [comment]
> I'm guessing it's a version issue, I'm on 59.0.3071.115

The wiki clearly states: "(This requires Chrome >= 61)".

**Comment by anthonymayfield111** [comment]
That is true :)
