### ISSUE TITLE
Collecting JavaScript errors on page

### ISSUE THREAD

**Issue by inikulin** [cyrus-and/chrome-remote-interface#234]
Hi, I'm trying to figure out how to collect JavaScript errors on page once it loaded. I've tried to search wiki and issues for such use case, but haven't found anything related. Is it possible?

**Comment by cyrus-and** [comment]
I think you're looking for the [`Log`][1] domain, in particular [`Log.entryAdded`][2]:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Log, Page, Runtime} = client;
    try {
        await Log.enable();
        await Log.clear();
        Log.entryAdded(({entry}) => {
            if (entry.source === 'javascript') {
                console.log(entry);
            }
        });
        await Page.navigate({url: 'https://reddit.com'});
    } catch (err) {
        console.error(err);
    }
}).on('error', (err) => {
    console.error(err);
});
```

This doesn't seem to work reliably though...

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Log/
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Log/#event-entryAdded

**Comment by inikulin** [comment]
Seems like it fits my needs. Thank you!
