### ISSUE TITLE
Window size is weird when printToPDF

### ISSUE THREAD

**Issue by quangbuule** [cyrus-and/chrome-remote-interface#235]
Hi guys, 

This may be not an issue of chrome-remote-interface, just want to open a discussion regarding weird window size.

I attempted to print 10inch x 10inch PDF, I declared some media queries in the html file, and the result is not as expected:

(blue texts are ones that match the queries)

---

![image](https://user-images.githubusercontent.com/5992964/29298187-2f638574-8190-11e7-9dd8-19227f9c1e34.png)

---

Here is my gist:
https://gist.github.com/quangbuule/4b781d581f203e59358111c075252d32

This may be the bug of chrome itself, any idea why?

**Comment by nmqanh** [comment]
I also have the same problem, it seems like when printing to pdf the chrome is using 72ppi for width and 54ppi for height, which is weird.

**Comment by hbakhtiyor** [comment]
> 72ppi for width and 54ppi for height

@nmqanh how did you recognize it?

**Comment by nmqanh** [comment]
@hbakhtiyor  According to the above example,
the size is 10inches x 10 inches.
when you set min-width 720px -> works, min-width 721px -> not working --> 720px ~ 10"inches width
when you set min-height 539px -> works, min-width 540px -> not working --> 539px ~ 10"inches height.

I just guess, may be I am wrong 😄

**Comment by hbakhtiyor** [comment]
@nmqanh the default value is 96, https://cs.chromium.org/chromium/src/printing/units.h?l=21

btw, what 'PPI' stand here? pixels per inches or points per inches?

**Comment by quangbuule** [comment]
I think it's just a thing about window size only.
Since I set the size to 10x10 inch but from the example, the media query match `min-width 7.5 inch` but not `min-width 7.6 inch`, that means the width is about 7.5~7.6 inch.

I assume that the paper size and windows size weren't matched when calling printToPDF.

**Comment by nmqanh** [comment]
@hbakhtiyor sorry, I mean pixel per inches

**Comment by cyrus-and** [comment]
@quangbuule yes the size detected by the media queries is approximately 7.5in x 5.6in and changes according to `paperWidth` / `paperHeight` and `scale`; it's not a fixed value, albeit it seems to be a fixed ratio (?).

This sounds like a bug of Chrome, if you decide to file an upstream issue then feel free to link it here so to help future visitors. I'm closing this now as there's nothing I can do about it.
