### ISSUE TITLE
requestChildNodes() using async/await interface?

### ISSUE THREAD

**Issue by f1nnix** [cyrus-and/chrome-remote-interface#237]
Hi! Thanks for `chrome-remote-interface`, awesome lib, helps me a lot.

I'm new to async/await interface. Trying to get `children[]` for existing `bodyNode<Node>`. It's unclear for me, how to use `aysnc/await` feature with Event handlers.

```js
>> console.log(bodyNode)
{ nodeId: 5,
  parentId: 3,
  backendNodeId: 675,
  nodeType: 1,
  nodeName: 'BODY',
  localName: 'body',
  nodeValue: '',
  childNodeCount: 1,
  attributes: [] }
```

According to [docs](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-requestChildNodes) I'm doing:

```js
await DOM.requestChildNodes(bodyNode, 1, false)
```

Now I need to catch `setChildNodes()` event, I suppose. How to do this? I've tried:

```js
DOM.requestChildNodes((bodyNode, nodes)=> {
  // logger.debug('requestChildNodes fired')
  logger.debug(bodyNode)
  logger.info(nodes)
})

// or this
let nodes = await DOM.setChildNodes(...) // ?
```

None of these worked. Any help is appreciated. Thank you.

| Component | Version
|-|-
| Operating system        | macOS 12.5
| Node.js         | v8.1.3
| Chrome/Chromium/...   | Chrome Canary
| chrome-remote-interface | 0.24.3

**Comment by cyrus-and** [comment]
Hey, thanks! :)

First enable the `DOM` domain:

```js
await DOM.enable();
```

Then setup the event handler for `DOM.setChildNodes` (not a simple `await` here because the event can trigger multiple times):

```js
DOM.setChildNodes(({parentId, nodes}) => {
    console.log(parentId, nodes);
});
```

Finally call `DOM.requestChildNodes` on the root node (or whatever subtree):

```js
const {root: {nodeId}} = await DOM.getDocument();
await DOM.requestChildNodes({nodeId});
```

All in all something like this:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {DOM, Page} = client;
    DOM.setChildNodes(({parentId, nodes}) => {
        console.log(parentId, nodes);
    });
    try {
        await DOM.enable();
        await Page.enable();
        await Page.navigate({url: 'https://example.com'});
        await Page.loadEventFired();
        const {root: {nodeId}} = await DOM.getDocument();
        await DOM.requestChildNodes({nodeId, depth: -1});
    } catch (err) {
        console.error(err);
    }
}).on('error', (err) => {
    console.error(err);
});
```

Hope it helps!

**Comment by f1nnix** [comment]
Oh, sorry, I see I've obviously messed up with `requestChildNodes`/`setChildNodes` functions.

Thanks a lot for fast reply!
