### ISSUE TITLE
Support fetching protocol.json from /json/protocol

### ISSUE THREAD

**Issue by auchenberg** [cyrus-and/chrome-remote-interface#24]
In the Edge Diagnostics Adaptor we have added new HTTP endpoint that allows clients to fetch the `protocol.json` on demand. 

I propose that the client will try to fetch it from this endpoint if `/json/version` provides to be `Edge`, and otherwise fallback to the Chrome specific repo.

API: https://github.com/Microsoft/edge-diagnostics-adaptor/wiki/HTTP-endpoint

**Comment by cyrus-and** [comment]
I have this feature ready but I was wondering if the endpoint is really `/protocol.json`; it seems a bit inconsistent IMHO considering that the others are `/json/version` and `/json/list`. Would't be better to use `/json/protocol` instead?

**Comment by auchenberg** [comment]
Indeed. The endpoint should be `/json/protocol`.

**Comment by cyrus-and** [comment]
OK, so I'll push the change as is; give it a try and let me know.

**Comment by auchenberg** [comment]
Looking great! Next release of the adaptor will have the proper implemented API.
