### ISSUE TITLE
Get js errors from the site

### ISSUE THREAD

**Issue by bookin** [cyrus-and/chrome-remote-interface#245]
I try to get js errors from the sites:

```js
CDP(async (client) => {
    const {Log, Page, Runtime, Network, Console} = client;
    try {
        await Network.enable();
        await Page.enable();

        await Log.enable();
        await Log.clear();
        Log.entryAdded(({entry}) => {
            console.log(entry);
            /*if (entry.level === 'error' && entry.source === 'javascript') {
                console.log(entry);
            }*/
        });

        await Console.enable();
        await Console.clearMessages();
        Console.messageAdded(({entry}) => {
            console.log(entry);
            /*if (entry != undefined && entry.level === 'error' && entry.source === 'javascript') {
                console.log(entry);
            }*/
        })

        await Page.navigate({url: url});
        await Page.loadEventFired();

        //console.log(html);
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }

})
```

But methods `Log.entryAdded` and `Console.messageAdded` don't want to give errors from some sites, for example - crucial.com.au or note.ly
And `Console.messageAdded` - just returns undefined.

Perhaps someone knows how to get js errors correctly?
Thanks.

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu
| Node.js					| Node.js	v7.10.0
| Chrome/Chromium/...		| 59.0.3071.36
| chrome-remote-interface	| 0.22.0

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
You're right, here's another example: https://jsfiddle.net/0rdz5qvk/

You should try to drop a message in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or file an issue [upstream](https://crbug.com/).

Please let me know if you manage to find a solution or, at least, the cause of this issue.

**Comment by bookin** [comment]
Thanks for response, for first I created a message on the [Google Group](https://groups.google.com/forum/#!topic/chrome-debugging-protocol/m-HHzoaLK9A)

**Comment by cyrus-and** [comment]
According to that thread the solution is using [`Runtime.exceptionThrown`][1] and it actually works for me:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Page, Runtime} = client;
    try {
        await Page.enable();
        await Runtime.enable();
        await Page.navigate({url: 'http://note.ly'});
        // this needs to be registered after the page load command in order to
        // avoid showing exceptions from the previous page state
        Runtime.exceptionThrown((params) => {
            console.log('>', params);
        });
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
});
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-exceptionThrown

**Comment by bookin** [comment]
I tested again, looks like yes, it works, I missed `Runtime.enable();` in the test script. It is a pity that the method `Log.entryAdded` also does not give a message. Thank you for help.

**Comment by cyrus-and** [comment]
You're welcome.

> It is a pity that the method Log.entryAdded also does not give a message.

This sounds like a bug since sometimes it does.
