### ISSUE TITLE
mamatcyber

### ISSUE THREAD

**Issue by mamatcyber** [cyrus-and/chrome-remote-interface#247]
| Component | Version
|-|-
| Operating system	  	 	| WRITE HERE
| Node.js					| WRITE HERE
| Chrome/Chromium/...		| WRITE HERE
| chrome-remote-interface	| WRITE HERE

Is Chrome running in a container? YES / NO

**Comment by mamatcyber** [comment]
No comment..I try

**Comment by cyrus-and** [comment]
Excuse me!?
