### ISSUE TITLE
chrome.Console.clearMessages doesnt clear console messages

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#25]
chrome.Console.enable();
chrome.Page.enable();

chrome.Console.clearMessages();

Even if I put clearMessages before Console.enable, it still doesnt clear them.

**Comment by cyrus-and** [comment]
It would be great if you could be a little more descriptive when you open issues, you know: scenario, code snippet, etc.

I have no problem with that method, after calling `Console.clearMessages()` the messages are actually removed from the console.

`Console.enable()` and `Page.enable()` are useless within this context as they just enable the event dispatching of the `Console` and `Page` domains respectively.

Also note that you cannot attach to a tab if the DevTools are open, it might put Chrome in an inconsistent state. Close and reload the tab if this happens.

**Comment by mato75** [comment]
Ah ok, thank you very much. I opened my dev tools to see if messages get really removed, and they were not. 

So as I understand now, if dev tools are opened, then clearMessages code should not work?

**Comment by cyrus-and** [comment]
You simply cannot use the remote debugging protocol with a tab when its DevTools are open, AFAIK this is a Chrome limitation and it has nothing to do with this module. For example, issuing a `Page.navigate()` when DevTools are open caused to load the URL in the DevTools itself, kind of split screen; it does not seem to work that way anymore, it simply does nothing.

**Comment by mato75** [comment]
Thank you.
