### ISSUE TITLE
Open a pdf file

### ISSUE THREAD

**Issue by bookin** [cyrus-and/chrome-remote-interface#250]
Perhaps, can you help me with a question - how can I handle opening a pdf file?

```js
const CDP = require('chrome-remote-interface');

const url =  'https://dph.georgia.gov/sites/dph.georgia.gov/files/related_files/site_page/Emergency%20Protocols%20and%20Procedures.pdf';

CDP(async (client) => {
    const {Page} = client;
    try {
        await Page.enable();


        await Page.navigate({url: url});
        await Page.loadEventFired();

        console.log('After');
        
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }

})
```

Script all time wait `Page.loadEventFired();` and nothing happens after.
Is it possible?

**Comment by cyrus-and** [comment]
Maybe using [`Page.setDownloadBehavior`][1] like this:

```js
await Page.setDownloadBehavior({
    behavior: 'allow',
    downloadPath: '/tmp/'
});
```

But AFAIK this is not implemented yet (tried up to 62.0.3192.0).

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDownloadBehavior

**Comment by bookin** [comment]
I somewhere read that Chrome can open pdf to views. I thought I can make a screenshot for pdf, looks like it is not possible.

**Comment by cyrus-and** [comment]
`Page.setDownloadBehavior` might be your solution but we cannot try it yet, I'm afraid we'll have to wait for the next Chrome release.

Anyway, taking PDF screenshots with Chrome is overkill IMHO, that would be merely a file conversion, for example (using [ImageMagick](https://www.imagemagick.org/script/index.php)):

    convert file.pdf file.png

I guess there are a number of libraries that allows you to accomplish this programmatically.

You may also want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

I'm closing this for now, feel free to add any useful info though.

**Comment by bookin** [comment]
Thank you for help.

Information for someone, now I open files in the `docs.google.com` and then take a screenshot:

```
let url= `https://dph.georgia.gov/sites/dph.georgia.gov/files/related_files/site_page/Emergency%20Protocols%20and%20Procedures.pdf`;

if(/\.(pdf|ppt|doc|docs|excel|dot|wbk|docm|dotx|dotm|docb|xls|xlt|xlm|pot|pps|pptx|pptm|potx|potm|ppam|ppsx|ppsm)($|\W)/.exec(url)){
    url='https://docs.google.com/gview?url='+url.trim()+'&embedded=true&toolbar=hide';
    wait=5000;
}

...
```
