### ISSUE TITLE
"Error: Node is not an Element" when calling CSS.getMatchedStylesForNode

### ISSUE THREAD

**Issue by Marcool04** [cyrus-and/chrome-remote-interface#251]
I am sorry to create a new issue for what I am sure is just my own misunderstanding of what exactly is going on here.
I am trying to write a function that uses headless chrome to get CSS from a specific page.
The method I am attempting to use is CSS.getMatchedStylesForNode().
I have the following code:

```js
#!/usr/bin/env node

const CDP = require('chrome-remote-interface');

const BASE_URL = "http://www.test.com";

CDP(  (chromeDebugClient) => {
    getCSSFromURL(chromeDebugClient, BASE_URL)
    .then( (CSS) => {
        console.log("CSS:");
        console.log(CSS);
        chromeDebugClient.close().finally( process.exit() );
    }).catch( (err) => {
        console.log("Error in getCSSFromURL.")
        console.error(err);
        chromeDebugClient.close().finally( process.exit() );
    });
}).on('error', (err) => {
    console.log("Cannot connect to headless chrome.");
    console.error(err);
    process.exit();
});

function getCSSFromURL(client, url) {
    console.log("Getting CSS from: " + url);
    return Promise.all([
            client.Network.enable(),
            client.Page.enable(),
            client.Network.setCacheDisabled({cacheDisabled: true}),
            client.DOM.enable(),
            client.Page.navigate({url: url}),
            client.Page.loadEventFired(),
            client.CSS.enable(),
            ])
    .then ( () => {
        return client.DOM.getDocument();
    }).then ( (documentObject) => {
        console.log("Document object:");
        console.log(documentObject);
        // THIS IS OBVIOUSLY THE PROBLEMATIC CODE:
        return client.CSS.getMatchedStylesForNode( {nodeId: documentObject.root.nodeId } );
        // I have also tried:
        // return client.CSS.getMatchedStylesForNode( documentObject.root.nodeId );
        // which gives an error saying: 
        // "Error: Invalid parameters (nodeId: integer value expected)"
    }).then ( (matchedStyles) => {
        return Promise.all([
            Promise.resolve(matchedStyles),
            client.DOM.disable(),
            client.CSS.disable(),
            client.Page.disable(),
            client.Network.disable(),
        ]);
    }).then( ([matchedStyles,,,,]) => {
        return matchedStyles;
    }).catch((err) => {
        console.log("Error in getCSSFromURL(" + url + ")");
        console.error(err);
        client.close().finally( process.exit() );
    });  
};
```

There is most certainly some problem with the code I have written there.
I did read issue https://github.com/cyrus-and/chrome-remote-interface/issues/37 in which I read that
> the lifespan of a unique DOM node identifier is not, as one would imagine, static, i.e., it gets regenerated every time chrome.DOM.getDocument is executed and of course between two consecutive sessions.

I believe that is probably related, but I am not sure what to make of this...
The example in that issue uses callbacks and I have build my code using promises. As I am not exactly a very experienced node.js developer I am not certain how to adapt my example accordingly.
Any help would be much appreciated.
Best regards,

Mark.

| Component | Version
|-|-
| Operating system	  	 	| macOS 10.12.6
| Node.js					| v8.2.1
| Chrome/Chromium/...		| Google Chrome 60.0.3112.101
| chrome-remote-interface	| 0.24.4

Is Chrome running in a container? NO

**Comment by Marcool04** [comment]
Damn it, solved my own problem!
I guess I should have just read the message properly.
Node is not an Element... I was trying to parse the root node. But that is not an Element, so has no css properties to parse!
This helped me understand the problem: https://developer.mozilla.org/en/docs/Web/API/Node/nodeType

| Constant | Value | Description
| -- | -- | --
| Node.ELEMENT_NODE | 1 | An Element node such as p or div.


Then I fixed the above code by replacing `DOM.getDocument` by `DOM.getFlattenedDocument()` and adding a walk down the nodes, with a check for Element nature:
```js
if (node.nodeType === 1) {
}
```
Sorry for the self solved issue...

**Comment by cyrus-and** [comment]
Awesome, thanks for the detailed explanation! :)

**Comment by Marcool04** [comment]
My pleasure!
