### ISSUE TITLE
Runtime.evaluate setting the full HTML of a page with resources pointing to relative URLs not resolving

### ISSUE THREAD

**Issue by nlepisto** [cyrus-and/chrome-remote-interface#252]
Hello -

I'm using this service mostly as a screenshot (clipped, not full page) service and have everything working almost 100%. 

I pass the entire DOM from the client (after removing all the script tags), and have relative URLs to CSS files (and then relative URLs within that CSS to fonts, images). I'm hosting this on a node server, but on the same box I have access to the actual CSS, font and image files, just in different directories than my node js script. 

Here is some of my code:

```js
const {frameId} = await Page.navigate({url: "about:blank"});
await Runtime.evaluate({expression: `document.getElementsByTagName('html')[0].innerHTML = \`${html}\``})
```

I can easily write a regex to replace relative URLs to absolute URLs for <link> tags, but it's a PITA (and giving me CORS errors) to replace the relative URLs to our absolute font urls in prod within the actual CSS files. I've tried using the CSS domain and writing a stylesheet to do this, to no avail:

```js
const {styleSheetId} = await CSS.createStyleSheet({frameId});
await CSS.setStyleSheetText({
	styleSheetId,
	text: `
@font-face {
	font-family: 'myfontfam';
	src:  url('myurl?edyy80');
	src:  url('myurl?edyy80#iefix') format('embedded-opentype'),
		  url('myurl?edyy80') format('truetype'),
		  url('myurl?edyy80') format('woff'),
		  url('myurl?edyy80#BrightFunnel') format('svg');
	font-weight: normal;
	font-style: normal;
}`
});
```

What is the context / base path the URL would be here? http://nodeserver:port? Can you think of a way I can access these font files (and CSS / images) from the file system instead?

I've tried creating symlinks to these folders (css, fonts, images) within my app, again, to no avail. Didn't know if the links should be in the chrome dir, node dir, or myapp.js dir... 

| Component | Version
|-|-
| Operating system	  	 | Ubuntu 14.04.5
| Node.js					| v8.4.0
| Chrome/Chromium/...		| Google Chrome 62.0.3188.2
| chrome-remote-interface	| 0.24.4

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Hm what about using [request interception][1] to hijack the URL ([`url`][2] field) so to point to your local content?

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-continueInterceptedRequest

**Comment by nlepisto** [comment]
When testing this, after upgrading to Version 62.0.3199.0 (Official Build) canary (64-bit) on my Mac, running 

```/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --headless --remote-debugging-port=9222 --disable-gpu``` 

doesn't show the headless app showing in my app bar like it used to. All APIs give me an error. I think the new version I updated to today broke something...

At any rate, I also built this with puppeteer.

I'm doing this:
```await page.setRequestInterceptionEnabled(true);
	page.on('request', interceptedRequest => {
		console.log(interceptedRequest.url);
		interceptedRequest.continue();
	});```

.... And relative URLs don't even appear.

After writing some regex replacement to change relative URLs to absolute URLs, it's still not working when updating the URL of the intercepted request:

```if(interceptedRequest.url.indexOf("https://app.myapp.com/fonts/myfont") >= 0) {
				interceptedRequest.url = interceptedRequest.url.replace("https://app.myapp.com/fonts/myfont", "file:///home/ubuntu/myapp/frontend/web-app/fonts/myfont");
			}
			
			interceptedRequest.continue();```


Any other ideas? Why wouldn't page.on('request') not intercept relative URLs?

**Comment by cyrus-and** [comment]
> All APIs give me an error.

What error?

> Why wouldn't page.on('request') not intercept relative URLs?

You should ask this to the Puppeteer team.

**Comment by nlepisto** [comment]
I stupidly left .catch statements after all the domain calls, which must have been deprecated. Now running Version 62.0.3200.0 (Official Build) canary (64-bit) locally on my MBP.

I've removed them (catch statements), and now can intercept the URL with the code you suggested. I have made all URLs absolute to our production site, FYI (CSS, Fonts & Images). Fonts are still failing. But how do you suggest being able to load the fonts from my local content?

I've tried all of these (depending on which env I'm using to test):
```
var pathname = url.parse(request.url);
if(pathname.href.indexOf("https://appdomain/fonts/myFont") >= 0) {
     pathname.href = pathname.href.replace("https://appdomain/fonts/myFont", "file:///home/ubuntu/app/frontend/web-app/fonts/myFont");
     pathname.href = pathname.href.replace("https://appdomain/fonts/myFont", "file:///Users/me/dir/app/frontend/web-app/fonts/myFont");
     pathname.href = pathname.href.replace("https://appdomain/fonts/myFont", "/fonts/myFont");
     pathname.href = pathname.href.replace("https://appdomain/fonts/myFont", "http://localhost:8080/fonts/myFont");
}
```

I also added this:
```
Network.loadingFailed(msg => {
     console.log(JSON.stringify(msg));
});
```

And each attempt always gives me the same error net::ERR_ABORTED and canceled is true.

**Comment by cyrus-and** [comment]
Does the rewritten URL (any of them) is correctly served if you manually try to fetch it? For example, using curl or Chrome itself directly.

**Comment by nlepisto** [comment]
Yes, when I use chrome directly, I'm able to go to the font URLs and they download automatically (locally, dev, stage & prod). That's why I'm so confused. Fonts have CORS restrictions is my only guess: https://deliciousbrains.com/wp-offload-s3/doc/font-cors/

So, maybe somehow, when running my node server on my local or an ubuntu box on port 8000, requesting the font resources fails for some reason. But I can get the CSS and images just fine. I'd think headless chrome would just be able to fetch the resources - unless there's some odd / undefined origin in the request

**Comment by cyrus-and** [comment]
I'm closing this as it doesn't seem to be strictly an issue with this module. Feel free to add details though and I'll do my best to help.

**Comment by tamilselvank** [comment]
Node JS: Install the below command
npm i --save @fortawesome/fontawesome
