### ISSUE TITLE
Ability to capture screenshots of specific HTML nodes

### ISSUE THREAD

**Issue by malyw** [cyrus-and/chrome-remote-interface#253]
**Version**
chrome-remote-interface 0.24.4

**Present in Chrome, but not available via API**
Ability to capture screenshots of specific HTML nodes arrived in Chrome Canary 62 Devtools:
https://twitter.com/ChromeDevTools/status/902662330240057344
but is not present via API

**Issue**
Is there a way to have this available via API?

**How to get a screenshot in Chrome Canary**
1. Open DevTools
2. Select a specific element
3. Press CMD+SHIFT+P
4. type ">node screenshot"
5. Press "Enter", screenshot is downloaded

**The reasoning** 
It will be an easy way for the Front-End components Visual Regression Testing
(making sure the components view didn't change unexpectedly after the code changes, comparing the screenshots before and after),
which previously was mainly used with PhantomJS and other solutions:
https://css-tricks.com/visual-regression-testing-with-phantomcss/

**Comment by cyrus-and** [comment]
I cannot add features to the protocol, but DevTools is as powerful as the protocol (API) itself.

I was going to suggest to inspect DevTools to figure out what's going on during that phase but this particular feature apparently doesn't work when DevTools is being inspected.

Anyway, if you take a look at the [source code][1] you can see that a full viewport screenshot is taken and then clipped using [`getBoundingClientRect`][2]. You can implement this logic in your own code.

Hope it helps.

[1]: https://github.com/ChromeDevTools/devtools-frontend/blob/9700aa6ed00497e374b484353c7b92401defed8b/front_end/emulation/DeviceModeWrapper.js#L103-L125
[2]: https://developer.mozilla.org/en/docs/Web/API/Element/getBoundingClientRect

**Comment by paulirish** [comment]
Over in puppeteer, the solution is to use to collect `getBoundingClientRect` from inside Runtime.evaluate and then use those values as as `clip` parameters on `Page.captureScreenshot`.

see: https://github.com/GoogleChrome/puppeteer/pull/452/files

note that the return val of gBCR is not serializable (BUMMER) so have to do both lines of this:
```js
    const {x, y, width, height} = element.getBoundingClientRect();
    return {left: x, top: y, width, height, id: element.id};
```

**Comment by malyw** [comment]
Works for me, thank you @paulirish 👍

**Comment by CTimmerman** [comment]
Captures wrong area for me in Disqus and YouTube comments. Also rather hard to find feature, compared to Firefox.

**Comment by cyrus-and** [comment]
@CTimmerman

> Captures wrong area for me in Disqus and YouTube comments.

Please file a new issue providing a reproducible example.

> Also rather hard to find feature, compared to Firefox.

This module is just a third-party library, Chrome issues should be filed elsewhere.

**Comment by zewa666** [comment]
@paulirish your example would require the user to have an local app running. I'd like to use the feature from within a Chrome Extension. Any chance to get access to the API in that case?

**Comment by paulirish** [comment]
The protocol is accessible via the `chrome.debugger` extension API.  You
won't use CRI in this case but it's kinda similar.
