### ISSUE TITLE
Network requests from Service Worker ignored

### ISSUE THREAD

**Issue by asakusuma** [cyrus-and/chrome-remote-interface#254]
Requests emitted directly from the service worker don't seem to be showing up in `Network.requestWillBeSent`. I confirmed in DevTools in normal chrome that the request is being sent from the service worker.

| Component | Version
|-|-
| Operating system	  	 	| Mac 10.2.6
| Node.js					| 6.11.2
| Chrome	| 60.0.3112.113
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Can you provide a working example of a web page using service workers that performs requests? So we can look at the same thing.

Also note that page and service worker are two separate targets, for example (some fields omitted):

```json
{
    "id": "a418d72c-d86e-4e11-959f-029976daed44",
    "type": "page"
},
{
    "id": "23c4e3ad-f3ac-4faa-9620-743b3013ccff",
    "title": "Worker pid:15682",
    "type": "service_worker"
}
```

**Comment by paulirish** [comment]
Yeah assuming you haven't yet connected to the service worker target, so you'll have to do that.
