### ISSUE TITLE
REPL hides function return value

### ISSUE THREAD

**Issue by ilanc** [cyrus-and/chrome-remote-interface#257]
Hi Andrea
I'm seeing inconsistent behaviour in the REPL compared to app code. The REPL does not expose the function result - though it does print it. This makes it tricky to test code from the REPL that relies on returned values. 

It's not a priority for me, rather it just caused some confusion, so I thought I'd mention it here in case others stumble upon it. Perhaps an item for the backlog? or the docs?

## app code
```js
const CDP = require('chrome-remote-interface');
(async function () {
  try {
    var client = await CDP();
    const { Network, Page } = client;
    await Promise.all([Network.enable(), Page.enable()]);
    var result = await Page.navigate({ url: 'https://google.com' });
    console.log('my result', result);
    await Page.loadEventFired();

  } catch (err) {
    console.error(err);

  } finally {
    if (client) {
      await client.close();
    }
  }
})();
```
Result
```
node app.js
my result { frameId: '11776.1' }
```

## chrome-remote-interface inspect
```js
(async function () {
  await Promise.all([Network.enable(), Page.enable()]);
  var result = await Page.navigate({ url: 'https://google.com' });
  console.log('my result', result);
})();
```
Result
```
Promise { <pending> }
>>> my result undefined
{ result: {} }
{ result: {} }
{ result: { frameId: '11776.1' } }
```

**Comment by cyrus-and** [comment]
Hi, yes, thanks for pointing it out, the REPL is a strange beast, I'm still not sure what I want it to be. Anyway the README [says][1]:

> But unlike the regular API the callbacks are overridden to conveniently display the result of the commands and the message of the events.

The original idea was to be a way to quickly try commands and events without having to care about the connection, the callbacks, the promises, etc.

In doing so commands and events have been wrapped into additional code that easily allows the user to inspect the result by printing it to the console. I don't really know how to implement this while keeping the proper semantics, i.e., returning a value.

Feel free to share your thoughts about this.

[1]: https://github.com/cyrus-and/chrome-remote-interface#inspection

**Comment by ilanc** [comment]
The REPL is a very handy testing tool. I'd like to use it in the same way as I use the dev tools in chrome - i.e. to fiddle about with some code until I have it working and then cut n paste it into a .js file to "turn it into an app" :)  Right now this doesn't work 100% because the REPL doesn't expose the value. I haven't looked at the source. Is it difficult to expose values to the shell? I'll have some time next week to look into this if you like - any pointers welcome.

**Comment by cyrus-and** [comment]
> Is it difficult to expose values to the shell?

No it's even easier than what I'm doing right now (with [wrappers][1]). The problem arise when I *just* want to see the output of a command, say, `Domain.method(params)`, since the interaction is asynchronous I basically have three choices:

- provide a callback:

    ```js
    Domain.method(params, console.log);
    ```

- use `then`/`catch`:

    ```js
    Domain.method(params).then(console.log).catch(console.error);
    ```

- use `async`/`await`:

    ```js
    (async () => {
        try {
            console.log(await client.Page.navigate({url: 'http://example.com'}));
        } catch (err) {
            console.error(err);
        }
    })();
    ```

These are increasingly verbose, the only viable choice is the first one, but it has some problems:
- the result will be in the form `<boolean> <object>` which may be confusing;
- being the interaction asynchronous this doesn't play nice with the REPL prompt (for this reason I'm using this [hack][2]).

It may be the case that some of these problems can be solved by implementing the REPL using `async`/`await`, even though I'm not sure. In any case such rewrite is planned but it will not be happening anytime soon.

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/49f330641dd804b08507d37efd8e0fbdcc65adaf/bin/client.js#L101-L142
[2]: https://github.com/cyrus-and/chrome-remote-interface/blob/49f330641dd804b08507d37efd8e0fbdcc65adaf/bin/client.js#L95-L99

**Comment by ilanc** [comment]
I hacked the following into `bin/client.js`:
```
// line 103:
            const override = function (params) {
                return new Promise((resolve, reject) => {
                    command(params, function (error, response) {
                        const repr = {};
                        repr[error ? 'error' : 'result'] = response;
                        overridePrompt(display(repr));
                        //overridePrompt('ichack');
                        if (error) reject(error);
                        resolve(response);
                    });
                });
            };
```

This let's me await the result if i want it. It also prints the result when it arrives as before (whether I await the result or not). Would that work for your use cases?

```
>>> (async function () {
...   await Promise.all([Network.enable(), Page.enable()]);
...   var result = await Page.navigate({ url: 'https://google.com' });
...   console.log('my result', result);
... })();
Promise { <pending> }
{ result: {} }
{ result: {} }
{ result: { frameId: '4164.1' } }
>>> my result { frameId: '4164.1' }

>>> Page.navigate({url: "https://github.com/"})
{ result: { frameId: '8776.1' } }
```

The `my result` bit is the part that I want. 

BTW where this started was me trying to do the following in the REPL:
1. issue a `Page.navigate`
2. wait for a requestId 
3. then `Network.getResponseBody({ requestId })`
which would be possible with the above hack to client.js I believe.

What do you think?

**Comment by ilanc** [comment]
BTW that should be `if (error) return reject(error);` - to avoid the resolve being executed on error

**Comment by cyrus-and** [comment]
The problem with this approach is that it creates noise in the console:

```
>>> Page.navigate({url: "https://github.com/"})
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
{ result: { frameId: '22307.1' } }
```

In this case I'd just want `{ result: { frameId: '22307.1' } }`; conversely in your example I would not want it (but I guess one can live with this latter case).

---

I'm experimenting with the following:

```js
function overrideCommand(command) {
    const override = function (params) {
        const promise = command(params);
        // use a custom inspect to display the outcome
        promise.inspect = function () {
            this.then((result) => {
                overridePrompt(display(result));
            }).catch((err) => {
                overridePrompt(display(err));
            });
            // temporary placeholder
            return '...';
        };
        return promise;
    };
    // inherit the doc decorations
    inheritProperties(command, override);
    return override;
}
```

The resulting interaction is:

```
>>> Page.navigate({url: "https://github.com/"})
...
{ frameId: '12433.1' }
>>> Page.navigate({nope: "https://github.com/"})
...
{ Error: Invalid parameters (url: string value expected)
    at /home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/lib/chrome.js:90:30
    at Chrome.handleMessage (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/lib/chrome.js:289:13)
    at WebSocket.<anonymous> (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/lib/chrome.js:266:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/home/cyrus/Dropbox/Backup/dev/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
  response:
   { code: -32602,
     message: 'Invalid parameters',
     data: 'url: string value expected' } }
>>> (async function () {
...   await Promise.all([Network.enable(), Page.enable()]);
...   var result = await Page.navigate({ url: 'https://google.com' });
...   console.log('my result', result);
... })();
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
>>> my result { frameId: '12605.1' }
```

Basically I used a custom [`inspect`][1] function only for the promises generated by commands, this function immediately prints the placeholder (`...`) then when the promise resolves it also prints the outcome.

[1]: ****

**Comment by ilanc** [comment]
Looks great! I'll try it when I'm back at the grindstone. I take it that the Promise output in the last example is coming from the await Promise.all

**Comment by cyrus-and** [comment]
> I take it that the Promise output in the last example is coming from the await Promise.all

Exactly, promises created by the user are left intact.

**Comment by ilanc** [comment]
I think your solution above is best. One other thing I tried:

It's possible to filter the output as well (e.g. to remove all Promises from REPL output) using a variant of the following. I suspect that this will probably just create confusion elsewhere - and it's not complete anyway (colors missing, and prints a blank line for Promises). 

```
const repl = require('repl');
const util = require('util');
const r = repl.start({ prompt: '> ', writer: myWriter });

function myWriter(output) {
  if (output instanceof Promise)
    return '';
  return util.inspect(output);
}
```

Sample output
```
node repl.js
> 1+1
2
> new Promise(() => {})

>
```

**Comment by cyrus-and** [comment]
Yes but those promises are created by the user, it may likewise be confusing to *not* show them since it's what happens in a common Node.js console IMHO.

**Comment by ilanc** [comment]
Yup I agree. I'm happy with your new `overrideCommand`. Feel free to close this issue.

**Comment by cyrus-and** [comment]
Just noticed that the proposed solution doesn't work when a callback is explicitly used. This should fix it:

```js
function overrideCommand(command) {
    const override = function (params, callback) {
        if (typeof callback === 'function') {
            // if a callback is provided the use it as is
            command(params, callback);
            return undefined;
        } else {
            const promise = command(params);
            // use a custom inspect to display the outcome
            promise.inspect = function () {
                this.then((result) => {
                    overridePrompt(display(result));
                }).catch((err) => {
                    overridePrompt(display(err));
                });
                // temporary placeholder
                return '...';
            };
            return promise;
        }
    };
    // inherit the doc decorations
    inheritProperties(command, override);
    return override;
}
```
