### ISSUE TITLE
Network.requestIntercepted does not intercept requests when chrome is started with a new user-data-dir for the first time

### ISSUE THREAD

**Issue by JarrodCTaylor** [cyrus-and/chrome-remote-interface#258]
When attempting to run the code from [Intercept-and-block-requests-by-URL](https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL) the first time chrome is started with a new user-data-dir `Network.requestIntercepted` doesn't intercept requests. If Chrome is stopped and started again with the same user-data-dir it works as expected. This only happens when not using the `--headless` flag. When used in conjunction with chrome-launcher it seems as though the code doesn't work as chrome-launcher creates a new user-data-dir every time. Here is a repo demonstrating this behavior: https://github.com/JarrodCTaylor/cri-request-interception

| Component | Version
|-|-
| Operating system	  	 	| macOS Sierra 10.12.6
| Node.js					| 8.2.1
| Chrome/Chromium/...		| 61.0.3163.79
| chrome-remote-interface	| 0.24.5

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Yep, that's weird, I can confirm it happens.

I suggest you to file an [upstream issue](crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

**Comment by JarrodCTaylor** [comment]
Related Google Group post: https://groups.google.com/forum/#!topic/chrome-debugging-protocol/YC6LbG8lls0

**Comment by cyrus-and** [comment]
Closing this; people may want to keep track of the above thread (if there will ever be a reply).

**Comment by cyrus-and** [comment]
Ops, fixed (https://crbug.com). Yes it might be a good idea IMHO.

**Comment by JarrodCTaylor** [comment]
crbug link: https://bugs.chromium.org/p/chromium/issues/detail?id=764505
