### ISSUE TITLE
Cannot capture a specific region of the page with Page.captureScreenshot

### ISSUE THREAD

**Issue by cratter49** [cyrus-and/chrome-remote-interface#259]
**Versions**
 chrome-launcher | 0.4.0
 chrome-remote-interface | 0.24.4
 Chrome Stable | 61.0.3163.79 (Have used Dev and Beta channels before and saw same issue) 
 Node | 8.4.0

Chrome is running within a Docker container on a image that is based on Ubuntu 14.04

**Issue**
I'm attempting to dynamically take screenshots of all iframes within a web page. In order to do this I have a script which extracts these elements from the DOM and determines their x/y position and dimensions by calling getBoundingClientRect method on the specified iframes. Then the following code is executed to generate PNG's of each iframe within the page.

```js            
for (var i = 0; i < boundingRectangles.length; i++) {
  var boundingRectangle = boundingRectangles[i];
  const{data} = await Page.captureScreenshot({
    clip: {x: boundingRectangle.x, y: boundingRectangle.y, width: boundingRectangle.width, height: 
    boundingRectangle.height, scale: 1.0},
    fromSurface: true
  })
  console.log("Making image "+i);                
   fileSystem.writeFile("image"+i+".png", Buffer.from(data, 'base64'), 'base64', function (err) {
     if (err) throw err;
     console.log('Saved!');
   })
}
```
The boundingRectangles is an array of DOMRect's which is returned from getBoundingClientRect(). Their values are as seen below:

```js
{ x: 57,
  y: 1501.578125,
  width: 1623.203125,
  height: 600,
  top: 1501.578125,
  right: 1680.203125,
  bottom: 2101.578125,
  left: 57 }
Making image 0
{ x: 57,
  y: 2563.359375,
  width: 1623.203125,
  height: 600,
  top: 2563.359375,
  right: 1680.203125,
  bottom: 3163.359375,
  left: 57 }
Making image 1
{ x: 57,
  y: 3664.328125,
  width: 1623.203125,
  height: 846.140625,
  top: 3664.328125,
  right: 1680.203125,
  bottom: 4510.46875,
  left: 57 }
Making image 2
```

Unfortunately, all of the resulting images display the same image which containing the entire page up to window-size discerned when Chrome is launched.  

Does anyone have any idea why setting the viewport each time I capture an image is not working on Linux? I've tested this same code on Mac OS Sierra 10.12.6 (16G29) and the viewport partially worked since half of the screenshots were completely greyed out and the other half were partially greyed out.  

I followed this article:

https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a?1 

and almost every other article suggested within an issue thread within this repository and have had no luck.

Any help would be much appreciated!

**Comment by cyrus-and** [comment]
So I tried on Linux and the `clip` parameter is ignored in Chrome 61 (despite is part of its protocol according to `chrome-remote-interface inspect --remote`) but it works with version 62, so it was probably a bug which has been fixed in the next release. I used this code to test:

```js
const CDP = require('chrome-remote-interface');

const fs = require('fs');

CDP(async (client) => {
    const {Page} = client;
    try {
        await Page.enable();
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
        const {data} = await Page.captureScreenshot({
            clip: {
                x: 100,
                y: 200,
                width: 300,
                height: 400,
                scale: 1.0
            },
            fromSurface: true
        });
        fs.writeFileSync('scrot.png', Buffer.from(data, 'base64'));
    } catch (err) {
        console.error(err);
    } finally {
        await client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by cratter49** [comment]
@cyrus-and I just switched to using the latest version (62.0.3202.9) of the dev channel for Chrome, ran your code, and still saw the same issue in which the screenshot that was taken containing the entire page dictated by the window size I set in the chromeFlags in chromeLauncher.launch. That code looks like this:

```js
function launchChrome(headless = true) {
    return chromeLauncher.launch({
        port: 9222,
        autoSelectChrome: true,
        chromeFlags: [
            '--headless',
            '--disable-gpu',
            '--enable-logging',
            '--no-sandbox',
            '--window-size=1750,1100',
            '--allow-running-insecure-content',
            '--log-net-log',
            '--enable-experimental-web-platform-features'
        ],
        startingUrl: 'https://github.com',
        logLevel: 'verbose'
    });
}
```
Do you think that the error could be stemming from the chrome-launcher package instead?

**Comment by cratter49** [comment]
So I've been trying to brute force any of the methods within Emulation to work but am unsuccessful and noticed some odd behavior. So ``setVisibleSize`` works as expected and changes the viewport of the page but does not help me for taking screenshots of particular elements since I need to move around the page also. But when using ``setDeviceMetricsOverride`` with 
```js
        const deviceMetrics = {
            width: 300,
            height: 400,
            deviceScaleFactor: 0,
            mobile: false,
            dontSetVisibleSize: false
        };
```

And then attempt to take a screenshot my script just hangs. I was able to reproduce this in the REPL client spawned by ``chrome-remote-interface inspect --remote``. When I called ``clearDeviceMetricsOverride`` the contents of multiple screenshots from my attempts to capture the page earlier appeared. However, those screenshots had the same dimensions from ``setVisibleSize``. 

What do you think is going on or how should I continue debugging this issue?

**Comment by cyrus-and** [comment]
Can you try to just start Chrome manually with `google-chrome-unstable --headless --remote-debugging-port=9222` instead of using `chrome-launcher`. In these conditions, using the above code of mine everything works as expected on my Linux box.

Also since you're using a container you may want to try running Chrome outside of it if you can and take a look at [this][1] `FAQ` entry.

[1]: https://github.com/cyrus-and/chrome-remote-interface#why-my-program-stalls-or-behave-unexpectedly-if-i-run-chrome-in-a-docker-container

**Comment by cratter49** [comment]
@cyrus-and I've tried running chrome via the CL in a docker container in the past, even after increasing the ``/dev/shm`` temp dir size, and ran into this error over and over again:

``Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap``

I attempted to research the issue in this [thread](https://github.com/jessfraz/dockerfiles/issues/65) but it required way too many changes to our Dockerfiles which would disrupt our workflow.

**Comment by cyrus-and** [comment]
And what about running on Ubuntu directly (not containerized)?

Anyway, I'm closing this issue as there is nothing I can do with these information and more importantly it's not about this module apparently, it's probably an upstream bug or something even subtler, but feel free to add more details if you want.

You may also want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).
