### ISSUE TITLE
Safari remote inspection support

### ISSUE THREAD

**Issue by SrinivasanTarget** [cyrus-and/chrome-remote-interface#26]
Is there any plans to support safari webviews inspection support like iwdp?

**Comment by cyrus-and** [comment]
Isn't this already possible using [iOS WebKit Debug Proxy][1] itself? AFAIK it should expose an entry point on `localhost:9222` to which you can connect using this module. Unfortunately I cannot try right now, but if you manage to make it work please let me know.

[1]: /google/ios-webkit-debug-proxy

**Comment by SrinivasanTarget** [comment]
Yup aware of iwdp but it is flaky on a long run it discontinues to listen in between.Accept there are workaround but would be great if we have this feature here as well.

**Comment by cyrus-and** [comment]
Oh, that's a shame. This module simply offers a convenient interface to the Chrome Remote Debugging Protocol, that is, it just requires a compliant endpoint, either provided by Chrome/ium itself or by an intermediate proxy/adapter, e.g., the [Edge Diagnostics Adapter][1].

So in this case the perfect candidate seems to be iwdp; I see no point in attempting to provide the same feature here. IMHO your best chance is to contribute to iwdp so to help to fix those issues.

I'm closing this as I assume that the *official* way to do what you're asking is by using iwdp, but feel free to comment here or open an issue if you have any problem concerning the interaction of this module with iwdp.

[1]: /Microsoft/edge-diagnostics-adaptor
