### ISSUE TITLE
 Error: No data found for resource with given identifier

### ISSUE THREAD

**Issue by bookin** [cyrus-and/chrome-remote-interface#260]
Perhaps you can help me with this, I try to get body from some ajax request on the page, but I all time getting  ` Error: No data found for resource with given identifier` and looks like problem only with this request, maybe I'm missing something

```js
const CDP = require('chrome-remote-interface');

setTimeout(() => {
    CDP(async (client) => {
        const {Network, Page, Runtime} = client;
        Network.requestWillBeSent(({requestId, request}) => {
            if(request.url.indexOf("ct2/results/rpc") != -1){
                console.log(`REQ [${requestId}] ${request.method} ${request.url} \n`);
            }
        });
        Network.responseReceived(async ({requestId, response}) => {
            if(response.url.indexOf("ct2/results/rpc") != -1){
                const {body, base64Encoded} = await Network.getResponseBody({requestId});
                console.log(`RES [${requestId}] body: ${body} \n`);
            }
        });
        try {
            await Promise.all([Network.enable(), Page.enable()]);
            await Page.navigate({url: 'https://clinicaltrials.gov/ct2/results?cond=Parents&term=&cntry1=&state1=&Search=Search&recrs=a#wrapper'});
            await Page.loadEventFired();
            await Runtime.evaluate({
                expression: `document.querySelector('.paginate_button.next').click()`
            });
        } catch (err) {
            console.error(err);
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 1000);
```

Thanks.

**Comment by cyrus-and** [comment]
This happens because AFAIK you're only allowed to call `Network.getResponseBody` when the [`Network.loadingFinished`][1] event has fired. Unfortunately this event doesn't contain the associated request object so you have to keep track of the `requestId` for which you want to fetch the response body.

I implemented this in the following using a [`Set`][2]:

```js
const CDP = require('chrome-remote-interface');

setTimeout(() => {
    CDP(async (client) => {
        const {Network, Page, Runtime} = client;

        const requests = new Set(); // <---------- HERE

        Network.requestWillBeSent(({requestId, request}) => {
            if(request.url.indexOf("ct2/results/rpc") != -1){
                console.log(`REQ [${requestId}] ${request.method} ${request.url} \n`);

                requests.add(requestId); // <---------- HERE

            }
        });
        Network.loadingFinished(async ({requestId}) => {

            if (requests.has(requestId)) { // <---------- HERE

                const {body, base64Encoded} = await Network.getResponseBody({requestId});
                console.log(`RES [${requestId}] body: ${body} \n`);
            }
        });
        try {
            await Promise.all([Network.enable(), Page.enable()]);
            await Page.navigate({url: 'https://clinicaltrials.gov/ct2/results?cond=Parents&term=&cntry1=&state1=&Search=Search&recrs=a#wrapper'});
            await Page.loadEventFired();
            await Runtime.evaluate({
                expression: `document.querySelector('.paginate_button.next').click()`
            });
        } catch (err) {
            console.error(err);
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 1000);
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by bookin** [comment]
Thank you very much for your help, only you are helping people)

**Comment by ilanc** [comment]
Wish I'd found this issue earlier - I actually reported this problem as a bug over on the chromium bug tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=805887

It still seems to fail sometimes occasionally but is much more reliable when called from `Network.loadingFinished`.

My test code is here:
https://github.com/ilanc/devtools-bugs/blob/master/getResponseBody.js

**Comment by cyrus-and** [comment]
@pmurley that may also happen (if I recall correctly) when you navigate away from the URL then you call `Network.getResponseBody` on a stale object; possibly not your case.

**Comment by pmurley** [comment]
Wow, you're quick! Yeah, that makes sense, and it's something I should look into a bit more, but I don't *think* that's what is going on here - at least not in a straightforward way. I'm certainly only calling `Page.navigate` once to visit the target site.

I guess it *could* be something caused by some sort of auto-navigation/redirection within a particular frame(?), but if anyone has any other ideas, I'd be grateful!

**Comment by cyrus-and** [comment]
@pmurley if you can come up with a minimal program that reproduces this issue I could take a look at it.

**Comment by pmurley** [comment]
Here's an example. This usually (but not every single time) prints "Why does this happen?" at least once.

```js
const CDP = require('chrome-remote-interface');

setTimeout(() => {
    CDP(async (client) => {
        const {Network, Page, Runtime} = client;
        var req_ids = new Set();
        Network.requestWillBeSent(({requestId, request}) => {
            req_ids.add(requestId);
        });
        Network.responseReceived(async ({requestId, response}) => {
        });
        Network.loadingFinished(async ({requestId, response}) => {
            if (req_ids.has(requestId)) {
                try {
                    var response_body = await Network.getResponseBody({requestId});
                } catch (err) {
                    console.log(err);
                    console.log('Why does this happen?');
                }
            } else {
                // I am also confused as to why we sometimes we get here,
                // but this is not my main concern.
                console.log('requestId not seen before');
            }

        });
        try {
            await Promise.all([Network.enable(), Page.enable()]);
            await Page.navigate({url: 'http://cnn.com'});
            await Page.loadEventFired();
        } catch (err) {
            console.error(err);
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 10000);
```

**Comment by xgj1988** [comment]
> This happens because AFAIK you're only allowed to call `Network.getResponseBody` when the [`Network.loadingFinished`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished) event has fired. Unfortunately this event doesn't contain the associated request object so you have to keep track of the `requestId` for which you want to fetch the response body.
> 
> I implemented this in the following using a [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set):
> 
> ```js
> const CDP = require('chrome-remote-interface');
> 
> setTimeout(() => {
>     CDP(async (client) => {
>         const {Network, Page, Runtime} = client;
> 
>         const requests = new Set(); // <---------- HERE
> 
>         Network.requestWillBeSent(({requestId, request}) => {
>             if(request.url.indexOf("ct2/results/rpc") != -1){
>                 console.log(`REQ [${requestId}] ${request.method} ${request.url} \n`);
> 
>                 requests.add(requestId); // <---------- HERE
> 
>             }
>         });
>         Network.loadingFinished(async ({requestId}) => {
> 
>             if (requests.has(requestId)) { // <---------- HERE
> 
>                 const {body, base64Encoded} = await Network.getResponseBody({requestId});
>                 console.log(`RES [${requestId}] body: ${body} \n`);
>             }
>         });
>         try {
>             await Promise.all([Network.enable(), Page.enable()]);
>             await Page.navigate({url: 'https://clinicaltrials.gov/ct2/results?cond=Parents&term=&cntry1=&state1=&Search=Search&recrs=a#wrapper'});
>             await Page.loadEventFired();
>             await Runtime.evaluate({
>                 expression: `document.querySelector('.paginate_button.next').click()`
>             });
>         } catch (err) {
>             console.error(err);
>         }
>     }).on('error', (err) => {
>         console.error(err);
>     });
> }, 1000);
> ```

How to filter url when i use loadingFinished.

**Comment by cyrus-and** [comment]
@xgj1988 you need to keep track of the actual request URL, e.g., using a [Map][1]. In a nutshell:

- in `Network.requestWillBeSent` associate `request.url` to `requestId`;
- in `Network.loadingFinished` fetch the URL using `requestId` as key.

This is off topic though, file a new issue if needed.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by xgj1988** [comment]
@xgj1988 Actually ,I use  webContens.debugger  of electron  ,I couldn't find how to get response body .I found the issue from this page , So i think you  know the electron too. Could you tell me how to get the response body in the electron ?

**Comment by cyrus-and** [comment]
@xgj1988 in the same way AFAIK, the API should be the same. Anyway I don't know electron at all. :)
Feel free to file a new issue with some minimal working example.

**Comment by xgj1988** [comment]
@cyrus-and  Network.getResponseBody how to get requetId?

**Comment by cyrus-and** [comment]
@xgj1988 as I told you, it's the one that you get in the `Network.requestWillBeSent`, it's all in the [original snippet][1] really.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/260#issuecomment-328274165

**Comment by xgj1988** [comment]
@cyrus-and  ok I got it . THANKS

**Comment by maklimcz** [comment]
@pmurley @xgj1988 did you figure out what causes problem getting response for some requests? i am also facing this in electron. Could you have a look https://stackoverflow.com/questions/66101799/electron-browserwindow-cannot-get-response-when-debugger-is-attached

**Comment by cyrus-and** [comment]
@maklimcz could it be about caching as mentioned above?

**Comment by maklimcz** [comment]
@cyrus-and  nay, I think it isn't loaded from cache because I don't get a ```Network.requestServedFromCache```
I have traced the event stack for this particular request and got:
```
Network.requestWillBeSentExtraInfo 13548.212
Network.requestWillBeSent 13548.212
Network.responseReceivedExtraInfo 13548.212
Network.responseReceived 13548.212
Network.dataReceived 13548.212 [repeated 135 times]
...
Network.loadingFinished 13548.212
```

**Comment by cyrus-and** [comment]
@maklimcz see if you can reproduce this without Electron.

**Comment by ilanc** [comment]
The conclusion that I came to was that any attempt to "sniff"[^1] network packets using the devtools protocol is not reliable. The `getResponse*` functions may work but when they fail you can't pin it down to anything that you can trace or correct - it's burried somwhere within chromium (more below).

My solution has been to use workaround code - e.g if I need data in the response body and fail to get it then either I find the data on the rendered html page, or I send a fetch request from the app code directly (i.e. rather than asking devtools to ask chrome to fetch it ... and then trying to sniff the response).

I expect that `getResponse*` are just poorly tested, poorly used parts of devtools and over time bugs are introduced or get resolved which leads to erratic performance i.e. there isn't a large enough community of people relying on them to moan about it. I came to this conclusion based on this [stackoverflow post](https://stackoverflow.com/questions/45578739/use-headless-chrome-to-intercept-image-request-data)[^2] which talks about various changes to to chromium which have caused `requestWillBeSent` to omit some headers, as well as a lot of my own failed experimentation[^3]. It's been years since I did any c++ dev though - so I can't say for sure (haven't tried to tack it down in the chromium source).

Hope it helps.

[^1] like `Network.getResponseBody`, `Network.getResponseBodyForInterception` on the receiving side, or `Network.requestWillBeSent` etc on the sending side
[^2] albeit about `requestWillBeSent` - not `getResponse*`
[^3] not much of which is public other than [intercept image data](https://stackoverflow.com/questions/45578739/use-headless-chrome-to-intercept-image-request-data) and my original [chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=805887)

**Comment by maklimcz** [comment]
@cyrus-and @ilanc  it seems i managed to do what I wanted. However I didn't use ```Network.getResponseBody```. I used https://chromedevtools.github.io/devtools-protocol/tot/Fetch/
To use that one need to subscribe for Responses matching a pattern. Then you can react on `Fetch.requestPaused` events. During that you have direct access to request and indirect to response. To get the response call `Fetch.getResponseBody` with proper requestId. Below I've pasted a snippet.

```
dbg.sendCommand('Fetch.enable', {
            patterns: [
                { urlPattern: interestingURLpattern, requestStage: "Response" }
            ]})

   var getResponseJson = async (requestId) => {
         const res = await dbg.sendCommand("Fetch.getResponseBody", {requestId: requestId})
         return JSON.parse(res.base64Encoded ? Buffer.from(res.body, 'base64').toString() : res.body)
     }
    dbg.on('message', (e, m, p) => {
        if(m === 'Fetch.requestPaused') {
            var reqJson = JSON.parse(p.request.postData)
            var resJson = await getResponseJson(p.requestId)
            ...
        }
    });
```

**Comment by iddoeldor** [comment]
> dbg.sendCommand('Fetch.enable', {

Can you please elaborate  how to run your example.

**Comment by robd** [comment]
One thing I found was that it was necessary to ignore 'preflight' requests when calling 

```ts
Network.on("responseReceived",(async (params) => {
  if (params.type == 'Preflight') return
  const {body} = await Network.getResponseBody(params);
  // Do something with the body
}));
```

**Comment by robkenworthy** [comment]
I have discovered that some web sites (like https://nfl.com at time of writing) create mutiple RequestWillBeSent objects for the same URL. Only the first RequestWillBeSent object will allow you to call Network.getResponseBody(...) successfully. The others will result in the "No data found..." error. I haven't thoroughly investigated why you can receive multiple RequestWillBeSent objects for the same URL, but I did notice that the successive RequestWillBeSent objects were of type "script" if you examine the RequestWillBeSent.getInitiator()'s type property, whereas the first one is of type "other". To resolve this problem, I only keep the first RequestWillBeSent for a given URL and discard the others.

Here is some sample output if I add this code when I receive a RequestWillBeSent object:

`System.out.println("RequestWillBeSent: " + requestWillBeSent.getRequestId() + " -> " + requestWillBeSent.getRequest().getUrl() + ", " + requestWillBeSent.getInitiator().getType());`

```
RequestWillBeSent: 37A457472C2662A67CB40AFDFE5852AA -> https://www.nfl.com/, other
RequestWillBeSent: 758821.132 -> https://www.nfl.com/, script
RequestWillBeSent: 758821.131 -> https://www.nfl.com/, script

```
(filtered to show only relevant output)
