### ISSUE TITLE
Using tot protocol does not enable functionality

### ISSUE THREAD

**Issue by kiwialec** [cyrus-and/chrome-remote-interface#261]
I need to use some functionality from the latest TOT protocol (Performance), so have downloaded the protocol, and am using it in my CDP with:
client = await CDP({ protocol: JSON.parse(fs.readFileSync('protocol.json'))});

When I check the protocol, all of the new domains exist, i.e. 'Performance' is listed when I use
CDP.Protocol(function (err, protocol) {
		if (!err) {
			protocol.descriptor.domains.forEach(function(val,i){
				console.log(i,val.domain)
			})
		}
});

However, when I later use client.send('Performance.enable'), I only get an error saying that Performance.enable was not found.

Is there something more that needs to be done to use a custom protocol?

**Comment by kiwialec** [comment]
Closing: Fixed by using newer version of chrome

**Comment by cyrus-and** [comment]
FYI the `CDP.Protocol` method doesn't take into account the protocol specified by`CDP({protocol: ...})`.
