### ISSUE TITLE
Page.loadEventFired occurs prior to loading fonts

### ISSUE THREAD

**Issue by gnat42** [cyrus-and/chrome-remote-interface#263]
| Component | Version
|-|-
| Operating system	  	 	| Linux (CentOS 7)
| Node.js					| 8.4
| Chrome/Chromium/...		| 60.0.3112.113
| chrome-remote-interface	| 0.24.2

Is Chrome running in a container? NO

Using the following code to produce a PDF.

```js
async function load(html) {
    console.log('Load(html) called');
    let tab = undefined;
    try {
        tab = await CDP.New({port: options.port});
        const client = await CDP({tab});
        const {Network, Page} = client;
        await Promise.all([Network.enable(), Page.enable(),DOM.enable()]);
        return new Promise(async (resolve, reject) => {
            let failed = false;
            const url = /^(https?|file|data):/i.test(html) ? html : `data:text/html,${html}`;

            Network.loadingFailed((params) => {
                failed = true;

                console.log('Load(html) Network.loadingFailed: "'+params.errorText+'"');
                reject(new Error('Load(html) unable to load remote URL: ' + url));
            });

            Network.requestWillBeSent((params) => {
               console.log('Load(html) Request ('+params.requestId+') will be sent: '+params.request.url);
            });

            Network.responseReceived((params) => {
              console.log('Load(html) Response Received: ('+params.requestId+') Status: '+params.response.status);
            });

            Page.navigate({url});
            await Page.loadEventFired();
            if (!failed) {
                console.log('Load(html) resolved');
                resolve({client: client, tab: tab});
                return;
            }
            await CDP.Close({port: options.port, id: tab.id});
        });
    } catch (error) {
        console.log('Load(html) error: ' + error);
        if (tab) {
            console.log('Load(html) closing open tab');
            CDP.Close({port: options.port, id: tab.id});
        }
    }
}
```
I see all assets loaded and response received before 'Load(html) resolved'. However after resolved I get the request for fonts and that received. Is there a way to know when fonts have loaded? Without the fonts, we get a white empty page. Oddly sometimes restarting the chrome instance helps. We even installed all fonts locally (in /usr/share/fonts) to try to address the issue.

If this isn't a bug, do I just wait a second or two from resolved before initiating a pdf?

**Comment by cyrus-and** [comment]
This isn't a bug (at least, not in this module). Being the font loading an asynchronous operation, it may be the case that the `Page.loadEventFired` event doesn't take them into consideration; I guess this is the desired behavior.

A possible solution would be to explicitly wait for the [`Network.loadingFinished`][1] event for the font requests in order to really consider the page *finished*.

You could track the font requests by checking the URL in `Network.requestWillBeSent`, place the request IDs into a [set][2] then do something like (untested):

```js
async function waitAll(requestIds) {
    return new Promise((fulfill, reject) => {
        while (requestIds.size !== 0) {
            const {requestId} = await Network.loadingFinished();
            requestIds.delete(requestId);
        }
        fulfill();
    });
}
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFinished
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by gnat42** [comment]
yeah, the issue is that it loads and gets the response *after* it considers the page loaded. So now I've introduced a 500ms delay post resolve to wait for any font loading.

**Comment by gnat42** [comment]
I guess a better idea would be to wait and listen for another request and resolve after that... Though I'm not sure how to do that at this point.
