### ISSUE TITLE
fetchFromChromeRepo could be removed

### ISSUE THREAD

**Issue by paulirish** [cyrus-and/chrome-remote-interface#264]
So /json/protocol has been available since Chrome 60.. and Chrome stable is now at 61 (as of last week) so 60 is basically dead.

----------------

FWIW here's how i checked that.

* from https://codereview.chromium.org/2867073006/ clicked through on the commit to get the git hash.
* put that hash into the "Find Releases" input on https://omahaproxy.appspot.com/
* it'll say "60.0.3097.0" in this case.
* omaha-proxy also lists what's the stable version, but a prettier version is here: https://googlechrome.github.io/current-versions/

**Comment by cyrus-and** [comment]
Right, finally! Then I guess I could even use `/json/protocol` by default.
