### ISSUE TITLE
Hangs on http://starhit.ru

### ISSUE THREAD

**Issue by hebedombiu** [cyrus-and/chrome-remote-interface#266]
Hangs on http://starhit.ru

Chrome-remote-interface version: 0.24.5
Chrome version: 61.0.3163.91
Operation system: Arch linux
Node.js version: 8.5.0

google-chrome-stable --remote-debugging-port=9222 --headless

```js
const CDP = require('chrome-remote-interface');

CDP((client) => {
    // extract domains
    const {Network, Page} = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
        console.log(params.request.url);
    });
    Page.loadEventFired(() => {
        client.close();
    });
    // enable events then start!
    Promise.all([
        Network.enable(),
        Page.enable()
    ]).then(() => {
        return Page.navigate({url: 'http://starhit.ru'});
    }).catch((err) => {
        console.error(err);
        client.close();
    });
}).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
});
```

**Comment by cyrus-and** [comment]
Yes it hangs because the page itself does, at least it does sometimes. If you try to load the URL in a non-headless instance you can see that the loading indicator never stops in such cases.

Roughly the `Page.loadEventFired` event corresponds to the loading indicator that stops spinning. You can use a timeout to handle this situation, for example:

```js
setTimeout(() => {
    client.close();
}, 10000);
```

**Comment by hebedombiu** [comment]
If I try to load this page in headless instance from devtools, this page loading normaly.

**Comment by cyrus-and** [comment]
> How i can handle this situation when I using chrome-har-capturer?

You can use the `-u, --timeout <ms>` option, it's the time to wait before giving up with the URL.

**Comment by cyrus-and** [comment]
The problem is that the `Page.loadEventFired` event is required to be fired in order to obtain a meaningful HAR file; a webpage shouldn't hang like that.
