### ISSUE TITLE
Network.setRequestInterceptionEnabled - Invalid InterceptionId and Chrome Crashes

### ISSUE THREAD

**Issue by kiwialec** [cyrus-and/chrome-remote-interface#267]
When using Network.setRequestInterceptionEnabled, I receive errors and Chrome frequently crashes when this happens. After some debugging, it seems like this is caused by resources failing (or at least this is one of the causes).

My script tells all intercepted requests to continue:
```
case "Network.requestIntercepted":
	console.log(params.interceptionId,"Network.requestIntercepted", params.request.url)
    let continueParams = {interceptionId: params.interceptionId}
    client.send('Network.continueInterceptedRequest',continueParams) 
break
```
My script records the various events:
- Network.requestIntercepted [ I send -> Continue]
- 7658.299 Network.requestWillBeSent
- Network.loadingFailed { requestId: '7658.299',
  timestamp: 865.973204,
  type: 'Fetch',
  errorText: 'net::ERR_ABORTED',
  canceled: true }
- (node:7600) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid InterceptionId.
- (node:7600) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

It looks like someone is having the same error on a different library: https://github.com/GoogleChrome/puppeteer/issues/627

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 17.04
| Node.js					| 8.1
| Chrome/Chromium/...		| Tested on 63.0.3213.3 and 62.0.3202.18
| chrome-remote-interface	| 0.24.5

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
I see, but how is this related to chrome-remote-interface? AFAICT the Puppeteer issue was about an unhandled (and *uncatchable*) promise rejection in Puppeteer itself.

**Comment by kiwialec** [comment]
True. I guess this is an error inside Chrome itself. Will follow up in the headless-dev group
