### ISSUE TITLE
Are Emulation.setVisibleSize & Emulation.setDeviceMetricsOverride operations async?

### ISSUE THREAD

**Issue by ApoorvSaxena** [cyrus-and/chrome-remote-interface#268]
We are making use of [`Emulation.setVisibleSize`](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setVisibleSize) & [`Emulation.setDeviceMetricsOverride`](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride) to size our screenshots. Also, have found occurrences where first screenshot is of a different size and rest of the continuing screenshots are of specified size.

```js
Emulation.setDeviceMetricsOverride(deviceMetrics);
Emulation.setVisibleSize({ width: deviceMetrics.width, height: deviceMetrics.height });
```

This behavior is possible if these operations are async, in which case we should wait before they complete. Please confirm.

**Comment by paulirish** [comment]
nearly all methods are async. (there are a few where it doesnt matter, but TBH its not worth trying to sort that out).

just await all protocol methods. :)

**Comment by ApoorvSaxena** [comment]
thanks @paulirish 👍
