### ISSUE TITLE
Is it possible to change the property of the window object before loading the page?

### ISSUE THREAD

**Issue by Dry7** [cyrus-and/chrome-remote-interface#269]
I would like to change some properties, such as **window.screen**, **window.navigator**.
Is it possible to do this before executing the scripts on the page?
Something similar to page.onInitialized in PhantomJS.

**Comment by cyrus-and** [comment]
It depends, what are you *really* trying to achieve here? AFAIK `window.screen` and `window.navigator` are read-only properties. If you're attempting to change the screen size or the user agent then you may want to take a look at [`Network.setUserAgentOverride`][1] and [`Emulation.setDeviceMetricsOverride`][2].

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setUserAgentOverride
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride

**Comment by Dry7** [comment]
@cyrus-and I need to replace window.navigator.platform.
I manage to do this in javascript, but I can not find an event where I can execute this code.

**Comment by cyrus-and** [comment]
Got it, you can give [`Page.addScriptToEvaluateOnNewDocument`](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-addScriptToEvaluateOnNewDocument) a try:

> Evaluates given script in every frame upon creation (before loading frame's scripts).

**Comment by Dry7** [comment]
@cyrus-and thanks for the help
