### ISSUE TITLE
Page.lifecycleEvent missing?

### ISSUE THREAD

**Issue by danieler1981** [cyrus-and/chrome-remote-interface#270]
Hi,

"Page.lifecycleEvent" is missing in the npm release version.
I just wondering to know when this event can be published in the NPM version.

**Comment by cyrus-and** [comment]
Starting from [v0.25.0](https://github.com/cyrus-and/chrome-remote-interface/releases/tag/v0.25.0) (just published) the protocol is fetched from Chrome by default. See 1457e73c4893a23241406d9a174930471da2d30c.

**Comment by danieler1981** [comment]
Page.lifecycleEvent is still undefined. Any suggestion?

**Comment by cyrus-and** [comment]
Most likely your Chrome version doesn't support that event. What version are you using?

**Comment by danieler1981** [comment]
61.0.3163.91 osx

**Comment by cyrus-and** [comment]
You need version 62.

**Comment by danieler1981** [comment]
thank you - it work
