### ISSUE TITLE
Cache the /protocol/json response?

### ISSUE THREAD

**Issue by paambaati** [cyrus-and/chrome-remote-interface#271]
@cyrus-and Is it possible to cache the `/protocol/json` response? Seeing as how it wouldn't change (under most circumstances), we could see some performance benefit in caching the JSON.

**Comment by cyrus-and** [comment]
The performance penalty should be negligible now that the protocol is fetched from Chrome directly, for example on my current machine:

```js
async function test() {
    console.time('CDP.Protocol()');
    const protocol = await CDP.Protocol();
    console.timeEnd('CDP.Protocol()');

    console.time('CDP()');
    const client1 = await CDP();
    console.timeEnd('CDP()');
    client1.close();

    console.time('CDP({protocol})');
    const client2 = await CDP({protocol});
    console.timeEnd('CDP({protocol})');
    client2.close();
}
```

yields:

```
CDP.Protocol(): 32.282ms
CDP(): 35.522ms
CDP({protocol}): 12.446ms
```

If you need to call `CDP()` many times in a second (I struggle to see a valid use case) and find that the protocol fetching is the real bottleneck, you can perform some caching on your side by using the `CDP({protocol})` variant.
