### ISSUE TITLE
Load-balanced remote Chrome?

### ISSUE THREAD

**Issue by paambaati** [cyrus-and/chrome-remote-interface#275]
I am experimenting with a load-balanced farm of Chromes, all running with their `remote-debugging-port` exposed. When I try creating a new target (with `bin/client.js --host chrome.myserver.com --port xxxx new`), it always succeeds. But as soon as I try to inspect it (with `bin/client.js --host chrome.myserver.com --port xxxx inspect 'u-u-i-d'`), it almost always fails with a `unexpected server response` error from `ws`. Note that this doesn't happen when the farm has only 1 Chrome.

I am guessing I'd need sticky sessions or some kind of affinity to always route the `inspect` command to whichever instance of Chrome responded to `new`.

I know this is more of an ops question, but I'm just looking for ideas, or find people who've done something similar.

CC: @cyrus-and, @paulirish

**Comment by paambaati** [comment]
I'm guessing I can get a custom header that will let me know the original target's address, using which I can then use that to construct the websocket URL and use it in a `new` call. Would this work?

**Comment by cyrus-and** [comment]
Instances are identified by their port and Chrome always listens on `localhost`, if you plan to instrument a  number of Chrome instances on node B from node A then you have to set up some network mechanism in order to *bind* the external port to the `localhost` port. IMO the most straightforward way is to setup an SSH tunnel for each instance (port). Please elaborate on how you set up these mechanisms.

**Comment by paambaati** [comment]
@cyrus-and Chrome is set up as a Mesos/Marathon app, load-balanced behind marathon-lb and HAProxy. The remote debugging port is bound to port `X`, which is why the `new` call succeeds - one of the Chrome app instances responds. The problem is being able to follow that same instance and get it to respond to the `inspect` command.

**Comment by paambaati** [comment]
@cyrus-and I've got it figured out; here's what I did —

1. Set up HAProxy to send a custom header in the response, identifying the backend IP and port.
2. Send a raw `new` call myself, read the original IP and port from the response custom header, modify the target's `webSocketDebuggerUrl` and `devtoolsFrontendUrl` and then use it as the target for `inspect`.
