### ISSUE TITLE
Conflicts with the application using WebSockets

### ISSUE THREAD

**Issue by anuraagvaidya** [cyrus-and/chrome-remote-interface#277]
I have a Node application running on the port 3000 that also uses Socket.io.
After a lot of testing, I have concluded that the debugging protocol conflicts with websockets on the server-side. If a browser (doesn't have to be chrome) establishes a websocket connection with the server that is actively using CDP for testing / automation tasks, `CDP((client)=>{})` will crash causing the following error:

```
Error: Invalid target undefined
    at fetchFromObject ($node_modules\chrome-remote-interface\lib\chrome.js:187:21)
    at $node_modules\chrome-remote-interface\lib\chrome.js:235:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

How to reproduce:

CDP script:
```
const CDP = require('chrome-remote-interface');
        async function example() {
            try {
                // connect to endpoint
                var client = await CDP();
                // extract domains
                const {Network, Page} = client;
                // setup handlers
                Network.requestWillBeSent((params) => {
                    console.log(params.request.url);
                });
                // enable events then start!
                await Promise.all([Network.enable(), Page.enable()]);
                await Page.navigate({url: 'https://github.com'});
                await Page.loadEventFired();
            } catch (err) {
                console.error(err);
            } finally {
                if (client) {
                    await client.close();
                }
            }
        }
        setInterval(()=>{
            // this basically is the usual example
            example();
        },10000);
```

1. Start an HTTP server using ExpressJS, hook up socket.io
2. Open a chrome instance with debugging on (for it to fail, debugging instance has to start before ANY socket.io sockets make connection to the server)
3. Test that the example works, and it will work
4. Open a page that connects to socket.io in your regular chrome instance, you can also do it on firefox
5. From this point, CDP will start failing and nothing will work, just CDP.New will work, but not anything else like navigating pages etc.

I have tested with Chrome and Firefox as a client-side browser for socket.io, promise-based as well as async-await examples. The issue is purely related to sockets.

| Component | Version
|-|-
| Operating system	  	 	| Windows 10, Windows 2008 R2, Ubuntu 16.04 LTS
| Node.js					| 8.4.0
| Chrome/Chromium/...		| Both
| chrome-remote-interface	| 0.25.1 (Latest)

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
> I have concluded that the debugging protocol conflicts with websockets on the server-side. 

This seems quite weird.

I think the problem here is that you're attempting to connect to the same Chrome instance more than once. That example doesn't create a new tab so if two `example();` invocations overlaps you may get that error.

**Comment by anuraagvaidya** [comment]
I understand what you're saying, but then it should fail everytime; whereas it fails only when another browser is connected to the server and socket connection is established.

I just tested again, and I confirm that the problem goes away when we run the script from another node process without socket.io. So definitely a socket.io or ws issue.

**Comment by cyrus-and** [comment]
> I understand what you're saying, but then it should fail everytime;

It actually depends on how fast one `example()` invocation completes compared to the 10 seconds interval. If for some reason one invocation hangs, e.g., `Page.loadEventFired()` is not fired, then again you may get that error.

I don't know, you might try to create a [new tab][1] in `example()` and see if it still happens.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab

**Comment by anuraagvaidya** [comment]
> I don't know, you might try to create a new tab in example() and see if it still happens.

Nope, just tested it. Still crashes. I added the timeout example to quickly be able to test, otherwise my implementation doesn't have a timeout, it executes the inner timeout when requested.

**Comment by cyrus-and** [comment]
I cannot reproduce this (and in fact I think it's highly unlikely that two separate processes using WebSockets -- which are just plain TCP sockets from the OS perspective -- creates some kind of interference each others).

This is what I tried:

```console
$ git clone https://github.com/socketio/chat-example.git
$ cd chat-example
$ npm install
$ npm start
```

Then:

```console
$ google-chrome-beta --remote-debugging-port=9222 &
$ node example.js
```

(And your example is running, loading that URL every 10s.)

Using another Chrome instance I navigate to `http://localhost:3000/` and start messing with it.

Everything works as expected.

**Comment by cyrus-and** [comment]
Did you try the scenario depicted in my [last comment][1]?

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/277#issuecomment-334740795
