### ISSUE TITLE
Get URL of current tab when responseReceived is fired

### ISSUE THREAD

**Issue by OlegBabakov** [cyrus-and/chrome-remote-interface#278]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04
| Node.js					| 7.6.0
| Chrome/Chromium/...		| Chrome
| chrome-remote-interface	| 0.25.1

Is Chrome running in a container? NO

Hello!

I'm using CDP and Chrome to catch redirects (301, meta, js redirect) by handling responseReceived event and checking params.type === 'Document' , but faced with problem :  iframes (and another widgets like YouTube videos) also loads as Document (and it's normal).  But I need handle url changes for tab only.  How I use this way:
```js
    Network.responseReceived((params) => {
        if (params.type === 'Document') {
            this.redirects.push(params.response.url);
        }
    });
```
I thought about run js  window.location.toString() for each responseReceived event, but I think it's bad way.
Is there way to get URL for current tab when responseReceived is fired ?

Many thanks!

```js

CDP({port : portCDP}, CDPHandler);

...

let CDPHandler = async function(client) {
    this.redirects = [];

    // Extract used DevTools domains.
    const {DOM, Emulation, Network, Page, Runtime, Security} = client;

    // Enable events on domains we are interested in.
    await Page.enable();
    await DOM.enable();
    await Network.enable();
    await Network.setCacheDisabled({cacheDisabled: true});
    await Security.enable();
    await Security.setOverrideCertificateErrors({override: true});

    // If user agent override was specified, pass to Network domain
    if (userAgent) {
        await Network.setUserAgentOverride({userAgent});
    }

    Network.responseReceived((params) => {
        if (params.type === 'Document') {
            this.redirects.push(params.response.url);
        }
    });

    Security.certificateError(({eventId}) => {
        Security.handleCertificateError({
            eventId,
            action: 'continue'
        });
    });

    await Page.navigate({url});
};
```

**Comment by cyrus-and** [comment]
Hi! I needed something similar in [chrome-har-capturer][1], the solution I came across was to keep track of the *original request* ([`Network.requestWillBeSent`][2]) and treat this one as a special kind of request. But this can help you only in the case of a simple 301 redirect; it's harder to discern the other two.

What you can do is to keep track of the `frameId` field of the original request (`originalFrameId`) and only consider requests (and responses) that have `initiator.type === 'other' && frameId === originalFrameId`.

You can also obtain the document URL via the `documentURL` field and consider only those requests that matches the tab URL (this should be the same as `window.location.toString() `) but I guess you'll have to take into account the redirects themselves here.

Hope it helps!

[1]: https://github.com/cyrus-and/chrome-har-capturer
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

**Comment by OlegBabakov** [comment]
Hi! Thanks for so detailed response ;)
I will try do it today to keep frameId, It can help

>  You can also obtain the document URL via the documentURL
Where can I find documentURL ?  (in requestWillBeSent or responseReceived ? I didn't find this field)

**Comment by cyrus-and** [comment]
You're welcome. It's in [`Network.requestWillBeSent`][1].

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

**Comment by shashidharus** [comment]
@OlegBabakov I used this

> ```
Network.responseReceived((params) => {
        if (params.type === 'Document') {
            this.redirects.push(params.response.url);
        }
    });
```
Then outside in a functio when i try and fetch `this.redirects` it returns empty array. Have you faced something like this?

**Comment by paulirish** [comment]
@shashidharus this will fail when you have iframe requests on the page. I agree with https://github.com/cyrus-and/chrome-remote-interface/issues/278#issuecomment-335135613

**Comment by OlegBabakov** [comment]
```js
    Network.requestWillBeSent((params) => {
        if (params.initiator !== undefined && params.initiator.url !== undefined && params.documentURL !== undefined &&
            this.redirects.indexOf(params.initiator.url) !== -1 && //If initiator page exist in redirects => it's iframe loads
            this.ignoredDocuments.indexOf(params.documentURL) === -1
        ) {
            this.ignoredDocuments.push(params.documentURL);
        }
    });
```

I check every request by this code on existing of params.initiator.url in redirects array. This helps me to avoid counting iframe requests as redirects

**Comment by robotic1** [comment]
I used this
`
...
var cp = await CDP();
...
var infos = await cp.Target.getTargets();
var myUrl=infos.targetInfos[0].url;
`
