### ISSUE TITLE
Performance Metrics

### ISSUE THREAD

**Issue by furlongmt** [cyrus-and/chrome-remote-interface#280]
I'm trying to use a newer feature of Chrome's Devtool Protocols, the Performance metric. However, I continue to get the error of "Cannot read property 'enable' of undefined". I've tried using local and remote protocols, this is an example of where the code fails:

```CDP(async (client) => {
    try {
        const {Performance, Page} = client;
        
        // enable domains to get events
        await Performance.enable();
```

Does chrome-remote-interface support Performance metrics? I see it listed in the protocol.json file.

| Component | Version
|-|-
| Operating system	  	 	| OSX Sierra 10.12.6
| Node.js					| v 8.6.0
| Chrome/Chromium/...		| Chrome 61
| chrome-remote-interface	| 0.25.4

Is Chrome running in a container?  No.

**Comment by cyrus-and** [comment]
You need Chrome version >= 62 for that.

**Comment by furlongmt** [comment]
Thanks so much! I didn't realize I needed the beta for that.

**Comment by Everettss** [comment]
Is it working for chrome 64? I have:
```
chrome-canary --version
Google Chrome 64.0.3254.0 canary
```

and have the same problem as @furlongmt 
```
console.log(client.Performance); // undefined
```
