### ISSUE TITLE
SYN flooding with multiple tabs opened in parallel

### ISSUE THREAD

**Issue by ApoorvSaxena** [cyrus-and/chrome-remote-interface#281]
| Component | Version
|-|-
| Operating system	  	| Debian GNU/Linux buster/sid
| Node.js					| v8.4.0
| Chrome/Chromium/...		| 61.0.3163.91
| chrome-remote-interface	| 0.23.3

Is Chrome running in a container? NO

We are running close to 75 tabs in parallel and on running `dmesg -w` getting following output:
`request_sock_TCP: Possible SYN flooding on port 9222. Sending cookies.  Check SNMP counters.`

Any best practice that we are missing or should we simply increase the limit of connections accepted by Chrome on 9222 port for running this many number of tabs in parallel?

**Comment by cyrus-and** [comment]
The [`CDP.Close()`][1] function always causes a new TCP connection, but AFAIK this is not enough to trigger a "possible SYN flooding" message, this check should be about the queue of connections for which a SYN is received, a SYN+ACK is sent but an ACK is not yet received, a *regular* TCP connection stays in this state for very little time thus making it hard to reach the maximum. I suspect that there are other things going on.

Anyway, there's an alternative, you can use [`Target.closeTarget`][2] from an existing connection, ideally you should use the special browser target which is not bound to any tab, for example:

```js
const CDP = require('chrome-remote-interface');

const browserTargetUrl = 'ws://127.0.0.1:9222/devtools/browser';

CDP({target: browserTargetUrl}, async (client) => {
    const {Target} = client;
    try {
        const targets = [];
        // create targets
        for (let i = 0; i < 100; i++) {
            const {targetId} = await Target.createTarget({url: 'http://example.com'});
            targets.push(targetId);
            console.log(`Target ${targetId} created`);
        }
        // close targets
        targets.forEach((targetId) => {
            Target.closeTarget({targetId});
            console.log(`Target ${targetId} closed`);
        });
        // should remain just one
        console.log(await CDP.List());
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

Note that the browser target URL is random in Chrome >= 62 and you can obtain it from [`CDP.Version()`][3], see an example [here][4].

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpcloseoptions-callback
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-closeTarget
[3]: https://github.com/cyrus-and/chrome-remote-interface#cdpversionoptions-callback
[4]: https://github.com/cyrus-and/chrome-har-capturer/commit/53bd59cea7bc50d43070dfc15bdb1e72c84ecfba

**Comment by ApoorvSaxena** [comment]
thanks @cyrus-and , will implement the recommended approach

**Comment by ApoorvSaxena** [comment]
@cyrus-and is it possible to extract modules like `Network`, `Page` and other modules of Chrome Dev tools specific to a particular tab using `targetId ` while using a single CDP connection?

**Comment by cyrus-and** [comment]
I'm not sure I'm fully understanding what you're asking here, once you have a `client` CDP connection, via `CDP()` you can extract the domains you want:

```js
const {Network, Page} = client;
```

or use it as is:

```js
client.Network.foo();
client.Page.bar();
```

**Comment by ApoorvSaxena** [comment]
but how will we differentiate Network activity of one tab with another's?

**Comment by cyrus-and** [comment]
You'll have one `client` object for each inspected tab. For each of them you can run the same code, just pass `client` as an argument.

**Comment by ApoorvSaxena** [comment]
```js
// close targets
targets.forEach((targetId, client) => {
  client.Network.foo();
  client.Page.bar()
});
```
Is this how we can get the client instance for every tab in reference to the [code above](https://github.com/cyrus-and/chrome-remote-interface/issues/281#issuecomment-335836510)?

**Comment by cyrus-and** [comment]
> Is this how we can get the client instance for every tab in reference to the code above?

Nope, the second parameter of [`forEach`][1] is the current index.

You need to list the targets and list over them:

```js
const CDP = require('chrome-remote-interface');

async function forEachTarget(callback) {
    const targets = await CDP.List();
    targets.forEach(async (target) => {
        try {
            const client = await CDP({target});
            callback(client);
        } catch (err) {
            console.error(err);
        }
    });
}

// for example write the URL of the tab in each document
forEachTarget(async (client) => {
    try {
        client.Runtime.evaluate({
            expression: 'document.write(window.location)'
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
});
```

A more elegant solution would use a `Promise` instead of a callback for `forEachTarget`, but you get the idea.

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Comment by ApoorvSaxena** [comment]
am skeptic about this implementation, as I expect a small pool of targets from
```js
const targets = await CDP.List();
```
which may not be equal to the number of tabs that I am opening in parallel, and there are async operations happening inside every tab.

**Comment by cyrus-and** [comment]
That example shows how to obtain a `CDP` connection *for each* target. You can obviously apply filtering and choose just the targets you need.

Maybe I'm not understanding your problem... what 's the scenario?

**Comment by ApoorvSaxena** [comment]
Scenario is to open up multiple urls in parallel and record there network activity while making use of a single CDP connection, as opening multiple CDP connections causes SYN flooding as per current implementation

**Comment by cyrus-and** [comment]
Eh the "solution" is to use [`Target.sendMessageToTarget`][1] but you basically lose all the aid offered by this library as you need to send raw JSON commands, definitely not recommended.

You should really dig into that SYN flooding message because it should really not happen. I'd love to have a standalone way to reproduce it on my end.

Also, apparently this is **the same** issue as #302.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-sendMessageToTarget

**Comment by cyrus-and** [comment]
> Also, apparently this is the same issue as #302.

In fact, let's move the discussion there.

**Comment by conanF** [comment]
Ask a question. When I close the Target, the browser's connection is not closed, and a lot of closewait appears.

**Comment by cyrus-and** [comment]
@conanF Closing the Target (e.g., `Target.closeTarget`) terminates the TCP connection. Your question is not clear, please provide some example code and a proper description.
