### ISSUE TITLE
Tutorial and resources about the Chrome DevTools Protocol?

### ISSUE THREAD

**Issue by Pacerier** [cyrus-and/chrome-remote-interface#282]
This whole chrome remote debugging affair is hard to navigate. Is there a link to a proper tutorial?

**Comment by cyrus-and** [comment]
The [README][1] and the [Wiki][2] are all that you need to get you started, also the [issues][3] contains a lot of useful use cases and solutions to problems.

Speaking of tutorials you may want to take a look at [Getting Started with Headless Chrome][4].

Finally, additional information can be found in the [Resources][5] section of the [README][1].

You have to consider that the Chrome DevTools Protocol is a pretty low-level solution, you may want to give [Puppeteer][6] a try which is a higher-level API.

[1]: https://github.com/cyrus-and/chrome-remote-interface
[2]: https://github.com/cyrus-and/chrome-remote-interface/wiki
[3]: https://github.com/cyrus-and/chrome-remote-interface/issues?q=is%3Aissue+is%3Aclosed
[4]: https://developers.google.com/web/updates/2017/04/headless-chrome
[5]: https://github.com/cyrus-and/chrome-remote-interface#resources
[6]: https://github.com/GoogleChrome/puppeteer

**Comment by Pacerier** [comment]
Google really needs to hire some of the Java guys to write up a Chrome Trail!, There's no low-level vs high-level, there's only good tutorial vs messy tutorial.

In any case, I bookmarked some creams in the mess for heritors' sake:
- https://stackoverflow.com/questions/28430479/using-google-chrome-remote-debugging-protocol
- https://blog.phantombuster.com/web-scraping-in-2017-headless-chrome-tips-tricks-4d6521d695e8
- https://minhcung.me/chrome-headless-a-whole-new-world-of-web-scraping/
- https://chromedevtools.github.io/devtools-protocol/
- https://chromium.googlesource.com/chromium/src/+/lkgr/headless/README.md
- https://developers.google.com/web/updates/2017/04/headless-chrome
- https://stackoverflow.com/questions/7848878/how-to-use-google-chrome-remote-debugging-protocol-in-http
- https://github.com/auchenberg/devtools-remote
- https://github.com/auchenberg/chrome-devtools-app
