### ISSUE TITLE
stuck on loading page

### ISSUE THREAD

**Issue by icecoldPHP** [cyrus-and/chrome-remote-interface#287]
| Component | Version
|-|-
| Operating system	  	 	| Debian
| Node.js					| 8
| Chrome/Chromium/...		| Chrome
| chrome-remote-interface	| latest

Is Chrome running in a container? YES (61)

Dear Cyrus,

Sorry for doing it like this.
but i'm a little stuck.
i'm trying to access a specific website.
but it's stuck i've tried closing the client but since i'm working with rabbitMQ.
it does not return any result so the whole script will just stand still.

i'm trying to access https://marketing.retailsale.nl/
and for some reason it will only hang if i use headless.

i already have a timeout at 30 sec but i was wondering if there is an other way to make the page loaded event fail and then return a empty object

**Comment by icecoldPHP** [comment]
Issue partially resolved.
It seems that it was a PNG with the dimesions of 7800 x 3800 px 
that was optimized by google pagespeed some time ago.
For some reason it caused the issue of making the webpage wait for that specific image
after altering the image with a newly cropped image this issue was resolved.
but it would be nice to know how i can avoid the whole process of hanging just for one image

**Comment by cyrus-and** [comment]
There is no ready-made way of doing that, it's something you have to implement yourself, if the browser is busy waiting for a resource (server not responding or downloading a big object) the load event is not triggered. It's the same thing as looking at the loading spinner of a regular browser session. I think the timeout is the proper solution in this case.
