### ISSUE TITLE
TypeError: Page.setDownloadBehavior is not a function

### ISSUE THREAD

**Issue by HenleyKuang** [cyrus-and/chrome-remote-interface#290]
I get the error `TypeError: Page.setDownloadBehavior is not a function` when I try to call the setDownloadBehavior API. `await Page.setDownloadBehavior({behavior: 'allow', downloadPath: downloadDirectory})` is my code.

When I print out Page, the output doesn't seem to have the setDownloadBehavior function: [console.log(Page)](https://pastebin.com/SHZTg1G4)

However, I can see the setDownloadBehavior function in the protocols json for my chrome version when I manually navigate to host:port/json/protocol. It's also listed in `lib\protocol.json`.

| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| v8.6.0
| Chrome/Chromium/...		| Chrome stable release 62.0.3202.62 (Official Build) (64-bit)
| chrome-remote-interface	| 0.25.2

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Chrome 62 should, in fact, support that method and the default behavior in chrome-remote-interface 0.25.2 is to fetch the protocol directly from Chrome (via `http://host:port/json/protocol`). Double check that you are using the correct versions. Also try with the CLI:

```console
$ chrome-remote-interface inspect
>>> Page.setDownloadBehavior()
...
```

**Comment by HenleyKuang** [comment]
@cyrus-and 
Just tried running 
`$ chrome-remote-interface inspect
>>> Page.setDownloadBehavior()`
and it worked. Not sure why my code is not able to call that function.

**Comment by cyrus-and** [comment]
Are you able to come up with a minimal program that reproduces this issue?

**Comment by HenleyKuang** [comment]
@cyrus-and 
I found the issue. My program was importing a different version of CDP from a directory I wasn't using anymore. Thanks for the help.

**Comment by cyrus-and** [comment]
You're welcome!
