### ISSUE TITLE
Catch js errors

### ISSUE THREAD

**Issue by anton-kulagin** [cyrus-and/chrome-remote-interface#291]
This issue was reported in past and when i try to use solution from there it didn`t work for me.  [issue #245](https://github.com/cyrus-and/chrome-remote-interface/issues/245). Runtime.exceptionThrown didnt catch errors. I use script provided by @cyrus-and without any changes

| Component | Version
------------ | -------------
| Operating system	  	 	| Windows 10
| Node.js					| v7.7.2
| Chrome/Chromium/...		| Version 61.0.3163.100 (Official Build) (64-bit)/ Version 64.0.3249.2 (Official Build) canary (64-bit)
| chrome-remote-interface	| 0.25.2

**Comment by cyrus-and** [comment]
I'm trying with Chrome 62 (stable) and the code in [this comment][1] still works for me.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/245#issuecomment-325117611

**Comment by cyrus-and** [comment]
Closing as I cannot do anything with the details you provided.
