### ISSUE TITLE
Retrieving the page's redirections

### ISSUE THREAD

**Issue by tsirolnik** [cyrus-and/chrome-remote-interface#292]
It's not an issue but rather a question - 

Is it possible to view the page's navigation history? I've tried using Page.getNavigationHistory but it gave me incorrect results.

Same goes for Network.requestIntercepted which returns incorrect information..

Thanks in advance.

**Comment by cyrus-and** [comment]
> I've tried using Page.getNavigationHistory but it gave me incorrect results.
> Same goes for Network.requestIntercepted which returns incorrect information..

Hi, care to elaborate and provide an example?

Also, what's your use case? Redirections are not part of the navigation history.

When a request is originated by a redirection the `redirectResponse` field of [`Network.requestWillBeSent`][1] is defined.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent

**Comment by tsirolnik** [comment]
Well, what I mean is the following - 

Assuming you navigate to page A (Page.navigate).

Page A then redirects you to page B which redirects you page C.

How can one get this navigation list?

I've tried both ways listed and none worked well.

**Comment by cyrus-and** [comment]
Try this:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Network, Page} = client;
    Network.requestWillBeSent(({request, redirectResponse}) => {
        console.log(`${(redirectResponse || {}).url} -> ${request.url}`);
    });
    try {
        await Network.enable();
        await Page.enable();
        await Page.navigate({url: 'https://httpbin.org/redirect/10'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by tsirolnik** [comment]
Well,

I've made a simple redirect chain using js.do and bit.ly to cnn - http://js.do/code/177866

I've tried using your code but it doesn't seem to work for some reason.

**Comment by cyrus-and** [comment]
You're using:

```js
window.top.location = 'http://cnn.it/1cTNZ3V';
```

which is not a proper *redirect*, that is, it doesn't trigger an HTTP 3xx response. You can inspect the `initiator` field of the [`Network.requestWillBeSent`][1] event to decide if a request is part of what you consider to be a redirect.

Conversely http://bit.ly/1cY78RZ results in:

```
HTTP/1.1 301 Moved Permanently
Location: http://example.com/
```

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent
