### ISSUE TITLE
Chrome tmp files took up all the disk space

### ISSUE THREAD

**Issue by hudidit** [cyrus-and/chrome-remote-interface#295]
| Component | Version
|-|-
| Operating system	  	 	| Linux
| Node.js					| v8.1.4
| Chrome/Chromium/...		| Google Chrome 59.0.3071.115
| chrome-remote-interface	| 0.23.3

Is Chrome running in a container? YES / NO (What does this mean? My app is running in a Docker container, if this is relative to the question.)

### my problem
I have a crawler running on my server. Every crawled page is opened with Chrome (chrome-remote-interface) and some testing scripts will be executed. After about 50 days, the tmp files of Chrome took up almost every bit of my disk space (more than 230G).

This is just a tip of iceberg:
![2017-11-06 4 18 11](https://user-images.githubusercontent.com/2347723/32439561-5384dcf6-c32a-11e7-9ef1-4b206322f231.png)

### Solutions (I guess)
a. Pass in some arguments when starting the Chrome instance, setting the quota of the disk space for Chrome tmp files to take.

b.Run a scheduled task to clear the tmp files.

**Comment by cyrus-and** [comment]
> What does this mean? My app is running in a Docker container, if this is relative to the question.

If the Chrome binary runs within a Docker container then there are some [limitations][1] that you might want to address.

---

This isn't really about chrome-remote-interface, it all depends on how you run Chrome (e.g., [`chrome-launcher`][2]?) and its lifecycle with respect to requests (e.g., do you run one Chrome instance for each request?).

AFAICT the *solution* is to avoid spawning too many Chrome instances, rather just keep one (or a pool of *n*) and make it serve all the requests, or clean up the session directory as soon as one instance terminates.

[1]: https://github.com/cyrus-and/chrome-remote-interface#why-my-program-stalls-or-behave-unexpectedly-if-i-run-chrome-in-a-docker-container
[2]: https://github.com/GoogleChrome/chrome-launcher

**Comment by hudidit** [comment]
@cyrus-and Thanks. I'm using [chrome-runner](https://github.com/gwuhaolin/chrome-runner). I will restart my app and check how many instances are created.
