### ISSUE TITLE
no edge support anymore

### ISSUE THREAD

**Issue by raphaelstary** [cyrus-and/chrome-remote-interface#298]
please remove edge 'implementation'/support from the docs.

it's not working anymore, and the issue is known for some time:
https://github.com/Microsoft/edge-diagnostics-adapter/issues/59

and it will never get fixed again:
https://github.com/Microsoft/edge-diagnostics-adapter/issues/59#issuecomment-343245521

**Comment by cyrus-and** [comment]
Oh, thanks for the heads up.

> and it will never get fixed again:

Well hopefully there will be no more need for an adapter in the future.
