### ISSUE TITLE
DOM.querySelectorAll returns error with code -32000

### ISSUE THREAD

**Issue by shindanim** [cyrus-and/chrome-remote-interface#299]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 14.04 LTS
| Node.js					| v7.10.0 (meteor node version is v8.8.1
| Chrome/Chromium/...		| 61.0.3163.79
| chrome-remote-interface	| chrome-remote-interface@^0.24.5

Is Chrome running in a container?  NO

Hi, I'd like get the all href property of <a>
To do this, I added code based on your previous q & a ( https://github.com/cyrus-and/chrome-remote-interface/issues/64)

and following is my code.

```js
DOM.getDocument((error, params) => {
  const options = {
    nodeId: params.root.nodeId,
    selector: 'a'
  };
  if (error)
  DOM.querySelectorAll(options, (error, params) => {
    if (error) {
      console.error(params);
      return;
    }
  });
```

console.error(params); >> always show error code. 
{ code: -32000, message: 'Could not find node with given id' }
I have searched about  it, and some people it is timing issue, 
so I tried to add sleep code, but it deosn't work for me :(

Do you know what is the problem ?

**Comment by cyrus-and** [comment]
Hi! That code is incomplete, I'm trying with the code from #64 (using `'a'` instead of `'img'` as selector):

```js
const CDP = require('chrome-remote-interface');

CDP((chrome) => {
    chrome.DOM.getDocument((error, params) => {
        if (error) {
            console.error(params);
            return;
        }
        const options = {
            nodeId: params.root.nodeId,
            selector: 'a'
        };
        chrome.DOM.querySelectorAll(options, (error, params) => {
            if (error) {
                console.error(params);
                return;
            }
            params.nodeIds.forEach((nodeId) => {
                const options = {
                    nodeId: nodeId
                };
                chrome.DOM.getAttributes(options, (error, params) => {
                    if (error) {
                        console.error(params);
                        return;
                    }
                    console.log(params.attributes);
                });
            });
        });
    });
}).on('error', (err) => {
    console.error(err);
});
```

This code works fine and prints all the attributes of `<a>` elements (you can fetch the `href` from there).

---

Time has passed since that issue, you can rewrite the above code more conveniently:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {DOM} = client;
    try {
        // get root document id
        const {root: {nodeId}} = await DOM.getDocument();
        // get all the <a> elements
        const {nodeIds} = await DOM.querySelectorAll({nodeId, selector: 'a'});
        // for each <a> element print its attributes
        nodeIds.forEach(async (nodeId) => {
            const {attributes} = await DOM.getAttributes({nodeId});
            console.log(attributes);
        });
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by shindanim** [comment]
Thank you, it was really helpful. -32000 error was because document had been changed so that nodeId is not valid anymore :)
