### ISSUE TITLE
Browser check fails for CEF / Opera when trying to connect

### ISSUE THREAD

**Issue by stekyne** [cyrus-and/chrome-remote-interface#300]
| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 8.40
| Chrome/Chromium/...		| CEF 3.3202.1680 / Chrome 3.3202.1680
| chrome-remote-interface	| 0.25.3

Is Chrome running in a container? No

This is a follow on from this thread: http://magpcss.org/ceforum/viewtopic.php?f=6&t=15556&p=36537#p36537

Basically, I couldn't get CRI to connect to my CEF application or Opera. I can see in the devtools.js that it checks the browser string and fails if it doesn't match. CEF doesn't populate this field so it fails and Opera is missing not an accepted match. 

Maybe this check is unneeded or too stringent? I would say if there is a response from that URL (json/version) and it contains say the "Protocol-Version" property, that is good enough? Let me know what you think! 

Thanks,
Stephen

**Comment by cyrus-and** [comment]
Cool I didn't know Opera supported the Chrome Debugging Protocol, I'm going to add it to the doc.

That check was needed in order to fetch the proper protocol, but now it is always fetched from `/json/protocol` so I guess I can just drop that version check altogether.

Thanks for the heads up!

**Comment by cyrus-and** [comment]
Give it a try, if everything is alright I'll bump a new version.

**Comment by stekyne** [comment]
Oh cool, I didn't know about `/json/protocol`. Is that interface defined anywhere? I couldn't find anything.

**Comment by cyrus-and** [comment]
It is a pretty recent (and long-awaited) [addition][1], it works at least for Chrome (and derivatives) and Node.js.

[1]: https://bugs.chromium.org/p/chromium/issues/detail?id=538300#c10

**Comment by stekyne** [comment]
Tested both my CEF app and Opera and they're both connecting now. Thank!
