### ISSUE TITLE
Network enable never fulfills

### ISSUE THREAD

**Issue by furstenheim** [cyrus-and/chrome-remote-interface#301]
Hi,
I'm connecting to the debugging port from a chrome extension background page (launching the browser with debugging port) and Network.enable never fulfills.

```js
  const client = await new Promise(function (resolve, reject) {
    CDP({
      target: function (targets) {
        return targets.find(t => t.id === myId)
      }
    }, client => resolve(client))
  await client.Network.enable()
// never gets here
```

However, it is working because if I don't enable it then I cannot listen to Network events like Response received.

Also, if I run the same code in Node.js it works as expected.

| Component | Version
|-|-
| Operating system	  	 	| Linux
| Node.js					| 7.7.1
| Chrome/Chromium/...		| Chromium 64.0.3240.0
| chrome-remote-interface	| 0.25.2

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
I think you miss a `})`. Anyway [`CDP()`][1] already returns a `Promise` and `target` can accept an id, so you probably just want something like this:

```js
const client = await CDP({target: myId});
await client.Network.enable();
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback

---

> I'm connecting to the debugging port from a chrome extension background page

So are you using [this][2]? Are you able to come up with a standalone minimal example so I can try that?

[2]: https://github.com/cyrus-and/chrome-remote-interface#browser-usage

**Comment by furstenheim** [comment]
No, I wasn't using the criRequest. It is inside an extension so I could allow CORS post to the debugging port.

As of a complete example, I think it is a bit too big:
[Here](https://github.com/furstenheim/Playback/blob/232db1ad8eb337753b378b3b3e7d5f65d083f7ce/extension/background.js#L24) is where the client is acquired.
And [here](https://github.com/furstenheim/Playback/blob/232db1ad8eb337753b378b3b3e7d5f65d083f7ce/lib/playback.js#L75) is where the promise was never resolved.

Btw, another two methods didn't get resolved, `Network.setRequestInterceptionEnabled({enabled: true})` and `Network.getResponseBody({requestId})`. However, if the same debugging code was ran from Node (just changing the way we [get the client](https://github.com/furstenheim/Playback/blob/232db1ad8eb337753b378b3b3e7d5f65d083f7ce/test.js#L14)) then all the promises got resolved as expected.

In the end I've avoided the error on the browser using the chrome.debugging API

**Comment by cyrus-and** [comment]
Is there any method that actually gets resolved?

**Comment by cyrus-and** [comment]
(Please also note that using your own promise to fetch the client you're silently ignoring any error, my suggestion is to use my above code.)

**Comment by furstenheim** [comment]
Yes, I get a client and all the listeners:
Network.requestWillBeSent
Network.requestIntercepted
Network.responseReceived
are resolved and the callbacks executed each time a response is executed, so that means that the connection is properly established.

**Comment by cyrus-and** [comment]
Listeners doesn't involve an actual communication (conversely to what happens for methods), it's just client-side code.

> and the callbacks executed each time a response is executed

How can they be if `Network.enable()` is never executed?

**Comment by furstenheim** [comment]
That is the thing, it is executed but the promise never fulfills. If I didn't execute `Network.enable()` then the listeners were never called.

**Comment by cyrus-and** [comment]
> it is executed but the promise never fulfills

So it is *not* executed.

I suspect that no connection is actually made. Try adding proper error handling and/or take a look at the console of the background page.

**Comment by furstenheim** [comment]
It _is_ executed. This listener:

```js
Network.responseReceived(async function ({requestId, response}) {
      debug('Reponse received for :', response.url)
})
```
Is logging the urls for all the requests. Commenting out the line `Network.enable()` makes those logs disappear, so it is doing something. All these logs are in the background page. I've also tried to save the promise to a global variable and it always remains as pending.

**Comment by cyrus-and** [comment]
OK I got it, sorry for the painful interaction browser usage is a very little used feature...

Anyway, it should work now and it wasn't about `Network.enable()`, it was about *all* the methods since the callback mechanism weren't implemented. Methods actually executed but no feedback was given thus `await` wasn't able to work.

Please let me know if it works on your end too.

---

As a side node, there's no need to `await` events if you provide a callback, for example here:

```js
await Network.requestWillBeSent(function () {/*...*/});
```

Conversely if you omit the callback a `Promise` object is returned:

```js
await Network.requestWillBeSent();
/*...*/
```

**Comment by furstenheim** [comment]
I haven't been able to try it, the 0.25.3 in npm does not have the fix and the code in github does not have the bundle. Nevertheless, I have the impression that the fix will only affect Network.enable, but it won't fix `Network.getResponseBody({requestId})` right? I'm guessing it will resolve to undefined instead of the response body.

**Comment by cyrus-and** [comment]
> and the code in github does not have the bundle

You can run `npm run webpack ` to generate it.

> I have the impression that the fix will only affect Network.enable, but it won't fix Network.getResponseBody({requestId}) right?

It should fix every method, the bug was about a missing callback in the WebSocket wrapper for the `send()` method.

**Comment by furstenheim** [comment]
Checked with 0.25.4. Promises complete and in the case of Network.getResponseBody it returns the body as expected.
Thanks
