### ISSUE TITLE
Interception of network requests in a new tab.

### ISSUE THREAD

**Issue by Dry7** [cyrus-and/chrome-remote-interface#303]
Is it possible to track queries in the tab that opens after clicking on the page (popup page)?
The problem is that there are a lot of redirects on this page and when I switch to it, all the redirects have already been executed.

**Comment by cyrus-and** [comment]
Take a look at this [comment][1], does it help?

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/130#issuecomment-302958071

**Comment by Dry7** [comment]
@cyrus-and it helped me, many thanks
