### ISSUE TITLE
Fetch that entire window object using Runtime

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#307]
Running commands like:
` Runtime.evaluate({expression: 'Object.getOwnPropertyNames( window )'}) `
or 
` Runtime.evaluate({expression: 'window'}) `
return a response in the form of 
```
{ result:
   { type: 'object',
     subtype: 'array',
     className: 'Array',
     description: 'Array(2339)',
     objectId: '{"injectedScriptId":1,"id":4}' } }
```
and not the actual object or the array?

**Comment by goelayu** [comment]
I think I partially understand as to why this is happening. 
You can only bring JSON-like objects into Node.js apparently. 

So, then the question would be what would be best way to fetch the entire `window` object, or/and the entire array of properties?

**Comment by cyrus-and** [comment]
> You can only bring JSON-like objects into Node.js apparently.

Precisely, once you have such objects you can fetch them by setting the `returnByValue` parameter to `true`:

```js
Runtime.evaluate({
    returnByValue: true,
    expression: `Object.getOwnPropertyNames(window)`
});
```

**Comment by goelayu** [comment]
If I fetch the entire window object using `expression: "window"`, I get the following error:
`{"code":-32000,"message":"Object reference chain is too long"}`

Is there anyway I fetch the entire window object? Either stream it, or send it in chunks somehow?

**Comment by cyrus-and** [comment]
`window` contains circular references, thus cannot be represented in JSON, try `JSON.stringify(window)`. You should only get what you *really* need from the `window` object.

**Comment by goelayu** [comment]
The error is no longer there however now I don't get the resultByValue. 
This is what I tried:
```
    Runtime.evaluate({
        returnByValue: true,
        expression: `${JSON.stringify("window")}`
    },(err, result) => {
        windowObject = result
    });
```

Output: `{"result":{"type":"string","value":"window"}}`

**Comment by cyrus-and** [comment]
Remove the quotes around `window`, you're passing a string.

**Comment by goelayu** [comment]
That's what I had tried before. Failed
```
        expression: `${JSON.stringify(window)}`
                                      ^

ReferenceError: window is not defined
```

**Comment by cyrus-and** [comment]
That's because you're interpolating the string (just noticed), you don't want to run `JSON.stringify(window)` in Node.js:

```js
Runtime.evaluate({
    expression: 'JSON.stringify(window)'
});
```
---

> `window` contains circular references, thus cannot be represented in JSON, try `JSON.stringify(window)`. 

Just to be clear you'll get an error, I was suggesting you to try to see how you cannot `JSON.stringify` `window`:

    TypeError: Converting circular structure to JSON
