### ISSUE TITLE
Initial request stops downloading

### ISSUE THREAD

**Issue by anthonymayfield111** [cyrus-and/chrome-remote-interface#308]
Hi,

I'm trying to make a request to 'https://pastebin.com/fwW5KqVD' which has a huge initial request file size.  However when I'm loading it through the chrome remote interface it stops receiving data early on at 4205249 bytes each time.

I'm guessing that there is a limit set somewhere either because it's in headless or because I'm missing a standard chrome switch but I can't find one anywhere.  The problem is that currently all event fires for the initial request (loadingFinished and dataReceived stops) so I have no way of knowing it's not loading correctly.

Do you know what might be causing this?

Kind Regards,

Anthony.

**Comment by cyrus-and** [comment]
Are you using Docker or similar?

*(The issue template was there for a reason.)*

It doesn't stop, it's just very slow (~3m on my machine); but that's understandable, that webpage is loading ~20MB of data in the DOM. Even more time is spent if I try to load that URL in a regular (non headless and not inspected) Chrome instance.

What are you really trying to achieve here? Fetching the [raw][1] paste is obviously much faster.

[1]: https://pastebin.com/raw/fwW5KqVD

**Comment by anthonymayfield111** [comment]
Hi Cyrus,  

Thanks for your response, I was expecting a notification but looks like I haven't got them turned on.  

This looks like a error on my part, it seems that the chrome remote interface is downloading the full file in the allotted time and that the events are being hit as expected.  It's just that the file is encrypted so is much smaller than the file size shown in the browser.  This is great for us as I can just access this directly using the getResponseBody.  Previously I was trying to access this through the DOM and looks like I was getting a timeout there instead which is why part of the file was getting returned, as you mentioned this is obviously much slower than retrieving the raw file.

Sorry to have bothered you but thanks to checking,

Anthony.

**Comment by cyrus-and** [comment]
No worries, good luck!
