### ISSUE TITLE
Connect to multiple windows in parallel

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#31]
Is it possible to connect to multiple chromium windows at the same time? Now we connect to a chromium browser through --remote-debugging-port, and we would like to run multiple evaluation tests on multiple windows at the same time.

Any suggestions?

**Comment by cyrus-and** [comment]
The port decides the Chrome instance while you can attach to a specific tab/window using the [`chooseTab`][1] option.

Now, *in parallel* means that you will have several instances of the client:

    Chrome(options1, function (chrome) { /*...*/ });
    Chrome(options2, function (chrome) { /*...*/ });
    // ...

[1]: https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback

**Comment by mato75** [comment]
Exactly, but how would you differentiate between windows? Can you specify to which window can Chrome connect to, and can multiple Chrome be connected to the same chromium browser?

**Comment by cyrus-and** [comment]
There's no such thing as *windows* for what concerns the remote debugging protocols, only tabs, be them part of the same window or not. You can obtain the list of the currently opened tabs for a given browser instance identified by a port with [`Chrome.List`][1], after that you can select one tab object from the returned array and feed it to the [`chooseTab`][2] option.

[1]: https://github.com/cyrus-and/chrome-remote-interface#modulelistoptions-callback
[2]: https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback

**Comment by mato75** [comment]
Ok thank you, will try. It is a bit of an issue, because as I understand, nw.js is build on chromium but it does not support tabs.

**Comment by cyrus-and** [comment]
Different windows of the same Chrome instance are considered tabs. Try this:

1. start your nw.js application like `nw --remote-debugging-port=9222 /the/app`;
2. manage to open multiple windows;
2. visit `http://localhost:9222/json` and see if there is an entry for each open window.

If that's the case you can use the method I described above.

**Comment by mato75** [comment]
Thx again.

**Comment by mato75** [comment]
I am having a little bit of trouble with never versions of nw.js - chromium and how to open my app inside of it.

Works with version 0.12.3:
````
Chrome.New({
	port: that.options.port,
	url: 'file:///' + config.launcher.def_officer_nwjs.appDir + '/index.html'
	}, function (err, tab) {
});
````

But with never versions ( > 0.12.3), url that is used for oppening app does not use file. First window that is successfully opened:
{
description: "",
devtoolsFrontendUrl: "/devtools/inspector.html?ws=localhost:12406/devtools/page/8573B029-FCF9-4EB2-B8BA-A5D2FFCD5EE4",
faviconUrl: "chrome://extension-icon/laeohklakmaeckjcebinbjcagklmbcnm/24/1",
id: "8573B029-FCF9-4EB2-B8BA-A5D2FFCD5EE4",
title: "nw-guardian-app",
type: "app",
url: "chrome-extension://laeohklakmaeckjcebinbjcagklmbcnm/index.html",
webSocketDebuggerUrl: "ws://localhost:12406/devtools/page/8573B029-FCF9-4EB2-B8BA-A5D2FFCD5EE4"
},


Any suggestions on how to successfully open my app in new window?

**Comment by cyrus-and** [comment]
I don't know, I've never used NW.js but I think you can always start a new application with `nw` using a [child process][1] (if you really need to do that from Node.js).

You should post a message on the NW.js [mailing list][2], this doesn't seem to concern chrome-remote-interface.

[1]: https://nodejs.org/api/child_process.html
[2]: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by mato75** [comment]
Well I dont want to do that through nw, but with this library, because Chrome.New opens a new window. When ran with nw, it will open up a new browser.

Ok thank's for your help.
