### ISSUE TITLE
Q: How to capture screenshot with negative offset?

### ISSUE THREAD

**Issue by shakiba** [cyrus-and/chrome-remote-interface#313]
This not an issue, but a question: I want to capture a screenshot with negative offset, is there any way to do that.  Sending negative `clip.x, y` to Page.captureScreenshot doesn't work, also sending negative `positionX/Y` or `viewport.x, y` to Emulation.setDeviceMetricsOverride.  Is there any other option to try?

**Comment by cyrus-and** [comment]
Why would you want to do that? Clipping coordinates starts from 0,0 and that is the top-left corner of the page (i.e., **not** the current viewport) so there's *nothing* in the negative region.

**Comment by shakiba** [comment]
I see! I'm trying to replace phantomjs with chrome in svgexport, sometimes I need to capture the svg from a negative coordinate.

**Comment by cyrus-and** [comment]
OK, does this answer your question?
