### ISSUE TITLE
Any chances i can get reqeust and response headers when downloading a file?

### ISSUE THREAD

**Issue by QueShengyao** [cyrus-and/chrome-remote-interface#314]
I am trying to download a file using chrome-remote-interface. The code is something like following:
```js
const CDP = require('chrome-remote-interface');

async function example() {
    try {
        var client = await CDP({port: 20034});
        // extract domains
        const {Network, Page} = client;
        // setup handlers

        // enable events then start!
        await Promise.all([
            Network.enable(),
            Page.enable()
        ]);
        Network.requestWillBeSent((param) => {
            console.log("Network.requestWillBeSent: " + JSON.stringify(param));
        });

        Network.responseReceived((param) => {
            console.log("Network.responseReceived: " + JSON.stringify(param));
        });

        await Page.setDownloadBehavior({
            behavior: 'allow',
            downloadPath: 'C:\\temp'
        });
        await Page.navigate({url: 'http://ipv4.download.thinkbroadband.com/5MB.zip'});

    }catch (err) {
        console.error(err);
    } finally {

    }
}
example();
```

I am expecting to get some meessages like `Network.requestWillBeSent: xxxx` and `Network.responseReceived: xxxx`. However, i get nothing on console. Is there any specific api i can use to get the headers?

Thanks in advance!

| Component | Version
|-|-
| Operating system	  	 	| Win 10
| Node.js					| 8.9.3
| Chrome/Chromium/...		| 63.0.3239.108
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container?  NO

**Comment by cyrus-and** [comment]
Well, yes, I would expect that too, I'm not sure whether this is the intended behavior or a bug. I suggest to file an [upstream issue](https://crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.
