### ISSUE TITLE
PDF url's just hang

### ISSUE THREAD

**Issue by anthonymayfield111** [cyrus-and/chrome-remote-interface#315]
Hi,

I'm trying to load a PDF page.  I'm actually not too bothered about taking any data from it, I just want to see the content type.  However it doesn't even get to the 'requestWillBeSent' method, do you know what happens in between the Page.navigate and this method?  and if there's any way to detect it.

Below is the code I'm running with a chrome already running on port 7601.   I've tested with different URLs and only the PDF ones seem to hang.

`const CDP = require('chrome-remote-interface');
const fs = require('fs');

CDP({port:7601}, async (client) => {
    const {Page, Network} = client;
    try {
        await Page.enable();
	await Network.enable();

	Network.requestWillBeSent(async(params) => {
	console.error(JSON.stringify(params));
	});

	Network.loadingFinished(async(params) => {
	    console.error("LoadingFinished");
	console.error(JSON.stringify(params));
	});

	Network.loadingFailed(async(params) => {
	    console.error("LoadingFailed");
	});

        console.error("Navigating");
        await Page.navigate({url: 'http://www.pdf995.com/samples/pdf.pdf'});

	
        await Page.loadEventFired();
        const {data} = await Page.captureScreenshot();
        fs.writeFileSync('scrot.png', Buffer.from(data, 'base64'));
    } catch (err) {
        console.error(err);
    } finally {
        await client.close();
    }
}).on('error', (err) => {
    console.error(err);
});`

**Comment by cyrus-and** [comment]
I think this is related to #314; I suggest to take the same steps.

**Comment by anthonymayfield111** [comment]
Ok, thanks, I'll try raising it there, I couldn't see any requests on those forums relating to that thread.
