### ISSUE TITLE
Custom event data

### ISSUE THREAD

**Issue by shokimble** [cyrus-and/chrome-remote-interface#316]
I'm hoping this is a usage question and not a missing feature but I can't find any details online anywhere.

I am firing a custom event from my web page

```
var data = "blah blah blah";
var event = new CustomEvent('captureready', { detail: { mydata: data } });
window.dispatchEvent(event);
```

I am successfully listening for the event (it's definitely triggered):

```
          client.Runtime.evaluate({
            awaitPromise: true,
            expression: `new Promise((fulfill, reject) => {
                          window.addEventListener('captureready', fulfill, {
                            once: true
                          });
                        })`
          }).then((e) => {
            console.log('ok');
            console.log(e.detail);
          }).catch((ex) => {
            console.log('fail', ex);
          });
```

However detail is undefined. It's definitely defined (in the event) as if I listen for it on the page itself I get a print out in the console of "blah blah blah".

```
window.addEventListener("captureready", function(e) {
    console.log(e);
    console.log("received capture ready event", e.detail.mydata);
})
```

I'm hoping I'm doing something wrong. The result I get back is nothing like expected so I think I'm getting a layer from Chrome Remote Interface or the underlying library.

Example of output:

```
{ result: 
   { type: 'object',
     className: 'CustomEvent',
     description: 'CustomEvent',
     objectId: '{"injectedScriptId":1,"id":1}' } }
```

**Comment by shokimble** [comment]
Rather quick update here...I have solved it, writing it down helped me think about it. 

I just realised the event is a native object so can't be serialised across the bridge. Instead just pass the details to the promise resolver.

eg change the expression to call fulfill with the data you want to send from detail.

```
window.addEventListener('printready', function(e) { fulfill(e.detail.mydata); }, {
```

So it ended up being a rooky mistake but it's worth keeping around in case someone wants to do the same thing.

**Comment by cyrus-and** [comment]
Hey thanks for the detailed write up. But remember that you can still pass arbitrary JSON using the `returnByValue` option, like this:

```js
client.Runtime.evaluate({
    awaitPromise: true,
    returnByValue: true,
    expression: `new Promise((fulfill, reject) => {
        window.addEventListener(
            'captureready',
            ({detail}) => fulfill(detail),
            {once: true}
        );
    })`
});
```
