### ISSUE TITLE
Change user agent?

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#32]
How would someone change user agent of the browser?

'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'

**Comment by cyrus-and** [comment]
Using [setUserAgentOverride][1], but this has nothing to do with this project.

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Network/#method-setUserAgentOverride

**Comment by c0b** [comment]
@cyrus-and do you have examples how to use setUserAgentOverride and setExtraHTTPHeaders ? I am using this sample api usage, but either I call `setUserAgentOverride` before Network.enable, or after, or in each `Network.requestWillBeSent` event, nothing happened, from tcpdump ouput the actual sent header / user agent is the old

https://www.npmjs.com/package/chrome-remote-interface#sample-api-usage

```javascript
var Chrome = require('chrome-remote-interface');
Chrome(function (chrome) {
    with (chrome) {
        Network.setUserAgentOverride('user agent');
        Network.setExtraHTTPHeaders({'X-Requested-by': 'Extra User Agent'});
        Network.requestWillBeSent(function (params) {
            console.log(params.request.url);
            // or here, setUserAgent in each request: Network.setUserAgentOverride('user agent');
        });
        Page.loadEventFired(close);
        Network.enable();
        // or here ???
        Page.enable();
        once('ready', function () {
            Page.navigate({'url': 'https://github.com'});
        });
    }
}).on('error', function () {
    console.error('Cannot connect to Chrome');
});
```

**Comment by cyrus-and** [comment]
All the methods of the RDP must specify the argument name, so:

```javascript
Network.setUserAgentOverride({'userAgent': 'user agent'});
Network.setExtraHTTPHeaders({'headers': {'X-Requested-by': 'Extra User Agent'}});
```

**Comment by c0b** [comment]
thanks! that works
