### ISSUE TITLE
Capture screenshot of lazy-loaded content

### ISSUE THREAD

**Issue by michaelknave** [cyrus-and/chrome-remote-interface#322]
Did anyone tried to capture a screenshot of website with lazy loaded content on it ? 

I mean, usually lazy loaded images are showing once you scroll over it, so I used function Input.synthesizeScrollGesture, which is used for scrolling over whole webpage. 

But obviously it didn't work ...

**Comment by paulirish** [comment]
probably need to wait some extra time.. 
you can also listen to network activity and wait for that to quiet down. You can use Page.lifecycleEvent for that and listen for networkidle.

**Comment by cyrus-and** [comment]
@michaelknave if you know what you are waiting for, you can also use a [`MutationObserver`][1], see this [wiki][2].

[1]: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
[2]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element

**Comment by michaelknave** [comment]
@paulirish It is not connected with the network activity, the content just appears when you scroll over it. So obviously, if don't scroll down, it's not there. So some extra time does not work. 

@cyrus-and Generally I don't know what I am waiting for. I f I want to make screenshots of thousands pages...

**Comment by cyrus-and** [comment]
@michaelknave 

> So obviously, if don't scroll down, it's not there. So some extra time does not work.

Obviously, some extra time after the synthetic scroll.

> Generally I don't know what I am waiting for.

That wiki uses a selector to match the newly created elements, it should let you be as generic as you want. You may need to use it in a loop or change it a bit to support repeated events.

Can you provide a real world use case or a simple example so I can try to reproduce this?
