### ISSUE TITLE
Difference between --headless and not, emulating login

### ISSUE THREAD

**Issue by nospam2k** [cyrus-and/chrome-remote-interface#323]
I don't think that this is directly a problem with chrome-remote-interface but I thought I would log it here just in case it is. In the following code, I'm emulating a login with amazon. The problem is that it works if I don't start chrome headless but with remote debugging. If I simply add the --headless and take a screenshot, it says "enter valid email or mobile number." The values show dumped to console in both instances and they are correct.

![screenshot](https://user-images.githubusercontent.com/1284287/35770585-f42e453c-08d2-11e8-821e-81cacd27c4f2.png)

```js
try {
    await Network.enable();
    await Security.enable();
    await Security.setOverrideCertificateErrors({override: true});
    await Page.enable();
    await DOM.enable();
    await Network.setCacheDisabled({cacheDisabled: true});
    await Page.navigate({url: 'https://www.amazon.com/'});
    await Page.loadEventFired();
    result = await Runtime.evaluate({
        expression: 'document.getElementById("ap_email").value = "email@host.com"'
    });
    var result = await Runtime.evaluate({
        expression: 'document.getElementById("ap_password").value = "password"'
    });
    result = await Runtime.evaluate({
        expression: 'document.getElementById("ap_password").value'
    });
    console.log(result);
    result = await Runtime.evaluate({
        expression: 'document.getElementById("ap_email").value'
    });
    console.log(result);
    result = await Runtime.evaluate({
        expression: 'document.getElementsByName("signIn")[0].submit()'
    });
    await Page.loadEventFired();
    const {data} = await Page.captureScreenshot();
    fs.writeFileSync('screenshot.png', Buffer.from(data, 'base64'));
} catch (err) {
    console.error(err);
} finally {
    client.close();
}
```

**Comment by cyrus-and** [comment]
Hm https://www.amazon.com is not the sign in page, and the actual sign in page (https://www.amazon.com/ap/signin ...) only has the email field and a "Continue" button so I cannot really try to reproduce this.

**Comment by nospam2k** [comment]
Sorry, I removed it as the login url contains personal information. To reproduce, you have to create an alexa device and have a client id to build the url with. The actual url (once you created a device is https://www.amazon.com/ap/oa?client_id=amzn1.application-oa2-client.000000000000000000000000000000&scope=alexa:all&scope_data={"alexa:all":{"productID":"alexa_device","productInstanceAttributes":{"deviceSerialNumber":"1234567890"}}}&response_type=code&state=1234-1234-1234&redirect_uri=https://myhttpsserver:3000/authresponse"
So you have to have a legit client id and redirect_uri and productid.

**Comment by cyrus-and** [comment]
Is there an easier way for me to reproduce this, without interacting with my Amazon account? Also I don't particularly like the idea of attempting a number of fake logins.

Amazon refuses the email, presumably only due to the format, yet the values that you get on the console are right, even more strange is the fact that it works in non-headless mode.

You can try to dump all the requests/replies (with [`Network.requestWillBeSent`][1] and [`Network.responseReceived`][2] respectively) so you can see what are the actual values sent to Amazon via the form and its reply.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestWillBeSent
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Network#event-responseReceived

**Comment by nospam2k** [comment]
I will try the Network request/replies and compare between head/headless. I don't know of any other way to actually reproduce. I imagine you could create a seperate amazon developer account. If I don't get anywhere with request/replies, I can set up an account with the necessary details to reproduce and then privately send you credentials.

**Comment by cyrus-and** [comment]
> I can set up an account with the necessary details to reproduce and then privately send you credentials.

Feel free to do that.

**Comment by nospam2k** [comment]
Ok, I've set up an account and I have a reproducable script in full. How can I get you the credentials?

```
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');
const fs = require('fs');

/**** Parameters ****/
const clientId = '';
const userName = '';
const password = '';
const headless = false;


let pageNum = 0;

chromeLauncher.launch({
	port: 9222,
	chromeFlags: [
		'--window-size=412,732',
		'--disable-gpu',
		(headless === true) ? '--headless' : ''
	]
}).then(async chrome => {
    try {
		var client = await CDP();
		const {DOM, Security, Network, Page, Runtime} = client;
		Security.certificateError(({eventId}) => {
			Security.handleCertificateError({
				eventId,
				action: 'continue'
			});
		});
        await Network.enable();
        await Security.enable();
        await Security.setOverrideCertificateErrors({override: true});
        await Page.enable();
        await DOM.enable();
        await Network.setCacheDisabled({cacheDisabled: true});
        await Page.navigate({url: 'https://www.amazon.com/ap/oa?client_id=' + clientId + '&scope=alexa%3Aall&scope_data=%7B%22alexa%3Aall%22%3A%7B%22productID%22%3A%22test_device%22%2C%22productInstanceAttributes%22%3A%7B%22deviceSerialNumber%22%3A%226507626777%22%7D%7D%7D&response_type=code&state=6022c10f-6cbc-50&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fauthresponse'});
        await Page.loadEventFired();
        await Runtime.evaluate({
            expression: 'document.getElementById("ap_email").value = "' + userName + '"'
        });
        await Runtime.evaluate({
            expression: 'document.getElementById("ap_password").value = "' + password + '"'
        });
        var result = await Runtime.evaluate({
            expression: 'document.getElementById("ap_password").value'
        });
        console.log(result);
        result = await Runtime.evaluate({
            expression: 'document.getElementById("ap_email").value'
        });
        console.log(result);
        result = await Runtime.evaluate({
            expression: 'document.getElementsByName("signIn")[0].submit()'
        });
        await Page.loadEventFired();
        const {data} = await Page.captureScreenshot();
        fs.writeFileSync('screenshot.png', Buffer.from(data, 'base64'));
		client.close();
		chrome.kill();
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
		chrome.kill();
    }
});
```

Result screen shots:
Full:
![screenshot-head](https://user-images.githubusercontent.com/1284287/35874805-52adfc78-0b22-11e8-95ce-3d62d2206c06.png)
Headless:
![screenshot-headless](https://user-images.githubusercontent.com/1284287/35874815-59f9898e-0b22-11e8-861b-5eb7209defb3.png)

**Comment by cyrus-and** [comment]
Email: cyrus (dot) and (at) gmail (dot) com

**Comment by cyrus-and** [comment]
OK I got it, even though the reason escapes me, to make it work you need to synthetically click on the button instead of calling the `.submit()` method on the form in headless mode:

```js
document.querySelector('input#signInSubmit').click()
```

Give it a try and let me know.

**Comment by nospam2k** [comment]
Ok, I tried that. Seems to work but now I get a captcha when headless. I'm happy to close this as I know from here on out is just messing with Amazon. Thanks for your efforts. I really appreciate the time you took.

**Comment by cyrus-and** [comment]
You're welcome! Yeah, I noticed the captcha too, I suspect that Amazon is detecting that headless Chrome is being used, you can try to spoof the UA like this:

```js
const userAgent = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36';
await Network.setUserAgentOverride({userAgent});
```

If that's not enough there are a number of other [tricks] that you may also want to try.

[tricks]: https://intoli.com/blog/not-possible-to-block-chrome-headless/

**Comment by nospam2k** [comment]
Thanks, I'll look into it.
