### ISSUE TITLE
Remaining previous request for new connection

### ISSUE THREAD

**Issue by shindanim** [cyrus-and/chrome-remote-interface#325]
Hello, first of all, thank you for the useful tool ;)

But I have a problem during using, 

The logic in my code looks like this:

Launch Puppeteer headless
  Connect CDP -> navigate (site1) -> stopLoading -> close
  Connect CDP -> navigate (site2) -> stopLoading -> close
  ... n loop
Close puppeteer headless

The problem is, 
After I started navigating to site2,
The data from site1 is received, and requestWillBeSent is called with the old data(site1).
Even though I make reconnection for CDP after stoploading and close :( 
When site 2's navigate starts, I'd like to ignore all data of site1 :(

It is hard to say that CDP itself is a problem,
Could I possibly get insight on this issue?

Br, 
Dayoung Shin

| Component | Version
|-|-
| Operating system	  	 	| ubuntu 14.04 LTS
| Node.js					| v7.10.0
| Chrome/Chromium/...		| puppeteer
| chrome-remote-interface	| chrome-remote-interface@^0.24.5

Is Chrome running in a container? NO

**Comment by shindanim** [comment]
In addition, there is a suspicious thing. `disconnect `event is not called after `Promise.await(client.close());`

**Comment by cyrus-and** [comment]
Hey, thanks to you! :)

I think the best option here is to load each URL in a separated tab (possibly using a different [browser context][1]). [This][2] wiki shows how to inspect a new tab (without browser context). While [here][3] you can find a real-world example how to use browser contexts to achieve what you want.

Browser contexts are ideal in this scenario as they grants storage, cache and cookies isolation across tabs, they're like multiple incognito modes.

Hope it helps!

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createBrowserContext
[2]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab
[3]: https://github.com/cyrus-and/chrome-har-capturer/blob/6165d09e99d7429e2ddc8adf8b571fe0c712556e/lib/context.js#L14-L53
