### ISSUE TITLE
Measuring CPU load

### ISSUE THREAD

**Issue by karthikrish9** [cyrus-and/chrome-remote-interface#326]
Hi all,

I am new to  chrome-remote-interface. Is it possible to calculate the CPU usage (load)
of a  webpage? 

Kind regards,
Karthik

**Comment by cyrus-and** [comment]
Well you can profile the page loading and extract some stats from it, see this [wiki][1] and [automated-chrome-profiling][2].

That's not exactly the CPU load as you would see in the OS task manager, if you really need to do that I guess you can always mix CDP commands and executions of, say, `ps` (on Linux) like this:

    ps -p $PID -o pcpu=

Using the [`child_process`][3] module.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Generate-timeline-data
[2]: https://github.com/paulirish/automated-chrome-profiling
[3]: https://nodejs.org/api/child_process.html

**Comment by cyrus-and** [comment]
Actually, there is such thing, the "Performance monitor" drawer does exactly that. It uses the [`Performance.getMetrics`][1] method (you need to call `Performance.enable()` first).

It's not superclear what those values are but you'll need the `ScriptDuration` metric to estimate the CPU load of the JavaScript running in your page; take a look [here][2] to see how DevTools interpret them.

There are other `*Duration` metrics, probably (once processed) taking the sum will give you a more fair estimate of the CPU load if you want to take into account also the rendering phase.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Performance#method-getMetrics
[2]: https://github.com/ChromeDevTools/devtools-frontend/blob/85535d62394d1324a662b776e5b3e4a2692627b8/front_end/timeline/PerformanceMonitor.js#L98-L139

**Comment by karthikrish9** [comment]
Thank you @cyrus-and .
