### ISSUE TITLE
Reason for XHR request and response inside JavaScript workers no being logged.

### ISSUE THREAD

**Issue by karthikrish9** [cyrus-and/chrome-remote-interface#328]
Hi,

I am trying to log all the XHR requests and responses from a website. However, I 
see some  XHR requests and responses  not captured by  `Network.requestWillBeSent` and  `Network.responseReceived` event handlers. What could be the reason for this?

Note that, I can see this XHR requests and responses, that my script failed to capture,
in the network tab in my chrome debug tools. So what could be 
the reason for the script to miss this request and response? 

Following is the code snippet that I am using:

```
Network.requestWillBeSent((params) => {
        fs.appendFile(requests, params.requestId +
        ',' + params.request.url + '\n', function(err){});
    });
    Network.responseReceived((params) => {   
      	  downloadFile[params.requestId] = params.type;
    });

  Network.loadingFinished((params) => {
        if (downloadFile[params.requestId]) {
            Network.getResponseBody({
                requestId: params.requestId
            }).then(response => {
                fs.appendFileSync(path.join(folder, downloadFile[params.requestId] + "-" + params.requestId),
                response.body, function(err){});
            });
        }
    });

```

**Comment by cyrus-and** [comment]
Can you set up a minimal working example so I can try to reproduce it?

Also, what's the point of not filing up the issue template?

**Comment by karthikrish9** [comment]
@cyrus-and,

Here is the script I used. https://gist.github.com/karthikrish9/44aef343d0d27ef0d082fd34169297b0

Run the following command: 

`node test.js https://websightjs.com/`

Then, we don't see a XHR GET request to `https://websightjs.com/cv-wasm.wasm` and the response getting logged.  But this is visible in chrome debug tools.  Kindly let me know why is it no logged.

**Comment by cyrus-and** [comment]
This happens because those requests are performed inside JavaScript workers and from a Chrome perspective they are separate (sub) targets. Bad news is that handling this case requires to write a much more complex code since you cannot use the usual JavaScript API, but if you're just interested in events from workers you can get away pretty easily:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Page, Target} = client;

    Target.attachedToTarget(({sessionId, targetInfo: {url}}) => {
        console.log(`ATTACHED ${sessionId}: ${url}`);
        // enable networks events in this target, you can't use the regular API
        // here, so you have to manually build the messages and take care of
        // ids; it's not really a big deal unless you need to match commands and
        // responses
        Target.sendMessageToTarget({
            sessionId,
            message: JSON.stringify({ // <-- a JSON string!
                id: 1,
                method: 'Network.enable'
            })
        });
    });

    Target.receivedMessageFromTarget(({sessionId, message}) => {
        const {id, method, params} = JSON.parse(message); // <-- a JSON string!
        // you can handle massages from the target here; the same apply about
        // the fact that you can't use the regular API here
        switch (method) {
        case 'Network.requestWillBeSent':
            {
                const {request: {url}} = params;
                console.log(`FROM ${sessionId}: ${url}`);
            }
        default:
            // skip...
        }
    });

    try {
        // automatically attach to newly created target so you don't have to do
        // that manually; you might not interested in all of them though...
        await Target.setAutoAttach({
            autoAttach: true,
            waitForDebuggerOnStart: false
        });
        await Page.navigate({url: 'https://websightjs.com/'});
    } catch (err) {
        console.error(err);
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by emanuelevineti** [comment]
@cyrus-and,

To extend the solution you suggested to also need to retrieve the body of the ServiceWorker responses I'm proceeding with the following code:
  
```
       case "Network.responseReceived":{
          console.log("RECEIVED: " + params.requestId + " " + params.type);

        } 
	case "Network.loadingFinished" :{
          console.log("LOADED: " + params.requestId + " " + params.type);
            Target.sendMessageToTarget({
              sessionId,
              message: JSON.stringify({
                id : tid++,
                method: "Network.getResponseBody",
                params: {requestId: params.requestId}
              })
            }).then(response => {
                  console.log(response);
                  fs.appendFileSync(path.join(folder,params.requestId),
                  response.body, function(err){});
              }); 
        }
```
From my understanding I should be able to receive the response with the body from the worker but instead the response is always empty {}.
Am I missing anything trivial?

**Comment by cyrus-and** [comment]
@emanuelevineti this is about *"but if you're just interested in events from workers you can get away pretty easily"*, in this case you can't. The reply of a method is not the reply of `Target.sendMessageToTarget`, instead you have to wait for a message from the target with a matching `id` field, that would be in the form:

```js
{"id": ..., "result": {...}}
```

See [`enqueueCommand`][1] and [`handleMessage`][2].

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/3297b55800779a35261e1c3a80335026c954015f/lib/chrome.js#L125-L140

[2]: https://github.com/cyrus-and/chrome-remote-interface/blob/3297b55800779a35261e1c3a80335026c954015f/lib/chrome.js#L285-L313

**Comment by karthikrish9** [comment]
Hi @cyrus-and ,

So what should be the approach to log the response data from the requests generated from a
Javascript worker thread? Any pointers appreciated. 

Thank you

**Comment by cyrus-and** [comment]
@karthikrish9 as I said you have to listen for the result message and match the id with the id you used in the request. The code from @emanuelevineti is a good starting point but the response will arrive inside the `Target.receivedMessageFromTarget` handler. It is likely that you'll need an additional data structure (e.g., a map: message id -> callback/info), please see the links in the [above comment][1].

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/328#issuecomment-367782390

**Comment by emanuelevineti** [comment]
Thanks @cyrus-and !
With your suggestions I managed to finally get also the body of the worker responses.
Since I'm working with @karthikrish9  I guess now our issue is solved.

Cheers!

**Comment by karthikrish9** [comment]
Okay, will try that. thank you.

**Comment by cyrus-and** [comment]
Great, you're welcome!

**Comment by goelayu** [comment]
This issue is closed, yet I'm posting here in case someone else got stuck with this issue as I did. 
Apparently just connecting to the service worker doesn't worker, as it further uses a dedicated worker to actually make the network requests. So you'll have to send a message from the main target to the service worker, which in turn should another message to the dedicated worker. 
Just to extend @cyrus-and 's solution, something like this should work 
```
Target.attachedToTarget(({sessionId, targetInfo: {url}}) => {
                console.log(`ATTACHED ${sessionId}: ${url}`);
                // enable networks events in this target, you can't use the regular API
                // here, so you have to manually build the messages and take care of
                // ids; it's not really a big deal unless you need to match commands and
                // responses
                Target.sendMessageToTarget({
                    sessionId,
                    message: JSON.stringify({ // <-- a JSON string!
                        id: 1,
                        method: 'Network.enable'
                    })
                });
                Target.sendMessageToTarget({
                    sessionId,
                    message: JSON.stringify({ // <-- a JSON string!
                        id: 2,
                        method: 'Target.setAutoAttach',
                        params: {autoAttach: true, waitForDebuggerOnStart:false}
                    })
                });
            });

            Target.receivedMessageFromTarget(({sessionId, message}) => {
                const {id, method, params} = JSON.parse(message); // <-- a JSON string!
                // you can handle massages from the target here; the same apply about
                // the fact that you can't use the regular API here
                // console.log(message);
                switch (method) {
                case 'Network.responseReceived':
                    {
                     
                        //params is the data you need
                        break;
                    }
                case "Target.attachedToTarget":{
                    const childSessionId = params.sessionId;
                    console.log("ATTACHED : " + childSessionId);
                    Target.sendMessageToTarget({
                        sessionId,
                        message: JSON.stringify({
                            id:3,
                            method: 'Target.sendMessageToTarget',
                            params: {
                                sessionId: childSessionId,
                                message: JSON.stringify({                   
                                    id:1,
                                    method:'Network.enable'  
                                })
                            }
                        })
                    });
                    break;
                }
                case "Target.receivedMessageFromTarget": {
                    const childMsg = JSON.parse(params.message);
                    // console.log(childMsg.method);
                    switch (childMsg.method){
                        case "Network.responseReceived" :{
                            //childMsg.params is the data you need
                            break;
                        }
                    }
                    break;
                }
                default:
                    // skip...
                }
            });
```
