### ISSUE TITLE
Add Security.setIgnoreCertificateErrors() to protocol.json

### ISSUE THREAD

**Issue by destrofer** [cyrus-and/chrome-remote-interface#330]
| Operating system	  	 	| Any
| Node.js					| Any
| Chrome/Chromium/...		| Chrome 65.0.3325.146
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container? NO

There was an update to chrome DevTools protocol documentation. They added a [new experimental method](https://chromedevtools.github.io/devtools-protocol/tot/Security#method-setIgnoreCertificateErrors) `Security.setIgnoreCertificateErrors()`, and marked methods `Security.handleCertificateError()` and `Security.setOverrideCertificateErrors()` as deprecated.

Please add `Security.setIgnoreCertificateErrors()` to `protocol.json` so we could start (or at least try to) using it before the [great recipe from wiki](https://github.com/cyrus-and/chrome-remote-interface/wiki/Bypass-certificate-errors-(%22Your-connection-is-not-private%22)) stops working.

**Comment by cyrus-and** [comment]
You don't really need that those methods are in the `protocol.json` file anymore, the protocol is fetched from Chrome by default. I'll update the file though...

**Comment by destrofer** [comment]
Thank you, and you're right. Chrome has updated when I opened it's "about" dialog to copy version here, and the new method "magically" started working :)
