### ISSUE TITLE
Socket Hang Up during CDP to Android Chrome over USB

### ISSUE THREAD

**Issue by kunal-mazumdar** [cyrus-and/chrome-remote-interface#332]
Trying to run `example` to Android Chrome with following configuration, chrome is crashing in Mobile and I could see this trace.

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:335:15)
    at Socket.socketOnEnd (_http_client.js:428:23)
    at Socket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19) code: 'ECONNRESET' }
```

I'm able to list, create or activate sessions but `CDP()` not working in seems.

| Component | Version
|-|-
| Operating system	  	 	| Windows
| Node.js					| 9.8.0
| Chrome/Chromium/...		| Android 7.1.1 Chrome 65.0
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container? NO

Am I missing something here??

**Comment by cyrus-and** [comment]
Well this is weird because you can list etc. so the endpoint is reachable. Try to navigate to `http://localhost:9222` from your PC and click on a mobile tab to inspect it with DevTools. Does it work?

**Comment by kunal-mazumdar** [comment]
Yes, it's accessible. Also I can inspect using chrome remote devices. Only CDP() is not working, showing this trace only. I also tried enabling USB debugging in different modes.

**Comment by cyrus-and** [comment]
That error basically means that the server killed the connection prematurely. You can try to manually establish a WebSocket connection to a mobile tab with [`wscat`][1], like this:

```
$ wscat -c ws://localhost:9222/devtools/page/E01769528A12C255DF71685CE2CEF573
connected (press CTRL+C to quit)
> {"id": 1, "method": "Runtime.evaluate", "params": {"expression": "alert(1)"}}
< {"id":1,"result":{"result":{"type":"undefined"}}}
```

You can obtain the address by listing the remote tabs. You should see a message box popping on the mobile tab.

[1]: https://github.com/websockets/wscat

**Comment by kunal-mazumdar** [comment]
I tried this and I'm able to establish the connection using `wscat` and able to run the Json script.
But when I keep this connection open and execute the node file with only following code

`const CDP = require('chrome-remote-interface');
CDP((client) => {
    console.log(client)
}).on('error', (err) => {
    console.error(err);
});`

it again crashes the chrome in mobile and the `wscat` connection also shows `disconnected` :(

**Comment by cyrus-and** [comment]
> it again crashes the chrome in mobile and the wscat connection also shows disconnected :(

Oh, if there is a *crash* then this is probably a Chrome bug. I cannot try to reproduce this right now, I'll do it ASAP.

**Comment by kunal-mazumdar** [comment]
Alright. 

Meanwhile, do you have information for minimum compatibility version of Android & Chrome, that you would have seen working?
I can limit my work till that version using emulators for time being.

Thanks for quick response and hope to hear soon.

**Comment by cyrus-and** [comment]
Yes, I can confirm, it crashes mobile Chrome. In particular, it's fetching the protocol that triggers the crash. You can reproduce it with:

    curl http://localhost:9222/json/protocol

This is definitely a Chrome bug that you should file [here][1]. Feel free to post the link here if you decide to do so.

[1]: http://crbug.com/

**Comment by kunal-mazumdar** [comment]
Well I tried with version 63 and 64 also, similar behavior.

I raised a bug and here is the [link](https://bugs.chromium.org/p/chromium/issues/detail?id=824626) here for tracking.

Thanks

**Comment by cyrus-and** [comment]
Thanks, as a workaround you can set the `local` option to `true` I guess.

**Comment by kunal-mazumdar** [comment]
Thanks a ton, with `{ local: true }`, I am able to make connection. 💯
