### ISSUE TITLE
Cannot figure out how to open up a page in a new tab

### ISSUE THREAD

**Issue by nddipiazza** [cyrus-and/chrome-remote-interface#335]
| Component | Version
|-|-
| Operating system	  	 	| Linux/Windows/Mac
| Node.js					| v9.8.0
| Chrome/Chromium/...		| Chromium 64.0.3282.167 Built on Ubuntu , running on Ubuntu 17.10
| chrome-remote-interface	| chrome-remote-interface@0.25.5

Is Chrome running in a container? YES - kubernetes/docker

Code: https://gist.github.com/nddipiazza/9d1e6f4ad7ca46a100b5ca0a6acba1c4

Is there a way I can alter this code to open a new tab instead of taking over the current tab? 

Right now when it calls Page.navigate it will take over the tab it's using originally.

I want to do something like when you call:

`chrome-remote-interface new 'http://example.com'`

This will open a new tab, then return the ID of the tab. Which is perfect.

I'd like to alter my little program above to take a list of URLs instead of just one. But I can't figure out how.

**Comment by cyrus-and** [comment]
See [this][1] wiki and the [README][2].

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab
[2]: https://github.com/cyrus-and/chrome-remote-interface#cdpnewoptions-callback
