### ISSUE TITLE
CDP.New(config) doesn't respect `host` or `port` parameters in the config you send

### ISSUE THREAD

**Issue by nddipiazza** [cyrus-and/chrome-remote-interface#336]
| Component | Version
|-|-
| Operating system	  	 	| Linux/Windows/Mac
| Node.js					| v9.8.0
| Chrome/Chromium/...		| Chromium 64.0.3282.167 Built on Ubuntu , running on Ubuntu 17.10
| chrome-remote-interface	| chrome-remote-interface@0.25.5

Is Chrome running in a container? NO

I am using this: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab

I tried

```
CDP.New({'host': host, 'port': port}).then((target) => {
          return CDP({target});
      }).then((client) => {
          return client.Runtime.evaluate({
              expression: 'alert("Closing this tab...")'
          }).then(() => {
              const id = client.target.id;
              return CDP.Close({id});
          });
      }).catch((err) => {
          console.error(err);
      });
```

But it still used the default `127.0.0.1:9222`

According to this https://github.com/cyrus-and/chrome-remote-interface#cdpnewoptions-callback it should have respected the config param.

It does however allow you to specify `{url: someUrl}` that works. 

Is this a bug? Or am I not doing it correctly?

**Comment by cyrus-and** [comment]
It's not about `New`, you have to change host and port in `Close` too.

**Comment by nddipiazza** [comment]
OK 

I'm looking at the code. the options should be getting to here:

https://github.com/nddipiazza/chrome-remote-interface/blob/master/lib/external-request.js#L7

It's not clear from the nodejs documentation if the options['host'] and options['port'] will make it in

**Comment by cyrus-and** [comment]
The documentation of `Close` clearly states that there are the `host` and `port` options.

**Comment by nddipiazza** [comment]
added to https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab to account for others might get confused with this similar thing
