### ISSUE TITLE
Chrome crashes when its stdio is not ignored

### ISSUE THREAD

**Issue by paps** [cyrus-and/chrome-remote-interface#338]
Hi, sorry in advance if this does not concern CRI. I think it might not... In this case, can you please redirect me to where I should post this issue?

| Component | Version
|-|-
| Operating system	  	 	| Debian sid
| Node.js					| 8.10
| Chrome/Chromium/...		| Google Chrome 64.0.3282.140 beta
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container? NO

---

The following code opens a lot of tabs (3 at a time) successively on a slightly heavy page. (Can be another page, it's not critical to reproduce the problem.)

If the Chrome sub-process is spawned with `{ stdio: 'ignore' }` then everything goes well. However, using `{ stdio: 'pipe' }` (the default), Chrome crashes (SIGTERM) after having opened a total of 6 tabs.

```js
const CDP = require("chrome-remote-interface")
const Promise = require("bluebird")

const chromeFlags = [
	'--remote-debugging-port=9222',
	"--enable-logging",
	"--v=1",
	"--headless",
]

const child = require("child_process").spawn("google-chrome-beta", chromeFlags, {
	stdio: 'pipe', // change this to 'ignore' and Chrome doesn't crash
})
process.on("exit", () => { child.kill() })
setTimeout(() => { runTest() }, 1000) // give time for Chrome to start

const newTab = async (callback) => {
	return new Promise((resolve, reject) => {
		CDP.New((err, tab) => {
			if (err) {
				console.log(`cannot create new chrome tab: ${err}`)
				process.exit(1)
			} else {
				CDP({ target: tab }, (client) => {
					console.log(`New tab created: ${tab.id}`)
					client.id = tab.id // save the id for a later call to CDP.Close()
					resolve(client)
				}).on('error', (err) => {
					console.log(`cannot connect to chrome tab: ${err}`)
					process.exit(1)
				})
			}
		})
	})
}

const runTab = () => {
	return new Promise(async (resolve, reject) => {
		const c = await newTab()
		await c.Page.enable()
		await c.Page.navigate({
			url: 'https://www.tradesy.com/i/hermes-brown-border-silk-twill-90-cm-scarfwrap/22902226/'
		})
		c.Page.loadEventFired(() => {
			c.close()
			CDP.Close({id: c.id})
			resolve()
		})
	})
}

const runTest = () => {
	const fakeArray = new Array(1000)
	return Promise.each(fakeArray, () => {
		return Promise.all([runTab(), runTab(), runTab()])
	})
}
```

Note that I added `--enable-logging --v=1` which makes Chrome write a lot to stdout/stderr. Removing these flags has the effect of prolonging the life of Chrome, it crashes on the ~450th tab on my system. So this is definitely related to IO.

Any idea of what's going on? This is weird

**Comment by cyrus-and** [comment]
Yup, I can't see how this is a CRI issue, anyway FYI there is a specific module to manage the Chrome process, [chrome-launcher][1], give it a try.

I tried to reproduce it and after 6 tabs the program *stops*, but Chrome does **not** crash. What happens here is that Node.js is expecting that you consume the output streams, which you do not, thus some buffer fills and the runtime stops the child process. Try adding the following to your program for example:

```js
child.stdout.on('data', () => { console.log('STDOUT'); });
child.stderr.on('data', () => { console.log('STDERR'); });
```

Hope it helps.

[1]: https://www.npmjs.com/package/chrome-launcher

**Comment by paps** [comment]
I am aware of chrome-launcher, I'm not using it because they ignore Chrome's stdio.

You're totally right, in my example Chrome does not crashes and the process hangs, my bad.

I had a previous example that used `child_process.execFile()` that made Chrome crash, and thanks to your comment I now understand: `execFile()` buffers the output. (Even though you can pipe the output elsewhere, the buffer still fills up and kills the child if too big...)

So, thanks. I think this fixes it for me
