### ISSUE TITLE
Full page screenshot example says it is out of date. Is it?

### ISSUE THREAD

**Issue by nddipiazza** [cyrus-and/chrome-remote-interface#339]
Your full page screenshot example: https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a?1

Says that it is out of date and to try puppeteer. Puppeteer isn't ideal for me for a few reasons so I'd prefer to use chrome-remote-interface. 

Some things are out of date with it like: 

`Emulation.forceViewport is not a function`

Can we get this example up to date? 

Related: https://github.com/cyrus-and/chrome-remote-interface/issues/203

**Comment by cyrus-and** [comment]
Well that's not *my* example, even though it's linked from the wiki, so I cannot update it.

For what concerns the `Emulation.forceViewport` issue, as mentioned in #203, the new way appears to be [`Emulation.setDeviceMetricsOverride`][1].

Finally, you can extract whatever feature you need from Puppeteer and implement it in chrome-remote-interface by peeking into the source code, e.g., the [screenshot code][2].

Hope it helps.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setDeviceMetricsOverride
[2]: https://github.com/GoogleChrome/puppeteer/blob/d244fced434b5ce1b290451288357f27295b0131/lib/Page.js#L715-L749

**Comment by nddipiazza** [comment]
i updated the wiki

**Comment by nddipiazza** [comment]
@cyrus-and i stripped it down to a more simple example.
