### ISSUE TITLE
Network.getResponseBody callback results are switched

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#34]
When trying to get body of a request, body is always boolean and base64Encoded is the body response.

````
Body: false
base64Encoded:  { body: '<html><body style="margin:0;padding:0"></body></html>',
  base64Encoded: false }
````

**Comment by cyrus-and** [comment]
It would be awesome if you could read the [documentation][1] before opening a new issue; you're clearly putting [no effort][2] into this...

> `callback` is executed when Chrome sends a response to this command, it gets the
following arguments:

> - `error`: a boolean value indicating the success status, as reported by Chrome;
> - `response`: an object containing either the response sent from Chrome
  (`result` field, if `error === false`) or the indication of the error (`error`
  field, if `error === true`).

> When `callback` is omitted a `Promise` object is returned instead, with the
fulfilled/rejected states implemented according to the `error` parameter.

[1]: https://github.com/cyrus-and/chrome-remote-interface#chromesendmethod-params-callback
[2]: https://github.com/cyrus-and/chrome-remote-interface/issues?utf8=%E2%9C%93&q=author%3Amato75

**Comment by mato75** [comment]
Sorry.

**Comment by snowman** [comment]
I am so sorry.
