### ISSUE TITLE
Triggering events on dynamically discovered elements

### ISSUE THREAD

**Issue by pmurley** [cyrus-and/chrome-remote-interface#342]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 16.04
| Node.js					| 9.11.1
| Chrome/Chromium/...		| 67
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container? NO

I'm writing a crawler and trying to get it to trigger input-based events (clicks, hovers, focus/blur, key presses) automatically for an arbitrary site. I'm walking the DOM tree and calling `DOMDebugger.getEventListeners` on each node, and I am able to successfully get all the listeners. However, I'm having some trouble triggering the events themselves. I'd like to be able to just do:

```js
Runtime.evaluate({expression: "document.getElementById('something').blur()"});
```

but I can't, because I don't have the 'something'. For some events (at least focus and click) I can get this done with `Input` or `DOM.focus()`, but it seems it would be way easier if there was a way to get hold of the element in some injected JavaScript.

Is there an easy way to do this? Am I going about it the wrong way?

Thanks for your time.

**Comment by cyrus-and** [comment]
Say you have the `NodeId`, you can obtain the `RemoteObjectId` using [`DOM.resolveNode`][1] and finally call [`Runtime.callFunctionOn`][2] on it:

```js
function blurObject() {
    this.blur();
    return 'result';
}

const nodeId = whatever();
const {object: {objectId}} = await DOM.resolveNode({nodeId});
const {result} = await Runtime.callFunctionOn({
    functionDeclaration: blurObject.toString(),
    objectId
});

console.log(result); // { type: 'string', value: 'result' }
```

You can also use [`Runtime.evaluate`][3] I guess, the return value of [`DOM.resolveNode`][1] is like the following, so `description` should contain the selector you want, but that field is optional and the documentation doesn't explicitly states that will be a CSS selector.

```js
{ type: 'object',
  subtype: 'node',
  className: 'HTMLDivElement',
  description: 'div#container',
  objectId: '{"injectedScriptId":1,"id":6}' }
```

Hope it helps!

[1]: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-resolveNode
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-callFunctionOn
[3]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-evaluate

**Comment by pmurley** [comment]
This is exactly what I need. Thanks; still getting the hang of this JavaScript thing 👍
