### ISSUE TITLE
How to pass options to command line "chrome-remote-interface inspect" command?

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#343]
| Component | Version
|-|-
| Operating system	  	 	| Mac OS X
| Node.js					| 8.7.0
| Chrome/Chromium/...		| 64
| chrome-remote-interface	| 0.25.2

Is Chrome running in a container?  NO

Chrome on android crashes when issuing the command`chrome-remote-interface inspect`  when used with adb forwarding. I'm trying to pass the option "local:true" to see if that would work or not?

**Comment by goelayu** [comment]
Chrome on android is crashing. Edited the question. 

I looked at that issue, and that is why I'm trying to figure out how to pass the option "local:true" from the command line?
The syntax looks like: `chrome-remote-interface inspect [options] [target] `
When I try `chrome-remote-interface inspect "local=true" ` I get `Cannot connect to remote endpoint: Error: Invalid target undefined` which means it is being parsed as the target field and not the options field.

**Comment by cyrus-and** [comment]
Pass the `--help` option to see the usage:

```console
$ chrome-remote-interface inspect -h

  Usage: inspect [options] [<target>]

  inspect a target (defaults to the first available target)


  Options:

    -w, --web-socket            interpret <target> as a WebSocket URL instead of a target id
    -j, --protocol <file.json>  Chrome Debugging Protocol descriptor (overrides `--local`)
    -l, --local                 Use the local protocol descriptor
    -h, --help                  output usage information
```

You need the `--local` option:

```console
$ chrome-remote-interface inspect -l
```

**Comment by goelayu** [comment]
Figured out. It's supposed to be used as ` chrome-remote-interface inspect -l`

My bad. The man page is quite helpful. 

I'll close the issue now. Thanks for the quick response though.

**Comment by cyrus-and** [comment]
You're welcome!
