### ISSUE TITLE
Is there a way to detect dangerous site (google safe browsing) ?

### ISSUE THREAD

**Issue by elaijuh** [cyrus-and/chrome-remote-interface#344]
| Component | Version
|-|-
| Operating system	  	 	|  OSX
| Node.js					| 9.5.0
| Chrome/Chromium/...		| Either
| chrome-remote-interface	| 90.25.6

Is Chrome running in a container?  NO

I would like to check out if there is any way to detect dangerous site through API here. Chrome will match url prefix hash to a local database and if match it send request to server for further match. If the URL is pointing to some dangerous site, chrome shows a big red screen. Any way that CDP can intercept here and do the same function?

**Comment by cyrus-and** [comment]
I don't think so, but you may want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

A simple `grep safe lib/protocol.json` led to nothing useful.

Feel free to comment if you find something relevant.
