### ISSUE TITLE
Responding to Auth Challenge when Chrome is started with --proxy-server flag

### ISSUE THREAD

**Issue by paambaati** [cyrus-and/chrome-remote-interface#345]
I use [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) to start Chrome with the `--startingUrl` flag, which launches Chrome with a single tab set to the given URL. Once it is launched, I query `/json/list`, get all targets, and attach to the `page` target.

I plan to use a third-party proxy (with the `--proxy-server` flag).The goal is to set up a network intercept on `*`, then respond to the `authChallenge` with the proxy credentials. The problem is, with the starting URL, the auth challenge is already presented by the time I attach my target, and I have no way of sending the credentials. How can I go about doing this?

| Component | Version
|-|-
| Operating system	  	 	| `Darwin`
| Node.js					| `10.4.1`
| Chromium					| `r564778`
| chrome-remote-interface	| `0.25.6`

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
You should avoid using the `--startingUrl` option and do everything with `chrome-remote-interface`:

```js
// ...
await Page.enable();
await Page.navigate({url: yourStaringUrl});
await Page.loadEventFired();
// ...
```

**Comment by SwitchGM** [comment]
> I plan to use a third-party proxy (with the `--proxy-server` flag).The goal is to set up a network intercept on `*`, then respond to the `authChallenge` with the proxy credentials. The problem is, with the starting URL, the auth challenge is already presented by the time I attach my target, and I have no way of sending the credentials. How can I go about doing this?

***paambaati*** would you by chance still have the proxy authentication code you mentioned a few years ago for this issue ? I'm currently trying to authenticate with proxies as well

**Comment by SonecaJones** [comment]
`await Network.setRequestInterception({ patterns: [{ urlPattern: '*' }] });

      // Evento para lidar com solicitações interceptadas
      Network.requestIntercepted(({interceptionId, authChallenge}) => {
        // console.log(`Interceptando solicitação para URL: ${request.url}`);

        // Aqui, você pode decidir o que fazer com a solicitação, como permitir, bloquear ou modificar.
        // Você pode usar `Network.continueInterceptedRequest` para permitir a solicitação original.
        // Ou usar `Network.failInterceptedRequest` para bloquear a solicitação.
        // console.log(authChallenge);

        // Network.setRequestInterception({ patterns: [] });
        // Exemplo: Permitir todas as solicitações
        if(authChallenge) {
          console.log("Detectado autenticação proxy, autorizando...")
          Network.continueInterceptedRequest({ interceptionId, authChallengeResponse: {response: "ProvideCredentials", username: "user-lu1965477-region-br", password: "Gabiru"} });
        }
        else {
          Network.continueInterceptedRequest({ interceptionId });
        }
      });`

**Comment by SonecaJones** [comment]
await Network.setRequestInterception({ patterns: [{ urlPattern: '*' }] });

      Network.requestIntercepted(({interceptionId, authChallenge}) => {

        if(authChallenge) {
          console.log("Detectado autenticação proxy, autorizando...")
          Network.continueInterceptedRequest({ interceptionId, authChallengeResponse: {response: "ProvideCredentials", username: "user-lu1965477-region-br", password: "Gabiru"} });
        }
        else {
          Network.continueInterceptedRequest({ interceptionId });
        }
      });
