### ISSUE TITLE
Tracing is already started

### ISSUE THREAD

**Issue by brunotg** [cyrus-and/chrome-remote-interface#348]
| Component | Tracing  - 0.26.0
| Operating system	  	 	|  Mac OS High Sierra
| Node.js					|   8.9.4
| Chrome/Chromium/...		| 67.0.3396.99
| chrome-remote-interface	|   0.26.0

Is Chrome running in a container?  NO

I'm trying to collect complete timelines using the chrome remote interface and tracing. The code that 
 I have navigates to a page using webdriver IO and the chromedriver. Once the webdriver session has started, I can obtain the port for the chrome debugging protocol from the fileDevToolsActivePort and connect to establish a connection to chrome debugging protocol and start tracing.

The code that I'm using is capable of connecting, but once i try to start tracing i get an error that states: "Tracing is already started". (Even though is the first time i start tracing) Debugging further, this seems to be coming from chrome, the code fails in these lines: https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/chrome.js#L87-L89

I've tried stopping the tracing before starting it, but it fails because i have not started tracing =|

I am not starting tracing anywhere else, only than in the code shown below. I have another method on where I'll end Tracing and write the events to a file. I make CDP client part of the webdriver io client.

`const options = {
            port: webdriverIOClient.remoteDebuggingPort,
            webSocketDebuggerUrl: `ws://localhost:${webdriverIOClient.remoteDebuggingPort}${webdriverIOClient.webSocketDebuggerUrl}`
        }; 

        const getCDP = async () => { 
          if (webdriverIOClient.cdpClient) {
            return webdriverIOClient.cdpClient;
          } 
          let cdpClient = null; 

          await CDP(options, async (browser) => {
            try { 
              const events = []; 
              const { Page, Tracing } = browser;
              Tracing.dataCollected(({ value }) => {
                events.push(...value);
              });  
              cdpClient = browser; 
              cdpClient.events = events;
              await Tracing.start({
                 bufferUsageReportingInterval: 500,
                 categories:
                   "-*,devtools.timeline,v8.execute,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,toplevel,blink.console,blink.user_timing,latencyInfo,disabled-by-default-v8.cpu_profiler,disabled-by-default-v8.cpu_profiler.hires,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot",
                 options: "sampling-frequency=10000",
                 transferMode: "ReportEvents"
               }); 
               webdriverIOClient.cdpClient = browser;   
            } catch (error) {
              console.log(`we hit an error trying to get the CDP `, error)
            } 
          }); 
          return cdpClient; 
        }; `

**Comment by paulirish** [comment]
This is a bug in Chrome and it's tracing controller. We run into it in Lighthouse as well. 

Currently we don't have a fix for it, unfortunately. It requires some investigation.

**Comment by brunotg** [comment]
Thanks @paulirish is this a recent issue? Maybe i can go back to old versions of chrome.

Also, It would be awesome if there was a chromium issue around (i haven't found one).

**Comment by cyrus-and** [comment]
@brunotg the Lighthouse issue is dated back to 2016: GoogleChrome/lighthouse#1091
