### ISSUE TITLE
Incomplete timeline  information using Tracing domain

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#350]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.04
| Node.js					| 8.11.2
| Chrome/Chromium/...		| 68
| chrome-remote-interface	| 0.26

Is Chrome running in a container?  NO

Snippet of code to obtain timeline information
```
rawEvents = []
Tracing.dataCollected(function(data){
                var events = data.value;
                rawEvents = rawEvents.concat(events);
            });
Page.loadEventFired(function(){Tracing.end()});
Tracing.start(); Page.navigate({'url': 'http://github.com'});
```
When I dump the contents of rawEvents in a file and load inside chrome's performance tab using the graphical interface, it gives an empty timeline.

**Comment by cyrus-and** [comment]
That's weird... well the JSON can be successfully loaded [here][1], so maybe this is due to some change in DevTools, try asking this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

[1]: https://chromedevtools.github.io/timeline-viewer/

**Comment by goelayu** [comment]
I tried using [your](https://github.com/cyrus-and/chrome-remote-interface/wiki/Generate-timeline-data) exact code snippet and load it in the timeline viewer. It does generate the timeline, but it is clearly incomplete ( shows scripting time to be 0.2ms and no other category) as opposed to when I generate the timeline using the graphic interface. 

If that same code snippet works for you, could you kindly just provide me the version of node, chrome-remote-interface and chrome it works for?

**Comment by cyrus-and** [comment]
I didn't thoroughly check the output, I just noticed that *something* has been loaded.

Anyway, if you inspect DevTools during the tracing you can see that it's using something like this:

```json
{
  "id": 63,
  "method": "Tracing.start",
  "params": {
    "categories": "-*,devtools.timeline,v8.execute,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,toplevel,blink.console,blink.user_timing,latencyInfo,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot",
    "options": "sampling-frequency=10000",
    "bufferUsageReportingInterval": 500,
    "transferMode": "ReportEvents"
  }
}
```

Maybe you could try playing with the `categories` param (not sure if it defaults to "everything"). I'm shooting in the dark here...

**Comment by goelayu** [comment]
Well the categories option is deprecated apparently https://chromedevtools.github.io/devtools-protocol/tot/Tracing#method-start

Is the chrome-remote-interface package updated accordingly?

**Comment by cyrus-and** [comment]
> Well the categories option is deprecated apparently

Yet it's used by DevTools in Chrome 68.0.3440.75.

> Is the chrome-remote-interface package updated accordingly?

chrome-remote-interface is merely an interface, the protocol is fetched from Chrome so nothing is to be done when a feature becomes deprecated.

**Comment by paulirish** [comment]
in lighthouse we still use `categories`. looks like we'll all have to move to TraceConfig at some point. you might as well start now.

fwiw this is how we trace: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/gather/driver.js#L860-L864

handling the result as a stream is more complicated but it's how DevTools and Lighthouse and Puppeteer do it, so.. it's possible the non-stream approach has broken?

**Comment by goelayu** [comment]
Perfect, that seems to work. Thanks a lot! 

I don't know why the dev protocol says the 'categories' option is deprecated since not using that doesn't work with the latest version of Chrome. 
I would leave it up to you guys if the dev protocol should be updated, or the example provided as a part of this repo. 

I'll be closing this issue.
