### ISSUE TITLE
Protocol error Invalid InterceptionId on cancelled requests

### ISSUE THREAD

**Issue by m4p1e** [cyrus-and/chrome-remote-interface#351]
| Component | Version
|-|-
| Operating system	  	 	| kali 1.0
| Node.js					| v8.11.1
| Chrome/Chromium/...		| HeadlessChrome/66.0.3359.139
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container?  NO

when i am using the Network.requestIntercepted, i got an error

```
(node:6141) UnhandledPromiseRejectionWarning: Error: Invalid InterceptionId.
    at /root/Desktop/node_modules/chrome-remote-interface/lib/chrome.js:96:30
    at Chrome.handleMessage (/root/Desktop/node_modules/chrome-remote-interface/lib/chrome.js:297:13)
    at WebSocket.<anonymous> (/root/Desktop/node_modules/chrome-remote-interface/lib/chrome.js:274:27)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/root/Desktop/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/root/Desktop/node_modules/ws/lib/Receiver.js:389:14)
    at perMessageDeflate.decompress (/root/Desktop/node_modules/ws/lib/Receiver.js:349:40)
    at _decompress (/root/Desktop/node_modules/ws/lib/PerMessageDeflate.js:306:9)
    at _inflate.flush (/root/Desktop/node_modules/ws/lib/PerMessageDeflate.js:386:7)
(node:6141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

it trigger when i am clicking the html like that:

```
<a href="./1.html" />
<a href="./2.html" />
<a href="./3.html" />
<a href="./4.html" />
<a href="./5.html" />
```

if click so fast   like node.click();

it turns out the request which cause the error has "canceled" status.

What I suspect is when I called interceptedRequest.continue(), the underlying Chromium process already "lost" the interception, which cause it to return this error.

if i want ignore these error, what need i do?

**Comment by cyrus-and** [comment]
> Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Just properly handle the errors in promises. If you provide your code I can be more specific.

**Comment by m4p1e** [comment]
`Network.requestIntercepted(async (result = {}) =>{
if(result.isNavigationRequest === true  && global.i ==0){
 global.i++;

 Network.continueInterceptedRequest({interceptionId:result.interceptionId});

}else if(result.isNavigationRequest === true){

Network.continueInterceptedRequest({interceptionId:result.interceptionId,errorReason:'Aborted'});

}

}
...`

i make it cuz i just want block other NavigationRequest ,just let the first NavigationRequest pass .

**Comment by cyrus-and** [comment]
I strongly suggest you to read about Promises and their relative error handling, anyway you can do something like:

```js
let firstTime = true;

Network.requestIntercepted(async ({interceptionId, isNavigationRequest}) => {
    if (isNavigationRequest) {
        try {
            await Network.continueInterceptedRequest({
                interceptionId,
                errorReason: firstTime ? undefined : 'Aborted'
            });
        } catch (err) {
            console.error(`ERROR: ${err}`);
        } finally {
            firstTime = false;
        }
    }
});
```

**Comment by m4p1e** [comment]
i just did await `Network.continueInterceptedRequest({interceptionId:result.interceptionId,errorReason:'Aborted'}).catch((error) => {console.log(error)});`
i got it ~ thanks alot
