### ISSUE TITLE
correct way to block request

### ISSUE THREAD

**Issue by hbakhtiyor** [cyrus-and/chrome-remote-interface#353]
what's the correct way to block ads? i saw your [example](https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL), but also there are Network.setBlockedURLs,

what's your recommendation for blocking ads? using your example or Network.setBlockedURLs?

**Comment by cyrus-and** [comment]
I guess whatever works for you, you can think of `Network.setBlockedURLs` as a much simpler interface with respect to `Network.setRequestInterception`. The latter might be overkill if you just need to block a set of resources by URL while it might be OK if you need to support more advanced conditions based on the whole request instead of just the URL.

**Comment by hbakhtiyor** [comment]
i'll be use the datasets to block ads, which methods suitable for such big datasets?

```
    "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
    "https://mirror1.malwaredomains.com/files/justdomains",
    "http://sysctl.org/cameleon/hosts",
    "https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist",
    "https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt",
    "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
    "https://hosts-file.net/ad_servers.txt",
   "http://winhelp2002.mvps.org/hosts.txt"
```

**Comment by cyrus-and** [comment]
My guess is that `Network.setBlockedURLs` might be the best choice, but you should really try both and measure the performance to properly compare the two methods.

**Comment by gsouf** [comment]
@cyrus-and how does `Network.setBlockedURLs` with a big list of urls to block? Would that introduce any overhead in the network performances if I had  20, 100, 1000, merci paterns blocked?

**Comment by cyrus-and** [comment]
@gsouf honestly I have no idea, your best bet is to measure it. You might also want to ask this [here](https://groups.google.com/forum/#!forum/chrome-debugging-protocol).

**Comment by gsouf** [comment]
@cyrus-and if you are interested here we got an answer https://groups.google.com/d/msg/chrome-debugging-protocol/SUZ7LHZlh1E/l0DZtX_PDAAJ

**Comment by cyrus-and** [comment]
@gsouf got it thank you!
