### ISSUE TITLE
Connection refused if I use IP address as host option parameter instead of localhost 

### ISSUE THREAD

**Issue by benzaremean** [cyrus-and/chrome-remote-interface#358]
| Component | Version
|-|-
| Operating system	  	 	| OS X High sierra
| Node.js					| v8.11.3
| Chrome/Chromium/...		| Google Chrome 69.0.3497.92
| chrome-remote-interface	| 0.26.1

Is Chrome running in a container? NO

Hi 
I get Error: connect `ECONNREFUSED IP_ADRESS:PORT` error when I use ip address as as host option parameter instead of localhost. From the docs I was hoping I could change the host to an IP and connect to a remote chrome instance running in debug mode.

The below works ok

```javascript
await CDP({
   port: 9222,
   host: localhost
});
```

But this doesn't
```javascript
await CDP({
   port: 9222,
   host: IP_ADDRESS
});
```

Could you help advise if my ambition to connect to remote chrome instance is possible?

**Comment by cyrus-and** [comment]
Of course it is possible. Are you sure that a running Chrome instance is running on that port? Try simply visiting `IP_ADRESS:PORT` in any browser or use `curl`.

**Comment by benzaremean** [comment]
seems to be some sort of network issue 

```
Your Internet access is blocked
Firewall or antivirus software may have blocked the connection.
Try:

Checking the connection
Checking firewall and antivirus configurations
ERR_NETWORK_ACCESS_DENIED
```

**Comment by cyrus-and** [comment]
Well, so you have to figure out what happens, this is not related to chrome-remote-interface.

What if you use `curl http://IP_ADRESS:PORT/json`?

Also why do you want to reach your Chrome instance by IP (which I assume is your NIC's IP) if it listens on localhost too? What do you really want to achieve?

**Comment by benzaremean** [comment]
I am using the library to listen to network on response receive events in my automated selenium tests. The tests can either run locally or on a remote node using selenium grid

**Comment by benzaremean** [comment]
Possibly I can fix this by starting chrome with one of the thousand available flags. By the way I don't have any firewalls set up locally

**Comment by cyrus-and** [comment]
Note that Chrome will listen to `localhost` by default, you need to use the `--remote-debugging-address=IP_ADDRESS` to bind it on a specific interface (`0.0.0.0` means any interface).

**Comment by benzaremean** [comment]
thanks will try that

**Comment by benzaremean** [comment]
tried starting chrome with with --remote-debugging-address=IP_ADDRESS and it still doesnt work

**Comment by benzaremean** [comment]
when I open localhost:PORT on browser I get the following

```
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:60245/devtools/page/32606ECFF6938A19DDA6E162B3D5AF63",
   "id": "32606ECFF6938A19DDA6E162B3D5AF63",
   "title": "Chrome Automation Extension",
   "type": "background_page",
   "url": "chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:60245/devtools/page/32606ECFF6938A19DDA6E162B3D5AF63"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:60245/devtools/page/30D608696961B17FCB0D6476DCD8E7E5",
   "id": "30D608696961B17FCB0D6476DCD8E7E5",
   "title": "DevToolsActivePort",
   "type": "page",
   "url": "file:///var/folders/py/s1f943t15n38cz764270h33rvv45s4/T/.org.chromium.Chromium.tc9BI9/DevToolsActivePort",
   "webSocketDebuggerUrl": "ws://localhost:60245/devtools/page/30D608696961B17FCB0D6476DCD8E7E5"
} ]
```

**Comment by benzaremean** [comment]
the devtoolsFrontendUrl has ws parameter beginning with localhost

**Comment by cyrus-and** [comment]
You should use:

    --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0

`--remote-debugging-port=0` means: use a random port. You can check with `lsof`, for example:

```conosole
$ lsof -nP -iTCP:9222
COMMAND     PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Google    15483 andrea   30u  IPv4 0x58b460cfc0ec8963      0t0  TCP *:9222 (LISTEN)
```

**Comment by benzaremean** [comment]
I understand that would work just trying to figure out how to connect to a remote chrome instance so testing locally with my IP
