### ISSUE TITLE
Debugger.paused  hangs (unable to pause the debugger from node.js)

### ISSUE THREAD

**Issue by oszyvik** [cyrus-and/chrome-remote-interface#359]
Hi,

We are facing an issue for a while.

There is a node.js server running, and we have a client connected to it. The client has a simple TextBox, where you can write javascript code. Once the desired code is written, you can send it to the node.js server.

In Node.js the received javascript code will be written in a .js file, and after that it will be started in a childProcess (execFile function).

We want to use chrome remote interface to be able to pause the execution of the js file, edit it and after resume the execution. This is important to do it from code (not with chrome://inspect) because when pausing the execution with the debugger we also have to pause some other things.

Our problem is that await Debugger.paused() is hangs, the debugger never gets paused, therefore calling await Debugger.resume() we are getting the error: Can only perform operation while paused.

Here is a code snippet about how we are connecting the debugger:
```js
const CDP = require('chrome-remote-interface');

exports.RemoteDebuggerInterface = class {
    constructor(port) {
        this.port = port;
        this.connected = false;
    }

    async connect(isScriptPausedByDefault = true) {
        let debuggerTargets = await this.getDebuggerTargets();

        if (debuggerTargets && debuggerTargets.length > 0) {

            let debuggerTarget = debuggerTargets[0];

            this.debuggerClient = await new CDP({
                port: this.port,
                target: debuggerTarget
            });

            if (this.debuggerClient) {
                console.log('Connected to remote debugger on: ' + debuggerTarget['webSocketDebuggerUrl']);
                console.log('DevTools can be reached on: ' + debuggerTarget['devtoolsFrontendUrl']);
            }
            this.connected = true;

            this.subscribeToClientEvent(this.debuggerClient, 'Runtime.executionContextDestroyed').then((message) => {
                console.log('Execution context destroyed :' + message);
            });

            if (isScriptPausedByDefault) {
                await this.debuggerClient.Runtime.runIfWaitingForDebugger();
            }
            this.subscribeToClientEvent(this.debuggerClient, 'Debugger.scriptParsed').then((message) => {
                console.log(message);
            });

            let id = await this.debuggerClient.Debugger.enable();
            console.log('Debugger enabled with unique id: ' + id);

          //to not copy a lot of code, we tried here to pause the debugger
          await this.debuggerClient.Debugger.paused();
          //by calling resume, we are getting the error: Can only perform operation while paused.
          await this.debuggerClient.Debugger.resume();


            return this.debuggerClient;
        }
        else {
            throw Error('error at connecting to the remote debugger');
        }
    }
```

Also, we are not able to open devtools by the given link (devtoolsFrontendUrl). The only way to open is using NIM extension for Chrome. BUT if the devtools is opened in chrome, then we get an error in node.js:
TypeError: Parameter "url" must be a string, not undefined
message:"Parameter "url" must be a string, not undefined"
stack:"TypeError: Parameter "url" must be a string, not undefined
at Url.parse (url.js:103:11)
at urlParse (url.js:97:13)
at Chrome._start (...\node_modules\chrome-remote-interface\lib\chrome.js:130:31)

I know I have a lot of questions, but I would like to start a discussion about this topic, because this is very important for us.

| Component | Version
|-|-
| Operating system	  	 	| Win8 64 bit
| Node.js					| v8.11.3
| Chrome/Chromium/...		| 69.0.3497.100
| chrome-remote-interface	| 0.26.1

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Would something like this help?

```js
const CDP = require('chrome-remote-interface');
const child_process = require('child_process');

const child = child_process.spawn('node', ['--inspect-brk=9222', 'script.js']);
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);

setTimeout(() => {
    CDP(async(client) => {
        const {Runtime} = client;
        try {

            console.log('the execution is paused here, resuming...');

            await Runtime.runIfWaitingForDebugger();
        } catch (err) {
            console.error(err);
        } finally {
            client.close();
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 1000); // TODO better poll for success
```

**Comment by cyrus-and** [comment]
To elaborate on that, please note that [`Debugger.paused`][1] is an event, conversely to [`Debugger.pause`][2] which is a method. So according to your code if `isScriptPausedByDefault` is true (`default`), [`Runtime.runIfWaitingForDebugger`][3] is called and the [`Debugger.paused`][1] event never fired, thus the hanging.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-paused
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Debugger#method-pause
[3]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-runIfWaitingForDebugger

> Also, we are not able to open devtools by the given link (devtoolsFrontendUrl). The only way to open is using NIM extension for Chrome. BUT if the devtools is opened in chrome, then we get an error in node.js

I guess that's a limitation of Chrome, it recently became possible to debug the same target simultaneously using more than one CDP/DevTools instance, but if I recall correctly not all the methods of all the domains allow that, and yours might just be one example, that is, if certain methods are used, then the `webSocketDebuggerUrl` field disappears from the target object so you get that error. But please take the above with a grain of salt since I've not tested it.

**Comment by oszyvik** [comment]
Thank you for the answer!

Yes, sorry for the mistake!

So, let's assume that the code is the same like in my very first comment, with one difference.

```js
          //to not copy a lot of code, we tried here to pause the debugger
          await this.debuggerClient.Debugger.pause();
          await this.debuggerClient.Debugger.paused();
          //by calling resume, we are getting the error: Can only perform operation while paused.
          await this.debuggerClient.Debugger.resume();
```
In this case we call the pause method, and after that we should wait for pausing with the paused event. Right?
But paused will be never fired as currently we can see.

We are calling the pause and the resume method from these two methods:

Resume:
```js
async resumeApplication() {
        this.checkIfConnectedToClient();
       //to check that the event is really fired, and resumed is always occurs
        this.debuggerClient.on('Debugger.resumed', (message) => {
            if (message.method === 'Debugger.resumed') {
                console.log(message.params);
            }
        });

        await this.debuggerClient.Debugger.resume();
        console.log('Executable file was resumed');
    }
```

Pause:
```js
    async pauseApplication() {
        this.checkIfConnectedToClient();
         //to check that the event is really fired, and paused is never occurs
        this.debuggerClient.on('Debugger.paused', (message) => {
            if (message.method === 'Debugger.paused') {
                console.log(message.params);
            }
        });

        await this.debuggerClient.Debugger.pause();
        console.log('Application was paused');
    }
```
It is strange, that at the very first run the resume works, but after a pause when we attempt to call the resume, we are getting the error message mentioned before.

At the first time resume works probably because of the -brk swtich? But after a pause manually, paused event never occurs :/

Sorry if I'm not too clear, I'm really new to this.

But anyway, a big thank you for helping us!

**Comment by cyrus-and** [comment]
> In this case we call the pause method, and after that we should wait for pausing with the paused event. Right?

The full *chain* would be something like this:

```js
// start ALWAYS with --inspect-brk

// XXX the order matters here!
await Runtime.runIfWaitingForDebugger();
await Debugger.enable();

console.log('resumed first time');

while (true) {
    await seconds(1); // XXX to simulate the interaction
    await Debugger.pause();   console.log('pausing...');
    await Debugger.paused();  console.log('paused');
    await Debugger.resume();  console.log('resuming...');
    await Debugger.resumed(); console.log('resumed');
}
```

Unfortunately the above never works basically. The reason, I guess, is that there's a race between the method and the event, e.g., the `Debugger.paused` event arrives before the actual `await`, so the correct version would be (full source code):

```js
const CDP = require('chrome-remote-interface');

const child_process = require('child_process');

const child = child_process.spawn('node', ['--inspect-brk=9222', 'script.js']);
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);

async function seconds(n) {
    return new Promise((fulfill) => setTimeout(fulfill, n * 1000));
}

setTimeout(() => {
    CDP(async(client) => {
        const {Debugger, Runtime} = client;
        try {

            Debugger.paused(async () => {
                console.log('paused');
                await Debugger.resume();
                console.log('resuming...');
            });

            Debugger.resumed(async () => {
                console.log('resumed');
                await seconds(1); // XXX to simulate the interaction
                await Debugger.pause();
                console.log('pausing...');
            });

            // XXX the order matters here!
            await Runtime.runIfWaitingForDebugger();
            await Debugger.enable();

        } catch (err) {
            console.error(err);
        }
    }).on('error', (err) => {
        console.error(err);
    });
}, 1000); // TODO better poll for success
```

So in short you cannot rely on `await` for these kind of events so you must make sure to enforce a consistent paused/resumed state using callbacks.

**Comment by cyrus-and** [comment]
Does the above make sense?

**Comment by cyrus-and** [comment]
Ok, then I'm closing this for now, but please don't hesitate to comment further if you need.
