### ISSUE TITLE
excute "GetDocumentCommand" returns null data.

### ISSUE THREAD

**Issue by cqsir** [cyrus-and/chrome-remote-interface#36]
I want run "GetDocumentCommand",but the result is null.
-------------------------------------
        //my test method
-------------------------------------
        private static void Test()
        {
            try
            {
                string url = "ws://localhost:9222/devtools/page/66CB09FA-3637-4C41-A1D8-DC4A3EDE428D";//url is ok,point to a chrome process with debug port 9222.
                ChromeSessionFactory sf = new ChromeSessionFactory();
                IChromeSession chromeSession = sf.Create(url);

                var x = chromeSession.SendAsync<GetDocumentCommand>().Result;

                var y = x as CommandResponse<GetDocumentCommandResponse>;
//here ,y.Resut=null,y.Method=null。but y.Id has value.

                WriteMessage(y.Result, "GetDocumentCommand=");
            }
            catch (Exception exp) { Console.WriteLine("exception="+exp.Message); }
            Console.ReadKey();
        }
-------------------------------------

I fix this ， But I don't know why this happend, Is other where influence by this error?

-------------------------------------
my fix
-------------------------------------
1.open ChromeProcessFactory.cs
2. add some code into "Create" method as follow：
        public ICommandResponse Create(string responseText)
        {
            var jObject = JObject.Parse(responseText);
            if (null != jObject["error"])
            {
                return jObject.ToObject<ErrorResponse>();
            }
            var methodString = GetMethod(jObject);
            if (null == methodString)
            {
                return null;
            }
            var typeInferredFromMethod = _methodTypeMap.GetCommandResponse(methodString);
            if (null == typeInferredFromMethod)
            {
                return null;
            }
            var genericEventType = typeof(CommandResponse<>);
            var commandResponseType = genericEventType.MakeGenericType(typeInferredFromMethod);
            var result = jObject.ToObject(commandResponseType);//here,don't know why:  result.Result=null,result.Method=null

            //new code begin
            var cqs_r = jObject.GetValue("result");
            var cqs_o = cqs_r.ToObject(typeInferredFromMethod);
            commandResponseType.GetProperty("Result").SetValue(result, cqs_o);
            commandResponseType.GetProperty("Method").SetValue(result, methodString);
            //new code end

            return result as ICommandResponse;
        }

**Comment by cyrus-and** [comment]
I'm confused, you maybe wanted to open this issue to [ChromeDevTools][1]? This project is a JavaScript interface to Chrome DevTools.

[1]: https://github.com/MasterDevs/ChromeDevTools

**Comment by cqsir** [comment]
sorry!!!

**Comment by cyrus-and** [comment]
No problem! :)
