### ISSUE TITLE
Why requestWillBeSent and responseReceived has no "timing" datas, or why they have -1 data if there are "timing" datas?

### ISSUE THREAD

**Issue by n3pixowe** [cyrus-and/chrome-remote-interface#361]
| Component | Version
|-|-
| Operating system	  	 	| Windows 7 Ultimate, 64bit
| Node.js					| Node.js 8.9
| Chrome/Chromium/...		| Chrome 69
| chrome-remote-interface	| 0.26.1

Is Chrome running in a container? YES

Hello, Im getting all requests of a website with "requestWillBeSent" method, all the request are come in but timing datas got "-1" value. Why this is happening? How can i calculate or get all timing datas successfully?

**Comment by cyrus-and** [comment]
I don't see any *timing data* in [`Network.requestWillBeSent`][1].

The [`ResourceTiming`][2] object (`response.timings` in [`Network.responseReceived`][3]) have its values set to -1 when they are not available/do not apply, e.g., `proxyStart` will be -1 if no proxy is used.

Also this [FAQ][4] concerns Chrome running in a container.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestWillBeSent
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ResourceTiming
[3]: https://chromedevtools.github.io/devtools-protocol/tot/Network#event-responseReceived
[4]: https://github.com/cyrus-and/chrome-remote-interface#why-my-program-stalls-or-behave-unexpectedly-if-i-run-chrome-in-a-docker-container

**Comment by n3pixowe** [comment]
> I don't see any _timing data_ in [`Network.requestWillBeSent`](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestWillBeSent).
> 
> The [`ResourceTiming`](https://chromedevtools.github.io/devtools-protocol/tot/Network#type-ResourceTiming) object (`response.timings` in [`Network.responseReceived`](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-responseReceived)) have its values set to -1 when they are not available/do not apply, e.g., `proxyStart` will be -1 if no proxy is used.
> 
> Also this [FAQ](https://github.com/cyrus-and/chrome-remote-interface#why-my-program-stalls-or-behave-unexpectedly-if-i-run-chrome-in-a-docker-container) concerns Chrome running in a container.

OK, thanks for your response. It helped too much. I have a new question about this timing issue;

I want to do a waterfall chart with reliable datas like, Google DevTools Network Waterfall but I don't get all timing datas that Google gets. Why is this happening? How can I get that datas like Google's Waterfall for the same target URL request/response?

![image](https://user-images.githubusercontent.com/37420200/46748105-852bf000-ccbb-11e8-8c96-cb51e24f8c4c.png)

**Comment by cyrus-and** [comment]
The timing computation is not a straightforward process, see my attempt [here][1] in [chrome-har-capturer][2].

[1]: https://github.com/cyrus-and/chrome-har-capturer/blob/dcb0435ed9c7a40ae3f49913f7ecf6ad4fbecee8/lib/har.js#L178-L208
[2]: https://github.com/cyrus-and/chrome-har-capturer

**Comment by chen1-CN** [comment]
hello ,I'm a novice，I want to get all data of network tab in chrome dev,header,response,etc..,Use the Chrome DevTools Protocol method to obtain the data,not inchrome

**Comment by cyrus-and** [comment]
@chen1-CN take a look at [chrome-har-capturer](https://github.com/cyrus-and/chrome-har-capturer).
