### ISSUE TITLE
Request Intercept and Self Signed Certificates

### ISSUE THREAD

**Issue by kamilmahmood** [cyrus-and/chrome-remote-interface#362]
I am trying to intercept every request, then modifying its response's body and sending to browser. It all works fine until SSL certificate of website is valid. If some website has self signed SSL certificate then request always shown as **pending** in network section of developer console of Chromium and my interception function is never called. Even I have added `setOverrideCertificateErrors` to `true` and added listener for `certificateError`. How to solve this issue?
 
```js
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');
const atob = require('atob');
const btoa = require('btoa');

async function main() {
    const chrome = await chromeLauncher.launch({
        chromeFlags:
            [
                '--window-size=1200,800',
                '--user-data-dir=/tmp/chrome-testing',
                '--auto-open-devtools-for-tabs'
            ]});

    const protocol = await CDP({ port: chrome.port });
    const { Runtime, Network, Security } = protocol;
    const activated = await Promise.all([Runtime.enable(), Network.enable(), Security.enable()]);

    Security.certificateError(({eventId}) => {
        console.log("Ignoring cert error for " + eventId);
        Security.handleCertificateError({
            eventId,
            action: 'continue'
        });
    });

    await Security.setOverrideCertificateErrors({override: true});

    console.log("Network enabled: " + activated);

    await Network.setRequestInterception({patterns: [{
        urlPattern: '*',
            interceptionStage: 'HeadersReceived' }]});

    Network.requestIntercepted(async ({interceptionId, request}) => {
        console.log(`Intercepted ${request.url} {interception id: ${interceptionId}}`);
        const response = await Network.getResponseBodyForInterception({ interceptionId });
        console.log("Actual Body: " + response.body);
        const bodyData = response.base64Encoded ? atob(response.body) : response.body;
        // Do some changes to original data then forward it
        console.log("Decoded Body: " + bodyData);
        Network.continueInterceptedRequest({interceptionId});
    });
}

promise = main();
promise.then(value => console.log("Done Setting Up"));
```

**Comment by cyrus-and** [comment]
I see, that's probably a bug in Chrome, here's how to reproduce it more easily:

```js
const CDP = require('chrome-remote-interface');

async function main() {
    const client = await CDP();
    const {Page, Network, Security} = client;

    Security.certificateError(({eventId}) => {
        console.log(`Security.certificateError: ${eventId}`);
        Security.handleCertificateError({eventId, action: 'continue'});
    });

    Network.requestIntercepted(({interceptionId}) => {
        console.log(`Network.requestIntercepted: ${interceptionId}`);
        Network.continueInterceptedRequest({interceptionId});
    });

    await Page.enable();
    await Network.enable();
    await Security.enable();
    await Security.setOverrideCertificateErrors({override: true});
    await Network.setRequestInterception({
        patterns: [{
            urlPattern: '*',
            interceptionStage: 'HeadersReceived'
        }]
    });

    await Page.navigate({url: 'https://self-signed.badssl.com/'});
    await Page.loadEventFired();
    console.log('Done');
    await client.close();
}

main();
```

I suggest to file an [upstream issue](https://crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

**Comment by kamilmahmood** [comment]
There is already a question about this in _chrome-debugging-protocol_ group but with no response. Is there any workaround or "hacky" solution for this problem? Thanks

Link to already existing question
[https://groups.google.com/forum/#!searchin/chrome-debugging-protocol/certificate|sort:date/chrome-debugging-protocol/MnqC0ipuJ4U/hkoNAs-hCQAJ](https://groups.google.com/forum/#!searchin/chrome-debugging-protocol/certificate|sort:date/chrome-debugging-protocol/MnqC0ipuJ4U/hkoNAs-hCQAJ)

**Comment by cyrus-and** [comment]
> There is already a question about this in _chrome-debugging-protocol_ group but with no response.

I see, you should file an issue then. Post the link here if you do.

> Is there any workaround or "hacky" solution for this problem?

If you don't need headless mode you can start Chrome with the `--ignore-certificate-errors` flag and remove from the program `Security.setOverrideCertificateErrors` and related code.

**Comment by kamilmahmood** [comment]
`--ignore-certificate-errors` seems to do the trick. It is working now. Thanks for helping.

**Comment by kamilmahmood** [comment]
I have opened a issue on Chromium Bug tracker. Link to the issue
[https://bugs.chromium.org/p/chromium/issues/detail?id=894847&can=2&q=certificate&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified](https://bugs.chromium.org/p/chromium/issues/detail?id=894847&can=2&q=certificate&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)
