### ISSUE TITLE
webpack4 electron-renderer window.criRequest is not a function

### ISSUE THREAD

**Issue by fishear** [cyrus-and/chrome-remote-interface#365]
I use chrome-remote-interface in electron render process, like this:
```
const CDP = require('chrome-remote-interface');
CDP.List(options, callback)
```
when bundled with webpack3 , everything is ok. But when I upgraded webpack to wepack 4,  I got an error:
```
window.criRequest is not a function
```
I know it's for browser usage, but I want to run in node. Is it a problem with webpack or Did I miss something?

| webpack | 4.21.0
| webpack-target | electron-renderer
| Operating system	  	 	| Mac
| Node.js					| v10.7.0
| chrome-remote-interface	| 0.25.7
| electron                                  | 2.0.10"

**Comment by cyrus-and** [comment]
I'm not familiar with Electron, can you provide a minimal application so I can try?

**Comment by fishear** [comment]
Hi, @cyrus-and 
I finally found a workaround about this issue, just use it in this way:
```
const CDP = require('chrome-remote-interface/index');
```
Actually, I don't understand why the package.json in the chrome-remote-interface has no 'main' filed but 
'browser' field, and it's pointed to the chrome-remote-interface.js which is bundled by webpack.
and in the webpack.config.js, it has the following code:
```
...
function criWrapper(_, options, callback) {
    window.criRequest(options, callback);
}
...
externals: [
        {
            './external-request.js': `var (${criWrapper})`
        }
    ],
```
I think maybe it's why I ran into the error:
```
window.criRequest is not a function
```
And I read the npm documentation, it explains:
```
browser:
If your module is meant to be used client-side the browser field should be used instead of the main field. This is helpful to hint users that it might rely on primitives that aren't available in Node.js modules. (e.g. window)
```
Is this package meant to be used in the browser? or did I use it in a wrong way? Thanks

**Comment by cyrus-and** [comment]
> Is this package meant to be used in the browser?

It is [also][1] meant to be used in the browser.

[1]: https://github.com/cyrus-and/chrome-remote-interface#browser-usage

> Actually, I don't understand why the package.json in the chrome-remote-interface has no 'main' filed but 'browser' field, and it's pointed to the chrome-remote-interface.js which is bundled by webpack.
and in the webpack.config.js, it has the following code:

And there we need a wrapper (`criRequest`) that performs the actual HTTP communication with Chrome, users should provide their own version. I cannot just perform the request from the library as it would violate the SOP as responses from Chrome doesn't have the `Access-Control-Allow-Origin` header.

> I'm not familiar with Electron, can you provide a minimal application so I can try?

I still need this. It's entirely possible that for Electron you don't need to rely on the generated webpack version...

**Comment by fishear** [comment]
> I still need this. It's entirely possible that for Electron you don't need to rely on the generated webpack version...
Hi Andrea, I wrote a simple demo( [Here](https://github.com/fishear/my-chrome-remote-interface-demo)) which quite similar to my project(especially the file structure...).

Thank you very much~~

**Comment by cyrus-and** [comment]
So I guess you just need to require `const CDP = require('chrome-remote-interface');` but provide your implementation of `criRequest` as a global variable, i.e., `window.criRequest`.

**Comment by fishear** [comment]
> So I guess you just need to require `const CDP = require('chrome-remote-interface');` but provide your implementation of `criRequest` as a global variable, i.e., `window.criRequest`.

Thanks Andrea, I know this is for browser usage, but [Electron Doc](https://github.com/electron/electron/blob/master/docs/glossary.md#renderer-process) says:

```
Electron users, however, have the power to use Node.js APIs in web pages allowing lower level operating system interactions.
```
I just want to use it in nodejs usage, and that's exactly how I used it when bundling with webpack3.

I don't know whether it is webpack4 that chose the brower usage for me...

Anyway, I will try to provide `window.criRequest` first, thank you~

**Comment by fishear** [comment]
I finally found this:
[remote.require](https://electronjs.org/docs/api/remote#remoterequiremodule)

I can use it in this way and no need to provide `window.criRequest`:
```
const CDP = require('electron').remote.require('chrome-remote-interface');
```

Sorry to disturb you so much and thank you all the same.

**Comment by fishear** [comment]
I found another solution from [this issue](https://github.com/webpack/webpack/issues/6811) and [this pr](https://github.com/webpack/webpack/pull/6814), and doc: [webpack resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields),

if I set the mailFields like this, it's ok too:
```
resolve: {
  mainFields: ['main', 'browser', 'module']
},
```
Maybe I asked in a wrong place...

**Comment by cyrus-and** [comment]
> Electron users, however, have the power to use Node.js APIs in web pages allowing lower level operating system interactions.

This makes sense and changes everything, you don't need to specify `criRequest` then.

The default value for `main` is actually `index.js` for this reason I omitted it in the `package.json`, I believe that webpack should do the same when you specify `main`.

But if it helps the development of Electron apps I can simply add it to the `package.json`, what do you think? I'm not aware of the Electron best practices.

**Comment by fishear** [comment]
> The default value for `main` is actually `index.js` for this reason I omitted it in the `package.json`, I believe that webpack should do the same when you specify `main`.

Yes, you are right when I only specify `mainFields: ['main']`, webpack resolved as `index.js`.

> But if it helps the development of Electron apps I can simply add it to the `package.json`, what do you think? I'm not aware of the Electron best practices.

I am a newbie in electron so I am not sure about the Electron best practices. But I would appreciate it a lot if you add it. Thanks~~

**Comment by cyrus-and** [comment]
Done, let me know if you figure out why `main` is not recognised by default.
