### ISSUE TITLE
Runtime.evaluate callback after Runtime.disbale had call backed

### ISSUE THREAD

**Issue by newbeenew** [cyrus-and/chrome-remote-interface#371]
I had do Runtime.disbale() in Promise.all and then do CDP.close(), but after that I still got a callback which I had set in the Runtime.evaluate before.

| Component | Version
|-|-
| Operating system	  	 	| ubuntu
| Node.js					| 8.11.3
| Chrome/Chromium/...		| v67
| chrome-remote-interface	| 0.25.6

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
I'm not sure I'm understanding this issue, please show me some **standalone** code.

**Comment by newbeenew** [comment]
I may do something wrong,sorry.
