### ISSUE TITLE
WebSocket logger

### ISSUE THREAD

**Issue by aleksdbr** [cyrus-and/chrome-remote-interface#373]
Is it possible to log all websocket frames? 

Somthing like this https://github.com/cyrus-and/chrome-remote-interface/wiki/Log-network-requests but for websocket.

**Comment by cyrus-and** [comment]
There are several WebSocket-related functions in the [`Network`][1] domain:

```js
Network.webSocketFrameSent((params) => {
    console.log('SENT', params);
});

Network.webSocketFrameReceived((params) => {
    console.log('RECEIVED', params);
});
```
