### ISSUE TITLE
How to get dimensions of Image File Requests/Responses with Network?

### ISSUE THREAD

**Issue by n3pixowe** [cyrus-and/chrome-remote-interface#377]
Hello!

I want to take dimensions (width and height) of Image File Requests/Responses that come from Network.requestWillBeSent and Network.responseReceived. I can't reach any solitions by the default Request/Reponse informations. How can I make this?

Thanks!!

**Comment by cyrus-and** [comment]
I guess you'll have to inject some JavaScript to try to fetch that once that the image is part of the DOM.
