### ISSUE TITLE
Closing and opening a new connection

### ISSUE THREAD

**Issue by GarthDB** [cyrus-and/chrome-remote-interface#38]
I see you have a test for this very case, but I am still getting some issues where I am closing a connection and opening a new one in my test suite, and it has issues sometimes.

I'm not sure what the root cause is, the only thing I can think is it isn't completely finished closing before starting to open a new connection. Since it also removes all listeners when calling `chrome.close()`, I can't add my own to the websocket.

I'm bypassing that method and just using this for now:

```js
closeConnection(){
  return new Promise((resolve, reject) => {
    this.chrome.ws.onclose = function(event){
      event.target.removeAllListeners();
      resolve(true);
    }
    this.chrome.ws.close();
  });
}
```

Would you be interested in a pull request adding a promise/callback to `chrome.close()`?

**Comment by cyrus-and** [comment]
Yes it's quite possible that this is the cause. But I don't understand, are you experiencing this issue when you run `make test` in this repo? If that's the case can you post some details of your setup? I'd like to try to reproduce it.

Anyway, feel free to send a PR, just try to match style and naming conventions.

Thank you!

**Comment by GarthDB** [comment]
Thanks for adding this - any idea when you'll be releasing it?

**Comment by cyrus-and** [comment]
Done: [v0.12.3](https://github.com/cyrus-and/chrome-remote-interface/releases/tag/v0.12.3). I was waiting for some feedback from you.

**Comment by GarthDB** [comment]
Oh it is excellent, thank you.
