### ISSUE TITLE
screenshot looks different from actual page

### ISSUE THREAD

**Issue by typedefstructer** [cyrus-and/chrome-remote-interface#380]
| Operating system	  	 	| Ubuntu 16.04
| Node.js					| 9.8.0
| Chrome/Chromium/...		| Google Chrome 71.0.3578.80 
| chrome-remote-interface	| 0.27.0

Is Chrome running in a container?  NO
I am trying to take screenshot of this page
https://bannerknight.animaapp.io/preview/VES4yRZ/pnbanner2
not the whole page just one particular section of it.

But the screenshot looks different compared the the real thing, not sure how to fix this.
I've attached the screenshot and the code below.
![output](https://user-images.githubusercontent.com/16563797/49647283-faac0680-fa47-11e8-9c36-1ecb25ceff1e.png)

```js
const CDP = require('chrome-remote-interface');
const fs = require('fs');
const format = 'png';
const url = 'https://bannerknight.animaapp.io/preview/VES4yRZ/pnbanner2';

CDP(async function(client) {
  const {DOM, Emulation, Network, Page, Runtime} = client;
  await Page.enable();
  await DOM.enable();
  await Network.enable();

  const deviceMetrics = {
    width: 1920,
    height: 1080,
    deviceScaleFactor: 1,
    mobile: false,
    fitWindow: false
  };


  await Emulation.setDeviceMetricsOverride(deviceMetrics);
  await Page.navigate({url});
  await Page.loadEventFired();
  await Network.loadingFinished();
  const { data } = await Page.captureScreenshot({ format,
                                                  fromSurface: true,
                                                  quality: 1,
                                                  clip: {
                                                    width: 1024,
                                                    height: 512,
                                                    x: 448,
                                                    y: 0,
                                                    scale: 1
                                                  }
                                                });
  console.log('start');
  fs.writeFileSync('output.png', Buffer.from(data, 'base64'));
  client.close();

}).on('error', err => {
  console.error('Cannot connect to browser:', err);
});

```

**Comment by cyrus-and** [comment]
I don't see any differences, meaning that the result is consistent between screenshot and actual page rendering. What I do see is that on a retina display (MacBook) the "Starting at ..." line does not overlap the team names while on a regular monitor (Linux) it does and l get something similar to your screenshot.

**Comment by typedefstructer** [comment]
I am going to upload the screen of the website and point out the differences.
##### Screenshot taken manually by using the screenshot tool that comes with ubuntu
![website](https://user-images.githubusercontent.com/16563797/49648604-67c19b00-fa4c-11e8-8665-e1eb38130621.png)
##### Screenshot taken with the script
![output](https://user-images.githubusercontent.com/16563797/49648693-d6065d80-fa4c-11e8-9710-38ac2436b58f.png)

1. Kerala Knights and Northern Warriors are not broken into two lines in the website
2. The rupee symbol in the website is in a different font compared to the screenshot taken with chrome remote interface

**Comment by cyrus-and** [comment]
> 1. Kerala Knights and Northern Warriors are not broken into two lines in the website

In my setup this is consistent as I said before, but the page renders differently on retina.

> 2. The rupee symbol in the website is in a different font compared to the screenshot taken with chrome remote interface

Yes, this is indeed different.

This could either be a Chrome bug or the result of wrong options, in any case I suggest to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

**Comment by typedefstructer** [comment]
I am now running the headless browser with this command
```google-chrome --headless --hide-scrollbars --remote-debugging-port=9222 --force-device-scale-factor=4```

And Modified the script to reflect this.

```js
const CDP = require('chrome-remote-interface');
const fs = require('fs');
const format = 'png';
const url = 'https://bannerknight.animaapp.io/preview/VES4yRZ/pnbanner2';

const scalef = 4;

CDP(async function(client) {
  const {DOM, Emulation, Network, Page, Runtime} = client;
  await Page.enable();
  await DOM.enable();
  await Network.enable();

  const deviceMetrics = {
    width: 1920,
    height: 1080,
    deviceScaleFactor: 1,
    mobile: false,
    fitWindow: false
  };


  await Emulation.setDeviceMetricsOverride(deviceMetrics);
  await Page.navigate({url});
  await Page.loadEventFired();
  await Network.loadingFinished();
  console.log('starting timeout');
  
  const { data } = await Page.captureScreenshot({ format,
                                                  fromSurface: true,
                                                  quality: 1,
                                                  clip: {
                                                    width: 1024,
                                                    height: 512,
                                                    x: 448*scalef,
                                                    y: 0,
                                                    scale: 1
                                                  }
                                                });
  console.log('start');
  fs.writeFileSync('output.png', Buffer.from(data, 'base64'));
  client.close();

}).on('error', err => {
  console.error('Cannot connect to browser:', err);
});
```

![output](https://user-images.githubusercontent.com/16563797/49650484-511e4280-fa52-11e8-924e-b4207bec5c2b.png).

Now atleast the text is not breaking, but the Rupee is in different font.

**Comment by typedefstructer** [comment]
Also, I tried changing this deviceScaleFactor: 1 to deviceScaleFactor: 4. But that didnt fix anything.
I had to use ```--force-device-scale-factor=4``` is that a bug?

**Comment by cyrus-and** [comment]
> Created a question in the google group, here's the link

Thanks! Well I'm closing this now as it's not strictly related to `chrome-remote-interface`. Feel free to comment if you find something that works for you.
