### ISSUE TITLE
Emulation.setUserAgentOverride not supported 

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#383]
[Emulation.setUserAgentOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setUserAgentOverride) which is a devtool API  is not supported in the node module. 

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.04
| Node.js					| 10.1
| Chrome/Chromium/...		| 68
| chrome-remote-interface	| 0.27.0

Is Chrome running in a container? NO

```

goelayu@goelayu-hp:~/research/WebPeformance/scripts$ chrome-remote-interface inspect -p 9224
>>> typeof Emulation.setUserAgentOverride
'undefined'
>>>
```

**Comment by goelayu** [comment]
@cyrus-and Updated the issue description

**Comment by cyrus-and** [comment]
There's a typo in your example, anyway it works with Chrome 71, I can only think that it was not available in Chrome 68 (cannot try with such version right now).

**Comment by goelayu** [comment]
Yes it works with the latest version. 
Thanks.
