### ISSUE TITLE
Support Electron Debugger API

### ISSUE THREAD

**Issue by hanoii** [cyrus-and/chrome-remote-interface#384]
I was looking into using https://github.com/N0taN3rd/node-warc that already has support for this but instead of attaching it to a running chrome I would like to use the internal Electron chromium [Debugger](https://electronjs.org/docs/api/debugger) API.

A very quick look imply that this API should work with it as a new implementation, am I right?

So it seems this is a feature request, one I might even be tempted to contribute if I am understanding it properly, so any pointers/quickstarters into it are welcomed.

**Comment by cyrus-and** [comment]
`chrome-remote-interface` should already work for Electron apps out-of-the box:

```console
node_modules/.bin/electron --inspect=9222 app.js
```

After that it's just a matter of how you use the provided protocol.

**Comment by btzsoft** [comment]
@cyrus-and hi, it's possible to use without setting the port?. I have an use case where I attach the debugger to a specified webContents then want to use this library. it's this possible? thx.

**Comment by cyrus-and** [comment]
@btzsoft how can you attach the debugger to anything without an underlying port? (I'm not an Electron user myself.) Feel free to open a new issue or reach me out via email.

**Comment by btzsoft** [comment]
@cyrus-and soory, i mean without `--inspect=9222`

**Comment by cyrus-and** [comment]
@btzsoft yeah, I mean you said that you "attach the debugger to a specified webContents", how can you do that without specifying/using a port? It would be a matter of finding out which port is used by your debugger and use it with `chrome-remote-interface`. I'm sorry I cannot help you further without a detailed standalone example.
