### ISSUE TITLE
A way to connect to Chrome's inspector's inspector

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#385]
According to [this](https://developers.google.com/web/updates/2015/07/who-inspects-the-inspector) you can inspect the Chrome's inspector itself. I am wondering if there is a way to connect to this window from the nodejs library and be able to issue the devtool API calls, instead of issuing them to the main Chrome window.

**Comment by cyrus-and** [comment]
Sure, you can fetch the `devtoolsFrontendUrl` of the tab you want to inspect from `CDP.List()` and navigate to that URL in a new tab so to inspect this one instead.

**Comment by goelayu** [comment]
So this is what I am doing. `CDP.List()` gives me the following
```
[ { description: '',
  devtoolsFrontendUrl: '/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/97701F2D8FBB8C5B3C25544B3CE2C852',
  faviconUrl: 'https://www.cnn.com/favicon.ie9.ico',
  id: '97701F2D8FBB8C5B3C25544B3CE2C852',
  title: 'CNN - Breaking News, Latest News and Videos',
  type: 'page',
  url: 'https://www.cnn.com/',
  webSocketDebuggerUrl: 'ws://127.0.0.1:9222/devtools/page/97701F2D8FBB8C5B3C25544B3CE2C852' } ]

```
Then I navigate to the given `devtoolsFrontendUrl` ( removing the ws prefix)  in a new tab and try and fetch some object values using `Runtime.evaluate`. However certain classes which are declared by devtoolsFrontEnd code ( for example `DataGrid` ) which is accessible in the console when I inspect the inspector, isn't accessible in this new tab.

**Comment by cyrus-and** [comment]
> Could you just tell which url did you exactly navigate to?

For example:

    http://localhost:9222/devtools/inspector.html?ws=localhost:9222/devtools/page/<hash>

**Comment by goelayu** [comment]
Interestingly the above link doesn't work for me. The link I mentioned in my previous comment does work. My Chrome version is 68 which might have something to do with it. 

Anyway, it solved the issue. Thanks
