### ISSUE TITLE
Clone Chrome devtools behaviour

### ISSUE THREAD

**Issue by aggounix** [cyrus-and/chrome-remote-interface#386]
I would like to clone the inspect functions of chrome devtools: I have an iframe to load a web page, click on a html elements inside it and get the source code of the element (like chrome devtool extensions F12). is it possible to use chrome-remote-interface to implement this?

**Comment by cyrus-and** [comment]
Take a look at [Overlay.setInspectMode][1] for the inspect part and to [DOM.getOuterHTML][2] to get the source from a `BackendNodeId`.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Overlay#method-setInspectMode
[2]: https://chromedevtools.github.io/devtools-protocol/tot/DOM#method-getOuterHTML

**Comment by aggounix** [comment]
great! How can I attach Overlay.setInspectMode to a specific iframe in ma page?

**Comment by cyrus-and** [comment]
You just turn it on then click on a element I guess...

**Comment by aggounix** [comment]
Ok Thx, I am going to try it
