### ISSUE TITLE
Significant difference between network requests logged between different Chrome versions

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#389]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.04
| Node.js					| 10.1.0
| Chrome/Chromium/...		| 73.69
| chrome-remote-interface	| 0.27.0

Is Chrome running in a container?  NO

I am using [this](https://github.com/cyrus-and/chrome-remote-interface/wiki/Log-network-requests) script from the wiki to log number of network requests fired by the browser. 
I can see significant difference between the number of requests logged when I move from chromium-browser v69.0 to google-chrome-stable v73.69. 

I am trying to isolate the bug and figure out if it is a problem at the end of the chrome remote interface or is it at the end of Chromium browser. 

In order to replicate the bug, try loading a site with large number of resources fetched ( for example: www.cnbeta.com - around ~500 resources fetched) and see if the script captures all those resources correctly. 
In my case, google-chrome v73 recorded about ~200 resources every time. 

I repeated the experiment enough number of times to make sure it wasn't a one time thing.

**Comment by cyrus-and** [comment]
In my experiment there's a lot of variability even across the runs of a single version and no noticeable trend. Plus that script exits as soon as the `Page.loadEventFired` fires, this means that it doesn't wait that all the resources are fully loaded. Moreover it doesn't clear cookies...

In any case I doubt this could be an issue related to chrome-remote-interface, it merely reads and parses events from the WebSocket.

I suggest to file an [upstream issue](https://crbug.com) if you manage to make it more reproducible.

**Comment by goelayu** [comment]
I agree with the variability, there's enough non determinism on the page. However the amount of difference I am seeing, specifically due to different chrome version, made me worry






 that something is wrong. 

I do agree, that crbugs might be a better place to file the issue. Just wanted to throw it out here, in case someone else experienced something similar! 
Thanks anyway. Closing this.

**Comment by cyrus-and** [comment]
Fell free to post here if you discover something relevant.
