### ISSUE TITLE
After `Debugger.pause()`, the debuggee program keeps executing.

### ISSUE THREAD

**Issue by anurbol** [cyrus-and/chrome-remote-interface#393]
Hi, @cyrus-and and others. Can you please help me?

I have two node.js processes, one of which is a debuggee (my program to be debugged) and the other one is a debugger client (launches chrome-remote-interface and connects/attaches to the debuggee).

Everything works fine, I get messages `Debugger listening...` and `Debugger attached`.
I also have in the client process this call `client.Debugger.pause()` and after the call I see `Debugger.paused` event with stack frames listed, and I can see the location of the current frame (in the middle of my program).

**The problem**: After paused, for some reason the debuggee program continues, i.e. keeps executing. Why is that?

**Another problem** I tried to put `debugger;` keyword to force stop but it has no effect.

Do you know what is the reason for the two problems I am facing? Is this probably an expectected behavior? I thought that a debugger should stop a program from executing further when `pause` is requested. 

I will appreciate any help, thank you.

P.S. The code is complicated a little bit, I am working on minimal standalone script to reproduce, until then I would be happy to simply know if this behavior is expected or no?

| Component | Version
|-|-
| Operating system	  	 	| windows 7
| Node.js					| 10.15.3
| Chrome/Chromium/...		| n/a (I am connecting to node process, not to chrome)
| chrome-remote-interface	| 0.27.1

Is Chrome running in a container? - no chrome, no containers, just a node.js on my windows.

**Comment by anurbol** [comment]
Sorry, was stupid error in my code... This happens everytime when the code is complicated... :smiley:

**Comment by cyrus-and** [comment]
Hi, is this resolved or not?

> P.S. The code is complicated a little bit, I am working on minimal standalone script to reproduce, until then I would be happy to simply know if this behavior is expected or no?

The `Debugger` part is quite complex and can have, in my experience, some surprising outcomes, but yes I guess that this should not happen. Waiting for the minimal standalone script...

**Comment by anurbol** [comment]
@cyrus-and First, thanks for response! Second, after I had received your confirmation that this is unexpected I tried to reproduce it in minimal example, but for some reason the minimal example works as expected, I am still working to find out what's the problem....

**Comment by anurbol** [comment]
@cyrus-and OMG, the problem was in this code:

```js
    finally {
        if (client) {
            await client.close();
        }
    }
```
which I blindly copied from the example in README.md of the repo. Lol! :smile: So I think the problem was that even if the debugger did pause on `debugger;`, the `finally` block closed the connection shortly after that, and closing the debugging connection led to resuming the debuggee script. Phew! This is another example of why making minimal reproducible example is a good thing :-) Thanks, for the response, even if short one, it really helped!

**Comment by cyrus-and** [comment]
You're welcome, glad you found the bug. :)
