### ISSUE TITLE
Support path prefix for devtools API

### ISSUE THREAD

**Issue by vania-pooh** [cyrus-and/chrome-remote-interface#395]
Currently this client is only able to work with Devtools API available under `/`, i.e. `http://127.0.0.1:9022/json/protocol` and so on. I am one of [Selenoid](https://github.com/aerokube/selenoid) project maintainers - an efficient implementation of Selenium protocol. We are currently working on Chrome Devtools support in Selenoid and the most important feature is that we are able to run several Chrome instances in parallel (in Docker containers). From Devtools perspective that means all the API (including web-sockets) is accessible remotely on some fixed path, e.g.:
```
http://some-host.example.com/<fixed-path-prefix>/json/protocol
```
So it would be great if this client in addition to `host` and `port` options, has an `path` option allowing to specify this constant prefix. This should be at least applied to all `devtools.js` functions doing HTTP requests to the API. Is it a reasonable change? How could I help delivering this?

| Component | Version
|-|-
| Operating system	  	 	| MacOS Sierra
| Node.js					| 12.3.1
| Chrome/Chromium/...		| 75.0
| chrome-remote-interface	| 0.27.2

Is Chrome running in a container? YES

**Comment by cyrus-and** [comment]
Basically [this][1] (thread).

My biggest issue is that the path prefix is only one possible way to multiplex, one could think of more fancy ways like `/manager.php?id=x&path=/json/protocol`, I'm OK with fixing this problem but I'm more oriented in requiring some kind of callback to determine *how* to reach the Chrome server, a more general solution... I need to thing about this. Thoughts and suggestions are welcome.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/294#issuecomment-341918032

**Comment by cyrus-and** [comment]
BTW can you clarify why in you case port numbers are not enough? If I understand correctly you will have multiple containers, each one running its own instance of Chrome.

**Comment by vania-pooh** [comment]
@cyrus-and yes, but containers are being run via Selenium API. That is to say all commands are sent to the same standard port 4444 and the multiplexed to one of containers depending on so called `sessionId` being sent in every request.

**Comment by cyrus-and** [comment]
So this would affect the WebSocket URL too? That is:

    ws://127.0.0.1:9222/<fixed-path-prefix>/devtools/page/0BBBC8B6208CDBF28D875AD8E89C3E8F

instead of:

    ws://127.0.0.1:9222/devtools/page/0BBBC8B6208CDBF28D875AD8E89C3E8F

**Comment by cyrus-and** [comment]
I sketched a possible solution in a temporary [`url-callback`][1] branch. Basically DevTools methods and `CDP` now accept an `alterUrl` callback that allows an user to edit the URL parameter before the connection, for example:

```js
const options = {
    alterUrl: (object) => {
        object.pathname = '/<fixed-path-prefix>' + object.pathname;
        return object;
    }
};

CDP(options, /*...*/);
```

What do you think? (@joelgriffith I'd love to hear your opinion too.)

[1]: https://github.com/cyrus-and/chrome-remote-interface/tree/url-callback

**Comment by vania-pooh** [comment]
@cyrus-and correct, this would affect websocket URL.

**Comment by cyrus-and** [comment]
@vania-pooh what do you think about the proposed solution?

**Comment by vania-pooh** [comment]
@cyrus-and seems to be ok.

**Comment by cyrus-and** [comment]
I decided to use the `alterPath` option instead:

```js
const options = {
    alterPath: path => '/<fixed-path-prefix>' + path
};

CDP(options, /*...*/);
```
