### ISSUE TITLE
Tracing events do not contain `TracingStartedInBrowser` or `TracingStartedInPage`

### ISSUE THREAD

**Issue by sarthak-sehgal** [cyrus-and/chrome-remote-interface#397]
The trace I am getting does not contain the events `TracingStartedInBrowser` or `TracingStartedInPage` and `navigationStart` which seem to be there when I profile the same app using DevTools. I've tried enabling Debugger, Page, LayerTree, Performance, Profiler, and Runtime before Tracing.start() but no luck (don't know if I have to).

| Component | Version
|-|-
| Operating system	  	 	| MacOS 10.14.2
| Node.js					| 10.11.0
| Chrome/Chromium/...		| Chrome 69.0.3497.128
| chrome-remote-interface	| 0.27.2

Is Chrome running in a container? YES (running inside Electron)

**Comment by cyrus-and** [comment]
Can you provide a simple program to reproduce this issue so I can try to help? Maybe even just Node.js + regular Chrome (not Electron).

Please bear in mind that I'm not responsible for the implementation of the methods of the protocol.

**Comment by sarthak-sehgal** [comment]
Thanks for the prompt reply.
I have pushed the code here: https://github.com/sarthak-sehgal/chrome-remote-interface-test
It uses the sample code given in the [Wiki](https://github.com/cyrus-and/chrome-remote-interface/wiki/Generate-timeline-data)

The file `GithubProfileUsingDevtools.json` contains the trace when you profile using Chrome DevTools. It contains the events I am talking about.

PS: It concerns me because tools like `Tracium` require those events to be there. Even [chrome devtools throws an error if it is not present](https://github.com/ChromeDevTools/devtools-frontend/blob/b7fd0cc5f36b64858886caa98e212e05ad9efcc7/front_end/sdk/TracingModel.js#L123).

**Comment by sarthak-sehgal** [comment]
I am seeing some other essential events like `FrameCommittedInBrowser` missing too. Am I missing something in configuration?
Btw, I updated the code to include all categories in `traceConfig` so that should not be causing any problems.

**Comment by cyrus-and** [comment]
Thank you. If I start a tracing session from DevTools the message that is sent to Chrome is:

```json
{
  "categories": "-*,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,v8.execute,blink.console,blink.user_timing,latencyInfo,disabled-by-default-v8.cpu_profiler,disabled-by-default-v8.cpu_profiler.hires,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot",
  "options": "sampling-frequency=10000",
  "bufferUsageReportingInterval": 500,
  "transferMode": "ReportEvents"
}
```

I see differences with your `traceConfig` so you might want to start from here.

**Comment by cyrus-and** [comment]
FYI to debug differences with DevTools see [Inspect the inspector][1].

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-the-inspector

**Comment by sarthak-sehgal** [comment]
> Thank you. If I start a tracing session from DevTools the message that is sent to Chrome is:
> 
> ```json
> {
>   "categories": "-*,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,v8.execute,blink.console,blink.user_timing,latencyInfo,disabled-by-default-v8.cpu_profiler,disabled-by-default-v8.cpu_profiler.hires,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.screenshot",
>   "options": "sampling-frequency=10000",
>   "bufferUsageReportingInterval": 500,
>   "transferMode": "ReportEvents"
> }
> ```
> 
> I see differences with your `traceConfig` so you might want to start from here.

The differences are due to [Chrome Devtools Protocol Viewer claiming that `categories` object has been depreciated](https://chromedevtools.github.io/devtools-protocol/tot/Tracing) (all other params in the config are default params). The event `TracingStartedInBrowser` has the category `disabled-by-default-devtools.timeline` so should be received ideally. Something might be messed up from Devtools Protocols side. 😞

**Comment by cyrus-and** [comment]
Deprecated or not that's what DevTools on Chrome 75.0.3770.100 uses, so I guess it's quite the authority here... :) And in fact using the above `traceConfig` I get:

```console
$ jq '.[] | select(.name == "TracingStartedInBrowser")' GithubProfileUsingCDP.json
{
  "pid": 5929,
  "tid": 5929,
  "ts": 9735971540,
  "ph": "I",
  "cat": "disabled-by-default-devtools.timeline",
  "name": "TracingStartedInBrowser",
  "s": "t",
  "tts": 1085766,
  "args": {
    "data": {
      "frameTreeNodeId": 1,
      "persistentIds": true,
      "frames": [
        {
          "frame": "426992F3A00586DB50E07C6B3698A581",
          "url": "https://github.com/",
          "name": "",
          "processId": 15738
        }
      ]
    }
  }
}
```

I wouldn't mind all the `DEPRECATED` and `EXPERIMENTAL` tags in the protocol.

**Comment by sarthak-sehgal** [comment]
Wow that works! 😀
Thanks for the prompt guidance and the awesome package! 🌟

**Comment by cyrus-and** [comment]
Glad to help, good luck! :)

So can we close this?

**Comment by sarthak-sehgal** [comment]
Yup :)
