### ISSUE TITLE
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by sarduk** [cyrus-and/chrome-remote-interface#400]
| Component                                | Version
|                                                     -|-
| Operating system	  	 	| ubuntu16.04 server on remote VPS
| Node.js					| v12.8.0
| Chrome/Chromium/...		| chromium-browser
| chrome-remote-interface	        | 0.27.2

Is Chrome running in a container?  NO

megerr when launching chrome in headlless mode :
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

I'm writing a script node express,
when express receive a http request, the script node launch new chrome instance in headless-mode using lib chrome_launcher do some stuff, and kill the istance.

the remote server is a VPS with ubuntu16.04.

to launch the webserver I connect via ssh with VPS:
$ node app_ws.js &

If the ssh connection is alive all works fine and node script can launch chrome regularly.

Instead, when I close the terminal and break-down the ssh connection (and the user session terminates) then starts the badly:

in the first request chrome is launched, OK,
from the second request onwards script cant launch chrome, the message error is:

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

code snippets

//launch chrome in hadless mode using npm lib chrome_launcher (https://github.com/cyrus-and/chrome-remote-interface)
const chrome = await chromeLauncher.launch({
    "chromeFlags": [ '--disable-gpu', '--headless' ]
});
//Kill Chrome
chrome.kill()

chrome.kill() return a promise but dont catch any error

thanks from now for help

**Comment by cyrus-and** [comment]
AFAIK there is no reason for that behavior apart from a bug in your code, can you put a working example somewhere so I can attempt to reproduce this issue?

**Comment by cyrus-and** [comment]
Using this minimal example I'm not able to reproduce the error:

```js
const http = require('http');
const ChromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

const server = http.createServer(async (req, res) => {
    try {
        // launch a new chrome instance
        const chrome = await ChromeLauncher.launch({
            chromeFlags: ['--headless', '--disable-gpu', '--no-sandbox']
        });
        console.log(`INFO: Chrome debugging port running on ${chrome.port}`);

        // interact with the instance, e.g., fetch the version info
        const version = await CDP.Version({port: chrome.port});
        res.end(JSON.stringify(version, null, 4));

        await chrome.kill();
    } catch (e) {
        const message = `ERROR: ${e.message}`;
        console.error(message);
        res.end(message);
    }
});

server.listen(8080);
```

**Comment by sarduk** [comment]
cyrus-and , thank you for the answer,
the error in my code that generates the problem:   
             } finally {
                 // the instruction responsible for the error
                 console.error ("try {} finally {");
             }


I never use "console.error", instead I wanted to write "console.log"
eliminated "console.error"  everything works!

here is a complete example that reproduces the malfunction:

    const http = require('http');
    const ChromeLauncher = require('chrome-launcher');
    const CDP = require('chrome-remote-interface');
    
    const server = http.createServer(async (req, res) => {
    
        let client;
        let chrome;
    
        try {
            
            chrome = await ChromeLauncher.launch({
              chromeFlags: ['--headless', '--disable-gpu', '--no-sandbox']
            });
            const client = await CDP({"port": chrome.port});
            
            // extract domains
            const {Network, Page} = client;
            
            // setup handlers
            await Network.enable();
            await Page.enable();
                
            //Page.navigate
            await Page.navigate({"url": "https://google.com"});
            
            await Page.loadEventFired(
                async () => {
    
                    //do something
    
                    await client.close();
                    await chrome.kill(); 
    
                    res.end("ok");
    
                }    
            );
    
        } catch (err) {
            
            await client.close();
            await chrome.kill(); 
    
            const message = `catch(err: ${err.message}`;
            console.log(message)
            res.end(message);
            
        } finally {
              const message = `finally {`;
              //  the instruction responsible for the error
              console.error(message)
        }
    
    });
    
    //server.listen(8080);
    server.listen(8080, function(){console.log("http server.listen 8080")});

**Comment by cyrus-and** [comment]
I still cannot reproduce the issue, but I'm glad you found the culprit.

Anyway you might want to try to redirect your standard streams, a possibly overkill example is:

```console
$ node app_ws.js </dev/null &>log.txt & disown; exit
```

Alternatively launch the application from a `tmux` or a `screen` session then detach the session and log out from the server.
