### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by fpsqdb** [cyrus-and/chrome-remote-interface#401]
| Component | Version
|-|-
| Operating system	  	 	| win10 18362.295
| Node.js					| 7.9
| Chrome/Chromium/...		| 58.0.3029.110
| chrome-remote-interface	| 0.28.0
| Webpack                        	| 4.18.1

Is Chrome running in a container? YES , Electron 1.7.9

Use webpack to bundle a single js.
```
Uncaught SyntaxError: Unexpected token ...
```
The previous version 0.27.2 works fine.

**Comment by cyrus-and** [comment]
> Alright then, please provide the following information along with a detailed description of what went wrong.
> 
> If appropriate, attach a MINIMAL STANDALONE SCRIPT to help to reproduce your issue.

**Comment by fpsqdb** [comment]
Here is the sample.
[chrome-remote-interface-bug.zip](https://github.com/cyrus-and/chrome-remote-interface/files/3545621/chrome-remote-interface-bug.zip)

```
npm intall
npm run compile
npm run start
```

![error](https://user-images.githubusercontent.com/6482819/63764192-d3a8a400-c8f8-11e9-9e98-b633a5a63f94.png)

**Comment by cyrus-and** [comment]
Thank you.

You're using an ancient version of Electron that bundles a V8 that does not support `...` (the spread operator). You should be able to fix this by upgrading Electron.
