### ISSUE TITLE
Missing webSocketDebuggerUrl property in /json/list response

### ISSUE THREAD

**Issue by ndimer** [cyrus-and/chrome-remote-interface#402]
My Node.js program forks another .js file using child_process.fork method and passes --inspect-brk flag. Then, from the parent process, I am trying to connect to the port specified in inspect-brk flag using chrome-remote-interface. I am getting this error when calling:

`await CDP({ port: port, host: host });`

Error: **No inspectable targets**

After investigating this issue, I saw that https://github.com/cyrus-and/chrome-remote-interface/blob/1003815fbf99e6973a8ab09bf10d8274c640d8ea/lib/chrome.js#L37 requires 'webSocketDebuggerUrl' property to be presented in /json/list response. However, in my case I am getting back the following payload from Node debugger: 

```
[ {
  "description": "node.js instance",
  "faviconUrl": "https://nodejs.org/static/favicon.ico",
  "id": "179a2c03-477e-4644-b545-0b236de1b179",
  "title": "/Users/n/Documents/worker.js",
  "type": "node",
  "url": "file:///Users/n/Documents/worker.js"
} ]
```
Any idea why in my case there is no 'webSocketDebuggerUrl' property returned and also why chrome-remote-interface doesn't support targets with no 'webSocketDebuggerUrl' property (the websocket URL can be built from the existing parameters without the explicit value)?

| Component | Version
|-|-
| Operating system	  	 	| MacOS
| Node.js					| v8.15.0
| Chrome/Chromium/...		| 77.0.3865.90
| chrome-remote-interface	| 0.27.2

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
What happens if you run the child process manually and then run `chrome-remote-interface list`?

```console
$ node --inspect=9222 --debug-brk script.js
Debugger listening on ws://127.0.0.1:9222/26d5acec-bc67-429b-8aee-f1b1c286487a
For help, see: https://nodejs.org/en/docs/inspector
```

```console
$ chrome-remote-interface list
[
    {
        "description": "node.js instance",
        "devtoolsFrontendUrl": "chrome-devtools://devtools/bundled/js_app.html?experiments=true&v8only=true&ws=127.0.0.1:9222/26d5acec-bc67-429b-8aee-f1b1c286487a",
        "devtoolsFrontendUrlCompat": "chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9222/26d5acec-bc67-429b-8aee-f1b1c286487a",
        "faviconUrl": "https://nodejs.org/static/favicon.ico",
        "id": "26d5acec-bc67-429b-8aee-f1b1c286487a",
        "title": "script.js",
        "type": "node",
        "url": "file:///storage/tmp/script.js",
        "webSocketDebuggerUrl": "ws://127.0.0.1:9222/26d5acec-bc67-429b-8aee-f1b1c286487a"
    }
]
```

> the websocket URL can be built from the existing parameters without the explicit value

Yes and no... I mean apparently the format is implementation defined, compare Node.js:

    ws://127.0.0.1:9222/d9fc5ea4-4b3f-481c-9720-ff86b4864b3f

with Chrome:

    ws://127.0.0.1:9222/devtools/page/A33073C1B425A1916849865124F6D47B

I could use `type` to discern the cases and build the URL but AFAIK there is no guarantee that the above is the rule and doesn't change.

**Comment by ndimer** [comment]
I tried to run it directly and got the same payload. No webSocketDebuggerUrl.


Please note that in both cases, I am able to connect to the debugging
session from Chrome's DevTools. So it seems like no-webSocketDebuggerUrl
session is officially supported by Chrome as well. So I think it worth
modifying your code and adding support for that case as well. If you like,
I can help you up with this?

**Comment by cyrus-and** [comment]
It's not a matter of support, if that field is not there it means that you won't be able to connect to the WebSocket. This used to happen in old implementations (i.e., Node.js 8.15.0) when a client is already attached to the debugger, in your case it's likely to be DevTools. In fact if you try to connect anyway you end up with an HTTP 400.

So either switch to a newer Node.js version or avoid simultaneous connections.
