### ISSUE TITLE
users profile management

### ISSUE THREAD

**Issue by sarduk** [cyrus-and/chrome-remote-interface#403]
how to manage user profiles? (create user profile, destroy user profile, get userprofile data, ...)
I've looked in the Chrome DevTools Protocol Viewer, but I don't find any!
https://chromedevtools.github.io/devtools-protocol/
tks for answers

**Comment by cyrus-and** [comment]
I'm afraid you can't do that via the debugging protocol. You may want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or file an issue in the [devtools-protocol](https://github.com/chromedevtools/devtools-protocol) repo.
