### ISSUE TITLE
How to set localStorage value before navigagte a page

### ISSUE THREAD

**Issue by lintaonz** [cyrus-and/chrome-remote-interface#406]
| Component | Version
|-|-
| Operating system	  	 	| macOS 10.15.1
| Node.js					| 8.11
| Chrome		| 78.0.3904.108
| chrome-remote-interface	| 0.25.3

Is Chrome running in a container? NO

Hi,

In my site, I need to set an item in the localStorage so that it can pass the authorization. Here is my code. But it seems not working as I always get the 403 back. 

My question: How can I set a localStorage value before request a page?

Thanks,

Tao

```js
await Page.navigate({
  url: 'https://dev.com/login'
}); // load a public page first

await Page.loadEventFired();
const storageId = {
  securityOrigin: 'https://dev.com',
  isLocalStorage: true
};
const userToken = await DOMStorage.setDOMStorageItem({
  storageId,
  key: "userToken",
  value: "xxx"
});

const items = await DOMStorage.getDOMStorageItems({ storageId });

await Page.navigate({ url: 'https://dev.com/dashboard' });  // then go to the authorized page, and I still got 403 error here
await Page.loadEventFired();
```

**Comment by cyrus-and** [comment]
Maybe you simply forgot to paste it here but you need to enable the `Page` domain in order for the `Page.loadEventFired` event to be handled:

```js
await Page.enable();
```

Here's a full example with a test web page:

```js
const CDP = require('chrome-remote-interface');

const PAGE_URL = new URL('http://www.sharonminsuk.com/code/storage-test.html');

CDP(async (client) => {
    const {Page, DOMStorage} = client;

    await Page.enable();

    await Page.navigate({
        url: PAGE_URL
    });
    await Page.loadEventFired();

    const storageId = {
        securityOrigin: PAGE_URL.origin,
        isLocalStorage: true
    };

    const userToken = await DOMStorage.setDOMStorageItem({
        storageId,
        key: 'theirValue',
        value: 'IT WORKS!'
    });

    const items = await DOMStorage.getDOMStorageItems({storageId});
    console.log(items);

    await Page.navigate({ url: PAGE_URL });
    await Page.loadEventFired();
}).on('error', (err) => {
    console.error(err);
});
```

You should see `IT WORKS!` in the first text field on the loaded page.

**Comment by lintaonz** [comment]
Thank you very much, @cyrus-and 

My code does have `await Page.enable()`. I believe my problem is not about the localStorage, it's my SPA need not only the userToken value but other two localStorage values as well. Once I set all the values, the code works perfectly. 

 Thank you for helping me to narrow down my issue.

Tao

**Comment by cyrus-and** [comment]
You're welcome!
