### ISSUE TITLE
TypeError: Cannot read property 'requestWillBeSent' of undefined

### ISSUE THREAD

**Issue by jvannier** [cyrus-and/chrome-remote-interface#407]
So, I'm on an Ubuntu computer,

running google chrome headless:
`google-chrome --headless --remote-debugging-port=9222`

and node:
`node --inspect=9222 --inspect-brk`

and running the example in the README:
```
const CDP = require('chrome-remote-interface');

async function example() {
    let client;
    try {
        // connect to endpoint
        client = await CDP();
        // extract domains
        const {Network, Page} = client;
        // setup handlers
        Network.requestWillBeSent((params) => {
            console.log(params.request.url);
        });
        // enable events then start!
        await Network.enable();
        await Page.enable();
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

via `node my_test.js`

And I'm getting the following error:
`
TypeError: Cannot read property 'requestWillBeSent' of undefined
    at example (/home/jennifer.vannier/workspace/testing-perf-stuff/my_test.js:12:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

referring to it not finding "Network" in the client var. I am very sure I'm missing something obvious and would appreciate the help.... :( 

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.04.3 LTS
| Node.js					| 12.12.0
| Chrome/Chromium/...		| 78.0.3904.108
| chrome-remote-interface	| 0.28.0

Is Chrome running in a container? NO

**Comment by jvannier** [comment]
AH, that's what it was. 🤦‍♂ Thank you very much!

**Comment by cyrus-and** [comment]
You're welcome!

To elaborate on that, if you're curious, what likely happened was that you run `node --inspect=9222 --inspect-brk` then `google-chrome --headless --remote-debugging-port=9222` which failed *silently* with:

```
[1205/184553.316516:ERROR:socket_posix.cc(145)] bind() failed: Address already in use (98)
```

Then the Node.js script connects to Node.js, but there's no `Network` domain there (see [here][1]) hence the `TypeError`.

[1]: https://chromedevtools.github.io/devtools-protocol/v8/
