### ISSUE TITLE
Trying to get Page load performance metrics

### ISSUE THREAD

**Issue by jvannier** [cyrus-and/chrome-remote-interface#408]
I'm trying to use this tool to get page load times, so I'm using the 'Performance' object in client, but I don't appear to be getting anything :(

running google chrome headless:
`google-chrome --headless --remote-debugging-port=9222`

and running the following code:
```
const CDP = require('chrome-remote-interface');
const fs = require('fs');

CDP(async (client) => {
    try {
        const {Page, Performance, Runtime, Tracing} = client;
        // enable Page domain events
        await Page.enable();
        await Performance.enable();

        Performance.getMetrics(({value}) => {
            console.log(value);
        }); 

        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();

        await Performance.getMetrics();
    } catch (err) {
        console.error(err);
    } finally {
        await client.close();
    }   
}).on('error', (err) => {
    console.error(err);
});
```

via `node my_test.js`

I just get:
`undefined`

Do I need to _also_ use paulirish's `automated-chrome-profiling`? I'm trying to avoid that if possible.

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.04.3 LTS
| Node.js					| 12.12.0
| Chrome/Chromium/...		| 78.0.3904.108
| chrome-remote-interface	| 0.28.0

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
The invocation of `Performance.getMetric` is wrong, if you're using the [callback flavor][1], the first argument is the `error` field and anyway there is no `value` field, that function returns an array named `metrics` so:

```js
Performance.getMetrics((error, {metrics}) => {
    // TODO handle error
    console.log(metrics);
});
```

Alternatively:

```js
const {metrics} = await Performance.getMetrics();
console.log(metrics);
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#clientsendmethod-params-callback

> Do I need to _also_ use paulirish's `automated-chrome-profiling`?

We implemented `automated-chrome-profiling` using this module, so you can do everything with `chrome-remote-interface` alone.

**Comment by jvannier** [comment]
Beautiful!! Thank you very very much!!!!!!!
