### ISSUE TITLE
Setting a cookie

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#41]
Is it possible to have a function setCookie that will allow us to set Cookie (https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Page/#type-Cookie)

**Comment by cyrus-and** [comment]
I cannot add functions to the protocol, this interface merely uses the provided protocol descriptor to communicate with Chrome.

Your best chance is to [set a cookie via JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie) by injecting the proper code with [Runtime.evaluate](https://chromedevtools.github.io/debugger-protocol-viewer/1-1/Runtime/#method-evaluate).

**Comment by mato75** [comment]
Thx

**Comment by cyrus-and** [comment]
FYI: it seems that it is possible with the [tip-of-the-tree][1] protocol.

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-setCookie
