### ISSUE TITLE
how to open new window and not tab

### ISSUE THREAD

**Issue by saikrishna321** [cyrus-and/chrome-remote-interface#410]
Hi,

I'm trying to open a new window and `createTarget` creates a Tab and not new window. Any help pls

**Comment by cyrus-and** [comment]
I'm afraid you cannot do that natively via the debugging protocol. What you can do instead is to inject some JavaScript in the *current* tab then use `window.open` to spawn a new window.

**Comment by saikrishna321** [comment]
@cyrus-and Thanks for a quick reply. window.open also would open new tab right?

Any code-snippet you can share?

**Comment by cyrus-and** [comment]
> window.open also would open new tab right?

Also a new window.

> Any code-snippet you can share?

It all depends on what you want to do with the newly created window, but this is a start:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    try {
        const {Page, Runtime} = client;

        // initially load a page that won't block popups
        await Page.navigate({url: 'chrome://version'});

        // open a new window
        await Runtime.evaluate({
            expression: `window.open('https://example.com', '', 'resizable')`
        });
    } catch (err) {
        console.error(err);
    } finally {
        await client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by saikrishna321** [comment]
Thanks @cyrus-and
