### ISSUE TITLE
Invalid character in header content

### ISSUE THREAD

**Issue by VoidMonk** [cyrus-and/chrome-remote-interface#411]
Hi, I've come across an issue with response headers of any webpage that emits multiple headers by the same name.

For example, the Facebook Marketplace (https://www.facebook.com/marketplace/) page is opened in Chrome, and its headers are read via `chrome-remote-interface` like:

```js
Network.responseReceived((params) => {
    console.error(params.response.headers);
});
```

The website emits multiple `date` headers, but they appear merged together when read, as:

```
date: 'Mon, 20 Jan 2020 21:34:56 GMT\nMon, 20 Jan 2020 21:34:56 GMT',
```

The new line character separator in the header value causes Node.js to throw an error on response piping: `Invalid character in header content`

I'm not sure where exactly does this issue originate, and how to fix it. I found a similar issue at https://github.com/puppeteer/puppeteer/issues/1893

Any suggestion is much appreciated.

| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 10.17.0
| Chrome		| 79.0.3945.117
| chrome-remote-interface	| 0.28.1

Is Chrome running in a container? No

**Comment by cyrus-and** [comment]
This has nothing to do with chrome-remote-interface, this is how Chrome returns multiple instance of the same header; I have no control over that, Puppeteer instead provides an API layer over the debug protocol so they might want to adjust this before returning the headers to the user.

It all boils down on what you need to do with the `Network.responseReceived` but the fix should be trivial, something like:

```js
Network.responseReceived((params) => {
    const myHeader = params.response.headers['my-header'];
    httpResponse.setHeader('my-header', myHeader.split('\n'));
});
```

And this works even if `my-header` is not actually present multiple times.

**Comment by VoidMonk** [comment]
Thank you @cyrus-and. It helped resolve the issue.
