### ISSUE TITLE
We should provide an easier way to get current page URL than `Runtime.evaluate({expression: 'window.location.toString()'})`

### ISSUE THREAD

**Issue by nddipiazza** [cyrus-and/chrome-remote-interface#412]
Unless I'm mistaken, the only way to get the current URL of your browser page is

```
Runtime.evaluate({expression: 'window.location.toString()'})
```

Can we create a simple utility method to do this like `Page.currentUrl` or something?

**Comment by cyrus-and** [comment]
Well no because chrome-remote-interface is a 1:1 mapping of the [Chrome DevTools Protocol][1], not an API layer over it, like Puppeteer.

[1]: https://chromedevtools.github.io/devtools-protocol/

**Comment by cyrus-and** [comment]
FYI another alternative could be:

```js
const {targetInfo: {url}} = await Target.getTargetInfo();
console.log(url);
```

**Comment by cyrus-and** [comment]
For what concerns the Chrome DevTools Protocol you should file suggestions [here][1]. Please let me know if something I wrote is unclear, closing now.

[1]: https://github.com/chromedevtools/devtools-protocol/issues

**Comment by nddipiazza** [comment]
I think the Target object is what I was missing. That's a way cleaner, more elegant solution.
