### ISSUE TITLE
Call to CDP domain does not return when chrome process crashes. 

### ISSUE THREAD

**Issue by negiDharmendra** [cyrus-and/chrome-remote-interface#413]
| Component | Version
|-|-
| Operating system	  	 	| MacOS
| Node.js					| v10.16.0
| Chrome/Chromium/...		| Chromium: 81.0.3994.0
| chrome-remote-interface	| 0.28.1

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
> Alright then, please provide the following information **along with a detailed
description of what went wrong**.

> **If appropriate, attach a MINIMAL STANDALONE SCRIPT to help to reproduce your
issue**.
