### ISSUE TITLE
Using experimental Methods

### ISSUE THREAD

**Issue by utkarshl** [cyrus-and/chrome-remote-interface#414]
I am unable to figure out how to use experimental methods. In particular, I am interested in using SystemInfo module. I followed the steps listed under ['**Listening to the protocol**'](https://chromedevtools.github.io/devtools-protocol/). I am able to call non experimental methods, such as `Emulation.setDeviceMetricsOverride`, but any attempt to call experimental methods results in `'SystemInfo.getProcessInfo' wasn't found`. I found that other people in the past have [also seen this issue](https://github.com/cyrus-and/chrome-remote-interface/issues/57), but I am unable to find out how to fix this.

| Component | Version
|---|--
| Operating system	  	 	|  Mac OS 10.15.3
| Node.js					|  N/A
| Chrome/Chromium/...		|  80.0.3987.163
| chrome-remote-interface	| N/A

Is Chrome running in a container? NO

MINIMAL STANDALONE SCRIPT
```js
await Main.sendOverProtocol('SystemInfo.getProcessInfo', {});
```

**Comment by cyrus-and** [comment]
> ```js
> await Main.sendOverProtocol('SystemInfo.getProcessInfo', {});
> ```

What's `Main.sendOverProtocol`?

Anyway they can apparently only used in the *browser context*:

```console
$ chrome-remote-interface version
{
    "Browser": "HeadlessChrome/81.0.4044.92",
    "Protocol-Version": "1.3",
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/81.0.4044.92 Safari/537.36",
    "V8-Version": "8.1.307.28",
    "WebKit-Version": "537.36 (@e98e6f21168a55e7ba57202f56323911cd9d31d1)",
    "webSocketDebuggerUrl": "ws://127.0.0.1:9222/devtools/browser/102239c1-97f5-4433-9001-50082f3fcb42"
}
```

That is `ws://127.0.0.1:9222/devtools/browser/102239c1-97f5-4433-9001-50082f3fcb42` in this case.
