### ISSUE TITLE
Different results in F12 and CDP

### ISSUE THREAD

**Issue by MilnerAlex** [cyrus-and/chrome-remote-interface#415]
The page https://www.bbc.co.uk/iplayer/live/bbcone
I can query element “div.p_playerControls”  in Chrome's F12 console: 

document.querySelector('div.p_playerControls')
div class=​"p_playerControls" style=​"display:​ block;​ clip:​ rect(1px, 1px, 1px, 1px)​;​"

...but cannot via remote interface:

result1 = await Runtime.evaluate({expression:"document.querySelector('div.p_playerControls')"})
result2 = await Runtime.evaluate({expression:"document.querySelector('.player__container')"})
console.log(result1.result.className)
console.log(result2.result.className)

Output:
Debugger attached.
undefined
HTMLDivElement

Am I do something wrong?.. :) Thanks!

![player2](https://user-images.githubusercontent.com/64533605/80593537-77bb8f80-8a32-11ea-8483-e57d88f4b295.jpg)

**Comment by cyrus-and** [comment]
That's because with DevTools you're in a different frame.

![2020-04-29_14-46](https://user-images.githubusercontent.com/1660263/80597558-4d64d480-8a28-11ea-904b-f3e8cbe01986.png)

**Comment by MilnerAlex** [comment]
Thanks  for your point! 

If you can please help to me how to get this element in JS (I should switch frames somehow?..) It's very valuable for me! :) Thanks in advance!

**Comment by cyrus-and** [comment]
Basically you need to hook the [`Runtime.ExecutionContextDescription`][1] event and take note of the `id` which is then passed to the `Runtime.evaluate` as the `Runtime.evaluate` parameter.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-executionContextCreated

**Comment by MilnerAlex** [comment]
Thank you for help, problem solved! :)
