### ISSUE TITLE
Firefox documentation needed

### ISSUE THREAD

**Issue by Niek** [cyrus-and/chrome-remote-interface#416]
I have some trouble getting CRI working with Firefox.

First of all the documentation should probably mention that ``--remote-debugger`` is only built in the nightly version of Firefox. Unfortunately it still doesn't work for me:

```bash
$ firefox-nightly --remote-debugger 127.0.0.1:44001
DevTools listening on ws://localhost:44001/devtools/browser/428fb6bc-b3d3-1f40-a278-ea4cb7f31abb
IPDL protocol error: Handler returned error code!
$ ./node_modules/chrome-remote-interface/bin/client.js -p 44001 list
Error: Bad request
```
Am I missing something?

**Comment by cyrus-and** [comment]
The documentation also explicitly states:

> Note: It might be broken in recent versions of Firefox, see #68.

Unfortunately it seems that Mozilla doesn't care about providing the documentation about this feature. You're more than welcome to reach them out it you want. That feature used to work in Firefox 70.

In the meanwhile you can show me the output of:

```
curl 127.0.0.1:44001/json/list -v
```

Also the `devtools.debugger.remote-enabled` config must supposedly be set to `true`.

**Comment by Niek** [comment]
Don't ask me why, but I managed to get it working with ``--remote-debugging-port PORT`` instead of ``--remote-debugger 127.0.0.1:PORT``. It seems that the latter one listens specifically on hostname ``localhost`` (even though I specify the IP) and requests without the ``Host: localhost`` header return a 400 Bad Request. Starting FF while specifying only the port works fine.

**Comment by cyrus-and** [comment]
I'm still unable to make it work... Plus the only documented flag is `--start-debugger-server`.

**Comment by Niek** [comment]
> I'm still unable to make it work... Plus the only documented flag is `--start-debugger-server`.
Seems documented to me, as long as you use nightly or compile your own Firefox with ``--enable-cdp``:
```bash
→ /Applications/Firefox\ Nightly.app/Contents/MacOS/firefox --help | grep remote-debugger -A3
  --remote-debugger [<host>][:<port>]
  --remote-debugging-port <port> Start the Firefox remote agent, which is
                     a low-level debugging interface based on the CDP protocol.
                     Defaults to listen on localhost:9222.
```

**Comment by cyrus-and** [comment]
Oh sorry it seems I used the beta this time... let me check.

**Comment by cyrus-and** [comment]
Alright yeah so the only option needed is `--remote-debugging-port 9222` if I omit the port Firefox (currently crashes). No settings in `about:config` need to be changed. So I'm going to update the README as follows, sound right?

---

### Firefox (Nightly)

Start Firefox with the `--remote-debugging-port` option, for example:

    firefox --remote-debugging-port 9222

**Comment by Niek** [comment]
Yes, I checked a fresh profile and it doesn't require any additional preferences. But I guess it wouldn't hurt to warn people that the Firefox CDP implementation is kinda buggy/half-implemented, so many calls will return a MethodNotImplemented error.

**Comment by cyrus-and** [comment]
OK for the buggy part (which I haven't really tested), the fact that it implements a subset of the original CDP is already stated, it would be nice that Mozilla provided documentation about what domains are implemented... Users can still obtain the actual protocol using the [Protocol](https://github.com/cyrus-and/chrome-remote-interface#cdpprotocoloptions-callback) function and  sub command.

Thanks for your timely support!
