### ISSUE TITLE
Using Updated Protocol

### ISSUE THREAD

**Issue by raju249** [cyrus-and/chrome-remote-interface#418]
On running the `update-protocol.sh` I could see a diff being generated. Is it possible to update them locally and use in the package?

**Comment by cyrus-and** [comment]
You see the diff because it's actually updated locally. You're not supposed to use that script though, the proper way is to use the protocol that comes with the browser you're instrumenting which by the way is the default behaviour.

**Comment by raju249** [comment]
Ah, alright. Thanks @cyrus-and 

Closing this issue.
