### ISSUE TITLE
[Question] Is it possible to interact with the devtools frontend with CDP?

### ISSUE THREAD

**Issue by manojVivek** [cyrus-and/chrome-remote-interface#419]
Hi, I'm trying to mimic the default chrome dev tools behavior on `Overlay.inspectNodeRequested` with [my application](https://github.com/manojVivek/responsively-app/), to open the `Elements` panel of the chrome dev-tools window, and selecting the inspected node.

But I don't find any message in the protocol to interact with the frontend UI. So just wanted to check with you.

Please feel free to throw at me any ideas on how that can be achieved.

BTW, thanks for this library, it is so helpful. 🙏

**Comment by cyrus-and** [comment]
Hopefully this should give you something to work on:

```javascript
const CDP = require('chrome-remote-interface');

async function example() {
    try {
        const client = await CDP();
        const {DOM, Overlay} = client;

        Overlay.inspectNodeRequested(async ({backendNodeId}) => {
            console.log(`node requested: ${backendNodeId}`);
            await Overlay.setInspectMode({
                mode: 'none',
                highlightConfig: {}
            });
        });

        await DOM.enable();
        await Overlay.enable();
        await Overlay.setInspectMode({
            mode: 'searchForNode',
            highlightConfig: {
                contentColor: {r: 255, g: 0, b:0, a: 0.5}
            }
        });
    } catch (err) {
        console.error(err);
    }
}

example();
```

**Comment by manojVivek** [comment]
@cyrus-and Thanks for the quick reply. I have been trying the same and I'm able to get the node inspected.

But I need Chrome's dev-tools window opened with the inspected node, which I'm quite not sure how to achieve.

I can open the dev-tools window through other means, but focusing this node on the `Elements` panel of the dev tools is what I'm not able to get through. 

Any ideas there?

**Comment by cyrus-and** [comment]
> But I need Chrome's dev-tools window opened with the inspected node, which I'm quite not sure how to achieve.

I'm quite sure this cannot be done, but you might want to ask [here][1] or [here][2].

> I can open the dev-tools window through other means

How?

[1]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol
[2]: https://github.com/ChromeDevTools/devtools-protocol

**Comment by manojVivek** [comment]
> I'm quite sure this cannot be done, but you might want to ask [here](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or [here](https://github.com/ChromeDevTools/devtools-protocol).

Thanks for these pointers, I looked into the [devtools-frontend](https://github.com/ChromeDevTools/devtools-frontend) and got some ideas to work on.

> How?

Since the pages are loaded using `electron webview`, there are APIs to open the dev-tools window.

I'm closing this issue now, thanks for the help!

**Comment by cyrus-and** [comment]
Feel free to post here a sketch of the solution if you find it so to help others.

**Comment by jernkuan** [comment]
I think he literally just called 
openDevTools

https://github.com/responsively-org/responsively-app/blob/90240a64b950a415447d50e4940e696aab8bee6f/desktop-app/app/main.dev.js#L588
