### ISSUE TITLE
node-inspector support

### ISSUE THREAD

**Issue by polkovnikov-ph** [cyrus-and/chrome-remote-interface#42]
`node-inspector` spawns debugger protocol compatible API on `ws://127.0.0.1:8080/?port=5858`. Path goes where?

**Comment by cyrus-and** [comment]
That is not supported at the moment, but you can work around with:

1. start a Chrome instance anyway with `--remote-debugging-port=9222`;

2. pass the following options to `Chrome(options, function (chrome) {})`:

    ```js
    var options = {
        'chooseTab': {
            'webSocketDebuggerUrl': 'ws://127.0.0.1:8080/?port=5858'
        }
    };
```

This should work, even though I'm unable to test it.

---

I may consider to properly support `node-inspector` in the future.

**Comment by polkovnikov-ph** [comment]
@cyrus-and The hack worked flawlessly. Thank you!

**Comment by cyrus-and** [comment]
You can avoid the Chrome instance by setting up a dummy web server. Something as simple as this Bash snippet:

```shell
while echo $'HTTP/1.1 200 OK\n\n[]' | nc -q 0 -lp 9222:; do :; done
```

**Comment by polkovnikov-ph** [comment]
@cyrus-and I see, it doesn't have to be a CDP-conforming server.

**Comment by cyrus-and** [comment]
So I realized that avoiding to fetch the list of tabs from `/json/list` was the right thing to do when a tab object is passed as [`chooseTab`][1]. After the refactoring adding the option to attach to a user-specified URL has been trivial.

You don't need the auxiliary server anymore. Thanks for your contribution.

[1]: https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback
