### ISSUE TITLE
Domain.Method wasn't found for Chrome in container

### ISSUE THREAD

**Issue by tymfear** [cyrus-and/chrome-remote-interface#423]
| Component | Version
| -|-
| Operating system	  	 	| MacOS 10.15.6
| Node.js					| v14.3.0
| Chrome/Chromium/...		| 84.0
| chrome-remote-interface	| 0.28.1

Is Chrome running in a container? **YES**

I'm trying to connect to Chrome instance that runs in the docker container started by [Selenoid](https://aerokube.com/selenoid/latest/#_accessing_browser_developer_tools).
No matter if I use local protocol, or protocol that is provided by the Chrome version from container [see here](https://gofile.io/d/7NARgX), I always get the he same error that Domain.Method wasn't found

```bash
ProtocolError: 'Network.enable' wasn't found
```
Here is an example of the test script
```javascript
const CDP = require('chrome-remote-interface');

(async () => {
  let client;
  try {
    // connect to endpoint
    client = await CDP({
      target: 'ws://127.0.0.1:4444/devtools/1214245f242f3f6b78af6f30f5c4b65b',
      protocol: require('./protocol.json'),
    });

    client.Network.requestWillBeSent((params) => {
      console.log(params.request.url);
    });
    // enable events then start!
    await client.Network.enable();

    await client.Page.navigate({ url: 'https://github.com' });
    await client.Page.loadEventFired();
  } catch (err) {
    console.error(err);
  } finally {
    if (client) {
      await client.close();
    }
  }
})();
```

I have read the FAQ sections that notes about difference in versions, but I tried with Chrome 79 and 84 - all the same.
Is there something else that I'm missing?

Even tried to use the latest version of protocol from [here](https://raw.githubusercontent.com/ChromeDevTools/devtools-protocol/master/json/browser_protocol.json)

**Comment by cyrus-and** [comment]
I think you're connecting to the *browser* WebSocket and not to one of the pages. List the inspectable targets with the `CDP.List()` function or with [`Target.getTargets`][1] method from the *browser* WebSocket in your example code.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-getTargets

**Comment by tymfear** [comment]
@cyrus-and could you elaborate your advise, please? I tried to connect to target like this
```javascript
await client.Target.activateTarget({ targetId: 'EF8A8F415DD420DF82E85C94A7EA661C' });
```
but it still fails.

Also tried to do the same in repl with:
```javascript
Target.attachToTarget({ targetId: 'E02C351D704DBF5F35AAD118414D9A26'})
```
and 
```javascript
Target.attachToBrowserTarget('EF8A8F415DD420DF82E85C94A7EA661C')
```

Got the same results 😞

**Comment by cyrus-and** [comment]
I still don't know where you get those identifier from...

So for example if you start a regular Chrome you get:

```console
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222

DevTools listening on ws://127.0.0.1:9222/devtools/browser/52162c6f-03bc-4e62-9d10-0af19c249a6e
```

If you connect to that WebSocket and you try to use `Network.enable` you get that error:

```console
$ chrome-remote-interface inspect -w ws://127.0.0.1:9222/devtools/browser/52162c6f-03bc-4e62-9d10-0af19c249a6e
>>> Network.enable()
Uncaught ProtocolError: 'Network.enable' wasn't found
    at /Users/cyrus/Dropbox/dev/chrome-remote-interface/lib/chrome.js:93:35
    at Chrome._handleMessage (/Users/cyrus/Dropbox/dev/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket.<anonymous> (/Users/cyrus/Dropbox/dev/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:486:12)
    at Receiver.receiverOnMessage (/Users/cyrus/Dropbox/dev/chrome-remote-interface/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:486:12)
    at Receiver.dataMessage (/Users/cyrus/Dropbox/dev/chrome-remote-interface/node_modules/ws/lib/receiver.js:436:14) {
  request: { method: 'Network.enable', params: undefined },
  response: { code: -32601, message: "'Network.enable' wasn't found" }
}
```

But if you use the same WebSocket to obtain the list of targets you can pick one (or create one) and connect to it:

```console
$ chrome-remote-interface inspect -w ws://127.0.0.1:9222/devtools/browser/52162c6f-03bc-4e62-9d10-0af19c249a6e
>>> Target.getTargets()
{
  targetInfos: [
    {
      targetId: '1CFC161FCAB31D334F6B7EF54EDE5B88',
      type: 'background_page',
      title: 'uBlock Origin',
      url: 'chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/background.html',
      attached: false,
      browserContextId: '285A7C317C41D917F7EF05B56B344EAD'
    }
  ]
}

```

Then:

```console
$ chrome-remote-interface inspect 1CFC161FCAB31D334F6B7EF54EDE5B88
>>> Network.enable()
{}
```
