### ISSUE TITLE
open tab in new context

### ISSUE THREAD

**Issue by saikrishna321** [cyrus-and/chrome-remote-interface#424]
I refer to https://github.com/cyrus-and/chrome-remote-interface/wiki/Load-a-URL-in-a-separate-context-(headless-mode-only) in getting the browser to open as incognito window. How do I get to open new tab in the same context.

Currently, the new window opens on the parent window and not the separate context. @cyrus-and Can you please help here?

```
const target = await CDP.New({host, port});
    const {Page} = await CDP({host, port, target});
    await Page.enable();
    await Page.navigate({url});
```

**Comment by matjaeck** [comment]
> How do I get to open new tab in the same context.

Do you want to open a new tab in the same browser context? In this case, https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab might help?

**Comment by cyrus-and** [comment]
@saikrishna321 it's not clear what you're asking here... Basically you have two options, open a new tab:
- [in the same context](https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-a-new-tab) (as @matjaeck [suggested](https://github.com/cyrus-and/chrome-remote-interface/issues/424#issuecomment-674891060));
- [in a new/separate context](https://github.com/cyrus-and/chrome-remote-interface/wiki/Load-a-URL-in-a-separate-context-(headless-mode-only)).

There is no concept of *window* in the CDP as far as I know, so if you want to manipulate windows you need to use JavaScript.

**Comment by saikrishna321** [comment]
Sorry for not being clear on my question. I have loaded a URL in separate context by following the wiki. Now I want to open a newTab on the separate content which I just created.

**Comment by cyrus-and** [comment]
Oh, now I get it! :)

You just need to call `Target.createBrowserContext` once and store the context id:

```javascript
 const {browserContextId} = await Target.createBrowserContext();
```

Then use it multiple times for multiple invocations of `Target.createTarget`:

```javascript
const {targetId} = await Target.createTarget({
    url: 'about:blank',
    browserContextId
});
```

I hope this helps.

**Comment by saikrishna321** [comment]
Thanks @cyrus-and. This helps 👍🏻
