### ISSUE TITLE
Network.setUserAgentOverride wasn't found

### ISSUE THREAD

**Issue by shi-yan** [cyrus-and/chrome-remote-interface#425]
| Component | Version
|-|-
| Operating system	  	 	| ubuntu 18.04
| Node.js					| 14
| Chrome/Chromium/...		| chrome 84
| chrome-remote-interface	| 1.3

Is Chrome running in a container?  NO

Network.setUserAgentOverride doesn't work

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setUserAgentOverride

```
        let result = await SEND(this.ws, {
            id: this.messageId++, // Note that IDs are independent between sessions.
            method: 'Network.setUserAgentOverride',
            params: {
                userAgent: userAgent
            },
        });

```

returns

```
{ id: 4,
  error:
   { code: -32601,
     message: '\'Network.setUserAgentOverride\' wasn\'t found' } }
```

**Comment by shi-yan** [comment]
I see what's wrong, I need to pass session id.

which function call needs session id? the document doesn't seem to explain it?

**Comment by cyrus-and** [comment]
Are you even using this module?
