### ISSUE TITLE
Android Chrome - Error: socket hang up / No http response

### ISSUE THREAD

**Issue by prescience-data** [cyrus-and/chrome-remote-interface#426]
I am encountering a different but similar problem to #332 when trying connect to a **Android Chrome 85** from http or node (Win 10).

* `adb forward tcp:9222 localabstract:chrome_devtools_remote` : `9222` (ie success)
* `chrome-remote-interface inspect --host localhost --port 9222` : `Cannot connect to remote endpoint: Error: socket hang up`
* `chrome-remote-interface inspect -l --port 9222` : `Cannot connect to remote endpoint: Error: socket hang up`
* `chrome-remote-interface inspect -l` : `Cannot connect to remote endpoint: Error: socket hang up`
* `GET http://localhost:9222/json/protocol` : `localhost didn’t send any data. ERR_EMPTY_RESPONSE`

I am able to connect manually via desktop Chrome `chrome://inspect/#devices`  : 
![image](https://user-images.githubusercontent.com/65471523/92296735-e7123480-ef7a-11ea-8ac5-dab0ba70eebd.png)

Ports seem to be open and forwarding:
![image](https://user-images.githubusercontent.com/65471523/92296770-4f611600-ef7b-11ea-959e-332248e2b99b.png)

I feel like I might be potentially misunderstanding something in relation to #332 but was hoping to see if you had any ideas?

Thanks!

| Component | Version
|-|-
| Operating system	  	 	| Android / Windows 10
| Node.js					| 12.18.2
| Chrome/Chromium/...		| 85.0.4183.81
| chrome-remote-interface	| 0.28.2

Is Chrome running in a container? `No`

**Comment by cyrus-and** [comment]
If you are unable to get the list of targets with:

```console
curl http://localhost:<PORT>/json/list
```

And connect to one of those with:

```console
wscat -c ws://localhost:9222/devtools/page/<ID>
```

Then I'm afraid this is a bug in Chrome and I cannot do anything about it except assisting you in the debug process; you should file a new issue in this case.

**Comment by cyrus-and** [comment]
PS I see you commented that [old](https://bugs.chromium.org/p/chromium/issues/detail?id=824626#c8) issue, you might have more luck in filing a new one.

**Comment by cyrus-and** [comment]
What happens if you try:

```
curl http://localhost:9222/json/list
```

Remember that `/json/protocol` is not implemented in Chrome for Android.

**Comment by prescience-data** [comment]
No worries, thanks for the quick reply - I was thinking more along the lines as to finding out if anyone else currently had it working as described to figure out if it was a local/device-related issue on my end or a global issue affecting everyone etc.
For reference, no I wasn't able to get any response to `/json/list` either  :( 

![image](https://user-images.githubusercontent.com/65471523/92316432-230acf80-f037-11ea-9285-8bf5ec31b2ad.png)

**Comment by cyrus-and** [comment]
> What I found most frustrating was that Desktop Chrome is clearly connecting "somehow" but I can't figure out a way to monitor "how" it's connecting...

You can use a packet sniffer like [Wireshark](https://www.wireshark.org/) and see if there's something different in the requests issued by Desktop Chrome.

**Comment by Niek** [comment]
I just tested:
* Connect Android device over USB
* `adb forward tcp:9222 localabstract:chrome_devtools_remote`
* `chrome-remote-interface list`: works fine, I see the tab open
* `chrome-remote-interface inspect`: hangs with the same error as reported (Error: socket hang up)

Some more observations after watching Wireshark:
* CRI list call works fine (http://127.0.0.1:9222/json/list)
* CRI protocol call hangs (http://127.0.0.1:9222/json/protocol)
* Chrome skips the a protocol call, instead it goes straight to the version call (http://127.0.0.1:9222/json/version) and continues

**Comment by cyrus-and** [comment]
> It would be nice if we can skip the protocol call if it's not supported by the remote browser.

That's what the `--local` option is about.

**Comment by Niek** [comment]
> > It would be nice if we can skip the protocol call if it's not supported by the remote browser.
> 
> That's what the `--local` option is about.

I see I didn't do my research :) `chrome-remote-interface inspect -l` works fine :)

**Comment by cyrus-and** [comment]
> * `chrome-remote-interface inspect -l --port 9222` : `Cannot connect to remote endpoint: Error: socket hang up`

I thought you've already tried that?

**Comment by Niek** [comment]
> > * `chrome-remote-interface inspect -l --port 9222` : `Cannot connect to remote endpoint: Error: socket hang up`
> 
> I thought you've already tried that?

@prescience-data is a different guy, was just trying to repro and add my comments 😄

**Comment by cyrus-and** [comment]
Oh lol OK :)

**Comment by prescience-data** [comment]
Now that @Niek has confirmed working, I believe it must be some sort of tcp conflict on my environment - thanks for the help guys!

**Comment by cyrus-and** [comment]
You're welcome! Feel free to add details if you need / come up with a solution.
