### ISSUE TITLE
Not able connect using ws debug url

### ISSUE THREAD

**Issue by saikrishna321** [cyrus-and/chrome-remote-interface#428]
| Component | Version
|-|-
| Operating system	  	 	| MAC
| Node.js					| v12.11.1
| Chrome/Chromium/...		| Chromium
| chrome-remote-interface	| 0.28.2

Is Chrome running in a container? YES 

Issue: https://github.com/cyrus-and/chrome-remote-interface/issues/423

@cyrus-and I'm trying to connect to running wsDebugUrl and it fails. When I try to connect with puppeteer it works.

Can you please help me with this. I have created a sample repo to reproduce the issue. 

https://github.com/saikrishna321/taiko-selenoid

**Comment by cyrus-and** [comment]
Does it fail with an error?

**Comment by saikrishna321** [comment]
Thanks for quick response! Yes, it fails with error as the endpoint returns a response as String. When I try it outside CRI like any ws client it works fine.

**Comment by cyrus-and** [comment]
> Yes, it fails with error as the endpoint returns a response as String.

I mean, what's the error printed by:

https://github.com/saikrishna321/taiko-selenoid/blob/89eb415099bc9498a6af0524ccff9e7010f01f85/__tests__/taiko-selenoid.spec.js#L42

**Comment by cyrus-and** [comment]
Anyway, I'm not sure but the WebSocket URLs used by my local Chromium have the following format:

    ws://127.0.0.1:9222/devtools/page/8B9E802A008E154C28C672598012492D

Using `ws://127.0.0.1:9222/devtools/8B9E802A008E154C28C672598012492D` (without `page/`) yields 404.

I ask all the version in the issue template to avoid asking again and again in a comment...

**Comment by saikrishna321** [comment]
> I mean, what's the error printed by:

https://github.com/saikrishna321/taiko-selenoid/blob/89eb415099bc9498a6af0524ccff9e7010f01f85/__tests__/taiko-selenoid.spec.js#L42

```
SyntaxError: Unexpected token Y in JSON at position 0
```

**Comment by cyrus-and** [comment]
OK, it's clear, chrome-remote-interface tries to fetch the protocol from Chrome and it obtains a response which is not a valid JSON, you can try to disable that by setting the `local` option to `true`. Anyway it should work for regular Chromes.

Also you can try to manually fetch that endpoint with:

```
curl http://${selenoidUrl}:4444/json/protocol
```

**Comment by saikrishna321** [comment]
```
curl http://${selenoidUrl}:4444/json/protocol
```

```
You are using Selenoid 1.10.0!%
```
********** https://aerokube.com/selenoid/latest/#_accessing_browser_developer_tools 
```
http://127.0.0.1:4444/devtools/e327e2dd89c571f101857c9e3d64722d/json/protocol
```

This returns all the protcol API like Domain, Page ..

**Comment by cyrus-and** [comment]
This is nonstandard AFAIK, try to use that option to fetch the local version of the protocol, or just fetch the JSON once then pass it using the `protocol` option if you need fancy stuff that are not present in the local version. See the [doc](https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback).

**Comment by saikrishna321** [comment]
Thanks Cyrus! Makesense to use local protocol, but how do we make sure CRI connects to that endpoint?

**Comment by matjaeck** [comment]
> trying to connect to running wsDebugUrl

Not sure if `helful,` but I read in https://github.com/puppeteer/puppeteer/blob/v5.3.0/docs/api.md#browserwsendpoint and https://chromedevtools.github.io/devtools-protocol/#how-do-i-access-the-browser-target that format is `ws://${host}:${port}/devtools/browser/<id>` ("browser" instead of "page").

> When I try to connect with puppeteer it works.

Puppeteer docs say it* shouldn't (or I misunderstand what it is about) - maybe there is some internal puppeteer magic fixing this silently?
*  `ws://${selenoidUrl}:4444/devtools/${sessionId}`

**Comment by cyrus-and** [comment]
@saikrishna321 it should be enough to just do this:

```js
const options = {
  target: `ws://${selenoidUrl}:4444/devtools/${sessionId}`,
  // either
  local: true,
  // or
  protocol: require('./local-protocol.json')
};
CDP(options, (client) => {
  console.log('Connected!');
  client.close();
}).on('error', (err) => {
  console.error(err);
});
```

Where:

```console
$ curl http://127.0.0.1:4444/devtools/e327e2dd89c571f101857c9e3d64722d/json/protocol >local-protocol.json
```

**Comment by saikrishna321** [comment]
Thanks for all the help!
