### ISSUE TITLE
Wait-for-a-specific-element works with Chrome but Not with Firefox

### ISSUE THREAD

**Issue by lobstrio** [cyrus-and/chrome-remote-interface#429]
Receppe : https://github.com/cyrus-and/chrome-remote-interface/wiki/Wait-for-a-specific-element

This Receppe works with Chrome perfectly, but unfortunatly not with Firefox.

Backtrace : 

`(node:16228) UnhandledPromiseRejectionWarning: Error: can't access property "evaluate", context is null (evaluate@chrome://remote/content/domains/content/Runtime.jsm:262:5`

Is there a way to make it work with Firefox Nightly ? 

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu
| Node.js					| v10.22.0
| Chrome/Chromium/...		| Firefox Nightly
| chrome-remote-interface	| WRITE HERE

Is Chrome running in a container? No

**Comment by cyrus-and** [comment]
For whatever reason (possibly a Firefox bug) you ned to reload the page after attaching:

```console
$ chrome-remote-interface inspect
>>> Runtime.evaluate({expression: '1+1'})
{
  request: { method: 'Runtime.evaluate', params: { expression: '1+1' } },
  response: {
    message: `can't access property "evaluate", context is null`,
    data: 'evaluate@chrome://remote/content/domains/content/Runtime.jsm:262:5\n' +
      'execute@chrome://remote/content/domains/DomainCache.jsm:99:25\n' +
      'receiveMessage@chrome://remote/content/sessions/ContentProcessSession.jsm:86:45\n' +
      'MessageListener.receiveMessage*ContentProcessSession@chrome://remote/content/sessions/ContentProcessSession.jsm:33:25\n' +
      '@chrome://remote/content/sessions/frame-script.js:12:1\n'
  }
}
>>> Page.reload()
{}
>>> Runtime.evaluate({expression: '1+1'})
{ result: { type: 'number', value: 2 } }
```
