### ISSUE TITLE
Chrome is fingerprinted by incapsula but not firefox

### ISSUE THREAD

**Issue by lobstrio** [cyrus-and/chrome-remote-interface#430]
After a few queries to this website https://www.carrefour.fr/evenements/mobilier-de-jardin, Chrome gets presented 2 re-captchas -> one by anti bot mitigation (Datadome) which even a regular browser gets **and** another re-captcha, presented this time by Incapsula.
However, Firefox gets only presented with the first re-captcha (Datadome)

I wonder if there is a property accessible in javascript which can flag the remote-debugging protocol.

Any idea where to look to avoid being flagged by a website ? 

| Component | Version
|-|-
| Operating system	  	 	| Ubuntu
| Node.js					| v10.22.0
| Chrome/Chromium/...		| Firefox Nightly and Chrome
| chrome-remote-interface	| Last VERSION

Is Chrome running in a container?  NO

**Comment by cyrus-and** [comment]
IIRC there was a way to tell that from JavaScript but I cannot remember exactly how...

Anyway I doubt they implement such an *advanced* check, I find it more likely that the rate of requests triggered that behaviour.

By the way I see no captcha when I'm navigating that page with Chrome, either inspected or not.

**Comment by cyrus-and** [comment]
You can detect headless though, and headless basically means that Chrome is inspected. But the inverse is not true.

See [this](https://antoinevastel.com/bot%20detection/2018/01/17/detect-chrome-headless-v2.html) post about a Datadome guy.

**Comment by lobstrio** [comment]
@cyrus-and thanks for you answer.

I have tested both browsers, many times and with great scrutiny.

I can confirm that **Firefox Nightly** is the only one which does not trigger Imperva Incapsula, whereas **Chrome, Opera** will trigger a recaptcha test from Imperva Incapsula, meaning a javascript test is failing, after few requests (10 to 15 maximum) while **Firefox Nightly** will not trigger Imperva Incapsula, but only datadome check, after ~30-40 requests.

Standalone chrome is working without triggering the test. 

I'll keep you posted if I find a way to check remote debugging from javascript.

**Comment by lobstrio** [comment]
@cyrus-and  I also confirm that **I don't** run the browser headless.
