### ISSUE TITLE
Page.getResourceTree doesn't return stylesheets

### ISSUE THREAD

**Issue by Tyron199** [cyrus-and/chrome-remote-interface#432]
| Operating system	  	 	| Windows 10
| Node.js					| 10.16.3
| Chrome                         	|  86.0.4240.75
Is Chrome running in a container? NO

When i run [Page.getResourceTree
](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getResourceTree)
The returned array of [resources ](https://chromedevtools.github.io/devtools-protocol/tot/Page/#type-FrameResourceTree)does not include stylesheets. Only javascript, images and fonts.

Im trying to get a detailed outline of the website structure, the same you would find when you look at "Sources" in devtools
![Preview](https://i.imgur.com/tVJCGG6.png)

**Comment by cyrus-and** [comment]
I cannot reproduce this, if you can tell me a web site where this happens I can take a look.

Make sure that the page is loaded during the debug session, for example:

```js
await Page.navigate({url: 'https://www.ansa.it'});
await Page.loadEventFired();
const tree = await Page.getResourceTree();
```

**Comment by Tyron199** [comment]
Try with this

> I cannot reproduce this, if you can tell me a web site where this happens I can take a look.
> 
> Make sure that the page is loaded during the debug session, for example:
> 
> ```js
> await Page.navigate({url: 'https://www.ansa.it'});
> await Page.loadEventFired();
> const tree = await Page.getResourceTree();
> ```

Try this one
https://nuruerotic.com

**Comment by cyrus-and** [comment]
With the following I see style sheets, which is basically my previous suggestion.

```js
(async () => {
    const CDP = require('chrome-remote-interface');
    const client = await CDP();
    const {Network, Page} = client;
    await Page.navigate({url: 'https://nuruerotic.com/'});

    // this page rarely finishes loading so use a timeout instead of await Page.loadEventFired()
    setTimeout(async () => {
        const {frameTree: {resources}} = await Page.getResourceTree();
        console.log(resources.filter((resource) => resource.type === 'Stylesheet'));
        client.close();
    }, 3000);
})();
```
