### ISSUE TITLE
Unable to connect over port 0

### ISSUE THREAD

**Issue by steveszc** [cyrus-and/chrome-remote-interface#433]
It appears that the following logic prevents the ability to run Chrome using `--remote-debugging-port=0`, which presumably should be possible.

https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/devtools.js#L12

In the above code, the `0` port number evaluates to falsey and the default value is used instead.

**Comment by cyrus-and** [comment]
Yeah it's by design, you cannot (usually) connect to port 0. `--remote-debugging-port=0` does not make Chrome listen on the port 0, rather it does signal the kernel to pick a random port to listen to, in fact you can see it from the output, for example:

```console
$ /Applications/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=0

DevTools listening on ws://127.0.0.1:50827/devtools/browser/08755fe6-b31c-42c0-b2bc-28d86848f164
```

Then:

```console
$ chrome-remote-interface --port 50827 version
{
    "Browser": "Chrome/89.0.4327.0",
    "Protocol-Version": "1.3",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4327.0 Safari/537.36",
    "V8-Version": "8.8.278",
    "WebKit-Version": "537.36 (@c2eb9777c03357d00559ac021ca9d92a58a21af1)",
    "webSocketDebuggerUrl": "ws://127.0.0.1:50827/devtools/browser/08755fe6-b31c-42c0-b2bc-28d86848f164"
}
```
