### ISSUE TITLE
Websocket data connectivity issue with Chrome headless?

### ISSUE THREAD

**Issue by kensoh** [cyrus-and/chrome-remote-interface#436]
| Component | Version
|-|-
| Operating system	  	 | macOS 10.15.7
| Node.js					| -
| Chrome/Chromium/...		| 87.0.4280.88
| chrome-remote-interface	| -

Is Chrome running in a container? YES / ~~NO~~

Hi Cyrus, Good Day to you!

I'm maintaining 2 digital automation tools ([TagUI](https://github.com/kelaberetiv/TagUI), and [RPA for Python](https://github.com/tebelorg/RPA-Python), a Python wrapper of the former). Recently I found that TagUI is not able to receive response back from Chrome websocket connection if it is run in headless mode. But the same code works fine with visible mode. Nothing changed from my side, so I suspect something changed with Chrome.

Did some troubleshooting but not getting any clues (https://github.com/kelaberetiv/TagUI/issues/890) and have not found anything from the internet. Thought to raise an issue here to see if you or your users have run into problems with Chrome headless as well.

The gist is after a websocket message is sent, it can take more than 10 seconds for the headless Chrome process to send back the response. Running the same code with Chrome visible gets instant response.

Best Regards,
Ken

**Comment by cyrus-and** [comment]
Hi Ken! Is there a way I can easily reproduce what you're saying using `chrome-remote-interface` or plain WebSocket interaction?

For example running the [example from the README][1] in headless mode works as intended.

[1]: https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage

**Comment by kensoh** [comment]
Thanks Cyrus for your quick reply!

It seems like a situation unique with my implementation for TagUI. What happens is in headless mode, when I provide `--user-data-dir=` with a relative path it no longer works, when it used to work in the past 2 years. When I tweak the relative path provided into a full path, it works in headless mode. For visible mode, it works whether relative or absolute path is provided.

Something probably has changed with how headless Chrome behaves when the path provided is a relative path. I'll close this issue because I don't think it happens outside of the TagUI implementation. I tried replicating the issue using Python websocket but it can't be replicated. So the fix has to be an updated implementation for TagUI headless Chrome.

**Comment by kensoh** [comment]
Thanks Cyrus! Have fixed it to work for TagUI. I did by changing the user profile directory value to absolute path, and also enclose that string as follows to handle cases where the path name has spaces. Otherwise, it will break Chrome. Fyi in case your users run into this strange issue in future. The updated implementation tested to work on [Windows](https://github.com/kelaberetiv/TagUI/commit/155c64e10eef007f120ae964065f9be8d314cc9d) and [macOS/Linux](https://github.com/kelaberetiv/TagUI/issues/890#issuecomment-743958713).

```
--user-data-dir="some_variable_that_maps_to_absolute_path_of_user_profile_directory"
```

**Comment by cyrus-and** [comment]
So `--user-data-dir` must be an absolute path, good to know! The fact that the behaviour is different between headless and not it means that this is probably a bug in Chrome though...

**Comment by kensoh** [comment]
Yep, for some reason for my implementation that seems to break Chrome. Took some trial and error to figure that out, because the websocket connection is still working but response only comes back after more than 10 seconds after a send. And the issue happens for both Windows and macOS, so it couldn't have been some mac-specific OS changes.

**Comment by cyrus-and** [comment]
That's super weird, you should file an issue to Chrome.

**Comment by kensoh** [comment]
That's true... But I can't seem to replicate outside of the way I implement it for the TagUI project (invoke via shell script and use a PHP websocket library to do the communications), so I didn't raise.

When I tried testing it using Python websocket the issue isn't replicable. So, something must have changed but only affecting specific usage scenarios. Btw, Happy 2021 to you Cyrus!

**Comment by cyrus-and** [comment]
I see, hopefully people running in the same problem will find this issue.

Happy 2021 to you too! ^_^

**Comment by kensoh** [comment]
Thanks Cyrus! And thanks for accepting my LinkedIn invite :)
