### ISSUE TITLE
NET::ERR_CERT_INVALID Error

### ISSUE THREAD

**Issue by flowingfirefly** [cyrus-and/chrome-remote-interface#438]
| Component | Version
|-|-
| Operating system	  	 	| macos catalina 10.15.7
| Node.js					| v14.15.1
| Chrome/Chromium/...		| 86.0.4240.198 stable
| chrome-remote-interface	| 0.28.2

Is Chrome running in a container? NO

first，I execute this command:
`
sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
`

second, I execute this command:
`
chrome-remote-interface new "https://www.bilibili.com/video/BV1c5411L7qC"
`

I got this error in browser tab:
`
Your connection is not private
Attackers might be trying to steal your information from www.bilibili.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_INVALID
...
`

**Comment by cyrus-and** [comment]
It doesn't happen here. Do you get that error also if you manually navigate to that website?

Also, why `sudo`?

**Comment by flowingfirefly** [comment]
It's so strange, my localhost domain name point to 127.0.0.1 and [::1], some times, `chrome --remote-debugging-port=9222` bind to 127.0.0.1, some time bind to [::1]。i solved this by specify hostname use option `-t`. and if close previous opened chrome windows, no error. 

`sudo` just is an attempt, because i cannot connect to port 9222, i'm doubt no privilege. but it's useless indeed.

thank you, this project is helpful for me!

(sorry for my poor english)

**Comment by cyrus-and** [comment]
Uh, weird indeed, so can we close this?

I'm glad you can find it useful! :)

(Your english is fine!)
