### ISSUE TITLE
`sessionId` support

### ISSUE THREAD

**Issue by flotwig** [cyrus-and/chrome-remote-interface#439]
AFAIK currently, there's no way to set a `sessionId` for a single message like:

```text
{
	id: ...,
	method: '...',
	params: { ... },
	sessionId: '...'
}
```

Chrome is planning to start requiring a `sessionId` to target a page at some point in the future: https://bugs.chromium.org/p/chromium/issues/detail?id=991325

Additionally, setting a `sessionId` is important if you connect to the global websocket instead of a target-specific websocket.

So this is probably something that should be added.

A `sendRaw` function that allows manually setting the entire message object would be fine for my use case too and wouldn't require too much refactoring.

**Comment by Niek** [comment]
I switched to the `chrome-debugging-client` package since that properly supports sessionIDs.
