### ISSUE TITLE
Callback is not a function

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#44]
I am pasting an error, don't know exactly how this happened. 

/app/node_modules/chrome-remote-interface/lib/chrome.js:60
            callback();
            ^

TypeError: callback is not a function
    at WebSocket.<anonymous> (/app/node_modules/chrome-remote-interface/lib/chrome.js:60:13)
    at WebSocket.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.cleanupWebsocketResources (/app/node_modules/ws/lib/WebSocket.js:950:8)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(node:84862) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

**Comment by cyrus-and** [comment]
Can you show me how do you invoke `chrome.close()`?

**Comment by mato75** [comment]
Just as you wrote. I save chrome to objects attribute page, and then:

this.page.close();

**Comment by cyrus-and** [comment]
And it doesn't happen all the time, right?
I'm unable to reproduce this as it's the most basic invocation of `close()`.

Also, which version of Node.js are you using?

**Comment by mato75** [comment]
Node v6

**Comment by mato75** [comment]
I am getting this when in evaluate code I dispatch an event.

````
var event = document.createEvent('MouseEvent');
event.initEvent('click', true, true);
toClickElement.dispatchEvent(event);

````

**Comment by cyrus-and** [comment]
I'm unable to reproduce it as is it, the above code works as expected once injected in a page with `Runtime.evaluate`. It would be very helpful if you could provide a minimal working example that triggers this behavior (full .js, URL to load, etc.).

**Comment by mato75** [comment]
Will try to do this as soon as possible.

**Comment by cyrus-and** [comment]
> If I remove chrome.Page.loadEventFired(chrome.close);, then error doesn't occur, why?

Probably because you do not close the connection otherwise.

Without a complete example I cannot help you further, the event dispatch has the only effect of causing a page navigation which in turn causes a page load event and ultimately `chrome.close()`.

**Comment by cyrus-and** [comment]
> Could the problem be, that I am connecting chrome-remote-interface with nw.js-chromium?

Tried also with NW.js, still unable to reproduce it.

Also, just ran `make test`, all the tests pass even with NW.js.

**Comment by mato75** [comment]
I found the problem. When clicking on hyperlink it changes the location, and that causes chrome-remote-interface to lose connection to the browser. That is why I load all URL's inside of an iframe. Now we change the target of the hyperlink to the iframe, and it works. 

Do you know why would chrome-remote-interface lose connection when changing its location/url?

**Comment by mato75** [comment]
It looks like there is an issue with nw.js. Anything after 0.14.7 it is throwing this issue.

**Comment by mato75** [comment]
I see that new version 0.13 is out. Sure this error log doesn't appear in this version, but still chrome-remote-interface disconnects from nw.js. When using 0.12.3 + nwjs 0.16.1 I see this log. 

Which version of nw.js are you using?

**Comment by cyrus-and** [comment]
> Which nw.js version are you using?

I'm using NW.js v0.16.1.

If your code contains `chrome.Page.loadEventFired(chrome.close);`, as you said, chrome-remote-interface will disconnect from NW.js at the next page re/load.

**Comment by mato75** [comment]
If I remove this line, will chrome remote interface disconnect only when I call .close, or never?

**Comment by cyrus-and** [comment]
Yes, sure, it will still disconnect when you call `chrome.close()`. That line basically means "whenever a `Page.loadEventFired` event arrives, close the connection", it is equivalent to:

```js
chrome.Page.loadEventFired(function () {
    // things to do when a Page.loadEventFired event arrives...
    chrome.close();
});
```

**Comment by cyrus-and** [comment]
OK so I finally figured out what happened. I'm writing here for the record.

* The `close()` call has been made asynchronous in 2ed9999842d79a049cce64f2b25ec5c8d13d2bb5 (v0.12.3), this implementation though had a bug which prevented to use `chrome.close()` in contexts like `chrome.Page.loadEventFired(chrome.close)` where the calling function passes an object to `chrome.close()` which was mistakenly interpreted as a callback. Basically causing what you reported in this issue.

* The fix landed in 1997b505afca4adbd5c34d42b2c284de8699c445 (v0.13.0).

* Also, to recap: the disconnection on `Page.loadEventFired` is the intended behavior if `chrome.Page.loadEventFired(chrome.close)` is used.

Next time please make sure check out the latest version, or even better, the master branch before opening a new issue, thank you.

**Comment by mato75** [comment]
Thx. Sorry, just one more question. When is loadEventFired triggered (when a new page is loaded, ...)?

**Comment by cyrus-and** [comment]
When any page in the current tab finished loading, i.e., due to page refreshes or user navigation.
