### ISSUE TITLE
[Feature request] Add .on method for each domainName

### ISSUE THREAD

**Issue by JonWallsten** [cyrus-and/chrome-remote-interface#443]
I understand that this is kind of redundant, but it would make the usage more consistent with the protocol and we could use the types from:
https://github.com/ChromeDevTools/devtools-protocol/blob/a5b6b3ebc9922bf681fbd260cb0f8bdc75fb067b/types/protocol-proxy-api.d.ts to enhance the experience for our devs.

`devtools-protocol` provide the typed events like this:
![image](https://user-images.githubusercontent.com/5993909/103748081-e14d5e00-5003-11eb-8729-f3da27b45be4.png)

So if each "domain" had an `on` method where you could provide `eventName` you could choose if you'd like to call `Domain.event(() => {})` or `Domain.on('event',  () => {})`

Something like this:
```
function prepare(object, protocol) {
    // assign the protocol and generate the shorthands
    object.protocol = protocol;
    protocol.domains.forEach((domain) => {
        const domainName = domain.domain;
        object[domainName] = {};
        // add commands
        (domain.commands || []).forEach((command) => {
            addCommand(object, domainName, command);
        });
        // add events
        (domain.events || []).forEach((event) => {
            addEvent(object, domainName, event);
        });
        // add types
        (domain.types || []).forEach((type) => {
            addType(object, domainName, type);
        });

        const handler = (eventName, handler) => {
            if (typeof handler === 'function') {
                object.on(eventName, handler);
                return () => object.removeListener(eventName, handler);
            } else {
                return new Promise((fulfill, reject) => {
                    object.once(eventName, fulfill);
                });
            }
        };

        domain.on = handler;
    });
}
```

It already looks like this in our editor, but the issue is of course that the method doesn't exist in runtime.
![image](https://user-images.githubusercontent.com/5993909/103749545-e90e0200-5005-11eb-9db9-3d612661ebea.png)

I can provide a PR if it's something you'd approve of, or else you can just close this issue.
Thanks!

**Comment by cyrus-and** [comment]
Sure open a PR we'll start from that. Thanks!
