### ISSUE TITLE
No inspectable targets when connecting to multiple instances of chrome

### ISSUE THREAD

**Issue by SwitchGM** [cyrus-and/chrome-remote-interface#445]
| Component | Version
|-|-
| Operating system	  	 	| win10
| Node.js					| 12.16.1
| Chrome/Chromium/...		| 87 ,using chrome-launcher 0.13.4
| chrome-remote-interface	| 0.29.0

Is Chrome running in a container? NO

I've got some very basic code that launches multiple instances of chrome and connects each with CDP to an individual chrome's debugging port (all the debugging ports are different). Usually when trying to do this with 15 instances of chrome, I recieve this error

*(node:20388) UnhandledPromiseRejectionWarning: Error: No inspectable targets
    at defaultTarget (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:48:23)
    at Chrome._fetchDebuggerURL (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:192:28)
    at async Chrome._start (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:139:25)
(node:20388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise 
rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.*

I have not been able to determine **yet** where in my program this error is being thrown. This error does not always come up, for example running 10 instances of chrome will usually be fine and on occassion throw this error. When attempting to run 11 this is where I start getting errors more often. 

EDIT: It seems that the error is being thrown when setting up CDP at

`let client = await CDP({ port: WHATEVER_PORT_CHROME_USED });`

EDIT 2: The chrome instances aren't failing on the same port, maybe it's due to me doing this asynchronously ???

EDIT 3: Tried firing up 20 chrome instances consecutivley with absoloutly no problem, definatly seems like an issue to asynchronously several of these instancesas the same time. (To be clear, I am first launching chrome and then launching CDP inside inside of an async function, and then proceeding to run this async function x' number of times asynchronously for as many instances as I want using `Promise#All`)

**Comment by cyrus-and** [comment]
It's hard to say without looking at the code.

**Comment by SwitchGM** [comment]
Apologies, the issue seems to have somehow resolved itself :/ If it comes up i'll reopen the ticket with the relevant code.

**Comment by SwitchGM** [comment]
Well, it seems as if I have re-run into the same issue. Before this happened, I was able to consistantly run around 100 headless chrome instances perfectly and test each, for some reason trying now has given me the error:

`
Error: No inspectable targets
    at defaultTarget (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:48:23)
    at Chrome._fetchDebuggerURL (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:192:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Chrome._start (C:\Users\joe\src\m3rl1n\node_modules\chrome-remote-interface\lib\chrome.js:139:25)
`

To make clear, the error is being thrown when calling the CDP function, catching the error obviously cascades into other parts of the program, ie; in trying to navigate when calling #test(), this.Page is undefined.

`javascript
this.client = await CDP({ port: this.chrome.port }).catch((error) => {
            // here is where we are getting the error !
            console.log("error on setting up CDP !");
            console.log(error);
        });
`

This error does not seem to occur when creating a small number of "headless chrome's", something like 5 seems to work perfectly. For larger number 10+ the errors seem to throw more frequently.

Here's the entire code:

`javascript
const chromeLauncher = require("chrome-launcher");
const CDP = require("chrome-remote-interface");


class HeadlessChrome {
    constructor(proxyOpt) {
        this.proxyOpt = proxyOpt;
        // proxyOpt.ip -> proxy ip
        // proxyOpt.port -> proxy port
        // proxyOpt.auth.username -> proxy username for auth
        // proxyOpt.auth.password -> proxy password for auth
    }

    async start() {
        await this._setupHeadlessChrome();
    }

    async stop() {
        await this.chrome.kill();
    }

    async test() {
        await this.Page.navigate({url: "https://whatismyip.akamai.com/"});
        await this.Page.loadEventFired();

        const { result: { value }} = await this.Runtime.evaluate({
            expression: 'document.body.innerHTML'
        });

        return value;
    }

    async _setupHeadlessChrome() {
        this.chrome = await chromeLauncher.launch({
            chromeFlags: [
                "--headless",
                "--disable-gpu",
                "--enable-logging",
                this.proxyOpt ? `--proxy-server=${this.proxyOpt.ip}:${this.proxyOpt.port}` : ""
            ]
        });

        this.client = await CDP({ port: this.chrome.port }).catch((error) => {
            // here is where we are getting the error !
            console.log("error on setting up CDP !");
            console.log(error);
        });
        this.Page = this.client.Page; 
        this.Fetch = this.client.Fetch; 
        this.Network = this.client.Network; 
        this.Runtime = this.client.Runtime; 
        this.Security = this.client.Security;

        this._setupStartOptions();

        await Promise.all([
            this.Page.enable(),
            this.Fetch.enable({ handleAuthRequests: true }),
            this.Network.enable(),
            this.Runtime.enable(),
            this.Security.enable(),
            this.Security.setOverrideCertificateErrors({override: true})
        ]);
    }

    _setupStartOptions() {
        this.Security.certificateError(({eventId}) => {
            this.Security.handleCertificateError({ 
                eventId, 
                action: 'continue' 
            });
        });
    
        this.Fetch.requestPaused(({requestId}) => {
            this.Fetch.continueRequest({requestId})
            .catch(() => { 
                    return; 
                }
            );
        });
    
        this.Fetch.authRequired(({requestId}) => {
            this.Fetch.continueWithAuth({
                requestId, 
                authChallengeResponse: { 
                    response: 'ProvideCredentials', 
                    ...this.proxyOpt.auth 
                }
            });
        });
    }
}

(async function() {
    
    let numberOfHeadlessChromes = 10;

    let proxyInfo = []; // list of proxy info objects
    let headlessChromes = [];
    for (let i = 0; i < numberOfHeadlessChromes; i++) {
        headlessChromes.push(new HeadlessChrome(proxyInfo[i]));
    }

    console.log("starting headless chromes...");

    await Promise.all(headlessChromes.map((headless) => {
        return headless.start();
    }));

    console.log("testing headless chromes...");

    let headlessIps = await Promise.all(headlessChromes.map((headless) => {
        return headless.test();
    }));

    console.log("finished testing");
    console.log(headlessIps);
    console.log("closing headless chromes...");

    await Promise.all(headlessChromes.map((headless) => {
        return headless.close();
    }));
})();
`

**Comment by cyrus-and** [comment]
In the meanwhile, why do you need to spawn so many Chrome instances? I mean why not just use tabs or [BrowserContext](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext)s?

Anyway, that error originates here:

https://github.com/cyrus-and/chrome-remote-interface/blob/699d7938c6d52c247993cd4284433eccb9ebedc4/lib/chrome.js#L31-L50

Meaning that at that moment there are targets returned by querying `/json/list` I suspect this is because the machine is super busy trying to spawn so many Chrome instances and the new tab page is simply not yet loaded, you could solve this by implementing a retry mechanism for `CDP()`, something like [this](https://github.com/cyrus-and/chrome-remote-interface/wiki/Delayed-connection-attempts).

**Comment by cyrus-and** [comment]
To debug this you can print the port of the failing instances and then try to manually visit `http://localhost:PORT/json/list` and see what's there, if you see a JSON list then it would confirm the above supposition.

**Comment by SwitchGM** [comment]
Connecting manually does show some json, so I would assume that the machine *is* too busy. As for why, I'm trying to use several proxies at a time, as well as scraping from multiple pages simultanously. With CDP right now, I assume you're not able connect to multiple proxies per browser, let alone navigate to multiple web pages at the same time and get content from each asynchronously ?

**Comment by cyrus-and** [comment]
> With CDP right now, I assume you're not able connect to multiple proxies per browser, let alone navigate to multiple web pages at the same time and get content from each asynchronously ?

Eh, I guess not.

I would do two things:
- implement a delayed connection attempt as I said before;
- implement a pool of Chrome instances, e.g., if you need to test N proxies you create a pool so that only K < N are running simultaneously.

**Comment by cyrus-and** [comment]
> Eh, I guess not.

Wrong. I just noticed this guy here: [Target.createBrowserContext](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext) that accepts a `proxyServer` option.

**Comment by cyrus-and** [comment]
FYI I confirm my suspicions:

```javascript
const chromeLauncher = require("chrome-launcher");
const CDP = require("chrome-remote-interface");

async function seconds(n) {
    return new Promise((fulfill) => {
        setTimeout(fulfill, n * 1000);
    });
}

async function connect(port) {
    try {
        return await CDP({port});
    } catch (err) {
        console.log(`Retrying on port ${port}`);
        await seconds(1);
        return connect(port);
    }
}

async function runChromeAndDoStuff() {
    const chrome = await chromeLauncher.launch({
            chromeFlags: [
                '--headless',
                '--disable-gpu',
            ]
    });

    try {
        ////////////////////////////////////////////////////////////
        const client = await CDP({port: chrome.port}); // ERROR
        // const client = await connect(chrome.port); // OK
        ////////////////////////////////////////////////////////////

        const {Target} = client;
        const targets = await Target.getTargets();
        console.log(chrome.port, targets.targetInfos[0].url);

        await chrome.kill();
    } catch (err) {
        console.log(chrome.port, err);
    }
}

for (let i = 0; i < 10; i++) {
    runChromeAndDoStuff();
}
```

Here on macOS 10 concurrent instances is enough to trigger the error, the solution of performing a delayed attempt it works.

**Comment by cyrus-and** [comment]
> I just noticed this guy here: [Target.createBrowserContext](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext) that accepts a `proxyServer` option.

Boring-bad-weather-covid sunday, so here's the code. For each proxy entry it spawns a new `BrowserContext` and run the `testCode`. I've successfully tried it with hundreds of proxy entries simultaneously, it appears to work. Hope it helps.

```javascript
const CDP = require("chrome-remote-interface");
const chromeLauncher = require("chrome-launcher");

async function createProxiedClients(port, proxyServers, testCode) {
    // fetch the DevTools browser target
    const {webSocketDebuggerUrl} = await CDP.Version({port});

    // connect to the DevTools browser target
    const browser = await CDP({
        target: webSocketDebuggerUrl
    });
    const {Target} = browser;

    // create the clients
    const asyncClients = proxyServers.map(async (proxyServer) => {
        // create a new context
        const {browserContextId} = await Target.createBrowserContext({
            proxyServer,
            disposeOnDetach: true
        });

        // create a target for it
        const {targetId} = await Target.createTarget({
            url: 'about:blank',
            browserContextId
        });

        // connct to the target
        const client = await CDP({
            port,
            target: targetId
        });

        // run test code
        await testCode(client);
        await client.close();
    });

    // wait for all the tests to complete
    const clients = await Promise.all(asyncClients);

    // done with the browser target
    await browser.close();
}

async function testCode(client) {
    const {Page} = client;
    await Page.enable();
    await Page.navigate({url: 'http://example.com'});
    await Page.loadEventFired();
}

async function start() {
    const chrome = await chromeLauncher.launch({
        chromeFlags: [
            '--headless',
            '--disable-gpu',
        ]
    });

    const proxyServers = [
        'http://localhost:8080',
        // ...
    ];

    await createProxiedClients(chrome.port, proxyServers, testCode);

    chrome.kill();
}

start();
```

**Comment by SwitchGM** [comment]
This is exactly what I've been looking for, and works perfectly for the project i'm working on! Would you be aware of a method to authenticate for the individual proxies (user and pass), I would assume that this is similar to the code you provided a while back in #442 inside of ```testCode```?

**Comment by cyrus-and** [comment]
Yeah, I guess you can use the `origin` field of the `authChallenge` parameter, something like this (untested):

```javascript
const PROXIES = {
    'http://localhost:8080': {
        username: '...',
        password: '...'
    }
};

// ...

Fetch.authRequired(({requestId, {origin}}) => {
    const proxyAuth = PROXIES[origin];
    if (!proxyAuth) {
        return;
    }

    Fetch.continueWithAuth({
        requestId,
        authChallengeResponse: {
            response: 'ProvideCredentials',
            ...proxyAuth
        }
    });
});
```

Where `PROXIES` is also used to `createProxiedClients` above.

**Comment by SwitchGM** [comment]
I've been trying to use your public proxy code to get started with, and I'm having issues. In order to test that the proxies work, I check the IP from https://www.ionos.co.uk/tools/ip-address, as https://whatismyip.akamai.com/ no longer seems to work ? In each case, my IP address is returned. 

To get a better understanding of how the browser contexts work, I'm trying this with just one browser context and using a public proxy. 

Here is the basic code that I'm using. I can use the proxy just fine in a non-headless chrome with `chrome --proxy-server=128.199.162.224:8888`, but I don't seem to be able to use the proxy server when creating a browser context ?

```javascript
const CDP = require("chrome-remote-interface");
const chromeLauncher = require("chrome-launcher");

const proxyIP = "http://128.199.162.224:8888";

(async function() {
    console.log("launching chrome...");
    let chrome = await chromeLauncher.launch({
        chromeFlags: [
            "--headless",
            "--disable-gpu"
        ]
    });

    console.log("CDP version...");
    let {webSocketDebuggerUrl} = await CDP.Version({port: chrome.port});
    console.log("CDP browser...");
    let browser = await CDP({target: webSocketDebuggerUrl});
    let {Target} = browser;
    console.log("creating browser context...");
    let {browserContextId} = await Target.createBrowserContext({
        proxyServer: proxyIP,
        disposeOnDetach: true
    });

    console.log("creating target..");
    let {targetId} = await Target.createTarget({
        url: "about:blank",
        browserContextId
    });

    console.log("creating client...");
    let client = await CDP({
        port: chrome.port,
        target: targetId
    });

    let {Page, Runtime, Security, Fetch} = client;

    console.log("enabling...");
    await Page.enable();
    await Runtime.enable();

    console.log("navigating to page...");
    await Page.navigate({url: "https://www.ionos.co.uk/tools/ip-address"});
    console.log("loaded...");
    await Page.loadEventFired();

    const a = await Runtime.evaluate({
        expression: 'document.querySelector("#content > div:nth-child(2) > div.text-md-center.text-lg-center.heading-1.ml-md-0.ml-lg-0.mw-lg-10.mw-md-10.mx-md-auto.mx-lg-auto.pt-12").innerHTML'
    });

    console.log("IP", a);
    console.log("closing...");

    await client.close();
    await browser.close();
    await chrome.kill();
    console.log("finished");
})();
```

**Comment by cyrus-and** [comment]
That works for me (using another proxy), I suspect it's how Windows handle proxy connections at the OS level. But have we already fixed that in #442?

**Comment by SwitchGM** [comment]
I'm pretty sure we sorted that out ? I've copied your code exactly, and used the proxy (changed the testing code to see the IP address). How exactly did you test that the proxies were actually being used ?
```javascript
const CDP = require("chrome-remote-interface");
const chromeLauncher = require("chrome-launcher");

async function createProxiedClients(port, proxyServers, testCode) {
    // fetch the DevTools browser target
    const {webSocketDebuggerUrl} = await CDP.Version({port});

    // connect to the DevTools browser target
    const browser = await CDP({
        target: webSocketDebuggerUrl
    });
    const {Target} = browser;

    // create the clients
    const asyncClients = proxyServers.map(async (proxyServer) => {
        // create a new context
        const {browserContextId} = await Target.createBrowserContext({
            proxyServer,
            disposeOnDetach: true
        });

        // create a target for it
        const {targetId} = await Target.createTarget({
            url: 'about:blank',
            browserContextId
        });

        // connct to the target
        const client = await CDP({
            port,
            target: targetId
        });

        // run test code
        await testCode(client);
        await client.close();
    });

    // wait for all the tests to complete
    const clients = await Promise.all(asyncClients);

    // done with the browser target
    await browser.close();
}

async function testCode(client) {
    const {Page, Runtime} = client;
    await Page.enable();
    await Runtime.enable();
    await Page.navigate({url: 'https://www.ionos.co.uk/tools/ip-address'});
    await Page.loadEventFired();
    let result = await Runtime.evaluate({
        expression: 'document.querySelector("#content > div:nth-child(2) > div.text-md-center.text-lg-center.heading-1.ml-md-0.ml-lg-0.mw-lg-10.mw-md-10.mx-md-auto.mx-lg-auto.pt-12").innerHTML'
    });
    console.log(result);
}

async function start() {
    const chrome = await chromeLauncher.launch({
        chromeFlags: [
            '--headless',
            '--disable-gpu',
        ]
    });

    const proxyServers = [
        '128.199.162.224:8888'
    ];

    await createProxiedClients(chrome.port, proxyServers, testCode);

    chrome.kill();
}

start();
```

**Comment by cyrus-and** [comment]
> How exactly did you test that the proxies were actually being used ?

I both use TOR (but it's a SOCKS proxy) and [Burp Suite](https://portswigger.net/burp/communitydownload) (to test HTTP, just to be sure). In both cases it works, but I always specify the scheme (I'm on macOS).

Also, as we already noticed, you need to handle certificate errors for HTTPS web sites, like the one that you're using to check the IP. Both http://whatismyip.akamai.com and http://ifconfig.me works for me.

**Comment by SwitchGM** [comment]
I'm at a bit of a loss then, I've tried both http://whatismyip.akamai.com, and http://ifconfig.me, and both return my IP. Could you suggest anything that may help me move forward from here ? Browser contexts seem like the best option, instead of creating multiple (individual) instances of chrome.

**Comment by cyrus-and** [comment]
I'd ditch Windows but... In any case can you please summarise what does work for you?

Also try to manually start Chrome from the command line passing the `--proxy-server=` option, try to make it work first, without adding the additional JavaScript layer of uncertainty.

**Comment by SwitchGM** [comment]
I'm able to connect to proxy servers just fine when launching with chrome and using the `--proxy-server` option, I'm also able to manually connect to the proxy using the `--proxy-server` option, running the command `chrome --proxy-server=IP:PORT`. I'm also able to nagivate to webpages using the browser context method that we've been talking about, but I'm not able to use (or it doesn't seem to do anything), when passing a proxy server in 

```javascript
const {browserContextId} = await Target.createBrowserContext({
            proxyServer,
            disposeOnDetach: true
        });
```

**Comment by cyrus-and** [comment]
You might want to file an [upstream issue](https://crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), or even in the [devtools-protocol](https://github.com/chromedevtools/devtools-protocol) repo. Make sure to specify that you're using Windows. It could also be useful to try the same code to Linux (it should be fairly easy to set up a VM) or macOS to see the difference.

**Comment by SwitchGM** [comment]
I'll check that out and see what I can do. Do you think there could be a difference in running this inside a docker container ?

**Comment by cyrus-and** [comment]
There shouldn't be any difference, the only thing is that if you experience weird crashes in Chrome try to increase the container's shared memory.

**Comment by SwitchGM** [comment]
Alrighty, thanks for all the help with this

**Comment by cyrus-and** [comment]
No worries! Feel free to keep me posted.

Good luck!
