### ISSUE TITLE
[Q][CLI] How do I run the inspect command with a string of code?

### ISSUE THREAD

**Issue by NightMachinary** [cyrus-and/chrome-remote-interface#447]
I want to get the currently active tab. I have tried:
```
❯ echo "Runtime.evaluate({expression: 'window.location.toString()'})" | chrome-remote-interface --port 8953 inspect
>>> Runtime.evaluate({expression: 'window.location.toString()'})

{
  result: {
    type: 'string',
    value: 'https://github.com/cyrus-and/chrome-remote-interface/issues/new'
  }
}
>>>
```
This output is not exactly clean. It also breaks if I pipe it:
```
❯ echo "Runtime.evaluate({expression: 'window.location.toString()'})" | chrome-remote-interface --port 8953 inspect |cat   
>>> /usr/local/lib/node_modules/chrome-remote-interface/bin/client.js:94
                    cdpRepl.history.push(entry);
                                    ^

TypeError: Cannot read property 'push' of undefined
    at /usr/local/lib/node_modules/chrome-remote-interface/bin/client.js:94:37
    at Array.forEach (<anonymous>)
    at loadHistory (/usr/local/lib/node_modules/chrome-remote-interface/bin/client.js:93:18)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/chrome-remote-interface/bin/client.js:123:9)
    at Object.onceWrapper (node:events:483:26)
    at EventEmitter.emit (node:events:376:20)
    at EventEmitter.emit (node:domain:470:12)
    at /usr/local/lib/node_modules/chrome-remote-interface/lib/chrome.js:157:32
    at processTicksAndRejections (node:internal/process/task_queues:75:11)
```

**Comment by cyrus-and** [comment]
The bundled client is not really meant for *scripting*, consider using the JavaScript library.

Having said that, you're right, it should behave differently, let me fix that.

Yet I cannot reproduce the crash.

**Comment by cyrus-and** [comment]
OK, give it a try now.

**Comment by NightMachinary** [comment]
[**@cyrus-and**](https://github.com/cyrus-and) commented on [Mar 3, 2021, 11:46 PM GMT+3:30](https://github.com/cyrus-and/chrome-remote-interface/issues/447#issuecomment-790026199 "2021-03-03T20:16:24Z - Replied by Github Reply Comments"):
> OK, give it a try now.

I could not install from master, there were errors. How would I get the active tab's info from the JS API? Running a node script is not difficult.

**Comment by cyrus-and** [comment]
> I could not install from master, there were errors.

I cannot help you if you don't tell me which errors...

> How would I get the active tab's info from the JS API?

In the same, way just wrapped in the usual setup code (see the [example](https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage)).

**Comment by NightMachinary** [comment]
> In the same, way just wrapped in the usual setup code (see the [example](https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage)).

After importing `const CDP = require('chrome-remote-interface');`, where is `Runtime`? `CDP.Runtime`?

**Comment by cyrus-and** [comment]
`Runtime` is a domain just like `Network` and `Page` in the above example.

**Comment by NightMachinary** [comment]
@cyrus-and Thanks!

**Comment by NightMachinary** [comment]
BTW, the errors were for `webpack`, though I am now going to use the latest stable anyway:
```
npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /usr/local/Cellar/node/15.4.0/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/evar/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /Users/evar/.npm/_cacache/tmp/git-clone-e74c1d63
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c webpack
npm ERR! npm ERR! sh: webpack: command not found
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/evar/.npm/_logs/2021-03-04T14_01_54_717Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/evar/.npm/_logs/2021-03-04T14_01_54_789Z-debug.log
```

**Comment by cyrus-and** [comment]
Oh that's weird, is this after a `npm install`? It's weird because `webpack` itself is fetched as a dependency. Also, I cannot reproduce this.
