### ISSUE TITLE
How I can check the current chrome tab url?

### ISSUE THREAD

**Issue by zydjohnHotmail** [cyrus-and/chrome-remote-interface#449]
| Component | Version
|-|-
| Operating system	  	 	| Windows 10 (Version 20H2)
| Node.js					| 15.10.0(x64) for Windows
| Chrome/Chromium/...		| Version 89.0.4389.82 (Official Build) (64-bit)
| chrome-remote-interface	| 0.29.0 

Is Chrome running in a container? NO
Hello:
I am new to chrome-remote-interface. Now I have a question: how I can check the current active tab url?
First, I open chrome with remote debug port enabled:
C:> chrome --remote-debugging-port=9222
Second, I visit one web site, like: https://www.bing.com/
Now, I have only one active tab, it is now at the url: https://www.bing.com/
Third, I install chrome-remote-interface npm version 0.29.
C:\Temp> npm install chrome-remote-interface
Now, which command under chrome-remote-interface command line, I can find what is the only active tab's url?
In my case, it is https://www.bing.com/.
Further more, if I have 2 tabs in chrome browser, one is https://www.bing.com/, another is https://www.google.com/
Then how I can find which tab's url is https://www.bing.com/, and which one's url is: https://www.google.com/
Do you have any API documents for this?
Thanks,

**Comment by cyrus-and** [comment]
> Now, which command under chrome-remote-interface command line, I can find what is the only active tab's url?

Commands are the same in both the command line interface and the library and they are part of the [protocol][]. In the command line client you can simply:

```console
$ chome-remote-interface inspect
>>> Target.getTargetInfo().then(({targetInfo}) => console.log(targetInfo.url))
https://www.bing.com/
```

> Then how I can find which tab's url is https://www.bing.com/, and which one's url is: https://www.google.com/

You can list all the targets with `chome-remote-interface list` or using the protocol itself:

```console
$ chome-remote-interface inspect
>>> Target.getTargets()
{
  targetInfos: [
    {
      targetId: '84B71B33A0531D32E8E6C6BF9A194528',
      type: 'page',
      title: 'Google',
      url: 'https://www.google.com/',
      attached: true,
      canAccessOpener: false,
      browserContextId: '4251CBFCBF814E1029FAE078AE37569A'
    },
    {
      targetId: 'DE9151AFDA66F82992D5A9445811D43D',
      type: 'page',
      title: 'Bing',
      url: 'https://www.bing.com/',
      attached: false,
      canAccessOpener: false,
      browserContextId: '4251CBFCBF814E1029FAE078AE37569A'
    }
  ]
}
```

> Do you have any API documents for this?

The [protocol][], the [wiki][], the [existing issues][], and a lot of trial and error is all you need. The command line utility is there just for convenience and debugging, you're encouraged to write your own applications, start from the [example][] in the README.

Hope it helps, and good luck! 

[protocol]: https://chromedevtools.github.io/devtools-protocol/
[wiki]: https://github.com/cyrus-and/chrome-remote-interface/wiki
[existing issues]: https://github.com/cyrus-and/chrome-remote-interface/issues?q=is%3Aissue+label%3Aquestion
[example]: https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage

**Comment by zydjohnHotmail** [comment]
Thanks, I will do some testing first!

**Comment by snowman** [comment]
Firefox does NOT work, while `Chrome` return expected data

see also same report here: https://github.com/getgauge/taiko/discussions/2160
