### ISSUE TITLE
Connect to mobail on USB

### ISSUE THREAD

**Issue by zirill** [cyrus-and/chrome-remote-interface#45]
Hello, how can I connect to the chrome in the phone via usb or emulator android on hyper-v?

**Comment by cyrus-and** [comment]
For both real devices via USB and emulators via AVD Manager you need to [forward the port 9222][1]:

    adb forward tcp:9222 localabstract:chrome_devtools_remote

Then use `localhost:9222` as usual.

[1]: https://developer.chrome.com/devtools/docs/remote-debugging-legacy

**Comment by zirill** [comment]
Possible to use a multi connection to two or more virtual machines?

**Comment by cyrus-and** [comment]
You need one [instance](https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback) for each virtual machine.

**Comment by zirill** [comment]
i run two emulator

after command
"adb forward tcp:9222 localabstract:chrome_devtools_remote"

message: "error: more then one device/emulator"

**Comment by cyrus-and** [comment]
That happens because you need to specify the target device with the `-s <specific device>` option. From `adb help`:

> directs command to the device or emulator with the given serial number or qualifier. Overrides ANDROID_SERIAL environment variable.

1. List your devices:

        $ adb devices
        List of devices attached
        emulator-5556	device
        emulator-5554	device

2. Issue a command to each of them:

        $ adb -s emulator-5556 forward tcp:9222 localabstract:chrome_devtools_remote
        $ adb -s emulator-5554 forward tcp:9222 localabstract:chrome_devtools_remote

**Comment by auchenberg** [comment]
I've written a Node module that can help with this, https://github.com/auchenberg/adb-devtools-devices
