### ISSUE TITLE
Can I use chrome-remote-interface to launch chrome extension again?

### ISSUE THREAD

**Issue by zydjohnHotmail** [cyrus-and/chrome-remote-interface#450]
| Component | Version
|-|-
| Operating system	  	 	| Windows 10 (Version 20H2)
| Node.js					| 15.10.0(x64) for Windows
| Chrome/Chromium/...		| Version 89.0.4389.82 (Official Build) (64-bit)
| chrome-remote-interface	| 0.29.0

Is Chrome running in a container? NO
Hello:
I have 2 chrome extensions to be used for 2 different web sites.  They both parse the current page DOM and send the parsed data to a localhost http server.  The extensions use window.setInterval to repeat the DOM parse action every a few seconds.
However, the issue is: from time to time, they both stop due to unknown reason, the window.setInterval simply stops working.  Some times, it works for only a few minutes, some times, it works for more than 9 hours without issue.  I can manually solve the issue by reload the underlying tab, and click on the extension icon to launch the extension again.
I want to know if I can use chrome-remote-interface to launch the chrome extensions again?
For example, if the extension1 has a unique ID#1, and the extension2 has a unique ID#2 from chrome://extensions/
Show me some code samples to launch chrome extensions ID#1 or ID#2.
Further more, as I don’t want to use 2 extensions in one browser, can I use extension ID#1 on chrome, and ID#2 on Edge (chrome based)? The code to launch chrome extension in both chrome and Edge (chrome based) is the same?

**Comment by cyrus-and** [comment]
> I want to know if I can use chrome-remote-interface to launch the chrome extensions again?

I don't think that's possible. But you can try to rewrite those extensions' logic using the [CDP][] with chrome-remote-interface.

[CDP]: https://chromedevtools.github.io/devtools-protocol/

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply. I try to see if I can rewrite the content.js to be used in CDP.
However, as my content.js used jquery to parse DOM.  I can't find any code example which I can use jquery in CDP domain, like runtime.runscript; if it is not possible, then I will try to rewrite my content.js using ordinary JavaScript.
However, my concern is: I have to run such content.js in CDP quite often, like every 10 second each time, is it good or bad for CDP?

**Comment by cyrus-and** [comment]
Well you can use the function provided by the protocol to access the [DOM][], consider that what you can do with chrome-remote-interface is as powerful as DevTools.

If you find interacting with the DOM domain to cumbersome you can always, as you say, inject plain JavaScript in the page being inspected like this:

```js
await Page.enable();
await Page.navigate({url:'https://example.com'});
await Page.loadEventFired();

const {result} = await Runtime.evaluate({
    expression: `document.querySelector('h1').innerText`
});

console.log(result.value); // Example Domain
```

> have to run such content.js in CDP quite often, like every 10 second each time, is it good or bad for CDP?

It doesn't really matter. I'm not aware of your use case, but it's probably better to listen for DOM events and act accordingly.

[DOM]: https://chromedevtools.github.io/devtools-protocol/tot/DOM/

**Comment by zydjohnHotmail** [comment]
Hello:
Here is the important part: 
expression: `document.querySelector('h1').innerText`
As my content.js is a little bit complicated, it is around 20 lines of jquery code, then give me an idea on how to use a JavaScript function to replace the expression value in your code example.
My content.js has the following jquery code (most of part is here):
  var json_data = [];
  $('.table.table-sm tr').each(function(){
  var currentRow=$(this).closest('tr'); 
  var cell1 = currentRow.find('td:eq(0)');
  var link1 = cell1.find('a').attr('href');
  var split1 = link1.split('/');
  var id1 = split1[2];
  var name1 = cell1.text();
  var cell2 = currentRow.find('td:eq(1)');
  var gmt1 = cell2.data('dt');
  var cell3_text = currentRow.find('td:eq(2)').text();
  var split_data = cell3_text.split(' # ');
  var cell5 = currentRow.find('td:eq(4)');
  var link5 = cell5.find('a').attr('href');
  var split_link = link5.split('/');
  var data1 = ({'ID': id1, 'Name': name1, 'GMT': gmt1, 'Link': split_link[1] });
  json_data.push(data1);
Thanks,

**Comment by cyrus-and** [comment]
You can put there whatever JavaScript you want.

**Comment by zydjohnHotmail** [comment]
Hi,
I want to know: if I put all the code inside `...`, then it is ugly.
Can I make a function, like: myFunction(), and put all the code inside myFunction.
Then, how I can call it? 
Like this: 
const {result} = await Runtime.evaluate({
    expression: myFunction
});
No idea about the syntax.
Please advise!

**Comment by cyrus-and** [comment]
You can put all the code in a separate file, then read that file into a variable, and pass that variable as `expression`.

**Comment by zydjohnHotmail** [comment]
Hi:
How I can read a file into a variable?  Using npm fs package?
Do you have any code sample for this?

**Comment by cyrus-and** [comment]
How about Googling that?
