### ISSUE TITLE
Incorrect encoding on redirect headers

### ISSUE THREAD

**Issue by ajimix** [cyrus-and/chrome-remote-interface#452]
| Component | Version
|-|-
| Operating system	  	 	| Tested on MacOS (latest) and Ubuntu 18
| Node.js					| Tested on 14.15
| Chrome/Chromium/...		| Tested on Chrome 89.0.4389.114 and Chromium 89.0.4389.90
| chrome-remote-interface	| 0.30.0

Is Chrome running in a container? NO

When loading a URL that redirects to a Thai URL (only tested with Thai), the URL containing Thai characters is not properly encoded in the redirect headers.

See the following script:

```js
const CDP = require('chrome-remote-interface');

async function example() {
  let client;
  try {
    // connect to endpoint
    client = await CDP();
    // extract domains
    const { Network, Page } = client;
    // setup handlers
    Network.requestWillBeSent(({ request, redirectResponse }) => {
      if (redirectResponse) {
        console.log(`Correct: ${request.url}`);
        console.log(`Incorrect: ${redirectResponse.headers.location}`);
      }
    });
    // enable events then start!
    await Network.enable();
    await Page.enable();
    await Page.navigate({ url: 'https://www.facebook.com/110583773890076' });
    await Page.loadEventFired();
  } catch (err) {
    console.error(err);
  } finally {
    if (client) {
      await client.close();
    }
  }
}

example();
```

This outputs the following:

```
Correct: https://www.facebook.com/%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%A5%E0%B9%88%E0%B8%99%E0%B9%80%E0%B8%AA%E0%B8%A3%E0%B8%B4%E0%B8%A1%E0%B8%9E%E0%B8%B1%E0%B8%92%E0%B8%99%E0%B8%B2%E0%B8%81%E0%B8%B2%E0%B8%A3-110583773890076/
Incorrect: https://www.facebook.com/à¸‚à¸à¸‡à¹€à¸¥à¹ˆà¸™à¹€à¸ªà¸£à¸´à¸¡à¸žà¸±à¸’à¸™à¸²à¸à¸²à¸£-110583773890076/
```

So looks like the headers are not properly encoded/decoded.

**Comment by cyrus-and** [comment]
Yep, I can reproduce this, but I doubt this is an issue with this module. You may want to report this to [Google](https://crbug.com) or to ask this in the related [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

**Comment by ajimix** [comment]
Submitted to Google [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1197382)

**Comment by cyrus-and** [comment]
Thanks!
