### ISSUE TITLE
Undefined error message while using it with testcafe's chrome browser.

### ISSUE THREAD

**Issue by MukulCode** [cyrus-and/chrome-remote-interface#455]
| Component | Version
|-|-
| Operating system	  	 	| Mac Os
| Node.js					| v14.15.5
| chrome-remote-interface	| 0.30.0

Is Chrome running in a container? (I am using chrome with the help of TestCafe)

My main Aim:  My Aim is to cut the network so that I can see the error dialog in the website while automation testing.

[Important]: Testcafe is opening with this url: //http://192.168.0.123:1234/someRandomString/https://theWebsiteThatIAmTesting.com/

``` 
const CDP = require('chrome-remote-interface');
let config = {
        offline: true,
        latency: 100,
        downloadThroughput: 750 * 1024 / 8,
        uploadThroughput: 250 * 1024 / 8
    };
let client = await CDP({
        port:1234,
        host:"192.168.0.123"
    });

    const {Network} = client;
    await Network.enable();
    Network.emulateNetworkConditions(config);
```

I am getting error at this line 34:
```
         29 |        });
         30 |        response.on('end', () => {
         31 |            if (response.statusCode === 200) {
         32 |                callback(null, data);
         33 |            } else {
       > 34 |                callback(new Error(data));
         35 |            }
         36 |        });
         37 |    });
         38 |    request.setTimeout(REQUEST_TIMEOUT, () => {
         39 |        request.abort();

         at IncomingMessage.<anonymous> (/.../node_modules/chrome-remote-interface/lib/external-request.js:34:26)
```

The error message is not visible and this is the main reason why I am putting this question over here.

**Comment by MukulCode** [comment]
I request @cyrus-and to have a look at it.
This will be really helpful If you can spend some minutes of your at this issue.
Thanks in advance and kudos for this amazing module :)

**Comment by cyrus-and** [comment]
What do you mean with "the error message is not visible"?

That code simply performs an HTTP request and return an error if the code is not 200, the body is returned so you can catch it, otherwise it will be printed on the terminal as part of the stack trace.

For example:

```js
(async () => {
    const CDP = require('chrome-remote-interface');

    try {
        await CDP({
            host: 'example.com',
            port: 80
        });
    } catch (err) {
        console.error(err.toString());
    }
})();
```

Which yields:

```
Error: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>

```

Note though that there's little to debug here as the above request is equivalent to:

```console
$ dig +short example.com
93.184.216.34

$ curl http://93.184.216.34/json/list -i
HTTP/1.1 404 Not Found
Content-Type: text/html
Date: Wed, 12 May 2021 07:06:10 GMT
Server: ECS (bsa/EB21)
Content-Length: 345

<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>
```

**Comment by MukulCode** [comment]
In your example, you are able to see the error like 
```
Error: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>404 - Not Found</title>
	</head>
	<body>
		<h1>404 - Not Found</h1>
	</body>
</html>
``` 

In my case I am getting only 

Error
that's it. This is what I mean by error not visible.

**Comment by cyrus-and** [comment]
Most likely `http://192.168.0.123:1234/json/list` returns an empty body, try with `curl` as I shown you above if you want to see the status code. In any case, that endpoint is not returning the list of targets as chrome-remote-interface expects to.

**Comment by MukulCode** [comment]
> Most likely `http://192.168.0.123:1234/json/list` returns an empty body, try with `curl` as I shown you above if you want to see the status code. In any case, that endpoint is not returning the list of targets as chrome-remote-interface expects to.

Got it.
Trying this.
Thanks for the explanation and help :)

**Comment by MukulCode** [comment]
Commenting here again to let you know that the issue is resolved.
It was not related to CDP but more related to ports and Testcafe.

For anyone who wants to use this awesome library in Testcafe: Please make sure you are not setting the parameter port1 and port2 as 9222, they are different from the cdpPort.
While running a test case you have to make sure you use the same cdpPort as CDP requires. By default it is 9222 but you can change using the parameter port while calling CDP.

Closing this issue :)

**Comment by cyrus-and** [comment]
Thanks, for sharing your knowledge. :)
