### ISSUE TITLE
Types Typescripts how to

### ISSUE THREAD

**Issue by UXDart** [cyrus-and/chrome-remote-interface#456]
Hello. I search the issues it seems is not possible but there are some comments suggesting it is possible but don't explain how to do it. how can I use Typescript with this repo? if I want to use devtools-protocol what I need to write in the tsconfig? Thank you! (tried a lot of options no one worked...)

**Comment by cyrus-and** [comment]
Hi, feel free to share your experience if you think it could help others. Unfortunately I cannot help with that.

**Comment by UXDart** [comment]
sorry, found that if you do 

`import Protocol from "devtools-protocol/types/protocol-proxy-api";`

and then

`const protocol: (Protocol.ProtocolApi) = await CDP({ port: port, });`

you will get ts support

**Comment by westy92** [comment]
Unofficial typings are now published here: https://www.npmjs.com/package/@types/chrome-remote-interface

Related: https://github.com/cyrus-and/chrome-remote-interface/issues/112
