### ISSUE TITLE
When connect to a raw WebSocket, the parameter should be "target"

### ISSUE THREAD

**Issue by eseking** [cyrus-and/chrome-remote-interface#459]
I am trying to connect an electron demo project, when there is only one window, this works fine

https://github.com/cyrus-and/chrome-remote-interface/wiki/Connect-to-a-raw-WebSocket

But when there is multiple window, the options should be target, and from the source code there is no tab parameter anymore.
`const options = {
    port: '8890'
    target: 'ws://localhost:8890/devtools/page/683d14ca-1f1e-4e33-957c-61ce0446ac8b'
};`

Then I can use CDP.List first and connect to each window by CDP(options, async (client) => {})

**Comment by cyrus-and** [comment]
Good catch, fixed, thanks!
