### ISSUE TITLE
Failed to output console print

### ISSUE THREAD

**Issue by AkatQuas** [cyrus-and/chrome-remote-interface#462]
| Component | Version
|-|-
| Operating system	  	 	| Mac OS Catalina, 10.15.7
| Node.js					| 14.16.0
| Chrome/Chromium/...		| N/A
| chrome-remote-interface	| 0.31.0

Is Chrome running in a container?  NO

---

I start a simple express server like this:

<details>
<summary> code </summary>

```javascript
const express = require('express');
const app = express();
const port = 3000;

const marquee = ['log', 'warn', 'debug', 'error'];

let id = 0;
function nonce() {
  console.log('Visit /');

  id = (id + 1) % 4;
  const method = marquee[id];
  console[method](`${method} works`);
}

app.get('/', (req, res) => {
  nonce();
  res.send('Hello World!');
});

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`);
});
```

</details>

And start the server using `node --inspect server.js` .

With the following Inspection script: 

<details>
<summary> code </summary>

```javascript
const CDP = require('chrome-remote-interface');

function wait2dead() {
  setTimeout(() => {
    process.exit(0);
  }, 1e8);
}
const connect2Node = async () => {
  CDP(
    {
      target: '<replace-with-the-debugger-connection-print-by-the-above-node-script>',
    },
    async (client) => {
      const { Debugger, Console, Runtime } = client;
      try {
        client.on('Runtime.consoleAPICalled', (p) => {
          console.log(p);
        });
        await Runtime.runIfWaitingForDebugger();
        await Runtime.enable();
        await Debugger.enable({
          maxScriptsCacheSize: 10000000,
        });
        await Console.enable();
        wait2dead();
      } catch (err) {
        console.error(err);
      } finally {
        client.close();
      }
    }
  ).on('error', (err) => {
    console.error(err);
  });
};

connect2Node();
```

</details>

The actual behavior is any log before debugger attached will be printed in the inspection.

Any log after attaching couldn't be forward to inspection.

![demo](https://user-images.githubusercontent.com/24731539/128299942-9fd223b0-5109-479e-affa-b78bf46b7b99.png)

Please help if there is any explanation.

**Comment by cyrus-and** [comment]
I observe a different behaviour. First of all `wait2dead` does not really wait and the `client` is closed right away. If I get rid of that and I slightly modify the `Runtime.consoleAPICalled` handler for clarity, I obtain the following:

![image](https://user-images.githubusercontent.com/1660263/128469602-f6a8282f-5cea-4462-abb5-7148ad06c366.png)

It is in fact weird the output you get in the bottom right terminal, you should see a JSON object.
