### ISSUE TITLE
How can I set the frame resources?

### ISSUE THREAD

**Issue by ono-max** [cyrus-and/chrome-remote-interface#465]
Is Chrome running in a container? NO

Thanks to existing knowledge here, I can write codes to get frame resources as follows. However, I couldn't figure out how to set the frame resources. Do you have any ideas?

```sample.js
const CDP = require('chrome-remote-interface');

async function example() {
    let client;
    try {
        // connect to endpoint
        client = await CDP();
        // extract domains
        const {Network, Page} = client;
        await Network.enable();
        await Page.enable();
        const {frameTree} = await Page.getResourceTree();
        console.log(frameTree.resources);
        Page.addScriptToEvaluateOnNewDocument({source: script});
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

**Comment by ono-max** [comment]
As the use case, I'd like to set some resources in the Page pane, not Filesystem.
![Screen Shot 2021-08-12 at 4 32 35 PM](https://user-images.githubusercontent.com/59436572/129156394-25a02f7c-8801-40db-9c0d-6a99b9d1837c.png)

**Comment by cyrus-and** [comment]
Are you sure that this is something possible? AFAIK you cannot do that even in DevTools.

What you can do instead is to add the resource you want, but the method changes according to the resource type, e.g., CSS, JavaScript, etc. each one has its own way.

Or maybe you can serve synthetic resources via interception...

What are you really trying to achieve here?

**Comment by ono-max** [comment]
> What are you really trying to achieve here?

The big goal is to build Chrome debugging functionality into [ruby/debug](https://github.com/ruby/debug). To achieve it, I need to add the resource in the Page pane through web socket from ruby's debugger. Does it make sence?

**Comment by ono-max** [comment]
@cyrus-and 

Thank you for your reply.

> What are you really trying to achieve here?

### What I try here
I try to set the frame resources on Page pane for debugging the script.

### Big goal
The big goal is to build Chrome debugging functionality into [ruby/debug](https://github.com/ruby/debug). Ruby/debug will communicate to Chrome Developer frontend via remote debugging protocol.

### Small goal
I create the prototype in chrome-remote-interface to learn how to use the Chrome DevTools Protocol, how to communicate, and so on.

**Comment by cyrus-and** [comment]
Hm OK, if the above hints are not useful, you might want to ask this question in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or file an issue in the [official repo](https://github.com/ChromeDevTools/devtools-protocol).

**Comment by ono-max** [comment]
Ok, I'd like to try your first hint as follows. For example, could you tell me which method I should use for JavaScript?

> What you can do instead is to add the resource you want, but the method changes according to the resource type, e.g., CSS, JavaScript, etc. each one has its own way.

**Comment by ono-max** [comment]
Ok, I'd like to try your hints as follows. For example, could you tell me which method I should use for JavaScript?

> What you can do instead is to add the resource you want, but the method changes according to the resource type, e.g., CSS, JavaScript, etc. each one has its own way.

I'll try this one, too. 

>  you can serve synthetic resources via interception

Thank you.

**Comment by cyrus-and** [comment]
> For example, could you tell me which method I should use for JavaScript?

You can simply inject JavaScript code with [Runtime.evaluate](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate) or (possibly more similar to what you're looking for) [Runtime.compileScript](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-compileScript). I've never tried the latter, but I suspect that by assigning `sourceURL` for the script, you can effectively achieve the same as adding that script as a resource. Not sure if it will appear in the above "Page" pane though.

As a last resort you can always inject `<script src="..."></script>`, `<link href="..." rel="stylesheet">`, etc. in your page.

**Comment by ono-max** [comment]
Thank you for your kind instruction 👍 

I'll try it.

**Comment by ono-max** [comment]
Thanks. Your advice was really helpful for me. The script appeared in the Page pane.

```sample.js
const CDP = require('chrome-remote-interface');

async function example() {
    let client;
    try {
        // connect to endpoint
        client = await CDP();
        // extract domains
        const {Runtime, Page} = client;
        await Page.enable();
        await Page.navigate({url:'http://example.com'});
        await Page.loadEventFired();
        await Runtime.enable();
        let {scriptId} = await Runtime.compileScript({
          expression: "console.log('hoge')",
          sourceURL: "http://localhost",
          persistScript: true
        });
        console.log(scriptId);
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

**Comment by ono-max** [comment]
Sorry, I don't know how to do this one. Could you explain me more detail?

> you can serve synthetic resources via interception

**Comment by cyrus-and** [comment]
> Do you have any ideas for creating directory in Page pane as follows?

Maybe specifying a path in the `sourceURL` like this?

```javascript
let {scriptId} = await Runtime.compileScript({
  expression: "console.log('foo')",
  sourceURL: "http://localhost/some/path/here.js",
  persistScript: true
});
```

> Sorry, I don't get how to do this one. Could you explain me more detail?

This is probably the most versatile method. I'm still unsure about your use case though...

```javascript
const CDP = require('chrome-remote-interface');

const FAKE_RESOURCES = {
    'http://fake/': {
        mime: 'text/html',
        body: `
            <!DOCTYPE html>
            <html>
                <head>
                    <link rel="stylesheet" href="/css/some-stylesheet.css">
                </head>
                <body>
                    <p>fake index page</p>
                    <iframe src="http://example.com"></iframe>
                    <img src="/unhandled" />
                    <script src="/js/some-script.js"></script>
                </body>
            </html>
        `
    },
    'http://fake/js/some-script.js': {
        mime: 'application/javascript',
        body: `
            alert(document.domain);
        `
    },
    'http://fake/css/some-stylesheet.css': {
        mime: 'text/css',
        body: `
            body {
                border: 10px solid red;
            }
        `
    }
};

(async () => {
    try {
        const {Fetch, Page} = await CDP();

        Fetch.requestPaused(async ({requestId, request}) => {
            const resource = FAKE_RESOURCES[request.url];
            if (resource) {
                await Fetch.fulfillRequest({
                    requestId,
                    responseCode: 200,
                    responseHeaders: [
                        {
                            name: 'content-type',
                            value: resource.mime
                        }
                    ],
                    body: Buffer.from(resource.body).toString('base64')
                });
            } else {
                await Fetch.failRequest({
                    requestId,
                    errorReason: 'Failed'
                });
            }
        });

        await Fetch.enable({
            patterns: [
                {
                    urlPattern: 'http://fake/*'
                }
            ]
        });

        await Page.navigate({url: 'http://fake/'});
    } catch (err) {
        console.error(err);
    }
})();
```

**Comment by ono-max** [comment]
Both works fine completely. You are amazing!

How do I deal with License of the codes on this page? I'd like to write codes based on them here.

**Comment by cyrus-and** [comment]
Glad to help! They have none, use them freely.

**Comment by ono-max** [comment]
Thanks!

**Comment by ono-max** [comment]
Sorry, I have one more question. Can I use the codes on other issue page without the license, too?

**Comment by ono-max** [comment]
@cyrus-and 

Sorry, I have one more question. Can I use the codes on other issue page without the license, too? (For example, https://github.com/cyrus-and/chrome-remote-interface/issues/179#issuecomment-312247441)

**Comment by cyrus-and** [comment]
> Can I use codes from other issue pages in this repository without the license, too?

Sure!
