### ISSUE TITLE
Is it possible to run programs other than JavaScript?

### ISSUE THREAD

**Issue by ono-max** [cyrus-and/chrome-remote-interface#466]
We can run JavaScript in Developer console as follows, but is it possible to run programs other than JavaScript like Python or Ruby?

![Screen Shot 2021-08-29 at 2 34 49 PM](https://user-images.githubusercontent.com/59436572/131239822-64d412b9-2019-4619-a310-867988ab1a22.png)

**Comment by cyrus-and** [comment]
This is unrelated to chrome-remote-interface, but no, I don't think that's possible.
