### ISSUE TITLE
Retrieving local scope from call frame

### ISSUE THREAD

**Issue by epiccucumber15** [cyrus-and/chrome-remote-interface#468]
I'm trying to retrieve the local scope data from chrome-remote-interface:
![image](https://user-images.githubusercontent.com/80056715/144274523-5b28c011-dba9-404b-a13b-795caf88e8cd.png)

But when logging the frame it shows this:
```
{
  callFrameId: '5692085564504316912.24.0',
  functionName: '$u',
  functionLocation: { scriptId: '1025', lineNumber: 3, columnNumber: 27701 },
  location: { scriptId: '1025', lineNumber: 3, columnNumber: 27729 },
  url: 'https://x/init.js',
  scopeChain: [
    {
      type: 'local',
      object: [Object],
      name: '$u',
      startLocation: [Object],
      endLocation: [Object]
    },
    {
      type: 'closure',
      object: [Object],
      startLocation: [Object],
      endLocation: [Object]
    },
    { type: 'global', object: [Object] }
  ],
  this: { type: 'undefined' },
  returnValue: { type: 'string', value: '/blocked' }
}
```

```
  {
    type: 'local',
    object: {
      type: 'object',
      className: 'Object',
      description: 'Object',
      objectId: '3902945018858753175.1.508'
    },
    name: '$u',
    startLocation: { scriptId: '9', lineNumber: 3, columnNumber: 27701 },
    endLocation: { scriptId: '9', lineNumber: 3, columnNumber: 27730 }
  }
```

How would you retrieve the e variable containing "pathname" from the local scope?

| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 14.18.0
| Chrome/Chromium/...		| Chrome 96.0.4664.45
| chrome-remote-interface	| 0.31.1

Is Chrome running in a container? NO

**Comment by epiccucumber15** [comment]
Closing. I have resolved this by calling Runtime.getProperties on the object.

**Comment by cyrus-and** [comment]
Glad you've found a solution. Feel free to post some code example if you think it could help future visitors.

**Comment by epiccucumber15** [comment]
Will do. Is there a way to call Runtime.getProperties on a frame and all its nested objects? Currently when I use the getProperties API, sometimes there are nested objects, this is expected but is there a simple way of doing this?

**Comment by cyrus-and** [comment]
Not 100% sure, but I'm afraid you'll have to iterate over the nested objects and call `Runtime.getProperties` for each of them. If you can come up with a standalone example I could maybe be more helpful.

**Comment by epiccucumber15** [comment]
No problem, I will just iterate over them. Thanks for the quick replies & hard work put into this interface.
