### ISSUE TITLE
avoid `with`?

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-remote-interface#47]
isn't it a consensus since many years back that javascript `with` keyword is bad and should be avoided at any time?

https://www.barryvan.com.au/2009/05/avoid-javascripts-with-keyword/

The `Sample API usage` section actually reminded me it's still there; for the first time I saw it I almost couldn't understand how did it work, on this line `Page.loadEventFired(close);` where is the `close` variable from, or is it a magic function, finally I realized it's actually the `chrome.close`
https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage

it's a bad use case I can make a PR to change it this is agreed.

**Comment by c0b** [comment]
this book also gives 1 of the 68 specific ways talking about the problems from `with` and some good practices to resist from its convenience temptation

Effective JavaScript: 68 Specific Ways to Harness the Power of JavaScript
by David Herman, Published by Addison-Wesley Professional, 2012

https://www.safaribooksonline.com/library/view/effective-javascript-68/9780132902281/ch02.html#ch02lev1sec3

**Comment by cyrus-and** [comment]
Yeah, I'm perfectly aware of that, but I find that for the sake of the first-impression example this is not a problem. Indeed, that snippet has the primary purpose of showing how *sexy* and idiomatic is to use this interface, burdening it with 6 more `chrome.` wouldn't probably have the same effect. After all, `with` is never used elsewhere (added some missing `chrome.` in the other examples though).
