### ISSUE TITLE
Cannot set Page.setBypassCSP(true)

### ISSUE THREAD

**Issue by workingxx92** [cyrus-and/chrome-remote-interface#470]
Hello,
Cannot set Page.setBypassCSP(true)
![Screen Shot 2021-12-10 at 5 44 35 PM](https://user-images.githubusercontent.com/86577210/145561675-40c44c6b-29b8-457e-b93a-353fd17f62c3.png)

**Comment by cyrus-and** [comment]
The issue template is not there just for fun, especially this part:

> If appropriate, attach a MINIMAL STANDALONE SCRIPT to help to reproduce your issue. (Use fenced blocks to display JavaScript code like this: ```js)

What am I supposed to do with "Cannot set Page.setBypassCSP(true)" and a random screenshot?
