### ISSUE TITLE
Keeping MV3 extension service worker alive using CDP?

### ISSUE THREAD

**Issue by markpatx** [cyrus-and/chrome-remote-interface#472]
I needed to migrate a private MV2 extension to MV3, but instead I tried emulating it using this repo. Got most of it working, but the extension uses the `chrome.proxy` api, which I couldn't find a way to replicate using the CDP, so I had to do that part in a MV3 extension. 

But then I encountered this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1152255 (tried a few of the workaround from there but didn't seem to work)

I know I could just launch chrome with the --proxy-server flag, but I'd like to be able to set and change the proxy without having to restart chrome.

Since opening the extension service worker devtools window manually on chrome does keep the sw alive, I was wondering if there's is a way to keep it alive using the CDP? I do see the sw target using `Target.getTargets()`, and tried sending a few random commands, but it still becomes inactive after like 30 seconds of inactivity.

**Comment by cyrus-and** [comment]
> Since opening the extension service worker devtools window manually on chrome does keep the sw alive, I was wondering if there's is a way to keep it alive using the CDP?

Hmm, there shouldn't be in principle any difference between DevTools and a script using the CDP. You can try to see what DevTools is doing under the hood and try to replicate that in your script, maybe there's something that allows the SW to stay alive.

To do that you can [inspect DevTools](https://github.com/cyrus-and/chrome-remote-interface/wiki/Inspect-the-inspector) itself.
