### ISSUE TITLE
Debug android device web view using remote debugging

### ISSUE THREAD

**Issue by chatur-sriganesh** [cyrus-and/chrome-remote-interface#473]
Hi, 
Is there a way we can launch the devtools session programmatically for an android device connected?
I am trying to automate performance capture for a webview in my android application

**Comment by cyrus-and** [comment]
> Is there a way we can launch the devtools session programmatically for an android device connected?

What do you mean exactly?

You need to eventually obtain a port to connect chrome-remote-interface to, and I think you can use `adb` to forward that port. Also the WebView must have [`setWebContentsDebuggingEnabled`][1] set to `true`. I can't recall exactly, I'm not even sure I ever did that, but it should be possible.

[1]: https://developer.android.com/reference/android/webkit/WebView#setWebContentsDebuggingEnabled(boolean)

**Comment by chatur-sriganesh** [comment]
Thanks a lot for the input, I assumed port forwarding in this case works only from dev machine to android device and not the other way around, I was able to connect to my device webview successfully, however came across another small issue, 

**chrome-remote-interface list** gives me a list of all targets(webviews in my case) that are available, how do i evaluate an expression say for a particular webview and not just the first one which gets picked by default.

I tried **chrome-remote-interface -p 9222 activate <target id>** , it doesn't seem to be doing anything, maybe i am using it wrong, any suggestions please?

**Comment by cyrus-and** [comment]
As you normally would when using regular tabs, for the protocol it really makes no difference if you're interacting with a tab, a WebView, or a Node.js instance.

You can specify the `target` in [`CDP()`][1], or interactively using `chrome-remote-interface inspect <target>`.

As for evaluating an expression you can use [`Runtime.evaluate()`][2], for example:

```js
const {result} = Runtime.evaluate({
    expression: '1 + 1'
});
console.log(result.value);
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by chatur-sriganesh** [comment]
Tried the following and received **TypeError: Cannot read properties of undefined (reading 'webSocketDebuggerUrl')**
1. chrome-remote-interface -p 9222 inspect -l BB5AA48C4415FECDC2D1CA6B9C1CB056
2. chrome-remote-interface -p 9222 inspect -l ws://127.0.0.1:9222/devtools/page/BB5AA48C4415FECDC2D1CA6B9C1CB034

also tried without the -l parameter and passed target id directly as follows:
chrome-remote-interface inspect 4EE499CC38C0DB8988F72DD96CD7B6D6 received a socket hang up error.

**Comment by cyrus-and** [comment]
1 should work, 2 instead should be like this:

    chrome-remote-interface -p 9222 inspect -l -w ws://127.0.0.1:9222/devtools/page/BB5AA48C4415FECDC2D1CA6B9C1CB034

And yes, `-l` should be there.

**Comment by chatur-sriganesh** [comment]
It Worked! Thanks a lot for your active support in this! :)

**Comment by cyrus-and** [comment]
Glad to help, good luck!
