### ISSUE TITLE
Socket hangup when trying to connect to android device webview

### ISSUE THREAD

**Issue by chatur-sriganesh** [cyrus-and/chrome-remote-interface#474]
Hi,
Im performing the following steps to connect to a device 
1. Find webview pid
 adb shell grep -a webview_devtools_remote /proc/net/unix

 2. Enable port forwarding with pid found in step 1
 adb forward tcp:9222 localabstract:webview_devtools_remote_[webview id]

 3. Run chrome-remote-interface 
 chrome-remote-interface -p 9222 inspect -l

The above steps are great for using this tool in interactive mode, coming to the scripted approach i fetched the web socket url for that webview using  chrome-remote-interface list, something like this:

ws://127.0.0.1:9222/devtools/page/798B4AA761EF61535CDD8097D91E3B51

and tried connecting using the recipe "**Connect to a raw WebSocket**" from the wiki: sample below:

```
import CDP from 'chrome-remote-interface';

const options = {
    target: 'ws://127.0.0.1:9222/devtools/page/90B5C7AE67808CB1F48C37F1BB6C3FC6'
};

CDP(options, (client) => {
    console.log('Connected!');
    client.close();
}).on('error', (err) => {
    console.error(err);
});
```

This gives me an error:

Error: socket hang up
    at connResetException (node:internal/errors:691:14)
    at Socket.socketCloseListener (node:_http_client:420:25)
    at Socket.emit (node:events:406:35)
    at TCP.<anonymous> (node:net:672:12) {
  code: 'ECONNRESET'
}

Quick update: I am able to connect to the ws url using wscat as well, wscat -c ws://localhost:9222/devtools/page/<ID>

Any suggestions please?

**Comment by cyrus-and** [comment]
Basically you miss the equivalent of the `-l` (`--local`) option in your scripted approach:

```js
const options = {
    target: 'ws://127.0.0.1:9222/devtools/page/90B5C7AE67808CB1F48C37F1BB6C3FC6',
    local: true
};
```

---

Anyway, there is no need to pass the WebSocket URL, the first one is automatically used:

```js
const CDP = require('chrome-remote-interface');

(async () => {
    const client = await CDP({local: true});
    const {Runtime} = client;
    await Runtime.evaluate({
        expression: `document.write('hello')`
    });
    await client.close();
})();
```

---

If you need to programmatically pick the right target you can always scan the output of [`CDP.List`](https://github.com/cyrus-and/chrome-remote-interface#cdplistoptions-callback):

```js
(async () => {
    const targets = await CDP.List();
    const target = targets.find((target) => {
        return target.url === 'https://example.com/';
    });

    const client = await CDP({target, local: true});
    const {Runtime} = client;
    await Runtime.evaluate({
        expression: `document.write('hello')`
    });
    await client.close();
})();
```

---

Bonus, here's a nice oneliner for the port forwarding:

```
adb forward tcp:9222 "localabstract:$(adb shell cat /proc/net/unix | awk -F @ '/webview_devtools_remote/ { print $2 }')"
```

**Comment by chatur-sriganesh** [comment]
Thanks a lot! The local parameter worked, the programmatic examples are super helpful!
