### ISSUE TITLE
[Help]: How to fake WebRTC address

### ISSUE THREAD

**Issue by workingxx92** [cyrus-and/chrome-remote-interface#477]
```

var RTCPeerConnection = window.RTCPeerConnection
                    || window.mozRTCPeerConnection
                    || window.webkitRTCPeerConnection;
                var useWebKit = !!window.webkitRTCPeerConnection;

                //bypass naive webrtc blocking using an iframe
                if(!RTCPeerConnection){
                    //NOTE: you need to have an iframe in the page right above the script tag
                    //
                    //<iframe id="iframe" sandbox="allow-same-origin" style="display: none"></iframe>
                    //<script>...getIPs called in here...
                    //
                    var win = iframe.contentWindow;
                    RTCPeerConnection = win.RTCPeerConnection
                        || win.mozRTCPeerConnection
                        || win.webkitRTCPeerConnection;
                    useWebKit = !!win.webkitRTCPeerConnection;
                }

                //minimal requirements for data connection
                var mediaConstraints = {
                    optional: [{RtpDataChannels: true}]
                };

                var servers = {iceServers: [{urls: "stun:stun.services.mozilla.com"}]};

                //construct a new RTCPeerConnection
                var pc = new RTCPeerConnection(servers, mediaConstraints);

                function handleCandidate(candidate){
                    //match just the IP address
                    var ip_regex = /([0-9]{1,3}(\.[0-9]{1,3}){3}|[a-f0-9]{1,4}(:[a-f0-9]{1,4}){7})/
                    var ip_addr = ip_regex.exec(candidate)[1];

                    //remove duplicates
                    if(ip_dups[ip_addr] === undefined)
                        callback(ip_addr);

                    ip_dups[ip_addr] = true;
                }
```

Link:
https://github.com/diafygi/webrtc-ips/blob/master/index.html

**Comment by cyrus-and** [comment]
I have no idea what you're talking about, nor I'm willing to waste my time in trying to understand such a poorly written issue.

**Comment by xjxckk** [comment]
This issue is about how WebRTC leaks your real IP when you are using a proxy ([https://restoreprivacy.com/webrtc-leaks/](https://restoreprivacy.com/webrtc-leaks/)).

Is it possible to change this behaviour with CDP? As far as I know, you can only block WebRTC with a Chrome extension ([https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml](https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml)) which can be detected by a site.

**Comment by cyrus-and** [comment]
I don't think that the [protocol](https://chromedevtools.github.io/devtools-protocol/) mentions anything about WebRTC.

**Comment by xjxckk** [comment]
Maybe this [https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webTransportConnectionEstablished](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webTransportConnectionEstablished)? Probably not, the WebRTC stun requests don't come up in dev tools network requests on a normal browser.

**Comment by cyrus-and** [comment]
AFAIK WebTransport != WebRTC.
