### ISSUE TITLE
Target.createBrowserContext with proxyServer parameter not working.

### ISSUE THREAD

**Issue by wxkk** [cyrus-and/chrome-remote-interface#478]
I was trying to test `Target.createBrowserContext` to see what it does, and can't seem to find a way to make the `proxyServer` parameter work. The same proxy works if I set it when launching chrome with the `--proxy-server=` flag. I tried setting the proxy with and without `scheme://` but the ip shown in the website visited with `Target.createTarget` is always my real ip, not the proxy.

To test it, I am launching chrome with `--remote-debugging-port=9222` and then running this nodejs script:
```js
const CDP = require('chrome-remote-interface');

async function start() {
    // get browser target
    const {webSocketDebuggerUrl} = await CDP.Version();
    const browser = await CDP({
        target: webSocketDebuggerUrl
    });
    const {Target} = browser;
    // create new context with proxy
    const {browserContextId} = await Target.createBrowserContext({
        proxyServer: '127.0.0.1:12345'
    });
    // create new target
    const {targetId} = await Target.createTarget({
        url: 'https://icanhazip.com',
        browserContextId
    });
}

start();
```

**Am I using it wrong?**

| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 14.17.5
| Chrome/Chromium/...		| Chrome 99.0.4844.82 (Official Build) (64-bit)
| chrome-remote-interface	| 0.31.1

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Weird, it seems to be working for me (macOS), I tried with Tor:

```js
proxyServer: 'socks5://127.0.0.1:9050'
```

Can you also try with it so that we're on the same page about the proxy server? Alternatively provide a free proxy of whatever kind that I too can try.

**Comment by wxkk** [comment]
Same issue with Tor, works using `--proxy-server="socks5://192.168.0.112:9050"` but not with `Target.createBrowserContext({ proxyServer: 'socks5://192.168.0.112:9050' })`. May be a windows issue, any idea what could cause it?

**Comment by cyrus-and** [comment]
Hmm that's weird... I remember a similar issue (#442) but I'm unsure about the OP's final solution. Removing the scheme for an HTTP-only proxy and implementing the certificate bypass?

You might want to file an [upstream issue](https://crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.

(Probably just a typo in writing the message but there should be only one `:`.)

**Comment by wxkk** [comment]
(Yes the :: was just an error in the message.)

I just tested in linux and it works there. Will try to test on a different windows box and see what happens.

**Comment by wxkk** [comment]
Tested on a Windows server 2019 and didn't work there either. I guess it's a windows issue, but no idea what could cause it.

**Comment by cyrus-and** [comment]
And I'm afraid I cannot do anything about it either. Closing this, feel free to add more information if you come up with something.

**Comment by mtsvetanoff** [comment]
You can work around this issue by starting the browser with the --proxy-server CLI flag without passing any value with it. Then the proxyServer parameter works.
