### ISSUE TITLE
Overlay.setShowWebVitals() is not working in Chrome remote interface

### ISSUE THREAD

**Issue by chatur-sriganesh** [cyrus-and/chrome-remote-interface#480]
Hi,

I was trying out different Overlay methods in CDP in interactive mode. 
When i hit  - Overlay.setShowWebVitalsMetrics({show:true})
I get **Uncaught TypeError: Overlay.setShowWebVitalsMetrics is not a function**

Is this due to an older version of CDP being supported by chrome remote interface?

Thanks,
Chatur

**Comment by cyrus-and** [comment]
AFAIK there is no `Overlay.setShowWebVitalsMetrics`, do you mean [`Overlay.setShowWebVitals`](https://chromedevtools.github.io/devtools-protocol/tot/Overlay/#method-setShowWebVitals)?

**Comment by chatur-sriganesh** [comment]
Apologies! yes, i meant Overlay.setShowWebVitals({show:true})

**Comment by cyrus-and** [comment]
Are you trying to use Chrome for Android? Please do not omit important details, the issue template is there for a reason...

**Comment by chatur-sriganesh** [comment]
Hi,
Sure, 

| Component | Version
| Operating system	  	 	| Android 10
| Node.js					| v16.9.1

My Android web view version is - 99.0.4844.88

Im actually trying to capture web vitals metrics for a web view present inside my app. 

Once i open the web view on my device, i access Chrome remote interface through interactive mode
As a pre-requisite i made sure to:
1. enable dom by DOM.enable()
2. enable overlay by Overlay.enable() 

Kindly let me know if you need any further info.

Thanks,
Chatur

**Comment by cyrus-and** [comment]
Version of chrome-remote-interface?

How do you start the interactive mode? (Write the exact command please.)

**Comment by chatur-sriganesh** [comment]
Version - 0.31.1 (i am yet to try with the new version, will update here on the same shortly)

Steps to connect to interactive mode:

1. find webview pid
     adb shell grep -a webview_devtools_remote /proc/net/unix
2.  adb forward tcp:9222 localabstract:webview_devtools_remote_<webview pid>
3. chrome-remote-interface -p 9222 inspect -l

**Comment by cyrus-and** [comment]
Yes, you need to update to the latest version in order to have `Overlay.setShowWebVitals`.

Alternatively you can pass the latest protocol via the `-j, --protocol` option (interactively), or via the `protocol` option (programmatically).

**Comment by chatur-sriganesh** [comment]
It Worked! Thanks a lot for your active support on this :)
