### ISSUE TITLE
Emulating device toolbars with Emulation.setDeviceMetricsOverride

### ISSUE THREAD

**Issue by markpatx** [cyrus-and/chrome-remote-interface#483]
| Component | Version
|-|-
| Node.js						| v14.17.5
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Win 10
| OS running the client			| Win 10
| chrome-remote-interface		| 0.31.1

Is the client running in a container? NO

## Description

I am trying to emulate a smartphone with chrome using `Emulation.setDeviceMetricsOverride` to automate some tests, and I see a difference in `document.body.clientHeight` between the real phone and my pc emulating it.

Using the **Android Debug Bridge** and `chrome://inspect/#devices` I got the following values from the real phone (`window.devicePixelRatio`, `screen.width/height` and `document.body.clientWidth/Height`):

![](https://i.imgur.com/zo5NUcg.png)

When I try to emulate those values using the node code in the example, I get this:

![](https://i.imgur.com/Zsn6dq6.png)

I am guessing the difference is because of the android toolbar/chrome url bar, but I am unsure about the right way to emulate it. I could add some css `margin-top` to the html element of all pages, but seems a bit hacky.

**Is there a better way to emulate the android toolbar height?**

## Example

```js
const CDP = require('chrome-remote-interface');

async function start() {
    client = await CDP({ host: 'localhost', port: 9222 });
    const {Page, Emulation, Runtime} = client;
    await Emulation.setDeviceMetricsOverride({
        width: 412,
        height: 869,
        deviceScaleFactor: 2.625,
        mobile: true
    });
    await Page.enable();
    await Page.navigate({ url: 'about:blank' });
    await Page.loadEventFired();
    let str = `
    document.write(
        '<font size="20">' +
            'devicePixelRatio=' + window.devicePixelRatio + '<br>' +
            'screen=' + screen.width + 'x' + screen.height + '<br>' +
            'body=' + document.body.clientWidth + 'x' + document.body.clientHeight +
        '</font>' +
        '<style>body { background: #ddd }</style>'
    )`
    await Runtime.evaluate({
        expression: str
    });
}

start();
```

**Comment by cyrus-and** [comment]
Yes that part accounts for the URL bar, the same way IIRC, the keyboard does when it opens, and also maybe other interface components. I don't think you should concern about that, also because the actual screen size changes wildly across Android devices.

If you really think this is important, you can always measure the `window.innerWidth`/`window.innerHeight` , and use them in `Emulation.setDeviceMetricsOverride` as `width`/`height`.

**Comment by markpatx** [comment]
If I go with the css route to only modify the browser viewport and keep the "real" screen size, what would be the correct way to inject something like:

```
<style>
     html { margin-top: 346px !important; }
</style>
```

I know I could do it with js using `Runtime.evaluate` but maybe using the `CSS` domain is the right way to do it.

**Comment by cyrus-and** [comment]
```js
const CDP = require('chrome-remote-interface');

const STYLE = `
html {
    margin-top: 346px !important;
}
`;

(async () => {
    const client = await CDP();
    const {CSS, DOM, Page} = client;

    await DOM.enable();
    await CSS.enable();

    const {frameId} = await Page.navigate({url: 'https://example.com'});
    const {styleSheetId} = await CSS.createStyleSheet({frameId});
    await CSS.addRule({
        styleSheetId,
        ruleText: STYLE,
        location: {
            startLine: 0,
            startColumn: 0,
            endLine: 0,
            endColumn: 0
        }
    });

    await client.close();
})();
```
