### ISSUE TITLE
Emulation.setTouchEmulationEnabled effects disappear after navigating to another page.

### ISSUE THREAD

**Issue by markpatx** [cyrus-and/chrome-remote-interface#484]
## Environment

| Component | Version
|-|-
| Node.js						| v14.17.5
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Win 10
| OS running the client			| Win 10
| chrome-remote-interface		| 0.31.1

Is the client running in a container? NO

## Description

Trying to use the dev tools device emulation features from the cdp I found that the `Emulation.setTouchEmulationEnabled` command seems to reset after clicking any link and changing the page. 

To demostrate the issue:

- Launch chrome with --remote-debugging-port=9222
- Run the node code from the example (github.com will open in chrome)
- Open dev tools and run `"ontouchstart" in window` on the console (it returns true)
- Click any link on the page
- Go back to the dev tools and run `"ontouchstart" in window` again (now it returns false)

When using a normal chrome with dev tool's device toolbar `"ontouchstart" in window` always returns true:
- Launch a normal chrome and open the dev tools
- Click the Toggle Device Toolbar icon at the top left (or press Ctrl+Shift+M)
- Navigate to any website
- Run `"ontouchstart" in window` on the console (it returns true)
- Click any link on the page
- Go back to the dev tools and run `"ontouchstart" in window` again (still returns true)

**Is this a bug or am I doing something wrong?**

## Example

```js
const CDP = require('chrome-remote-interface');
async function start() {
    client = await CDP({ host: 'localhost', port: 9222 });
    const {Page, Emulation} = client;
    await Emulation.setDeviceMetricsOverride({ width: 800, height: 800, deviceScaleFactor: 2, mobile: true });
    await Emulation.setTouchEmulationEnabled({ enabled: true, maxTouchPoints: 1 });
    await Emulation.setEmitTouchEventsForMouse({ enabled: true, configuration: "mobile" });
    await Page.navigate({ url: 'https://github.com' });
}
start();
```

**Comment by maksim-obodkov** [comment]
@cyrus-and @markpatx Why did you write wrong here? How to fix the same issue
