### ISSUE TITLE
Unable to capture tracing events into a file for executions beyond 2 minutes

### ISSUE THREAD

**Issue by chatur-sriganesh** [cyrus-and/chrome-remote-interface#485]
| Component | Version
|-|-
| Node.js						| v16.9.1
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Mac Os Big Sur
| OS running the client			| Android 10
| chrome-remote-interface		| 0.31.2

Is the client running in a container? NO

## Description

Hi, 
I am currently using this recipe to run tracing on android web view, 
https://github.com/cyrus-and/chrome-remote-interface/wiki/Generate-timeline-data

Once thing i noticed was, if I run the tracing beyond 2 mins approximately, i see that the program just quits with no errors or exceptions and no timeline json is generated, I suspect this could be due to a huge number of events getting captured.
On https://chromedevtools.github.io/devtools-protocol/tot/Tracing/#method-start , i could see that we can start tracing and set the **transfer mode** as **returnAsStream** and maybe utilize that to our advantage to avoid this issue. 

Do you think this approach will help?, also it would be super helpful if you could share some recipes around using Transfermode returnAsStream and TraceConfig.

## Example

Here is a very basic code of what i'm doing,

```
(async () => {
    // Select active web view on which we need to run perf
    const targets = await CDP.List();
    const target = targets.find((target) => {
        for(var i = 0;i< targets.length;i++){
            console.log(targets[i].url);
            if(targets[i].url.includes(<targetName>)){
                console.log(targets[i].url + " FOUND")
                return targets[i].url;
            }else{
                console.log("URL not found");
                process.exit(1);
            }
        }
    });

    const client = await CDP({target, local: true});
    console.log('Connected!');
    const {Tracing} = client;
    var events = [];
    Tracing.dataCollected(({value}) => {
        events.push(...value);
        });
    await Tracing.start({categories:'-*,devtools.timeline,v8.execute,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,toplevel,blink.console,latencyInfo,disabled-by-default-v8.cpu_profiler'});
    //Wait for user to press some key to stop tracing
    await keyPress(); 
    await Tracing.end();
    await Tracing.tracingComplete();
   //Write tracing file to system
   fs.writeFileSync('timeline.json', JSON.stringify(events),null,4);
   })();
```

**Comment by cyrus-and** [comment]
> Once thing i noticed was, if I run the tracing beyond 2 mins approximately, i see that the program just quits with no errors or exceptions and no timeline json is generated, I suspect this could be due to a huge number of events getting captured.

Hmm, I don't think this can be the case, events are gathered on the Node.js side, any error there would result in an exception to be printed on the console.

About the generated JSON file, is it empty or `[]`? Is just not there? This is weird, if you take a look at the recipe, the program flow either ends up in `fs.writeFileSync` or in an exception handler.

You should figure out where does the program actually exists, if that's the case, by putting some debug prints or something.

> also it would be super helpful if you could share some recipes around using Transfermode returnAsStream and TraceConfig.

Streams can be handled like follows (also see #216):

```js
const CDP = require('chrome-remote-interface');

(async () => {
    const client = await CDP();
    const {IO, Page, Tracing} = client;

    // enable page events
    await Page.enable();

    // start tracing and navigate to the page
    await Tracing.start({transferMode: 'ReturnAsStream'});
    await Page.navigate({url: 'https://example.com'});

    // wait for the page load then stop tracing
    await Page.loadEventFired();
    await Tracing.end();

    // wait for the tracing data to be ready
    const {stream: handle} = await Tracing.tracingComplete();

    // process the event stream
    while (true) {
        // read the next chunk
        const {base64Encoded, data, eof} = await IO.read({handle});

        // done with the stream
        if (eof) {
            await IO.close({handle});
            break;
        }

        // TODO do something with the data...
        console.log(base64Encoded, data);
    }

    await client.close();
})();
```

**Comment by chatur-sriganesh** [comment]
Hi ,

Thanks a lot for your valuable inputs, turns out this is due to webview crashing i guess!? i tried to replicate this using chrome devtools:
1. Inspected the device
2. Ran performance recording for about 2.5 mins
3. Stopped and waited for trace to be processed, suddenly the webview on which i was recording closed and devtools got disconnected.

As for the recipe you provided, it worked like a charm! Thanks again! 

Do i also use TraceConfig in a similar way as above?

**Comment by cyrus-and** [comment]
> Do i also use TraceConfig in a similar way as above?

I guess you can just pass the [Tracing.TraceConfig](https://chromedevtools.github.io/devtools-protocol/tot/Tracing/#type-TraceConfig) object in your `Tracing.start`, for example:

```js
await Tracing.start({
    transferMode: 'ReturnAsStream',
    traceConfig: {
        recordMode: 'recordContinuously',
        // [...]
    }
});
```

**Comment by chatur-sriganesh** [comment]
Thanks a lot for your active support and invaluable inputs! 
I guess for the webview closing/crash ill log an issue in chrome devtools frontend project.
