### ISSUE TITLE
[Help] Is there any "API"-way to get the coordinates (`.getBoundingClientRect()`) of a `Node`?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#487]
Unfortunately, I can't write much here because the title says it all. I would hate to evaluate script when there is an "already existing way" to get the coordinates (x, y, height, width) of a `Node`.

Unfortunately, I could not find anything regarding "ClientRect".

**Comment by cyrus-and** [comment]
Maybe [DOM.getContentQuads](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getContentQuads)?

**Comment by cyrus-and** [comment]
Hm I guess, you can obtain the window position with:

- `window.screenTop` / `window.screenLeft`

Then the window sizes with:

- `window.innerHeight` / `window.innerWidth`
- `window.outerHeight` / `window.outerWidth`

And do the proper math. If your browser is Chrome you can be sure there's no bottom bar.

Unfortunately the above is part of the HTML JavaScript API. I don't think there's anything similar via the protocol.

**Comment by himat** [comment]
@0x7357 are you saying you switched to using puppeteer in order to get this? Puppeteer has this built in?
