### ISSUE TITLE
[Question] Is there any way to get the Viewport Dimensions?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#488]
Has `chrome-remote-interface` something to get the Viewport Dimensions? Actually I'm taking a screenshot and using another repository to get the image dimensions - but this feels a little hacky. :-)

**Comment by cyrus-and** [comment]
Isn't this related to #487?

It's not something to be implemented at the `chrome-remote-interface` level, that value is either returned by the [protocol](https://chromedevtools.github.io/devtools-protocol/) or fetched via JavaScript evaluation with [Runtime.evaluate](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate).

**Comment by cyrus-and** [comment]
> Looks like `Page.getLayoutMetrics()` has what I was looking for. But I'd need to pass a page, I guess. I really hoped there is something `Browser` related.

No you don't, just call it.
