### ISSUE TITLE
Chrome Remote Interface is only controlling one browser at a time

### ISSUE THREAD

**Issue by JordanSinko** [cyrus-and/chrome-remote-interface#491]
## Environment

| Component | Version
|-|-
| Node.js						| 17.6.0
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Windows 11
| OS running the client			| Windows 11
| chrome-remote-interface		| 0.31.2

Is the client running in a container? NO

## Description

I am trying to have multiple chrome browser running at one time. What I am noticing is that the CDP commands are suspended until the browser is at the forefront, so only one is completing the tasks at any given moment. 

I am able to fan these out with Playwright and Puppeteer, so I am not sure if this is a CDP thing, although I am connecting over CDP with those other tools.

**Comment by cyrus-and** [comment]
This is something that you have to handle at the JavaScript level.

**Comment by cyrus-and** [comment]
The following snippet spawns 10 Chrome instances and runs some JavaScript on each of them in parallel:

```js
const CDP = require('chrome-remote-interface');
const ChromeLauncher = require('chrome-launcher');

async function doStuff(i) {
    const chrome = await ChromeLauncher.launch();
    const client = await CDP({port: chrome.port});
    const result = await client.Runtime.evaluate({
        expression: `new Promise(x => setTimeout(x, 3000))`,
        awaitPromise: true
    });
    console.log(`${new Date()} ${i}`);
    await client.close();
    await chrome.kill();
}

Promise.all([...Array(10).keys()].map(doStuff));
```

As you can see, they finish around the same time.

**Comment by JordanSinko** [comment]
Yeah this very simple example works but fails when doing more complicated interactions with the webpage. I am finding issues filling out forms with multiple concurrent browsers open. It will only fill the form out if the browser is focused. I will create an example.
