### ISSUE TITLE
Is there a way to emulate devicemotion events?

### ISSUE THREAD

**Issue by markpatx** [cyrus-and/chrome-remote-interface#492]
I see that there is a method to mock [deviceorientation](https://developer.mozilla.org/en-US/docs/Web/API/Window/deviceorientation_event) events ([DeviceOrientation.setDeviceOrientationOverride](https://chromedevtools.github.io/devtools-protocol/tot/DeviceOrientation/#method-setDeviceOrientationOverride)).

Is there something like that but for [devicemotion](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicemotion_event) events?

**Comment by cyrus-and** [comment]
I don't think so, even in DevTools ("Sensors" drawer) there's no such option. You may want to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol) or file an issue to the [devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol) repo.

Feel free to post here your findings if you want, so to help others.
