### ISSUE TITLE
How to get list of elements using Runtime.evaluate

### ISSUE THREAD

**Issue by x8serv** [cyrus-and/chrome-remote-interface#494]
Using CDP i am trying to mouse over an element (not by position but using javacript executor)

const { result } = await Runtime.callFunctionOn({
          functionDeclaration: 'function(){this.click()}',
          objectId: object.objectId!,
        });

Using above how do i achieve this?

Can anyone please help

**Comment by cyrus-and** [comment]
As you normally would in plain JavaScript?

```js
const {result} = await Runtime.callFunctionOn({
    functionDeclaration: `function () {
        this.dispatchEvent(new Event('mouseover'));
    }`,
    objectId
});
```

**Comment by x8serv** [comment]
Thank you so much
