### ISSUE TITLE
Auto-select a webview target that is currently in the foreground

### ISSUE THREAD

**Issue by chatur-sriganesh** [cyrus-and/chrome-remote-interface#499]
## Environment

| Component | Version
|-|-
| Node.js						| v16.9.1
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Mac Os Big Sur
| OS running the client			| Android 10
| chrome-remote-interface		| 0.31.2
Is the client running in a container? NO

## Description

Hi, I am currently running CRI to capture trace metrics of a webview in my app running in an android device.
I currently iterate through the list of targets available , then pick the one i need to run my tracing on. 
It is always the target webview which is present in the foreground and can be interacted with.

I am looking for a way where in the CRI can automatically pick a target that is active and in the foreground, this would save me a rather unnecessary step of searching and specifying the target every time i run the script.

Here is a basic code of what i am doing currently.
Is there a method or a way to directly assign my currently active foreground webview as a target?

## Example

```js
const CDP = require('chrome-remote-interface');

async function example() {
     const targets = await CDP.List();
    const target = targets.find((target) => {
        for(var i = 0;i< targets.length;i++){
            console.log(targets[i].url);
            if(targets[i].url.includes(<targetName>)){
                console.log(targets[i].url + " FOUND")
                return targets[i].url;
            }else{
                console.log("URL not found");
                process.exit(1);
            }
        }
    });
}

example();
```

**Comment by slhck** [comment]
I don't see a way to know whether a target is in the foreground at all. Even so, I think it does not have anything to do with this package.

Anyway: maybe the `setAutoAttach` method of the `Target` domain helps?

**Comment by cyrus-and** [comment]
@chatur-sriganesh yes, I don't think there's a way to do that either, it could easily be the case that the foreground target is always the first one (I seem to recall it was the case for regular tabs), but even then I don't think it's documented and you can't rely on that.

Looping on the target is fine IMHO, I don't see any drawbacks. You can either use the `List()` method (as you do), or call the [`Target.getTargets`](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-getTargets) protocol method when attached to the *browser* target.
