### ISSUE TITLE
Allow connection to arbitrary duplex stream

### ISSUE THREAD

**Issue by sidorares** [cyrus-and/chrome-remote-interface#5]
I'd like to be able to connect to android device without intermediate local port-forwarding adb server. With https://github.com/sidorares/node-adbhost a can create duplex node stream connected to chrome devtools on android device.

From initial research it looks like it's possible to pass custom Agent as an option to ws client, which should use android-connected stream instead of creating new tcp socket from url parameter.

**Comment by cyrus-and** [comment]
Since this project is moving a bit away from being a pure Chrome interface, I don't think that adding Android-specific code is a good idea anymore; such feature should possibly belong to clients.
