### ISSUE TITLE
Split repl into a different repo, keep this as just the library

### ISSUE THREAD

**Issue by evantorrie** [cyrus-and/chrome-remote-interface#50]
Is there any possibility of splitting this up so that chrome-remote-interface is just an npm package containing the library only?  i.e. get rid of the repl client and move it into a separate npm package which depends on this one?

For tools that are controlling DevTools directly, having the repl client built into this package doesn't make much sense.

**Comment by cyrus-and** [comment]
I see your point, but that client is there mainly as a debug tool, a quite rudimentary tool in fact, which probably does not justify a separate package. Out of curiosity, what is the problem of having a lightweight client bundled into the library package?

**Comment by evantorrie** [comment]
Sorry, didn't answer this before.  My only concern was one of package weight (since this may go into docker containers).  But given that it's small, it's not a huge concern.
