### ISSUE TITLE
How to take heap snapshot with version 0.31.3?

### ISSUE THREAD

**Issue by foreseaz** [cyrus-and/chrome-remote-interface#507]
## Environment

| Component | Version
|-|-
| Node.js						| v16.14.2
| Client (Chrome/Chromium/...)	| NodeJS
| OS running Node.js			| Mac V12.4
| OS running the client			| N/A
| chrome-remote-interface		| 0.31.3

Is the client running in a container? NO

## Description

I'm currently debugging a NodeJS program that runs with `node --inspect index.js` and connect with CDP as following example. and the `HeapProfiler` seems deprecated from the type definition. I'm wondering how can I take Heap snapshot with current version of `chrome-remote-interface`. 

## Example

```js
const CDP = require('chrome-remote-interface');

async function example() {
  const _debugger = await cdp({ port: 9229 }) // default node debugging port
  _debugger.HeapProfiler.addHeapSnapshotChunk
}

example();
```

**Comment by cyrus-and** [comment]
> and the `HeapProfiler` seems deprecated from the type definition

Where does exactly is this written?

**Comment by foreseaz** [comment]
> > and the `HeapProfiler` seems deprecated from the type definition
> 
> Where does exactly is this written?

Plesase refer to this https://chromedevtools.github.io/devtools-protocol/tot/HeapProfiler/

**Comment by cyrus-and** [comment]
Nowhere it says that `HeapProfiler` is deprecated...
