### ISSUE TITLE
Get current scroll position without `evaluate`

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#509]
Is there any way to get the actual scroll position for a target/page without the usage of `Runtime.evaluate`?

**Comment by cyrus-and** [comment]
You can try this:

```js
const CDP = require('chrome-remote-interface');

async function getScrollYRuntimeEvaluate({Runtime}) {
    const {result: {value}} = await Runtime.evaluate({
        expression: `window.pageYOffset`
    });
    return value;
}

async function getScrollYDOM({DOM}) {
    const {root} = await DOM.getDocument();
    const {nodeId} = await DOM.querySelector({
        nodeId: root.nodeId,
        selector: 'body'
    });
    const {model: {content}} = await DOM.getBoxModel({nodeId});
    return -content[1];
}

(async () => {
    const client = await CDP();

    console.log(await getScrollYRuntimeEvaluate(client), 'Runtime.evaluate');
    console.log(await getScrollYDOM(client), 'DOM');

    await client.close();
})();
```

**Comment by tenkuken** [comment]
I'm struggle, how to get DOM.getBoxModel from iframe. anyone can help me?

**Comment by cyrus-and** [comment]
@tenkuken I guess you can start by fetching the [document](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getDocument), traversing it (e.g., with [DOM.querySelector](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-querySelector)), then you should be able to use the `nodeId` with [DOM.getBoxModel](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getBoxModel).
