### ISSUE TITLE
How to create a sub CDP client of `const client = await CDP({ target: webSocketDebuggerUrl })`?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#510]
Im creating a new CDP client via `const client = await CDP({ target: webSocketDebuggerUrl });`.

How can I create a "sub client" for this created CDP client with a specified target id (like "25B9A14AD6A1DA9F2A2539874E03A751")? (The browser is indeed remote and accordingly `127.0.0.1` and `9222` cannot work.)

**Comment by cyrus-and** [comment]
You cannot enforce a specific target id, the implementation will generate one for you.

**Comment by cyrus-and** [comment]
[`CDP`](https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback) supports `host` and `port` options.

**Comment by cyrus-and** [comment]
Usually events need to be enabled on a per-domain basis, for example, `Target.enable()`.

**Comment by cyrus-and** [comment]
If you come up with a standalone example I could help you in the process of debugging.

**Comment by cyrus-and** [comment]
Just move `Runtime.on('executionContextCreated', ...)` out.

**Comment by cyrus-and** [comment]
(BTW, it seems to work reliably for me.)

**Comment by cyrus-and** [comment]
> Just move `Runtime.on('executionContextCreated', ...)` out.

[This](https://github.com/cyrus-and/chrome-remote-interface/issues/510#issuecomment-1268581502).

**Comment by cyrus-and** [comment]
Wait at *root-level* for both events to fire, then pass both outcomes to the `CustomPage` class. This library provides promises for events too, so you can do something like this (simplified):

```js
const [outcome1, outcome2] = await Promise.all([
    Target.targetCreated(),
    Runtime.executionContextCreated()
]);

const page = CustomPage.create(client, outcome1, outcome2);
```

**Comment by cyrus-and** [comment]
Sorry I missed the target creation:

```js
const [outcome1, outcome2] = await Promise.all([
    Target.targetCreated(),
    Runtime.executionContextCreated(),
    Target.createTarget({
        url: 'https://www.example.com',
    });
]);

const page = CustomPage.create(client, outcome1, outcome2);
```

**Comment by cyrus-and** [comment]
> Or is only one context created initially?

I have no idea about that. I'm not aware of the internals, it's all trial and error + <https://chromedevtools.github.io/devtools-protocol/> for me too.

**Comment by cyrus-and** [comment]
Another option it to *globally* listen for those events, then use some data structure to keep a map from ids to actual returned objects, so it will work for multiple concurrent context (if ever really needed).

> Keeps stucking at console output `1`. And I can't enable Runtime because of `'Runtime.enable' wasn't found` (`const { Runtime, Target } = client;`).

`Target` is from the browser client, `Runtime` from the actual page.

**Comment by cyrus-and** [comment]
Yes, I think the `about:blank` solution is a nice one, at least you can create the target first. In any case you need to listen for both events, before the navigation, to avoid the original race condition.

**Comment by cyrus-and** [comment]
> Wow, can't remember how many of these race-conditions I had, but they're frustrating.

At least Node.js itself is single-threaded... :P

Cheers mate, glad to help. Good luck!
