### ISSUE TITLE
Is there any way to know when a "navigation" starts?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#511]
Since anything here is event based I'd love to know if there is a way to know when the main frame or a children frame STARTS navigating.

**Comment by cyrus-and** [comment]
What about [Page.frameStartedLoading](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-frameStartedLoading)?

**Comment by cyrus-and** [comment]
So you tried and it didn't work...?

Also bear in mind that I'm not the one who wrote the protocol nor the one that implemented the protocol in Chrome.

**Comment by cyrus-and** [comment]
I would simply go about simulating the click, then waiting for the page load event. I don't see any particular problem here.
