### ISSUE TITLE
`Runtime.callFunctionOn`, `awaitPromise` and context id destroyed before resolving

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#512]
As the title says: if I call `Runtime.callFunctionOn` with `awaitPromise: true` and the execution context id gets destroyed (race) - while I'm waiting for the resolve - it feels like an endless loop. Nothing happens and it stucks there.

How would you solve that? Creating a custom race? (I guess a `Runtime.callFunctionOn` call usually takes some milliseconds. But having a race with a static timeout value kinda feels dirty. Because maybe a website takes a little longer to resolve? Anyway, I don't like magic numbers.)

**Comment by cyrus-and** [comment]
```
<!-- Attach a minimal standalone script that reproduces your issue. -->
```

**Comment by cyrus-and** [comment]
AFAIK only a timeout can save you from:

```
functionDeclaration: `async () => { }`,
```

but that's not the original issue. How does the context gets destroyed in your case?

**Comment by cyrus-and** [comment]
FYI [`Runtime.evaluate`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate) has an embedded `timeout` option.
