### ISSUE TITLE
How would you catch `Page.navigate({ url: 'https://www.google.com/404' })` (404)?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#514]
I'd like to know if `Page.navigate({ url: '...' })` ends in a 404. Have you any ideas?

**Comment by cyrus-and** [comment]
1. listen for [`Network.requestWillBeSent`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-requestWillBeSent) and save the `requestId` of the event whose `documentURL` matches the one you navigated to;
2. listen for [`Network.responseReceived`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-responseReceived) and check the `response.status` for those event that matches the above `requestId`.
