### ISSUE TITLE
Is `Runtime.enable` just there to enable `executionContextCreated` events?

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#516]
```
Runtime.enable

Enables reporting of execution contexts creation by means of executionContextCreated event. When the reporting gets enabled the event will be sent immediately for each existing execution context.
```

`Runtime.enable` just enables the `executionContextCreated` event, if I read correctly. Does it mean that `executionContextDestroyed` doesn't need to have the Runtime Domain enabled?

**Comment by cyrus-and** [comment]
I don't know... have you tried it? Usually the `.enable()` methods enable the event generation for domains. In some cases they even do something more.

**Comment by cyrus-and** [comment]
It is indeed, but there's nothing I can do about it. You could check out [devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol).
