### ISSUE TITLE
DOMStorage.getDOMStorageItems 'Frame not found for the given storage id'

### ISSUE THREAD

**Issue by brunoshine** [cyrus-and/chrome-remote-interface#521]
## Environment

| Component | Version
|-|-
| Node.js						| v16.13.1
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Windows
| OS running the client			| Windows
| chrome-remote-interface		| 0.32.0

Is the client running in a container? NO

## Description

When trying to get local storage data, I get the following error 'Frame not found for the given storage id'.
Can you help out? thanks

## Example

```js
const CDP = require('chrome-remote-interface');
const browser = await chrome.launch({
  userDataDir: false, //profilePath,
  startingUrl: "about:blank",
  ignoreDefaultFlags: true,
  chromeFlags: newFlags
})
const client = await CDP({ port: browser.port })
const { Page, DOMStorage, Storage, Console } = client;
const PAGE_URL = new URL(config.APP.domain); //       http://localhost:4000
await Page.enable();
await Page.navigate({ url: PAGE_URL.origin });
await Page.loadEventFired();
const storageId = {
  securityOrigin: PAGE_URL.origin,
  isLocalStorage: true
};

try {
    const c = await DOMStorage.getDOMStorageItems({storageId});
} catch (e) {
    console.error(e);
}
```

**Comment by fioleto** [comment]
Same issue.
Maybe 'StorageKey' is missing at lib/protocol.json:7196.
(Snippet view is not available due to a file size is too large.)

```json
{
    "id": "StorageId",
    "description": "DOM Storage identifier.",
    "type": "object",
    "properties": [
        {
            "name": "securityOrigin",
            "description": "Security origin for the storage.",
            "type": "string"
        },
        {
            "name": "isLocalStorage",
            "description": "Whether the storage is local storage (not session storage).",
            "type": "boolean"
        }
    ]
},
```

* Chrome DevTools Protocol Reference.
https://chromedevtools.github.io/devtools-protocol/tot/DOMStorage/#type-SerializedStorageKey

* SerializedStorageKey Reference.
https://chromedevtools.github.io/devtools-protocol/tot/DOMStorage/#type-SerializedStorageKey

In my opinion, The SerializedStorageKey type is 'string'. and protocol.json should wrote by
```json
{
    "name": "SerializedStorageKey",
    "description": "hoge hoge",
    "type": "string"
}
```

**Comment by cyrus-and** [comment]
@brunoshine don't ask me why but you also need to specify the `storageKey` parameter and set is the same as `securityOrigin` (mind the trailing `/`). You can figure this out by listening for, e.g., the `DOMStorage.domStorageItemAdded` event, then add an item via DevTools:

```js
localStorage.setItem('xxx', 123);
```

You'll receive:

```js
{
  storageId: {
    securityOrigin: 'https://example.com',
    storageKey: 'https://example.com/',
    isLocalStorage: true
  },
  key: 'xxx',
  newValue: '123'
}
```

@fioleto the protocol is fetched by Chrome, that file is only a fallback.

**Comment by brunoshine** [comment]
Hi @cyrus-and 
Thanks for the reply. I think I hit an issue on that because of typescript validation. Let me run the code again and I’ll get back to you.

cheers
Bruno

**Comment by brunoshine** [comment]
Hi @cyrus-and 

still the same error. So I have the following storageId object:
```
{
  securityOrigin: 'http://localhost:4000',
  isLocalStorage: true,
  storageKey: 'http://localhost:4000/'
}
```

and I'm still getting 'ProtocolError: Frame not found for the given storage id' 

code:
```
const storageId = {
      securityOrigin: PAGE_URL.origin,
      isLocalStorage: true,
      storageKey: `${PAGE_URL.origin}/`
  };
  console.log(storageId) // aboce output
  try {
      const c = await DOMStorage.getDOMStorageItems({ storageId });
  } catch (e) {
      console.error(e);
  }
```

Any thoughts? Thanks.

**Comment by cyrus-and** [comment]
> You can figure this out by listening for, e.g., the `DOMStorage.domStorageItemAdded`

@brunoshine what if you try this?
