### ISSUE TITLE
Detect when Page is about to close and stop

### ISSUE THREAD

**Issue by iustinpericica** [cyrus-and/chrome-remote-interface#525]
## Environment

| Component | Version
|-|-
| Node.js						| 18.4.1
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Window
| OS running the client			| Window
| chrome-remote-interface		| 0.32.1

Is the client running in a container? NO

## Description

I have the following situation:
Run some tests against a web application. That web application opens multiple pages ( tabs ) and closes some of them during the test.
My goal is to take coverage from all pages ( tabs ) that run during a test.

So, there are 2 steps for each page ( tab ) that I must proceed.

1. StartCoverage with Profiler.enable and Profiler.startPreciseCoverage
2. TakeCoverage

For step 1, I have control when pages ( tabs ) start, so I can start the coverage.

For step 2, it is complicated when pages ( tabs ) close during the test, because CDP session for that page is lost, if session is lost, coverage data gets lost too.
I can take coverage from tabs that stay open until the end of the test, but for those that close during the test I haven't found a way.

Is there a way to get notification through CDP that a page is about to get closed and block the closing until coverage is taken?

**Comment by cyrus-and** [comment]
Some random ideas (I'd go for 1):

1. Restructure the test code (if possible) so that the CDP script is in charge of opening and closing pages.

2. Use a breakpoint or otherwise pause the JavaScript execution when the page is about to close. Not sure how it works when coupled with coverage analysis.
