### ISSUE TITLE
The client disconnects when I close all "non-system tabs"

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#531]
## Environment

| Component | Version
|-|-
| Node.js						| Latest
| Client (Chrome/Chromium/...)	| Latest
| OS running Node.js			| Windows 10
| OS running the client			| Windows 10
| chrome-remote-interface		| Latest

Is the client running in a container? **NO**

## Description

If I close all tabs that should be closed via `closeAllNonSystemTabs()` while one page (for example "https://www.example.com") is open, the client disconnects (`client.on("disconnect", () => {})` is fired). If no other page is open, but only "System Tabs", then the client does not disconnect. **Why does the client disconnect?** And how can I prevent this?

## Example

```js
const CDP = require("chrome-remote-interface");

async function main() {
  const initialUrl = "about:blank#hello";

  const client = await CDP();

  client.on("disconnect", async () => {
    console.log("Client disconnected.");
  });

  const ensureSystemTab = async () => {
    const { targetInfos } = await Target.getTargets();

    const systemTabs = targetInfos.filter((targetInfo) => {
      return targetInfo.type === "page" && (targetInfo.url.startsWith("about:blank") || targetInfo.url.startsWith("chrome://"));
    });

    const hasSystemTabs = systemTabs.length > 0;

    if (!hasSystemTabs) {
      await Target.createTarget({ url: "chrome://newtab/" });
    }
  };

  const closeAllNonSystemTabs = async () => {
    const { targetInfos } = await Target.getTargets();

    const targetInfosFiltered = targetInfos.filter((targetInfo) => {
      return targetInfo.type === "page" && !targetInfo.url.startsWith("about:blank") && !targetInfo.url.startsWith("chrome://");
    });

    await Promise.all(
      targetInfosFiltered.map((targetInfo) => {
        return Target.closeTarget({ targetId: targetInfo.targetId });
      })
    );
  };

  await ensureSystemTab();
  await closeAllNonSystemTabs();

  await Target.createTarget({
    url: initialUrl,
  });
}

main();
```

**Comment by cyrus-and** [comment]
Correct, just calling `CDP()` has the effect to connect to the first suitable session found in `/json/list`, which yeah, usually is the active one.

**Comment by cyrus-and** [comment]
> Oh, wait. Does this mean, that `/json/list` is a suitable way to get the current active target?

I mean, it works. :P

As you noticed, the documentation is lacking, AFAIK this is always the case, and I suspect that `/json/list` is sorted by recency. If you plan to only support Chrome you should be fairly sure that this is reliable.

**Comment by cyrus-and** [comment]
Closing this, feel free to comment if you have further questions.
