### ISSUE TITLE
nodeHighlightRequested did not trigger

### ISSUE THREAD

**Issue by Rabbitzzc** [cyrus-and/chrome-remote-interface#532]
```ts
Overlay.on('inspectNodeRequested', (params) => {
      console.error('inspectNodeRequested params ', params);
    });
    Overlay.on('nodeHighlightRequested', (params) => {
      console.error('nodeHighlightRequested params ', params.nodeId);
    });
    await Overlay.setInspectMode({
      mode: 'searchForNode',
      highlightConfig: TEST_HIGHLIGHT_CONFIG,
    });
```
When the mouse slides over the webview, the nodeHighlightRequested event is not triggered; 
But the inspectNodeRequested event is triggered  when mouse click...

**Comment by cyrus-and** [comment]
I have no idea, you might want to file an [upstream issue](https://crbug.com) or to ask this in the [Google Group](https://groups.google.com/forum/#!forum/chrome-debugging-protocol), feel free to post the link here if you decide to do so.
