### ISSUE TITLE
question - does this work with multiple concurrent contexts/sessions?

### ISSUE THREAD

**Issue by dgtlmoon** [cyrus-and/chrome-remote-interface#533]
Cool project!

question - does this work with multiple concurrent contexts/sessions?

## Environment

Chrome, node, linux

**Comment by cyrus-and** [comment]
Yes, of course. Each [`CDP`](https://github.com/cyrus-and/chrome-remote-interface#class-cdp) instance represents a session.

But you might want to use a [browser target](https://github.com/cyrus-and/chrome-remote-interface/issues/531#issuecomment-1504905469) to manage them.

**Comment by dgtlmoon** [comment]
amazing! thanks for the info :)
