### ISSUE TITLE
Property 'redirectHasExtraInfo' is missing in type

### ISSUE THREAD

**Issue by slhck** [cyrus-and/chrome-remote-interface#535]
## Environment

| Component | Version
|-|-
| Node.js						| 18
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| macOS
| OS running the client			| macOS
| chrome-remote-interface		| 0.32.2
| devtools-protocol                          | 0.0.1165779

Is the client running in a container? NO

## Description

A type property seems to be missing?

`
Property 'redirectHasExtraInfo' is missing in type 'import("./node_modules/@types/chrome-remote-interface/node_modules/devtools-protocol/types/protocol").Protocol.Network.RequestWillBeSentEvent' but required in type 'import("./node_modules/devtools-protocol/types/protocol").Protocol.Network.RequestWillBeSentEvent'.ts(2741)
protocol.d.ts(11401, 13): 'redirectHasExtraInfo' is declared here.
`

## Example

```typescript
import { Protocol } from 'devtools-protocol';
import CDP from 'chrome-remote-interface';

async function init() {
  let lastRequest: Protocol.Network.RequestWillBeSentEvent;

  const client: CDP.Client = await CDP();

  client.Network.requestWillBeSent((request) => {
    lastRequest = request;
    // ^---------- error here
  });
}
```

/cc @westy92 @kazarmy

I hope it's fine to post this type issue here? I see no issues related to `chrome-remote-interface` in https://github.com/DefinitelyTyped/DefinitelyTyped, and I am not sure anyone would be monitoring the discussion forum …

**Comment by cyrus-and** [comment]
> I hope it's fine to post this type issue here?

Sure, even though I'm not responsible for that kind of issues.

**Comment by kazarmy** [comment]
> `Property 'redirectHasExtraInfo' is missing in type 'import("./node_modules/@types/chrome-remote-interface/node_modules/devtools-protocol/types/protocol").Protocol.Network.RequestWillBeSentEvent'` ...

@slhck Apparently you have a `node_modules` directory within a `node_modules` directory. My suggestion to fix this is:

1. `npm uninstall devtools-protocol @types/chrome-remote-interface`
2. `npm install @types/chrome-remote-interface`
3. Follow the instructions in https://github.com/cyrus-and/chrome-remote-interface#typescript-support for your version of `devtools-protocol` that is other than 0.0.927104

It would be nice if one could just modify permanently the `devtools-protocol` version [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3d5f320ea82cfb2077687560927df712c0da9f9d/types/chrome-remote-interface/package.json#L4) but I'm not sure whether there is a simple way to do that that survives package updates.

**Comment by slhck** [comment]
Thanks, this seems to have done the job:

```
yarn remove chrome-remote-interface @types/chrome-remote-interface devtools-protocol
yarn add chrome-remote-interface @types/chrome-remote-interface
```

I guess the issue arose because at some point an explicit dependency on `devtools-protocol` was added to get the type. (Which apparently is not necessary brcause the version is bundled.)
