### ISSUE TITLE
chrome-remote-interface for mobile chrome

### ISSUE THREAD

**Issue by daddybh** [cyrus-and/chrome-remote-interface#54]
Hi， @cyrus-and I am wondering how to connect mobile chrome within my android device?

I cannot find any clue in the README. Could you advice? thank you.

**Comment by cyrus-and** [comment]
> enable [port forwarding][1] in Chrome for Android

Have you tried that?

[1]: https://developer.chrome.com/devtools/docs/remote-debugging-legacy

**Comment by daddybh** [comment]
thank you @cyrus-and. It works with port forwarding.
