### ISSUE TITLE
How to use SSL websocket with remote debugging?

### ISSUE THREAD

**Issue by honestydeveloper** [cyrus-and/chrome-remote-interface#540]
Hope doing well. I am going to use SSL web socket for remote debugging on Puppeteer. But in regular, we are using ws://127.0.0.1:9222 for the remote debugging.

I will appreciate if you could please help me. Thank you.

ws://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8 to wss://localhost:9222/devtools/browser/b0b8a4fb-bb17-4359-9533-a8d9f3908bd8

**Comment by cyrus-and** [comment]
I'm not sure I understand... You can't just use SSL, Chrome listens on `ws:` not `wss:`. Your best bet is to set up a proxy in the middle then use the [`secure` option](https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback) when using this library.

**Comment by honestydeveloper** [comment]
Would you like to explain more detail how can I use "secure" property ?
https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback

**Comment by cyrus-and** [comment]
Basically if you want to use SSL you have to do the secure proxying yourself (it can't work out-of-the-box), then set the `secure` option to `true` when using this library.
