### ISSUE TITLE
failed to load response, no resource with given identifier found

### ISSUE THREAD

**Issue by wudidehuangtiandi** [cyrus-and/chrome-remote-interface#544]
We want to listen to the target path and get the return value. There is a nearly half chance that it will fail to load the response and no resource with given identifier found will appear. This path will not have this problem on google browser debugging. Can someone help us understand what is going on? Please help me with the preceding paragraph.

```js
const chrome = await CDP();
const { Network } = chrome;
await Network.enable();
Network.responseReceived(async (params) => {
  if (params.type == "Preflight") return;
  if (params.response.url === "urlxxxxx") {
    Network.loadingFinished({ requestId: params.requestId }).then(
      async (info) => {
        const response = await Network.getResponseBody({
          requestId: params.requestId,
        });
        const goodsList = JSON.parse(response.body).result.goods_list;
        mainWindow.webContents.send(
          "send-goods-list",
          JSON.stringify(goodsList)
        );
      }
    );
  }
});
```

**Comment by cyrus-and** [comment]
`Network.loadingFinished` is an event, so it either takes a callback function, or it returns a promise. Please refer to the documentation.

**Comment by wudidehuangtiandi** [comment]
Sry Sorry, I gave the wrong code version. This is the current code
`const chrome = await CDP();
const { Network } = chrome;
await Network.enable();
Network.responseReceived(async (params) => {
  if (params.type == "Preflight") return;

if (
      params.response.url ===
      "https://xxx"
    ) {
      Network.loadingFinished().then(
        async (info) => {
          const response = await Network.getResponseBody({
            requestId: params.requestId,
          })
          const goodsList = JSON.parse(response.body).result.goods_list
          mainWindow.webContents.send(
            "send-goods-list",
            JSON.stringify(goodsList)
          )
        }
      ).catch((error) => {
        console.log('error', error)
      })
    } `

  ); `

**Comment by wudidehuangtiandi** [comment]
Sorry, I gave the wrong code version. This is the current code




const chrome = await CDP();
const { Network } = chrome;
await Network.enable();
Network.responseReceived(async (params) => {
  if (params.type == "Preflight") return;

if (
      params.response.url ===
      "https://xxx"
    ) {
      Network.loadingFinished().then(
        async (info) => {
          const response = await Network.getResponseBody({
            requestId: params.requestId,
          })
          const goodsList = JSON.parse(response.body).result.goods_list
          mainWindow.webContents.send(
            "send-goods-list",
            JSON.stringify(goodsList)
          )
        }
      ).catch((error) => {
        console.log('error', error)
      })
    } `

  );

**Comment by wudidehuangtiandi** [comment]
Sorry, I gave the wrong code version. This is the current code
`const chrome = await CDP();
const { Network } = chrome;
await Network.enable();
Network.responseReceived(async (params) => {

if (
      params.response.url ===
      "https://xxx"
    ) {
      Network.loadingFinished().then(
        async (info) => {
          const response = await Network.getResponseBody({
            requestId: params.requestId,
          })
          const goodsList = JSON.parse(response.body).result.goods_list
          mainWindow.webContents.send(
            "send-goods-list",
            JSON.stringify(goodsList)
          )
        }
      ).catch((error) => {
        console.log('error', error)
      })
}
    }) `

**Comment by cyrus-and** [comment]
You can edit your comments you know...

BTW if you can come up with a standalone reproducible example (meaning that I can just run it and see the issue), then I might take a look, otherwise this is too messy.
