### ISSUE TITLE
Unable to Run SystemInfo.getProcessInfo; Browser Target not listed in Target.getTargets

### ISSUE THREAD

**Issue by saaraahfar** [cyrus-and/chrome-remote-interface#545]
Issue:
When attempting to run the SystemInfo.getProcessInfo method, I am encountering an error stating "SystemInfo.getProcessInfo is only supported on the browser target". When running Target.getTargets to list available targets, the browser target is not returned in the list. The documentation does not provide clear guidance on how to capture the browser target to run this method.

Steps to Reproduce:
1. Launch Chrome with remote debugging enabled.
2. Connect to Chrome using chrome-remote-interface.
3. Run Target.getTargets to list available targets.
4. Attempt to call SystemInfo.getProcessInfo on a page or frame target.

Expected Result:
Able to retrieve process information.

Actual Result:
Error: "SystemInfo.getProcessInfo is only supported on the browser target".

##Environment:
- OS: Linux Mint 21.2
- Node.js version: v20.5.1
- tested on Chrome 98.102 and Chrome 117.0.5938.132 
- chrome-remote-interface version:  v0.33.0

I would appreciate any guidance or updated documentation on how to capture the browser target to run SystemInfo.getProcessInfo. 

Is the client running in a container? NO

## Example

```js
const CDP = require('chrome-remote-interface');

async function getProcessInfo() {
  let client;
  try {
    client = await CDP({ port: 9222 });
    // if we run Target.getTargets in this stage it wouldn't return a entry with type "browser" the same way that explained here: https://github.com/aslushnikov/getting-started-with-cdp/blob/master/README.md 
    
    await client.Runtime.enable();
    await client.Page.enable();
    const processInfo = await client.SystemInfo.getProcessInfo();

    console.log(processInfo);
  } catch (err) {
    console.error(err);
  }
}

getProcessInfo();

```

**Comment by cyrus-and** [comment]
That target is different from all the others. Manually, the URL can be obtained from the Chrome output, you'll see something like the following in your terminal:

```
DevTools listening on ws://127.0.0.1:9222/devtools/browser/36ae5218-0f94-436c-a1a3-452a9b24a673
```

Programmatically instead, it can be obtained with the [`Version`](https://github.com/cyrus-and/chrome-remote-interface#cdpversionoptions-callback) DevTools method, for example:

```js
const {webSocketDebuggerUrl: target} = await CDP.Version();
const browserClient = await CDP({target});
```

Hope it helps!
