### ISSUE TITLE
chrome-remote-interface activate returns not found for Firefox

### ISSUE THREAD

**Issue by farzadmf** [cyrus-and/chrome-remote-interface#546]
## Environment

| Component | Version
|-|-
| Node.js | v21.1.0
| Client (Chrome/Chromium/...)	| Firefox
| OS running Node.js | MacOS Venture 13.6
| OS running the client | MacOS Venture 13.6
| chrome-remote-interface | 0.33.0

Is the client running in a container?  NO

## Description

I'm starting Firefox using `--remote-debugging-port=9223`. When I try to `activate` a tab using its `id`, I'm getting a not found error:
```html
Error: <html>                    <head><title>404 Not Found</title></head>                    <body> 
                     <h1>404 Not Found</h1>                      <p>                        <span 
style='font-family: 
monospace;'>&#47;&#106;&#115;&#111;&#110;&#47;&#97;&#99;&#116;&#105;&#118;&#97;&#116;&#101;&#47;&#57
;&#50;&#52;&#53;&#101;&#102;&#53;&#57;&#45;&#52;&#102;&#56;&#55;&#45;&#52;&#97;&#53;&#99;&#45;&#97;&
#98;&#100;&#102;&#45;&#50;&#52;&#51;&#51;&#56;&#55;&#98;&#101;&#50;&#56;&#57;&#49;</span> was not 
found.                      </p>                    </body>                  </html>
```

I'm using the bundled binary to do this and not through code.

## Example

```sh
# Doing this to see the list of URLs/IDs
chrome-remote-interface -p 9223 list | jq '.[] | select(.type == "page") | [.url, .id]'

# Trying to activate one of the IDs
chrome-remote-interface -p 9223 activate <uuid-from-above>

# ... error above appears here ...
```

**Comment by cyrus-and** [comment]
I'm sorry, I cannot reproduce this of version 119. What version of Firefox do you have?

**Comment by cyrus-and** [comment]
What if you do the same with Chrome?

**Comment by farzadmf** [comment]
Hey @cyrus-and , sorry for the delay.

Turns out I was running an old version (long term support, which is 115) of Firefox. Because I could get a list of tabs, I just assumed that things should be working!

I upgraded to 119, and the `activate` function is working.

Thank you for the tool; it's SUPER cool!

**Comment by farzadmf** [comment]
Hey @cyrus-and , hope you're doing great!

Everything was working fine for me on Firefox, but it's been a while recently that the issue is back 🙁 ; I'm getting this error when doing `chrome-remote-interface list -p 9223` (breaking down the lines to avoid the horizontal scroll):
```
Error: <html>                    <head><title>404 Not Found</title></head>   
<body>                      <h1>404 Not Found</h1>                      <p>                        
<span style='font-family: 
monospace;'>&#47;&#106;&#115;&#111;&#110;&#47;&#108;&#105;&#115;&#116;</span> was not found.                      
</p>                    </body>                  </html>
```

I have a Mac, and I'm starting Firefox using a custom script I have:
```
#!/usr/bin/env sh

open -a Firefox --args --remote-debugging-port=9223
```

And when Firefox loads, the address bar has a "background color" and the robot face to let me know it's running "differently" and "under remote control"
![image](https://github.com/user-attachments/assets/85aaa9fd-d12b-49d6-804b-6b018b755e73)

Is there anything I can look into to troubleshoot?

**Comment by cyrus-and** [comment]
So let's strip chrome-remote-interface away from this. Apparently the `/json/*` endpoints are not served by Firefox anymore (?). If you start it directly, i.e., not with `open` you can see that it mentions a `WebDriver BiDi` WebSocket:

```
$ /Applications/Firefox.app/Contents/MacOS/firefox --remote-debugging-port
WebDriver BiDi listening on ws://127.0.0.1:9222
```

But I'm unable to connect to it apparently:

```
$ npx wscat -c ws://127.0.0.1:9222
error: Unexpected server response: 200
```

But according to the [documentation](https://firefox-source-docs.mozilla.org/remote/index.html#webdriver-bidi-header) this is not what we want here:

> [The WebDriver BiDi specification](https://w3c.github.io/webdriver-bidi) extends WebDriver HTTP to add bidirectional communication. Dedicated documentation will be added as the Firefox implementation makes progress.

The same page mentions the [CDP](https://firefox-source-docs.mozilla.org/remote/cdp/) actually, and it still says that the `/json/*` endpoints should work. It also [mentions](https://firefox-source-docs.mozilla.org/remote/cdp/RequiredPreferences.html) that some settings needs to be changed in order to keep using the CDP:

- `fission.bfcacheInParent` should be set to `false`.

- `fission.webContentIsolationStrategy` should be set to `0`.

But they have no effect at this stage.

Moreover, always according to the above documentation, the expected output should be different (maybe it's outdated):

```
% firefox --remote-debugging-port
DevTools listening on ws://localhost:9222/devtools/browser/7b4e84a4-597f-4839-ac6d-c9e86d16fb83
```

(Instead of `WebDriver BiDi`.)

I suggest you to ping someone at Firefox to figure out this mess...

**Comment by farzadmf** [comment]
Oh wow, thank you @cyrus-and for the super detailed answer. I thought it's gonna be the case of you telling me the obvious thing I've missed, but seems like it's a real issue.

> I suggest you to ping someone at Firefox to figure out this mess...
Not even sure how I can do that 😆

**Comment by jonnytest1** [comment]
are there any new findings on this ? i have the same problem

**Comment by farzadmf** [comment]
Not on my side, I basically gave up on Firefox, unfortunately

**Comment by nenahp** [comment]
cdp removed in firefox 0.141+ https://fxdx.dev/deprecating-cdp-support-in-firefox-embracing-the-future-with-webdriver-bidi/#:~:text=But%20starting%20with%20Firefox%20141%20our%20experimental%20CDP%20support%20is%20now%20fully%20gone.
