### ISSUE TITLE
How to evaluate javascript inside an iframe?

### ISSUE THREAD

**Issue by BeatBroccoli** [cyrus-and/chrome-remote-interface#552]
## Environment

| Component | Version
|-|-
| Node.js						| v20.11.1
| Client (Chrome/Chromium/...)	| Google Chrome 122
| OS running Node.js			| Windows 11
| OS running the client			| Windows 11
| chrome-remote-interface		| 0.33.0

Is the client running in a container? NO

## Description
I cant find a way to click a checkbox inside an iframe, I tried many many things but none seems to be working!
In puppeteer it can be done but here I cant figure it out.
Thanks

## Example
```js
    import * as chromeLauncher from 'chrome-launcher';
    import CDP, * as cri from 'chrome-remote-interface';

    let chrome = await chromeLauncher.launch();
    let client = await cri.default({ port: chrome.port });

    const { Runtime, Page, Target, Network } = client;
    await Promise.all([Page.enable(), Runtime.enable()]);
    await Target.setAutoAttach({ autoAttach: true, waitForDebuggerOnStart: false });
    client.Target.targetCreated(({ targetInfo }) => { console.log(`New target created: ${targetInfo.url}`); });

    await Page.navigate({ url: 'https://example.com/pagewithiframe/' });
    await new Promise(res => setTimeout(res, 3000));

    const targets = (await Target.getTargets()).targetInfos;
    for (let tid in targets) {
        try {
            const { sessionId } = await Target.attachToTarget({ targetId: targets[tid].targetId });
            await Runtime.evaluate({ expression: '(() => { alert("JS! "' + document.location.href + '); debugger; })()' }, sessionId);
        } catch (err) {
            console.error(tid, err)
        }
    }
```

**Comment by BeatBroccoli** [comment]
Context id doesnt seem to be working
```
const frameTree = await Page.getFrameTree();
const iframeFrame = frameTree.frameTree.childFrames.find(frame => frame.frame.url.indexOf('frame.html') > 0);
const contentDocument = await Runtime.evaluate({
     expression: '(function() { alert("Press F12"); debugger; })()',
     returnByValue: false,
     contextId: iframeFrame.frame.id,
     allowUnsafeEvalBlockedByCSP: true
});
```

**Comment by cyrus-and** [comment]
Does this help? https://github.com/cyrus-and/chrome-remote-interface/issues/276#issuecomment-334162378

**Comment by BeatBroccoli** [comment]
Dunno, I was trying with that right now

**Comment by BeatBroccoli** [comment]
Is that the only way or are there better ways? This kind of approach presumes the track of every context, what if i have many iframes? The data provided by context is kinda generic...

```
{
  context: {
    id: 2,
    origin: "https://applive.cloud",
    name: "",
    uniqueId: "-6994244425873745744.6102053809077439231",
    auxData: {
      isDefault: true,
      type: "default",
      frameId: "BDE1E7573F526A00E54C3AABF03CDA2A",
    },
  },
}
```

**Comment by cyrus-and** [comment]
You can keep track of frames and use that `frameId` field.

**Comment by BeatBroccoli** [comment]
Thanks! Porcoddio 🤣

**Comment by BeatBroccoli** [comment]
Was trying the other suggested methods from a new tab but seems like contextId is missing from Page.getFrameTree
and Page.frameAttached never get triggered... what Im doing wrong? Thanks again

```
import * as chromeLauncher from 'chrome-launcher';
import CDP, * as cri from 'chrome-remote-interface';

(async () => {

    let chrome = await chromeLauncher.launch({ port: 9500 });
    let client = await cri.default({ port: chrome.port });

    const { Runtime, Page, Target, DOM, Network } = client;
    await Promise.all([Page.enable(), Runtime.enable(), DOM.enable()]);
    await Target.setAutoAttach({ autoAttach: true, waitForDebuggerOnStart: false });

    // Runtime.executionContextCreated(async (evt) => {
    //     console.warn('executionContextCreated', evt);
    //     let contextId = evt.context.id;
    //     await Runtime.callFunctionOn({
    //         executionContextId: contextId, awaitPromise: true,
    //         functionDeclaration: 'function() { document.body.innerHTML += "executionContextCreated<br>" }',
    //     });
    //     console.warn(href);
    // });
    // await Target.targetCreated(async (targetInfo) => {
    //     console.warn(`New target created`, targetInfo);
    // });

    const targetId = (await Target.createTarget({ url: 'about:blank' })).targetId;
    const sessionId = (await Target.attachToTarget({ targetId: targetId, flatten: true })).sessionId;

    Page.frameAttached(function () {
        console.log('frameAttached', arguments);
    });

    await Page.navigate({ url: 'https://applive.cloud/temp/frame/' }, sessionId);
    await new Promise(res => setTimeout(res, 2000));

    try {
        const frames = (await Page.getFrameTree(sessionId)).frameTree;
        for (let fid in frames.childFrames) {
            console.log('Found frames:', JSON.stringify(frames, null, 2));
            await Runtime.callFunctionOn({
                executionContextId: frames.childFrames[fid].frame.contextId,
                functionDeclaration: 'function() { document.body.innerHTML += "execution from childframes<br>" }',
                awaitPromise: true
            });
        }
    } catch (err) {
        console.error(err)
    }

})();
```

**Comment by BeatBroccoli** [comment]
Here how to do it from a new tab. Seems to be working. Next will try getFrameTree and FrameAttached

```
import * as chromeLauncher from 'chrome-launcher';
import CDP, * as cri from 'chrome-remote-interface';

(async () => {

    let chrome = await chromeLauncher.launch({ port: 9500 });
    let client = await cri.default({ port: chrome.port });

    const { Runtime, Page, Target } = client;

    const targetId = (await Target.createTarget({ url: 'about:blank' })).targetId;
    const sessionId = (await Target.attachToTarget({ targetId: targetId, flatten: true })).sessionId;

    await Promise.all([
        Page.enable({}, sessionId),
        Runtime.enable({}, sessionId)
    ]);

    Runtime.executionContextCreated(sessionId, async (evt) => {
        await Runtime.callFunctionOn({
            executionContextId: evt.context.id,
            functionDeclaration: 'function() { let $box = document.querySelector("input"); if($box) $box.click(); return $box; }'
        }, sessionId);
    });

    await Page.navigate({ url: 'https://applive.cloud/temp/frame/' }, sessionId);
    await new Promise(res => setTimeout(res, 2000));

})();
```

**Comment by BeatBroccoli** [comment]
How can i get the contextId or something else using Page.getFrameTree? Becouse contextId is missing from there...

import * as chromeLauncher from 'chrome-launcher';
import CDP, * as cri from 'chrome-remote-interface';

import http from 'node:http';
const requestListener = function (req, res) {
    if (req.url.indexOf('frame') > 0) res.end('<html> <head> <title>Frame</title> </head> <body> <div> <label><input type="checkbox"> Click this checkbox!</label> </div> </body> </html>');
    else res.end('<html> <head> <title>Main</title> </head> <body> <iframe src="./frame.html" style="border-radius: 15px; margin: 20px"></iframe> </body> </html>');
};
const server = http.createServer(requestListener);
server.listen(3000, 'localhost', () => { console.log(`Mock server running`); });

(async () => {

    let chrome = await chromeLauncher.launch({ port: 9500 });
    let client = await cri.default({ port: chrome.port });

    const { Runtime, Page, Target } = client;

    const targetId = (await Target.createTarget({ url: 'about:blank' })).targetId;
    const sessionId = (await Target.attachToTarget({ targetId: targetId, flatten: true })).sessionId;

    await Promise.all([
        Page.enable({}, sessionId),
        Runtime.enable({}, sessionId)
    ]);

    Runtime.executionContextCreated(sessionId, async (evt) => {
        await Runtime.callFunctionOn({
            executionContextId: evt.context.id,
            functionDeclaration: 'function() { let $box = document.querySelector("input"); if($box) $box.click(); return $box; }'
        }, sessionId);
    });

    await Page.navigate({ url: 'http://localhost:3000' }, sessionId);
    await new Promise(res => setTimeout(res, 2000));

    try {
        const frames = (await Page.getFrameTree({}, sessionId)).frameTree;
        for (let fid in frames.childFrames) {
            console.log('Found frames:', JSON.stringify(frames, null, 2));
            await Runtime.callFunctionOn({
                executionContextId: frames.childFrames[fid].frame.contextId,
                functionDeclaration: 'function() { document.body.innerHTML += "execution from childframes<br>" }',
                awaitPromise: true
            });
        }
    } catch (err) {
        console.error(err)
    }

})();

**Comment by cyrus-and** [comment]
You get the `contextId` from the `Runtime.executionContextCreated` event, then you can walk the frame tree (`Page.getFrameTree`) to find out additional information about the frame and decide if that's the frame you want.
