### ISSUE TITLE
Does this work in Bun?

### ISSUE THREAD

**Issue by aleclarson** [cyrus-and/chrome-remote-interface#555]
…or is there support for Bun planned? Thanks.

**Comment by aleclarson** [comment]
Looks like a problem with Bun. Tracking it here: https://github.com/oven-sh/bun/issues/9505

**Comment by cyrus-and** [comment]
Thanks for linking the issue, it might help others.

In any case, there's no plan to explicitly support other runtimes, unless the change is trivial.
