### ISSUE TITLE
Removing event subscriptions on Domain

### ISSUE THREAD

**Issue by himat** [cyrus-and/chrome-remote-interface#556]
## Environment

| Component | Version
|-|-
| Node.js						| v20.9.0
| Client (Chrome/Chromium/...)	| Chromium
| OS running Node.js			| MacOS
| OS running the client			| MacOS
| chrome-remote-interface		| 0.33.0
| @types/chrome-remote-interface | 0.31.14

Is the client running in a container? NO

## Description
Hi, I'm wondering if there is a way or even a need to remove event listeners on domains 
e.g. if I have:
```
    const { Page } = client
    Page.on("lifecycleEvent", navEventListener)
```
In Puppeteer or Electron, you would usually call `.addEventListener` and then `.removeEventListener` to clean up when your scope is over.

I saw https://github.com/cyrus-and/chrome-remote-interface/issues/93 but that seems to only exist for cleaning up on event on the `client` itself, but in this case, I'm listening to an event on the `Page` domain and it doesn't seem like there's a function stop listening? Is this correct?

**Comment by cyrus-and** [comment]
I mean, you could've tried... also #93 is about the `HeapProfiler` domain. Events on domains are still events on the client, in that issue you can see the equivalence of the two forms (also documented in the README).

Additionally, a [third form](https://github.com/cyrus-and/chrome-remote-interface?tab=readme-ov-file#clientdomaineventsessionid-callback) provides a more convenient way.

Hope it helps.
