### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by slhck** [cyrus-and/chrome-remote-interface#561]
Could we please get a new release to fix https://github.com/advisories/GHSA-3h5v-q93c-6h6q (which has been fixed in https://github.com/cyrus-and/chrome-remote-interface/commit/56d269a88acb8454d1774f0a38b3fcc11d898fd3)? Thanks!

**Comment by cyrus-and** [comment]
Here it is: [v0.33.2](https://www.npmjs.com/package/chrome-remote-interface/v/0.33.2)

**Comment by slhck** [comment]
That was super quick, thank you! 🎉

**Comment by slhck** [comment]
I noticed this is still probably not entirely fixed, because in your `package.json` your dependencies have `ws` at 7.2.0:

https://github.com/cyrus-and/chrome-remote-interface/blob/6aaee210008369b9f0299c3b4e605edc61ff5e3c/package.json#L31

Since all versions < 7.5.10 are affected, you may want to bump this too.

**Comment by cyrus-and** [comment]
It's the `package-lock.json` that matters, no? Versions in the `package.json` are more about functional requirements.

**Comment by slhck** [comment]
You're right. I think the dependency was not updated when simply bumping `chrome-remote-interface` in `package.json`, because it thought it already fulfilled its `ws` dependency — it required a `yarn upgrade`. (Not your fault, more to do with the way `yarn` works and bumps its deps.)
