### ISSUE TITLE
Open devtools for android web view programmatically

### ISSUE THREAD

**Issue by mustafa0x** [cyrus-and/chrome-remote-interface#562]
Hi, I'm trying to automate opening devtools for android webviews. Currently I go to `chrome://inspect` and click inspect on my device, but that takes a lot of time throughout the day. So, I want to open devtools using cli.

So far I have this,

```
devtools_port=$(adb shell "cat /proc/net/unix" | rg 'webview_devtools_remote_([0-9]+)' -or '$1')
adb forward tcp:9222 localabstract:webview_devtools_remote_${devtools_port}
open -n -a "Google Chrome" $(chrome-remote-interface list | jq -r .[0].devtoolsFrontendUrl)
```

However it tells me "Debugging connection was closed. Reason: WebSocket disconnected"

![image](https://github.com/user-attachments/assets/af900344-c4dc-4fa7-b5d2-08cfeed37ae0)

Related issue: https://github.com/cyrus-and/chrome-remote-interface/issues/473

**Comment by cyrus-and** [comment]
Not sure how is this related to chrome-remote-interface. The `list` command is merely returning data from `/json/list`.

**Comment by mustafa0x** [comment]
Thanks for the reply. I assumed that chrome-remote-interface might be able to help with this, especially when I saw #473.

So chrome-remote-interface can't help here?

**Comment by cyrus-and** [comment]
You _could_ use chrome-remote-interface to interact with the target, as seen in #473, just remember to use `-l` to use the local version of the protocol, since Chrome for Android doesn't come with it.

But that's another story, what you're trying to do should work, I can reproduce your issue (even with regular Chrome pages; I don't have any WebView to test). The cause was this:

```
Rejected an incoming WebSocket connection from the devtools://devtools origin. Use the command line flag --remote-allow-origins=devtools://devtools to allow connections from this origin or --remote-allow-origins=* to allow all origins.
```

Not sure how to go about it with Android.

**Comment by mustafa0x** [comment]
Truly appreciate your help. I tried adding that argument, but same exact error ("WebSocket disconnected").

```bash
devtools_port=$(adb shell "cat /proc/net/unix" | rg 'webview_devtools_remote_([0-9]+)' -or '$1')
adb forward tcp:9222 localabstract:webview_devtools_remote_${devtools_port}
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
  $(chrome-remote-interface list | jq -r .[0].devtoolsFrontendUrl) \
  --args --remote-allow-origins=*
```

If interested, I could build you a plain capacitorjs APK in debug mode, so that chrome://inspect can open it.

**Comment by cyrus-and** [comment]
That flag should be passed to Chrome on Android, or the WebView in your case. Of course passing a flag to a WebView makes no sense, maybe there's something to put in the manifest.

**Comment by mustafa0x** [comment]
Thanks again. It's strange that this is all needed, while `chrome://inspect` lists all devices without any steps, and with a single click opens the inspector.

I added a break point to `chrome://inspect` and saw this data passed to the callback.

![image](https://github.com/user-attachments/assets/44445a5d-4a34-444e-b9db-da0a466f8b41)

Don't see how that helps. I'll try to ask the Chrome team directly how to programmatically open a device listed on `chrome://inspect`.

**Comment by cyrus-and** [comment]
Yes, it's strange indeed, and I'm pretty sure it used to work the way you describe, i.e., passing the `ws=` query parameter; it must be a recent change.
