### ISSUE TITLE
How to change navigator.deviceMemory value 

### ISSUE THREAD

**Issue by eejeet** [cyrus-and/chrome-remote-interface#563]
## Environment

| Component | Version
|-|-
| Node.js						| 18
| Client (Chrome/Chromium/...)	| Chrome
| OS running Node.js			| Node.js
| OS running the client			| Windows/MAC
| chrome-remote-interface		| 0.33.2

how to change  navigator.deviceMemory  value emulation in not found any thing please help me

**Comment by cyrus-and** [comment]
I don't think you can do that, AFAIK, all you can do is to throttle the CPU and the network.

Feel free to comment here if you find a way.
