### ISSUE TITLE
Error Message "SystemInfo.getInfo wasn't found"

### ISSUE THREAD

**Issue by dwcIntegral** [cyrus-and/chrome-remote-interface#57]
Hi there,

I am trying to access the `SystemInfo` through the chrome-remote-interface, and when running the code snippet pasted below I get the following return values:

returnValue1 = `true`
returnValue2 = `{ code: -32601, message: '\'SystemInfo.getInfo\' wasn\'t found' }`

While I understand that `systemInfo` is experimental currently in the [tip-of-tree](https://chromedevtools.github.io/debugger-protocol-viewer/tot/SystemInfo/) API,  I am trying to figure out if the returned error is from the chrome-remote-interface, or from the remote debugging protocol itself as I had hard time tracking down this error code in either.. 

My hunch is the later, but just wanted to confirm. Any info you could provide here would be greatly appreciated. Thanks again.

Code Snippet ran to gather SystemInfo..

```
var Chrome = require('chrome-remote-interface');

Chrome(function (chrome) {
    with (chrome) {
        
Page.enable();

        Page.navigate({'url': 'http://example.com'});

        Page.loadEventFired(function () {

            SystemInfo.getInfo(function(returnValue1, returnValue2, returnValue3) {
                console.log(returnValue1, returnValue2, returnValue3);
                close();
            });
        });
    }
}).on('error', function (e) {
    console.error('Cannot connect to Chrome', e);
});
```

**Comment by cyrus-and** [comment]
The problem is that your Chrome version does not support the `SystemInfo` module, even though it is present in the tip-of-tree version and also in the [local protocol.json][1] (which is used by default).

You can check this by inspecting with the `--remote` oprion:

```
$ chrome-remote-interface inspect -r
>>> SystemInfo.getInfo
ReferenceError: SystemInfo is not defined
[...]
```

Versus:

```
$ chrome-remote-interface inspect
>>> SystemInfo.getInfo
{ [Function: override]
[...]
```

So in short you need to upgrade your Chrome version in order to use that feature.

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/eca96b8e93737e640d6928773a2fc8fc5d6c355d/lib/protocol.json

**Comment by dwcIntegral** [comment]
Hey @cyrus-and, 

Thanks for the quick reply, wanted to confirm that I just upgraded to the latest chrome ( Version 54.0.2840.71 (64-bit) ), and am still receiving the same error code posted above when trying to retrieve the SystemInfo..

I can also confirm when inspecting with the remote option, `SystemInfo` is defined, and when I execute the `SystemInfo.getInfo` method from the command line I get the same error, please see below..

```
$ chrome-remote-interface inspect -r
>>> SystemInfo.getInfo
{ [Function]
  category: 'command',
  async: true,
  description: 'Returns information about the system.',
  returns:
   [ { name: 'gpu',
       '$ref': 'GPUInfo',
       description: 'Information about the GPUs on the system.' },
     { name: 'modelName',
       type: 'string',
       description: 'A platform-dependent description of the model of the machine. On Mac OS, this is, for example, \'MacBookPro\'. Will be the empty string if not supported.' },
     { name: 'modelVersion',
       type: 'string',
       description: 'A platform-dependent description of the version of the machine. On Mac OS, this is, for example, \'10.1\'. Will be the empty string if not supported.' } ],
  handlers: [ 'browser' ] }
>>> SystemInfo.getInfo();
{ error:
   { code: -32601,
     message: '\'SystemInfo.getInfo\' wasn\'t found' } }
```

And when inspecting without the remote option I also get the following:

```
$ chrome-remote-interface inspect
>>> SystemInfo.getInfo
{ [Function]
  category: 'command',
  async: true,
  description: 'Returns information about the system.',
  returns:
   [ { name: 'gpu',
       '$ref': 'GPUInfo',
       description: 'Information about the GPUs on the system.' },
     { name: 'modelName',
       type: 'string',
       description: 'A platform-dependent description of the model of the machine. On Mac OS, this is, for example, \'MacBookPro\'. Will be the empty string if not supported.' },
     { name: 'modelVersion',
       type: 'string',
       description: 'A platform-dependent description of the version of the machine. On Mac OS, this is, for example, \'10.1\'. Will be the empty string if not supported.' } ],
  handlers: [ 'browser' ] }
```

In this case still just trying to find the source of the issue, any feedback would greatly appreciated, thanks again.

**Comment by cyrus-and** [comment]
Yes, you're right, I'm using the same version and that's exactly what happens.

But I'm afraid this has little to do with this module, as [you can see][1] that method is present in the protocol descriptor of that version, yet Chrome refuses to execute it.

You should probably file a bug against [Chromium][2] or look for help in the [mailing list][3].

FYI the same happens with `56.0.2897.0`.

[1]: https://chromium.googlesource.com/chromium/src/+/54.0.2840.71/third_party/WebKit/Source/core/inspector/browser_protocol.json#4457
[2]: https://bugs.chromium.org
[3]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by dwcIntegral** [comment]
Yes, I agree, that is what I was afraid of, thanks again for the quick responses and all of your help here!
