### ISSUE TITLE
How to Fix the Error "Cannot connect to Chrome: Error: socket hang up"?

### ISSUE THREAD

**Issue by desvu** [cyrus-and/chrome-remote-interface#58]
C:\Windows\system32>npm install -g chrome-remote-interface

C:\Program Files (x86)\Google\Chrome\Application>chrome --remote-debugging-port=9222

C:\Windows\system32>chrome-remote-interface inspect --host localhost --port 9222
**Cannot connect to Chrome: Error: socket hang up**

C:\Windows\system32>node -v
v6.9.1

C:\Windows\system32>npm -v
3.10.8

C:\Windows\system32>git --version
git version 2.10.1.windows.1

Browser: Chrome/54.0.2840.71
Microsoft Windows: Version 10.0.10586

**Comment by cyrus-and** [comment]
Does this also happen if you run the [example][1]?
Please give it a try and paste the full output here.
Thanks.

[1]: https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage

**Comment by desvu** [comment]
Cannot connect to Chrome: { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' }

**Comment by cyrus-and** [comment]
I just tried in your same environment but I'm unable to reproduce this issue.

Can you please check if the HTTP server is up when Chrome is started? Try to navigate to `http://localhost:9222/json` you should see some JSON code.

**Comment by desvu** [comment]
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/b47bb800-efcc-4a58-a6dc-6c40d0f01ad1",
   "faviconUrl": "https://d13yacurqjgara.cloudfront.net/assets/favicon-63b2904a073c89b52b19aa08cebc16a154bcf83fee8ecc6439968b1e6db569c7.ico",
   "id": "b47bb800-efcc-4a58-a6dc-6c40d0f01ad1",
   "thumbnailUrl": "/thumb/b47bb800-efcc-4a58-a6dc-6c40d0f01ad1",
   "title": "Dribbble - Show and tell for designers",
   "type": "page",
   "url": "https://dribbble.com/",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/b47bb800-efcc-4a58-a6dc-6c40d0f01ad1"

   **... Chrome Extensions  ...**
} ]

**Comment by desvu** [comment]
chrome-remote-interface (devtools.js)
/json/list (tab)
/json/new (tab ?url)
/json/activate/ (tab (id tab))
/json/close/ (tab (id tab))
/json/version 
```
{
   "Browser": "Chrome/54.0.2840.71",
   "Protocol-Version": "1.2",
   "User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36",
   "WebKit-Version": "537.36 (@5e302be61aa30f443d8ba24c9ece85e8f6076fb9)"
}
```
/json/protocol
`Unknown command: protocol`

**Comment by cyrus-and** [comment]
Well this is quite strange, everything seem to be OK.

There a couple more things you can try:

1. Install `wscat` via NPM and try to connect to the raw WebSocket directly (the `webSocketDebuggerUrl` field in `http://localhost:9222/json`). For example:

        ...> wscat -c ws://localhost:9222/devtools/page/b47bb800-efcc-4a58-a6dc-6c40d0f01ad1
        connected (press CTRL+C to quit)
        > {"id": 1, "method": "Page.reload"}
        < {"id":1,"result":{}}

    This should reload the tab.

2. Run Node.js in debug mode:

        ...> set NODE_DEBUG=net
        ...> chrome-remote-interface inspect

    You should get a very verbose output.

**Comment by cyrus-and** [comment]
Also, you might want to try with a fresh new Chrome profile. Start it with:

    --no-first-run --disable-extensions --user-data-dir=<some dir here> --remote-debugging-port=9222

**Comment by cyrus-and** [comment]
Did you get any further with this?

**Comment by kimocode** [comment]
Looks like /json/protocol was added in Chrome 60 according to https://chromedevtools.github.io/devtools-protocol/.
