### ISSUE TITLE
Error connecting when using 'iOS WebKit Debug Proxy'

### ISSUE THREAD

**Issue by dwcIntegral** [cyrus-and/chrome-remote-interface#59]
Hi there,

I am currently running into errors when trying to connect the chrome-remote-interface module to the debug server running on 'http://localhost:9222/' when it has been started with the [iOS WebKit Debug Proxy](https://github.com/google/ios-webkit-debug-proxy).

I feel this might be a compatibility issue but just wanted to confirm that I am not missing anything obvious here, since to my understanding the [iOS WebKit Debug Proxy](https://github.com/google/ios-webkit-debug-proxy) uses the Chrome Remote Debugging Protocol and therefore the chrome-remote-interface should be able to connect. Also confirming that I can open the Dev Tools Frontend Url and see the proper network requests from my local iPhone simulator being emitted, so I know that this part is working as expected.

When running this code:

```
var chrome = require('chrome-remote-interface')

var url = 'https://github.com/'
var options = {
    chooseTab: function(tabs) {
      var targetTab = tabs.filter(function(tab) {
        return tab.url == url
      })

      if(targetTab.length) {
        return tabs.indexOf(targetTab[0])
      } 
      
      return 0
    }
  }

chrome(options, function(client) {

  console.log('Connected!');

  client.Page.enable();

  client.once('ready', function () {
      client.Page.navigate({
        'url': 'https://github.com'
      });
  });
}).on('error', function(err) {
  console.error('Cannot connect to IOS:');
  console.log(err);
});
```

I get this error (with no other console messages, it does not make it to the callback):
```
[Error: <html><title>Error 404 (Not Found)</title>
<p><b>404.</b> <ins>That's an error.</ins>
<p>The requested URL <code>/json/list</code> was not found.
</html>]
```

I seems the root of the issue is that the debug server for iwdp returns a 404 error when visiting route 'json/list'. 

My main question is, should  iwdp be providing the route 'json/list' for the chrome-remote-interface to be able to connect, or am I missing something else in setting up this connection?

Thanks again for your help here.

**Comment by cyrus-and** [comment]
Thanks for reporting this in a such accurate way. I always wanted to give IWDP a try but I'm not an iOS user/developer. If you succeed in doing so I can add it to the list of supported implementations.

> My main question is, should iwdp be providing the route 'json/list' for the chrome-remote-interface to be able to connect, or am I missing something else in setting up this connection?

No, it is not mandatory but it's the default. [`chooseTab`][1] will lookup `/json/list` only when a function is provided. You can directly pass the WebSocket URL:

```js
var options = {
    chooseTab: 'ws://localhost:9222/devtools/page/d1ec5032-ee90-4820-bc75-1f6f007edfe8'
}
```

[1]: https://github.com/cyrus-and/chrome-remote-interface#moduleoptions-callback

**Comment by cyrus-and** [comment]
I could make an exception just for IWDP and fetch `/json` instead of `/json/list` or even just fetch `/json` in any case, but I think it would make much more sense to file an issue against IWDP to request the `/json/list` endpoint. I can do it, if the rest works.

**Comment by cyrus-and** [comment]
I've forked IWDP and added that trivial change, if you can compile it yourself try cloning my [`json-list`][1] branch. If everything works I will send a PR.

[1]: https://github.com/cyrus-and/ios-webkit-debug-proxy/tree/json-list

**Comment by dwcIntegral** [comment]
Hey @cyrus-and ,

Thanks again for the help here, explicitly setting `chooseTab` to the WebSocket URL worked like a charm. (In my case visiting "http://localhost:9222/json" shows `webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/1"` I believe this may be the default for IWDP if that helps anyone..).

However, some small issues still presented themselves, like when running the below code snippet:

```
var chrome = require('chrome-remote-interface');

var options = {
  chooseTab: 'ws://localhost:9222/devtools/page/1'
}

chrome(options, function(client) {
  
  console.log('Connected!');

  client.Page.enable();
  client.Profiler.enable();
  client.Profiler.start();

  client.Page.loadEventFired(function () {
    console.log('Enabled - Page Load Fired');

      client.Profiler.stop().then(function(profile) {
          console.log('Profiler Stop Fired', profile);
          client.close();
      });
  });
  
 client.Profiler.setSamplingInterval({ 'interval': 100 }, function () {
      client.Page.navigate({'url': 'http://example.com'});
  });

}).on('error', function(err) {
  console.error('Cannot connect to IOS:');
  console.log(err);
});
```

We never reach the line `console.log('Profiler Stop Fired', profile);`, and I believe it's due to [this issue with IWDP](https://github.com/google/ios-webkit-debug-proxy/issues/86#issuecomment-91132203). Basically the [Chrome DevTools protocol](https://chromedevtools.github.io/debugger-protocol-viewer/) and the  [Safari Inspector protocol](http://trac.webkit.org/browser/trunk/Source/JavaScriptCore/inspector/protocol) diverging at some point. 

I guess at this point (admittedly without testing myself yet), if I had the chrome-remote-interface utilize the correct [Safari Inspector Protocol](https://github.com/mozilla/valence/tree/master/protocol-docs) should the chrome-remote-interface work as expected in this case?

I will do some more playing around with it this weekend on my end and will and let you know my findings, just wanted to hear your thoughts.

Thanks again for your help here..

**Comment by cyrus-and** [comment]
> I guess at this point (admittedly without testing myself yet), if I had the chrome-remote-interface utilize the correct Safari Inspector Protocol should the chrome-remote-interface work as expected in this case?

From the `chrome-remote-interface` perspective, knowing the exact protocol is quite handy but not mandatory. The JSON descriptor is just used to *build* the API but remember that you can always use the *raw* methods for [commands][1] and [events][2]:

```js
chrome.send('UnknownDomain.unknownCommand', params, callback);
chrome.on('UnknownEvent', callback);
```

Surely, it would be nice to have the proper [fetcher][3] for IWDP too. But this will require:

1. an updated code repository from which to fetch the latest protocol (since the implementation does not provide `/json/protocol`);

2. that IWDP provides the `/json/version` endpoint.

I'm confident that both points are easily achievable.

Thanks for your time.

[1]: https://github.com/cyrus-and/chrome-remote-interface#chromesendmethod-params-callback
[2]: https://github.com/cyrus-and/chrome-remote-interface#event-method
[3]: https://github.com/cyrus-and/chrome-remote-interface/blob/0b013161732efd4ec54e78cc1ff765b0ac753e35/lib/devtools.js#L29

---

PS you can use <code>```js</code> to enable the syntax highlighting for your snippets.

**Comment by cyrus-and** [comment]
OK I managed to borrow an iPad and set up everything on my box, the [patch][1] works flawlessly.
Here's the [PR][2].

[1]: https://github.com/cyrus-and/ios-webkit-debug-proxy/commit/d9c7ef7e535ac14159e755591033acd8c6fcefc5
[2]: https://github.com/google/ios-webkit-debug-proxy/pull/171

**Comment by cyrus-and** [comment]
> We never reach the line `console.log('Profiler Stop Fired', profile);`

Well it seems that there is no `Profile` domain available on Safari.

```
$ chrome-remote-interface -p 9223 inspect
>>> Profiler.enable()
{ error: 
   { code: -32601,
     message: '\'Profiler\' domain was not found',
     data: [ { code: -32601, message: '\'Profiler\' domain was not found' } ] } }
```

As you say the two protocols are clearly different, but it is [quite common][1] among implementations.

[1]: https://github.com/cyrus-and/chrome-remote-interface#implementations

**Comment by cyrus-and** [comment]
The PR has been merged into master. The Safari (iOS) support is now official (54a6ad6cbdcaca379ec441b2fcdf611e9cf2e9e5).
Thanks!

I'm closing this issue since it was about the *connection* with IWDP. All the other issues you mentioned are valid, but concern the differences between the Chromium protocol and Safari's.

As a personal TODO I might consider submitting another PR for [point 2][1], I'll keep you posted.

[1]: https://github.com/cyrus-and/chrome-remote-interface/issues/59#issuecomment-257088810

**Comment by dwcIntegral** [comment]
> From the chrome-remote-interface perspective, knowing the exact protocol is quite handy but not mandatory. The JSON descriptor is just used to build the API but remember that you can always use the raw methods for commands and events

Awesome, this all makes sense, and great to know that I can use the raw methods for commands and events.

> The PR has been merged into master. The Safari (iOS) support is now official (54a6ad6).

And yes, this is great news! Thanks again for being so responsive and for all of your help here!

**Comment by lilili87222** [comment]
[WebDebugX](https://www.webdebugx.com) support new version ios 
![Image](https://github.com/user-attachments/assets/47e1733c-ee5f-4555-8deb-95f381b00bdd)
