### ISSUE TITLE
Support Chrome Debugging Protocol version 1.1

### ISSUE THREAD

**Issue by marcelofernandez** [cyrus-and/chrome-remote-interface#6]
Hello,

I guess chrome-remote-interface needs an update, now version 1.1 supports doing some Input (keystrokes and mouse clicks).

https://developers.google.com/chrome-developer-tools/docs/protocol/1.1/

Thank you

**Comment by valaxy** [comment]
What if I want a old version of protocol, how can I change to use it?

**Comment by cyrus-and** [comment]
@valaxy Provided that you have the old `protocol.json` (e.g., taken from an old Blink revision or from some earlier commit of this module) you can simply overwrite the one found in the `lib` directory. Refer to the [README](https://github.com/cyrus-and/chrome-remote-interface#remote-debugging-protocol-versions) for more information.
