### ISSUE TITLE
Unexpected number in JSON at position 458

### ISSUE THREAD

**Issue by danieler1981** [cyrus-and/chrome-remote-interface#61]
I'm receiving an errore when i try to use chrome-remote-interface:

>  at JSON.parse (<anonymous>)
>     at WebSocket.<anonymous> (/Users/danieletassone/WebstormProjects/cri/node_modules/chrome-remote-interface/lib/chrome.js:196:34)
> 

This is the JSON i'm receiving:
`{"method":"Network.requestWillBeSent","params":{"requestId":"87916.125","frameId":"87916.2","loaderId":"87916.2","documentURL":"https://github.com/","request":{"url":"https://github.com/","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh"},"timestamp":397570,616493,"wallTime":1479730888,909882,"initiator":{"type":"other"},"type":"Document"}}`

It happen on OSX + Chrome 54.

**Comment by cyrus-and** [comment]
Well, this is weird... That JSON is invalid indeed, but it is received as is from Chrome. It is using the comma `,` as the decimal separator, instead of the dot `.`, e.g.:

    397570,616493

It looks like a issue with your locale, which is Italian isn't it?

You can try this:

1. install `wscat` or any other WebSocket client:

        npm install -g wscat

2. list all the available WebSockets:

        curl localhost:9222/json | grep webSocketDebuggerUrl

3. pick one and try this:

        wscat -c ws://localhost:9222/devtools/page/e83d8f03-01c6-4e1f-af8a-5b5a98ca8e9e
        connected (press CTRL+C to quit)
        > {"id": 1, "method": "Network.enable"}
        < {"id":1,"result":{}}
        > {"id": 2, "method": "Page.reload"}
        < [...]

    Strings beginning with `>` are the ones that you must issue.

You should now see a bunch of events. For example, one of the latest should be like:

    < {"method":"Network.loadingFinished","params":{"requestId":"1564.49","timestamp":3221.890560,"encodedDataLength":1538.000000}}

Check whether the numbers use the comma or the dot as the decimal separator. In the former case you're having an issue with Chrome itself.

**Comment by danieler1981** [comment]
Ciao Andrea,

At point (3) I was not able to receive any events.
Yes - I have Italian locale setting but I don't think the issue is coming from that point.

Original issue came from Lighthouse (that internally use chrome-remote-interface?):
https://github.com/GoogleChrome/lighthouse/issues/847
One of the guy has the same issue is (https://www.linkedin.com/in/felixzapata) and is not Italian.

**Comment by cyrus-and** [comment]
> At point (3) I was not able to receive any events.

Did you receive the `{"id":1,"result":{}}` as a reply?

Anyway (apart from the Italian locale) I'm in the same environment as yours, but I'm not able to reproduce the issue.

> that internally use chrome-remote-interface?

They used to, now they seem to have switched to their own wrapper. This is most likely an issue with Chrome.

**Comment by danieler1981** [comment]
> Did you receive the {"id":1,"result":{}} as a reply?

No

Ok then I think is better to open a bug in chromium.
I will investigate more to figure out why it happen.

**Comment by danieler1981** [comment]
I just opened Chrome Dev Console, to inspect the Frame as described in the API/Documentation here:

https://developer.chrome.com/devtools/docs/debugger-protocol#remote

The result is the same, at this point i will try to explain at chromium community.

> [2883:775:1122/100715:ERROR:CONSOLE(1557)] "SyntaxError: Unexpected number in JSON at position 94 SyntaxError: Unexpected number in JSON at position 94
>     at JSON.parse (<anonymous>)
>     at WebInspector.MainConnection.dispatch (chrome-devtools://devtools/bundled/inspector.js:4413:154)
>     at WebInspector.MainConnection._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10591:7)
>     at WebInspector.Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:738:185)
>     at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1557:58)
>     at InspectorFrontendAPIImpl._dispatch (chrome-devtools://devtools/bundled/inspector.js:1556:1)
>     at DevToolsAPIImpl._dispatchOnInspectorFrontendAPI (<anonymous>:62:21)
>     at DevToolsAPIImpl.dispatchMessage (<anonymous>:147:14)
>     at <anonymous>:1:13", source: chrome-devtools://devtools/bundled/inspector.js (1557)
>

**Comment by danieler1981** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=667699#

**Comment by cyrus-and** [comment]
Starred, thank you.
