### ISSUE TITLE
Support custom fetch function

### ISSUE THREAD

**Issue by jasonLaster** [cyrus-and/chrome-remote-interface#63]
It would be nice to be able to use a fetch function instead of `fetchObject`.

The motivation is that in a web context, you cannot make a cross origin request to `localhost:9222/json/list` so you need to ping a local server which can request it on your behalf.

Here's what the API would look like

```js
function fetch(http, options, callback) {
  const {host, path, port} = options;
  const url = `http://${host}:${port}${path}`;
  return networkRequest(url).then(res => callback(null, res.content))
}

return CDP.List({ port, fetch })
  .then(tabs => createTabs(tabs, { browser: "chrome", type: "page" }))
  .catch(err => {});
```

Here's a link to a [branch](https://github.com/cyrus-and/chrome-remote-interface/compare/master...jasonLaster:fetcher?expand=1) where I try it out.

Here's another similar API (which is perhaps less obtrusive):

```js
function fetch(http, options, callback) {
  const {host, path, port} = options;
  const url = `http://${host}:${port}${path}`;
  return networkRequest(url).then(res => callback(null, res.content))
}

CDP.setFetcher(fetch);

return CDP.List({ port })
  .then(tabs => createTabs(tabs, { browser: "chrome", type: "page" }))
  .catch(err => {});
```

**Comment by jasonLaster** [comment]
Hey @cyrus-and, just updated the issue description.

We opted to continue using our implementation for the time being so that we would not be blocked. https://github.com/devtools-html/debugger.html/pull/1295.

It would be great to switch over to CRI though. To that end, I can put together another branch which explores the `CDP.setFetcher` API next week. Also open to alternatives. This should be a relatively small patch to land. And is non-breaking.

**Comment by cyrus-and** [comment]
The point is that having a custom fetcher makes no sense from the perspective of CRI as it is supposed to be running within a Node.js context. I mean, even if it would be a tiny patch, it would still be useful for debugger.html only, there is no other valid use case.

It would be easier IMO to move the Chrome Debugging Protocol logic on the backend, which it is there to stay, you just can't get rid of it.

**Comment by jasonLaster** [comment]
Thanks for the reply. 

I'm happy to close this. And I understand that this is another use case you'd need to support. 

I'll see if we can move the HTTP layer to the backend. The websocket will stay in the frintend so there aren't two hops. 

It's also easy for me to fork and support the small patch.
