### ISSUE TITLE
How to get element?

### ISSUE THREAD

**Issue by cailin-lai** [cyrus-and/chrome-remote-interface#64]
I wanna get all image elements from DOM with their attributes, with following code code segments, yes, I can certainly get nodeIds. But when I called it throws "not opened" error.
Could you please show me how to do this? Appreciate!

chrome.DOM.getDocument(function (error, params) {
        chrome.DOM.querySelectorAll({
            'nodeId': params.root.nodeId,
            'selector': 'img'
        }, function () {
            console.log(arguments);
           //throws error here.
            chrome.DOM.getAttributes({'nodeId':46}, function(err3, attr){
                                                console.log(arguments);
            });
        });
    });

**Comment by cyrus-and** [comment]
Apart from hard-coding `46`, your code seems fine to me. I'm unable to reproduce that "not opened" error. The following full example should do what you want (I've just added error checking and the for-each loop):

```js
const CDP = require('chrome-remote-interface');

CDP((chrome) => {
    chrome.DOM.getDocument((error, params) => {
        if (error) {
            console.error(params);
            return;
        }
        const options = {
            nodeId: params.root.nodeId,
            selector: 'img'
        };
        chrome.DOM.querySelectorAll(options, (error, params) => {
            if (error) {
                console.error(params);
                return;
            }
            params.nodeIds.forEach((nodeId) => {
                const options = {
                    nodeId: nodeId
                };
                chrome.DOM.getAttributes(options, (error, params) => {
                    if (error) {
                        console.error(params);
                        return;
                    }
                    console.log(params.attributes);
                });
            });
        });
    });
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by cailin-lai** [comment]
Thank you so much! Yep, it works very well to get the image attributes.
One more question is, how can I get a real javascript element to have more actions, i.e. calculate the image offset (with parentElement) to the screen?
I tried to have "Chrome.DOM.resolveNode", following things were shown
{ object: 
   { type: 'object',
     subtype: 'node',
     className: 'HTMLImageElement',
     description: 'img',
     objectId: '{"injectedScriptId":11,"id":1}' } }
{ object: 
   { type: 'object',
     subtype: 'node',
     className: 'HTMLImageElement',
     description: 'img',
     objectId: '{"injectedScriptId":11,"id":2}' } }

**Comment by cyrus-and** [comment]
Since you're able to retrieve the `RemoteObjectId` (e.g., `objectId: '{"injectedScriptId":11,"id":2}'`) I guess you'll have to experiment with methods that take a `RemoteObjectId` as a parameter: [Runtime.callFunctionOn], [Runtime.getProperties], etc. I never tried that myself though...

You may also want to take a look at [DOM.getBoxModel] for your specific use case.

Anyway, if you're looking for more in-depth information about the protocol I suggest you to drop an email to the [Google Group].

[Runtime.callFunctionOn]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-callFunctionOn
[Runtime.getProperties]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-getProperties
[DOM.getBoxModel]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/DOM/#method-getBoxModel
[Google Group]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by cailin-lai** [comment]
Thank you sir! Appreciate for your patients.
The "DOM.getBoxModel" works for me to get the element offset! i.e. the data looks like following, it can exactly point the way.
{ model: 
   { content: [ 383, 38, 653, 38, 653, 167, 383, 167 ],
     padding: [ 383, 38, 653, 38, 653, 167, 383, 167 ],
     border: [ 383, 38, 653, 38, 653, 167, 383, 167 ],
     margin: [ 383, 38, 653, 38, 653, 167, 383, 167 ],
     width: 270,
     height: 129 } }

**Comment by cailin-lai** [comment]
Thanks!

**Comment by cyrus-and** [comment]
Glad to hear that, you're welcome!

**Comment by UrielCh** [comment]
A modern version of the responce

```typescript
import CDP from 'chrome-remote-interface';

const selector = 'img';
const { root } = await client.DOM.getDocument({ depth: 1 });
const selection = await client.DOM.querySelectorAll({ nodeId: root.nodeId, selector });
console.log('selection', selection);
for (const nodeId of selection.nodeIds) {
    const { attributes } = await client.DOM.getAttributes({ nodeId });
    console.log(`NodeID: ${nodeId}:`, attributes);
    const { outerHTML } = await client.DOM.getOuterHTML({ nodeId });
    console.log(`outerHTML:`, outerHTML);
}
```
