### ISSUE TITLE
get screen image

### ISSUE THREAD

**Issue by zirill** [cyrus-and/chrome-remote-interface#66]
if you can get a screen image?

**Comment by cyrus-and** [comment]
You can use [Page.captureScreenshot], find a complete exaple [here].

[Page.captureScreenshot]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#method-captureScreenshot
[here]: http://www.zackarychapple.guru/chrome/2016/08/24/chrome-headless.html
