### ISSUE TITLE
Mouse click

### ISSUE THREAD

**Issue by zirill** [cyrus-and/chrome-remote-interface#67]
Please example of mouse clicks "dispatchMouseEvent".

PS: Many thanks for all the answers, and create an extensive wiki.

**Comment by cyrus-and** [comment]
You just need to specify the right values, for example to simulate a click event you'll need to dispatch two separate events:

```js
function click(x, y) {
    const options = {
        x: x,
        y: y,
        button: 'left',
        clickCount: 1
    };

    options.type = 'mousePressed';
    Input.dispatchMouseEvent(options);

    options.type = 'mouseReleased';
    Input.dispatchMouseEvent(options);
}
```

PS you're welcome!

**Comment by zirill** [comment]
do not click on andoid

**Comment by cyrus-and** [comment]
Just tried and works, here's the test page:

```html
<body>
  <script>
    const body = document.querySelector('body');
    body.addEventListener('click', (e) => {
        alert(`${e.clientX}, ${e.clientY}`);
    });
  </script>
</body>
```

**Comment by cyrus-and** [comment]
FYI [here][1]'s the wiki example using promises.

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Trigger-synthetic-click-events

**Comment by zirill** [comment]
i click on mobail screen no show alert

**Comment by cyrus-and** [comment]
I really don't know, it works with Chrome 54 on my Nexus 5. In any case I doubt it's a problem with this module. Try to debug the client-side JavaScript code.

**Comment by zirill** [comment]
i work in changed on addEventListener('touchend'
chrom 54 andoid 6

**Comment by zirill** [comment]
I have worked in this way:
function click(cri, x, y) {
    const options = {
        touchPoints: [{x:x,y:y, state:'touchPressed'}]
    };


    options.type = 'touchStart';
    cri.Input.dispatchTouchEvent(options, function (e,p) {
        console.log(e,p);
    });

    options.touchPoints[0].state = 'touchReleased';
    options.type = 'touchEnd';
    cri.Input.dispatchTouchEvent(options);
}

**Comment by zirill** [comment]
help position mouse in chage page (big grey border)

```
                    chrome.Page.setDeviceMetricsOverride({
                        width: 320,
                        height: 240,
                        deviceScaleFactor: 3,
                        mobile: true,
                        emulateViewport: true,
                        fitWindow: true
                    });
```

Home moves to the center of the screen, and coordinate the eyes remain the same. how to move the grid coordinates or to define the beginning of the axis on the page?

**Comment by cyrus-and** [comment]
You should try to ask this in the [Google Group]; it's a bit off-topic here and I've never experimented too much with `Page.setDeviceMetricsOverride`.

[Google Group]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol
