### ISSUE TITLE
Specify which tab should CRI should attach to

### ISSUE THREAD

**Issue by dwcIntegral** [cyrus-and/chrome-remote-interface#69]
Hey there, 

I am working on a performance monitoring tool using CRI that opens a _new instance_ of the Chrome browser with the remote debugging server on (while a normal Chrome browser is already running, remote debugging server off).

The issue I am currently having is connecting CRI commands to work with this new Chrome instance.

When I visit "http://localhost:9222/json" on this new Chrome instance I can see:

```
[ {
   "description": "",
   "id": "a07cbe89-d7fb-4e95-aadd-56066bfaeb89",
   "thumbnailUrl": "/thumb/a07cbe89-d7fb-4e95-aadd-56066bfaeb89",
   "title": "",
   "type": "page",
   "url": "http://localhost:9222/json"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/a86979c7-454c-46d1-907f-a315124bf2eb",
   "id": "a86979c7-454c-46d1-907f-a315124bf2eb",
   "title": "chrome-devtools://devtools/bundled/inspector.html?&amp;remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@8ee402c67ff2f8f7c746e56d3530b4dcec0709ad/&amp;can_dock=true&amp;dockSide=undocked",
   "type": "other",
   "url": "chrome-devtools://devtools/bundled/inspector.html?&remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@8ee402c67ff2f8f7c746e56d3530b4dcec0709ad/&can_dock=true&dockSide=undocked",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/a86979c7-454c-46d1-907f-a315124bf2eb"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/63e44b17-beb7-4222-a8ae-ef9be47eb871",
   "faviconUrl": "chrome://extension-icon/pkedcjkdefgpdelpbcmbmeomcjbeemfm/24/1",
   "id": "63e44b17-beb7-4222-a8ae-ef9be47eb871",
   "title": "Chrome Media Router",
   "type": "background_page",
   "url": "chrome-extension://pkedcjkdefgpdelpbcmbmeomcjbeemfm/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/63e44b17-beb7-4222-a8ae-ef9be47eb871"
} ]
```
And using CDP.List I can return the tab list which looks something like:

```
[ { description: '',
    devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:9222/devtools/page/a07cbe89-d7fb-4e95-aadd-56066bfaeb89',
    id: 'a07cbe89-d7fb-4e95-aadd-56066bfaeb89',
    thumbnailUrl: '/thumb/a07cbe89-d7fb-4e95-aadd-56066bfaeb89',
    title: 'localhost:9222/json',
    type: 'page',
    url: 'http://localhost:9222/json',
    webSocketDebuggerUrl: 'ws://localhost:9222/devtools/page/a07cbe89-d7fb-4e95-aadd-56066bfaeb89' },
  { description: '',
    devtoolsFrontendUrl: '/devtools/inspector.html?ws=localhost:9222/devtools/page/a86979c7-454c-46d1-907f-a315124bf2eb',
    id: 'a86979c7-454c-46d1-907f-a315124bf2eb',
    thumbnailUrl: '/thumb/a86979c7-454c-46d1-907f-a315124bf2eb',
    title: 'Performance Monitoring Test Page',
    type: 'other',
    url: 'http://localhost:8080/performance-test',
    webSocketDebuggerUrl: 'ws://localhost:9222/devtools/page/a86979c7-454c-46d1-907f-a315124bf2eb' } ]
```
I then have manually started CRI with each of the webSocketDebuggerUrls listed above to see if I could connect to this new Chrome instance (something like the below):

```
var Chrome = require('chrome-remote-interface');

Chrome({
	tab: 'ws://localhost:9222/devtools/page/a86979c7-454c-46d1-907f-a315124bf2eb'
}, function(chrome) {

var page = chrome.Page;
var network = chrome.Network;

page.enable();
network.enable();

network.responseReceived(function(response) {
  console.log(response);
});

page.navigate('http://www.google.com');

}).on('error', (err) => {
    console.error('Cannot connect to remote endpoint:', err);
});
```

But I still could not connect to this instance. Any ideas on how to connect and send commands to this new Chrome instance running the remote debugging server?

Also Note: On this new chrome browser instance if I create a new tab, and then close it, everything works as expected on the first tab that was open. This is my current solution to get things to work, but ideally would like to get things to work in  a less hacky manner.

Thanks for any input you can provide here !

**Comment by cyrus-and** [comment]
Hey, I'm afraid I'm not fully understanding your issue here. 

Chrome instances launched without the `--remote-debugging-port` flag are simply ignored so CRI is just aware of your second instance.

> I then have manually started CRI with each of the webSocketDebuggerUrls listed above to see if I could connect to this new Chrome instance

What does the error message say?

Also, remember that the [`tab`][1] option accepts different types of values.

[1]: https://github.com/cyrus-and/chrome-remote-interface#cdpoptions-callback

**Comment by dwcIntegral** [comment]
Hey @cyrus-and ,

Sorry about this, please feel free to close this issue, I now have this working as expected. I am passing in the `webSocketDebuggerUrl` for the `tab` option and seeing expected results.

Thanks again for the quick response here.
