### ISSUE TITLE
consider rejecting with instances of Error

### ISSUE THREAD

**Issue by Janpot** [cyrus-and/chrome-remote-interface#70]
It seems generally accepted as good practice to only use instances of `Error` as rejections when using promises. (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject)

Would you mind having this in your library. I don't mind contributing this.

**Comment by cyrus-and** [comment]
Well, it should already be like this, if it is not it means that it should be fixed.

I quickly double-checked all the rejects and it seems that the only one which returns a non-`Error` object is [here][1]. But in this case I need to return a complex protocol object, simply converting it to string and putting it into an `Error` object as a message doesn't feel right:

> message Optional. Human-readable description of the error.

What do you think?

Have you spotted any other instances?

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/9b9e14c85c266a31d1e06d5f1487524374f14dee/lib/chrome.js#L51

**Comment by Janpot** [comment]
I had it on `.Network.getResponseBody()` when I used an invalid `requestId`. But I guess that just delegates to the `.send` command.

Depending on the platforms you support, doing a simple

```js
var error = new Error(rawError.message);
Object.assign(error, rawError);
```

should be all that's necessary

**Comment by cyrus-and** [comment]
I like the idea of having a `ProtocolError` which takes the `response` object and inherits its properties. This also has the nice side-effect that the `message` property is automatically assigned. AFAIK the error object returned by Chrome is not documented anywhere, but it seems that the `code` and the `message` fields are always present, so I think it's a reasonable assumption...

Feel free to send me a PR if you want. In any case thanks!
