### ISSUE TITLE
Cannot connect to Chrome

### ISSUE THREAD

**Issue by ali-bugdayci** [cyrus-and/chrome-remote-interface#73]
Getting the following error:

Cannot connect to Chrome [Error: unknown command: json/list]

Chrome version: Version 51.0.2704.106 (64-bit)

Since we are using node v.0.12 I stay at the following version. Could this be the cause ?

chrome-remote-interface "version": "0.15.1",

**Comment by cyrus-and** [comment]
I don't think it could be the cause of `Error: unknown command: json/list`, but the minimum required version of Node.js is 4.

Anyway, can you show me a minimal script that reproduces this issue?

**Comment by ali-bugdayci** [comment]
Node 4 is required for version 16 and above.

I tested with 0.15 to 0.10 and getting the same error.

The script I test it is:

```
var Chrome = require('chrome-remote-interface');
var connectCrome = function(port){
  Chrome({port: port},function (chrome) {
          with (chrome) {
              Page.enable();
              global.mainProfiler = Profiler;

              Profiler.enable();
              Profiler.consoleProfileFinished(function (params) {
                  // CPUProfile object (params.profile) described here:
                  //    https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/devtools/protocol.json&q=protocol.json%20%22CPUProfile%22,&sq=package:chromium

                  // Either:  1. process the data however you wish… or,
                  //          2. Use the JSON file, open Chrome DevTools, Profiles tab, select CPU Profile radio button,
                  //             click `load` and view the profile data in the full devtools UI.
                  var file = 'profile-' + Date.now() + '.cpuprofile';
                  var data = JSON.stringify(params.profile);
                  fs.writeFile(file, data);
                  close();
              });
          }
      }).on('error', function(e){
        console.error('Cannot connect to Chrome', e);
      })
}
```

Thx in advance

**Comment by ali-bugdayci** [comment]
Getting same error with node v4.4.5 with chrome-remote-interface 0.17 (latest)

Cheking if chromedriver is working on the port I run:

```
> netstat -plnt | grep 'chromedriver' 
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:57650         0.0.0.0:*               LISTEN      15553/chromedriver
```

So I run it with: connectCrome(57650)

**Comment by cyrus-and** [comment]
Oh now it's clear! This module is not a WebDriver client, this is a [Chrome Debugging Protocol] client and it is supposed to communicate with Chrome directly (port 9222 by default) when it is started as:

    google-chrome --remote-debugging-port=9222

[Chrome Debugging Protocol]: https://developer.chrome.com/devtools/docs/debugger-protocol

**Comment by ali-bugdayci** [comment]
Oh thanks in advance
