### ISSUE TITLE
Dispatching mouse events after Page.loadEventFired

### ISSUE THREAD

**Issue by locovich** [cyrus-and/chrome-remote-interface#74]
This is not an issue report, but a help request. I'm new to node, sorry if is a stupid question.

What I'm trying to achieve is to have the node client dispatch some mouse events in intervals, after a Page.navigate returns the load event.

The issue I'm having is that when trying to dispatch those events using:

```
function clickDown(){
        options.type = 'mousePressed';
        return client.Input.dispatchMouseEvent(options);        
}
function clickUp(){
        options.type = 'mouseReleased';
        console.log("Click release mouse");
        var res = client.Input.dispatchMouseEvent(options);
        return res;
}
function moveMouse(){
        options.type = 'mouseMoved';
        options.x = 5;
        options.y = 10;
        options.clickCount = 0;
        options.button = 'none';
        console.log("Moving mouse to x: " + options.x + ", and y: " + options.y);
        return client.Input.dispatchMouseEvent(options);
}

Page.loadEventFired(() => {
	console.log("loadEventFired");
        var interval = setInterval(() => {
            moveMouse();
            clickDown();
            clickUp();
            console.log("end interval");
        }, 1000);
        setTimeout(function(){
            client.close();
            clearInterval(interval);
            console.log("closed client");
        }, 10000);
    });

Promise.all([
        Network.enable(),
        Page.enable()
]).then(() => {
        return Page.navigate({url: 'http://www.mytestpage.com'});
}.catch((err) => {
        console.error(err);
});
```

the event is not processed in the testing page (attached an click listener to body).

BUT, if I run the dispatch functions IN the promise->then structure, then they are sometimes correctly processed in the browser (when the load of the page is quick enough I guess).

This works sometimes:

```
    Promise.all([
        Network.enable(),
        Page.enable()
    ]).then(() => {
        return Page.navigate({url: 'http://www.mytestpage.com'});
    }).then(() => {
        options.type = 'mousePressed';
        return client.Input.dispatchMouseEvent(options);
    }).then(() => {
        options.type = 'mouseReleased';
	return client.Input.dispatchMouseEvent(options);
    }).catch((err) => {
        console.error(err);
    });
```

Since my guess is the page is not ready, I'd like to find a way to hold the event dispatches until the page is fully rendered. How can I do that?

Any help will be appreciated.

**Comment by cyrus-and** [comment]
No worries! The first version is the correct one as you have to wait for the `Page.loadEventFired` event. But in this case only `mousemove` events are delivered because you specify no buttons. Try this:

```js
options.clickCount = 1;
options.button = 'left';
```

If that doesn't solve your problem, show me the full JavaScript and HTML test page so I can try to reproduce the issue in the same scenario as yours.

**Comment by locovich** [comment]
Ah! My bad. Thanks for pointing that out.
Corrected it and is working perfectly now.

**Comment by cyrus-and** [comment]
You're welcome!
