### ISSUE TITLE
question on rewrite url or cancel the request entry?

### ISSUE THREAD

**Issue by c0b** [cyrus-and/chrome-remote-interface#75]
this could be a question to upstream chrome developers, but wonder if here anyone tried to rewrite a request url? from the debugger protocol viewer I don't find such an API:

https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#event-requestWillBeSent

the use scenario is for some automation testing, we're driving a chrome to test a target web page, before calling `Page.navigate`, I know we can register proper callbacks on `Network.requestWillBeSent`, to catch all the network request entries, but this callback seems like a callback to get information only, what I want to do is to change the request entry partially, like to rewrite the entry url, or cancel it, all programmatically based on some testing rules; steps like

1. use chrome-remote-interface to drive a chrome open a page, like https://www.nytimes.com
2. this website will load some same site scripts / css / imgs, also some third party scripts / css / imgs
3. we want to simulate to know how does the page behaves when some third party sites failed, or when some third party scripts have additional parameters we want to rewrite net entry url on the fly, or block some urls on the runtime
 I have seen this https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-addBlockedURL but it seems required to be called before start `Page.navigate` ?

I'm not sure if it has the features or we can redirect these questions to chrome developers, all these features can make it much stronger programmability, for automation software

**Comment by cyrus-and** [comment]
That would be a great feature to have, but I'm pretty sure that can't be done using the CDP and this module is just an interface for it.

Apart from `addBlockedURL` (which yes I think it must be called *before*) other interesting methods are:

- Network.setUserAgentOverride
- Network.setExtraHTTPHeaders
- Network.setCookie
- Network.emulateNetworkConditions (with the `offline` option)

But they all are far from providing the granularity you need. I'm afraid that your best chance is to write an auxiliary Chrome extension for that, see [chrome.webRequest][1].

Anyway, I suggest you to ask this in the [Google Group][2].

[1]: https://developer.chrome.com/extensions/webRequest
[2]:https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by c0b** [comment]
thanks; that is a great answer; I am aware of the methods on Network you mentioned those indeed work as described, but they're working at page level, does not support on per net entry granularity, like set extra header on a single particular network entry only; so will request the feature on the `chrome-debugging-protocol` group is better.
