### ISSUE TITLE
Questions: get HTML, cancel requests, proxy, cookies/session

### ISSUE THREAD

**Issue by voidmonk** [cyrus-and/chrome-remote-interface#76]
Hi, I'm trying out `chrome-remote-interface` with Chrome (headless shell) using Node.js. I have a few questions:

1. How can I get the full HTML (doctype + markup, as string) of a tab/page, once loading has finished?

2. Is it possible to trace and programmatically cancel some network requests (e.g. all CSS files) of a tab/page?

3. Is it possible to specify a proxy per tab? I'm guessing there can only be one proxy assigned per instance (through a Chrome command line argument).

4. How can I configure a non-persistent isolated cookies & session container per tab/instance?

Hoping for some tips. Thanks!

**Comment by cyrus-and** [comment]
> How can I get the full HTML (doctype + markup, as string) of a tab/page, once loading has finished?

You can get the *first request* HTML with [Network.getResponseBody]. To fetch the DOM once the page is loaded ([Page.loadEventFired] event) I'm afraid you'll have to walk all the nodes and build the string manually. Another option might be injecting ([Runtime.evaluate]) some JavaScript code, like:

```js
document.documentElement.outerHTML
```

In any case you might have problem with frames.

[Network.getResponseBody]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-getResponseBody

[Page.loadEventFired]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Page/#event-loadEventFired

[Runtime.evaluate]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate

> Is it possible to trace and programmatically cancel some network requests (e.g. all CSS files) of a tab/page?

You can trace (see the [main example][1]), but you cannot block requests AFAIK (see #75).

[1]: https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage

> Is it possible to specify a proxy per tab? I'm guessing there can only be one proxy assigned per instance (through a Chrome command line argument).

Not that I'm aware of.

> How can I configure a non-persistent isolated cookies & session container per tab/instance?

You could use [Target.createBrowserContext]. Never experimented with browser contexts though...

[Target.createBrowserContext]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Target/#method-createBrowserContext

**Comment by cyrus-and** [comment]
Hope that helps, I'm closing this but feel free to comment if you have any other questions.

**Comment by voidmonk** [comment]
Thanks @cyrus-and.
