### ISSUE TITLE
Get image natural size

### ISSUE THREAD

**Issue by gyscos** [cyrus-and/chrome-remote-interface#78]
Hi!
In the chrome dev tools, when looking at an image resource, I can see the natural size of this image (corresponding the the `naturalWidth` and `naturalHeight` properties of the element).

![screenshot from 2017-01-25 16-19-44](https://cloud.githubusercontent.com/assets/564903/22315226/4e4dafd8-e31a-11e6-8e0b-73b98f799430.png)

However, I cannot find a way to get this information here. Do I have to re-parse the resource body to get this information? Or is there an easier way?
Thanks!

**Comment by cyrus-and** [comment]
Hi!

To answer this kind of questions is sometimes useful to [inspect the inspector][1] (see "Sniffing the protocol", the anchor is broken). Here's what I found...

Request:

```json
{
    "id": 304,
    "method": "Runtime.callFunctionOn",
    "params": {
        "objectId": "{\"injectedScriptId\":11,\"id\":1}",
        "functionDeclaration": "function features()\n{return{offsetWidth:this.offsetWidth,offsetHeight:this.offsetHeight,naturalWidth:this.naturalWidth,naturalHeight:this.naturalHeight,currentSrc:this.currentSrc};}",
        "silent": true,
        "returnByValue": true,
        "generatePreview": false
    }
}
```

Response:

```json
{
    "id": 304,
    "result": {
        "result": {
            "type": "object",
            "value": {
                "offsetWidth": 252,
                "offsetHeight": 150,
                "naturalWidth": 252,
                "naturalHeight": 150,
                "currentSrc": "https://cloud.githubusercontent.com/assets/564903/22315226/4e4dafd8-e31a-11e6-8e0b-73b98f799430.png"
            }
        }
    }
}
```

So in short DevTools simply calls a JavaScript on the given object:

```js
function features() {
    return {
        offsetWidth: this.offsetWidth,
        offsetHeight: this.offsetHeight,
        naturalWidth: this.naturalWidth,
        naturalHeight: this.naturalHeight,
        currentSrc: this.currentSrc
    };
}
```

Hope it helps!

[1]: https://developer.chrome.com/devtools/docs/debugger-protocol

**Comment by gyscos** [comment]
Awesome, thank you very much!
