### ISSUE TITLE
Disable images, and get response headers

### ISSUE THREAD

**Issue by voidmonk** [cyrus-and/chrome-remote-interface#81]
Hi, is there a way to disable download & display of images, plugins, fonts etc., through this interface/protocol or a Chrome command line switch maybe? I read about a `-disable-images` switch in some places, but it doesn't seem to have any affect.

**Comment by voidmonk** [comment]
Figured it can be done with a [policy](https://www.chromium.org/administrators/policy-templates).

Other thing is how to get the response headers using the sample API usage code in this repo? For some odd reason, `Network.Response.headers` (as per the [protocol viewer](https://chromedevtools.github.io/debugger-protocol-viewer/1-2/Network/#type-Response)) returns `undefined`.

**Comment by cyrus-and** [comment]
`Network.Response` (literally) is just the `Response` type representation, it's mainly used for help purposes. What you really want is to get the `headers` property of the `response` property of the object returned by the `Network.responseReceived` event. So:

```js
Network.responseReceived((params) => {
    console.log(params.response.headers);
});
```

instead of:

```js
Network.requestWillBeSent((params) => {
    console.log(params.request.url);
});
```

**Comment by vvo** [comment]
Is there another way than policies (which I did not get how to use) to disable downloading of everything BUT the HTML page? Basically use chrome remote interface only for DOM interpretation for now.

**Comment by cyrus-and** [comment]
@vvo you could use [`Network.setBlockedURLs`] but it's not a great solution. AFAIK there's no other protocol method.

> which I did not get how to use

@voidmonk I too would be interested, can you show us what you come up with?

[`Network.setBlockedURLs`]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-setBlockedURLs

**Comment by voidmonk** [comment]
I've been using `Network.addBlockedURL` to block images, but looks like it has been replaced with `Network.setBlockedURLs` (not sure since when).
