### ISSUE TITLE
Cannot use `Tracing.start` with PhantomJS?

### ISSUE THREAD

**Issue by joelalejandro** [cyrus-and/chrome-remote-interface#85]
I've attempted to use `chrome-remote-interface` with PhantomJS 2.1.1 in order to integrate it with [`speedline`](https://github.com/pmdartus/speedline) + [`devtools-timeline-model`](https://github.com/paulirish/devtools-timeline-model) to perform a CI-enabled Speed Index check.

However, I'm getting the following error:

```
(node:40632) UnhandledPromiseRejectionWarning: Unhandled promise rejection
  (rejection id: 1): 
  Error: 'Tracing.start' wasn't found
```

[I've filed an issue on PhantomJS as well.](https://github.com/ariya/phantomjs/issues/14872) I don't know if `chrome-remote-interface` has been tested against it, but since it has support for the CRP via Web Sockets, I thought it was fully available.

Maybe it's related to #84, since PhantomJS is headless?

**Comment by cyrus-and** [comment]
It seems that the protocol exposed by PhantomJS doesn't support the `Tracing.start` method. By default chrome-remote-interface uses the bundles [`protocol.json`][1] which is taken from the Chromium repo. For some [implementations][2] it's possible to fetch that protocol from the implementation directly (see the "Protocol" column).

PhantomJS doesn't seem to document the methods available via its protocol. Something works something doesn't:

```
>>> Network.enable()
{ result: {} }
>>> Network.requestWillBeSent(params => params.request.url)
{ 'Network.requestWillBeSent': 'params => params.request.url' }
>>> Page.navigate({url: 'http://example.com'})
{ 'Network.requestWillBeSent': 'http://example.com/' }
{ result: {} }
>>> Tracing.start()
{ error: { code: -32601, message: '\'Tracing.start\' wasn\'t found' } }
>>> Profiler.enable()
{ result: {} }
>>> HeapProfiler.enable()
{ error: 
   { code: -32601,
     message: '\'HeapProfiler.enable\' wasn\'t found' } }
```

You just need to figure out the methods that are supported by PhantomJS.

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/master/lib/protocol.json
[2]: https://github.com/cyrus-and/chrome-remote-interface#implementations

> Maybe it's related to #84, since PhantomJS is headless?

No that issue solely concern Google Chrome/ium.

**Comment by joelalejandro** [comment]
@cyrus-and A few hours and lines of code later, I found out that the protocol exposed by PhantomJS works differently when connected via Web Sockets. When hooking up to `ws://localhost:9222/devtools/browser`, the `Tracing.start()` method does work, but now I'm having trouble with the `Page.loadEventFired()` not being triggered. 😢

**Comment by cyrus-and** [comment]
AFAIK `ws://localhost:9222/devtools/browser` is a special target which can be used to create and manage [Target][1]s (albeit it doesn't quite work with PhantomJS).

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Target/

This works though:

```
$ chrome-remote-interface inspect -w ws://localhost:9222/devtools/page/1
>>> Page.enable()
{ result: {} }
>>> Page.loadEventFired()
{ 'Page.loadEventFired': true }
>>> Page.navigate({url: 'http://example.com'})
{ result: {} }
{ 'Page.loadEventFired': { timestamp: 1488806508.278981 } }
```

**Comment by joelalejandro** [comment]
\*sigh\* Guess I won't be having both methods in the same target. `/devtools/page/1` doesn't have Tracing but Page.loadEventFired works, `/devtools/page/browser` exactly the other way around.

**Comment by cyrus-and** [comment]
I'm afraid that's not the case, `Tracing.start()` from `ws://localhost:9222/devtools/browser` simply does nothing (bug?), it should return *something*, like:

```
>>> Tracing.start()
{ result: {} }
```

**Comment by cyrus-and** [comment]
So, I'm closing this as it is about PhantomJS and its (not) exposed protocol. Feel free to provide additional details if you manage to get it to work.

**Comment by joelalejandro** [comment]
Thanks a lot for all the valuable info! :)
