### ISSUE TITLE
How to submit post request with chrome-remote-interface?

### ISSUE THREAD

**Issue by Candunc** [cyrus-and/chrome-remote-interface#86]
I've looked through both the wiki here as well as the [chrome debugging protocol](https://chromedevtools.github.io/debugger-protocol-viewer/tot/), however I cannot figure out how to send a post request. It has something to do with the [Request object](https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#type-Request), but I'm unsure how to relate that into the Page.navigate function. 

Is there some documentation I'm missing, or some example code?

**Comment by cyrus-and** [comment]
I don't think the protocol allows to submit arbitrary POST requests (yet it can intercept them). What you can do is to [inject][1] some JavaScript code in the page and use the [XMLHttpRequest API][2] to perform the request.

The Network.Request object is used by the protocol to represent a previously intercepted request.

Also relevant: [Network.replayXHR][3]

[1]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Runtime/#method-evaluate
[2]: https://developer.mozilla.org/en-US/docs/AJAX
[3]: https://chromedevtools.github.io/debugger-protocol-viewer/tot/Network/#method-replayXHR

**Comment by Candunc** [comment]
Alright, thank you for the quick response! I will look into injecting a post request, rather than explicitly attempting it through the protocol.

**Comment by cyrus-and** [comment]
You're welcome!
Remember that there's also a [Google Group][1] for protocol-related questions.

[1]: https://groups.google.com/forum/#!forum/chrome-debugging-protocol

**Comment by LucianoGanga** [comment]
Hi! 
I am making a module with some functions that works thanks to this module (you can check it here if you want to see full code: https://github.com/LucianoGanga/simple-headless-chrome). 

The thing is that I already implemented a method to do the POST, but I don't know how to convert it in an async call, so I can wait it until it finishes and return the request response directly when the POST method is called :( 

This is what I've got until now: 
`js
/**
 * Post data from the browser context
 * @param {string} url - The URL or path to POST to
 * @param {object} [data] - The data object to be posted
 * @param {object} [options] - Options of the request
 * @return {object} - Request status and data
 */
exports.post = async function (url, data = {}, options = {}) {
  debug(`:: post => Posting on URL "${url}" data: ${JSON.stringify(data, null, 2)} with options ${options}...`)

  if (!url) {
    throw new Error(`An URL must be supplied in order to make the POST request`)
  }

  let requestData = data
  if (typeof data === 'object') {
    requestData = objectToEncodedUri(data)
  }

  const requestOptions = Object.assign({
    contentType: 'application/x-www-form-urlencoded',
    timeout: this.options.loadPageTimeout
  }, options)

  return this.evaluate(function (url, data, options) {
    const xhr = new XMLHttpRequest()
    xhr.open('POST', url)
    xhr.setRequestHeader('Content-Type', options.contentType)
    xhr.onload = function () {
      if (xhr.status === 200) {
        alert('Done! status 200: ' + xhr.responseText)
      } else if (xhr.status !== 200) {
        alert('Request failed. Returned status: ' + xhr.status)
      }
    }
    data ? xhr.send(data) : xhr.send()
  }, url, requestData, requestOptions)
}
`

Any idea on how can I accomplish this? 

Thanks! 
Luciano

**Comment by cyrus-and** [comment]
@LucianoGanga `Runtime.evaluate` is able to await a `Promise`, just change your browser code in order to return one and call it with `awaitPromise: true`. Something like:

```js
return this.client.Runtime.evaluate({
  expression: exp,
  returnByValue: true,
  awaitPromise: true
})
```

```js
return evaluate.call(this, function (url, data, options) {
  return new Promise(function (fulfill, reject) {
    const xhr = new XMLHttpRequest()
    xhr.open('POST', url)
    xhr.setRequestHeader('Content-Type', options.contentType)
    xhr.onload = function () {
      if (xhr.status === 200) {
        fulfill(xhr.responseText)
      } else {
        reject(xhr.status)
      }
    }
    data ? xhr.send(data) : xhr.send()
  })
}, url, requestData, requestOptions)
```
