### ISSUE TITLE
Having trouble connecting debugger to Chrome background page

### ISSUE THREAD

**Issue by gsingh93** [cyrus-and/chrome-remote-interface#87]
Hey, I'm having some trouble connecting to a Chrome background page with this extension. For normal scripts, I can simply put `debugger;` at the top of the JavaScript, and then I open the tab using `CDP.New` and the debugger connects. However, when I do something similar where the JavaScript is in the background page for a Chrome extension, the debugger never connects. I'm using `Debugger.paused` to check for this connect.

Do you know if this is a limitation with Chrome itself, your library, or am I just using the library incorrectly?

**Comment by cyrus-and** [comment]
Well it seems that it works for me, here's what I tried.

`manifest.json`:

```json
{
    "manifest_version": 2,
    "name": "Test",
    "version": "0.0.0",
    "background": {
        "scripts": ["/background.js"]
    }
}
```

`background.js`:

```js
setInterval(() => {
    document.write(1);
    debugger;
    document.write(2);
}, 1000);
```

Manually load this extension then:

1. `chrome-remote-interface list` to fetch the background page id;

2. `chrome-remote-interface inspect 9cf26183-e0b1-410f-bc4d-e6bc98802a5d` to inspect it;

3. register the event and enable the debugger:

        >>> Debugger.paused()
        { 'Debugger.paused': true }    # event registered
        >>> Debugger.enable()
        { result: {} }
        { 'Debugger.paused': 
           { callFrames: 
        [...]

I think the trick here is to ensure that the background script hits the `debugger` statement while the debugger is active. In particular if you use event pages (`"persistent": false`) remember that Chrome will disable a page if it is inactive for a certain time.

Anyway if you attach to a background page and you miss the `debugger` statement you can always reload the extension without losing the connection.

**Comment by gsingh93** [comment]
Thanks for looking into this! I swear I tried `setInterval`/`setTimeout`, but I must have made a mistake.

**Comment by cyrus-and** [comment]
No worries! :)
