### ISSUE TITLE
Not getting callbacks for Profiler.stop and start

### ISSUE THREAD

**Issue by edaena** [cyrus-and/chrome-remote-interface#9]
I'm using this framework to get data from the profiler but whenever I send Profiler.stop and Profiler.start my callback functions don't get called. 

Example:
chrome.send('Profiler.stop', function(){console.log("Stop concluded.");});

**Comment by cyrus-and** [comment]
@edaena FYI: This should work on latest versions of Chrome; you may also be interested in [this document](https://github.com/paulirish/automated-chrome-profiling).
