### ISSUE TITLE
Removing event subscriptions?

### ISSUE THREAD

**Issue by devnill** [cyrus-and/chrome-remote-interface#93]
When subscribing to an event (such as  HeapProfiler.reportHeapSnapshotProgress()), it will continue to be called even if multiple callbacks are registered. Is there a way to either remove an old subscription or replace it with a new one?

**Comment by cyrus-and** [comment]
Since:

```js
client.HeapProfiler.reportHeapSnapshotProgress(foo)
```

 is a [shorthand] for:

```js
client.on('HeapProfiler.reportHeapSnapshotProgress', foo)
```

You can use the usual [Node.js events API] to manage the listeners, specifically:

```js
client.removeAllListeners('HeapProfiler.reportHeapSnapshotProgress')
client.removeListener('HeapProfiler.reportHeapSnapshotProgress', foo)
```

[shorthand]: https://github.com/cyrus-and/chrome-remote-interface#event-domainmethod
[Node.js events API]: https://nodejs.org/api/events.html
