### ISSUE TITLE
Are all API calls sending back Promises?

### ISSUE THREAD

**Issue by vvo** [cyrus-and/chrome-remote-interface#94]
Are all API calls of https://chromedevtools.github.io/debugger-protocol-viewer/tot/ available via chrome-remote-interface sending back Promises?

I guess it may be the case but did not find somewhere in the documentation where we clearly state it.

BTW, this is an awesome project :)

**Comment by cyrus-and** [comment]
Hey thanks!

Yes they are. The debugger-protocol-viewer describes the *on-the-wire* JSON protocol whereas the JavaScript API is totally up to this module and supports both callbacks and promises. See the documentation of [`client.send(method, [params], [callback])`][1]:

> When callback is omitted a Promise object is returned instead, with the fulfilled/rejected states implemented according to the error parameter.

Please note that event registration, e.g., `client.Network.requestWillBeSent(console.log);`, even though it's a function call accepting a callback, does not returns a promise.

[1]: https://github.com/cyrus-and/chrome-remote-interface#clientsendmethod-params-callback
