### ISSUE TITLE
New tab official example not working for headless mode

### ISSUE THREAD

**Issue by jdat82** [cyrus-and/chrome-remote-interface#96]
I must have missed something but executing the official example for creating a new tab in headless mode doesn't work for me:

```js
const CDP = require('chrome-remote-interface');

CDP.New().then((tab) => {
    return CDP({tab: tab});
}).then((client) => {
    return client.Runtime.evaluate({
        expression: 'alert("Closing this tab...")'
    }).then(() => {
        const tab = client.chooseTab;
        return CDP.Close({id: tab.id});
    });
}).catch((err) => {
    console.error(err);
});
```

I get: `Error: Could not create new page`

I tried with the command line: `chrome-remote-interface new http://www.ingdirect.fr`. Same error.

I'm executing Chrome on Ubuntu. I customized the IP on which chrome listen but I tried with the default (localhost) and I observed same results.

Regarding the command line, `inspect` and `list` works. But not `new` nor `close`.

```bash
[ { description: '',
    devtoolsFrontendUrl: '/devtools/inspector.html?ws=192.168.1.44:9222/devtools/page/49db60ac-cc96-4e0f-bba2-7403f40a82bf',
    id: '49db60ac-cc96-4e0f-bba2-7403f40a82bf',
    title: 'about:blank',
    type: 'page',
    url: 'about:blank',
    webSocketDebuggerUrl: 'ws://192.168.1.44:9222/devtools/page/49db60ac-cc96-4e0f-bba2-7403f40a82bf' } ]
```

I'm using the latest version of node and CRI:

```bash
 npm ls -g --depth=0
/home/jon/.nvm/versions/node/v7.9.0/lib
├── chrome-remote-interface@0.18.0
└── npm@4.2.0
```

**Comment by cyrus-and** [comment]
There's a note about the [headless] version:

> Please note that currently the DevTools methods are not properly supported in headless mode; use the Target domain instead. See #83 and #84 for more information.

It will be fixed in Chrome 59, you can use the `google-chrome-unstable` Ubuntu package.

[headless]: https://github.com/cyrus-and/chrome-remote-interface#headless

**Comment by jdat82** [comment]
OK good to know. Saw that but thought DevTools was a domain. Thanks.

**Comment by jdat82** [comment]
Switching to Chrome 59 unstable resolved several issues I had including creating a new tab.

**Comment by pthieu** [comment]
@jdat82 what OS are you on?

**Comment by jdat82** [comment]
The chrome server was on Ubuntu and the client script on a Mac. Can't wait to get rid of Linux for chrome headless.

**Comment by skaliber** [comment]
@cyrus-and I cant get new tab working using headless 
I tried debian and ubuntu docker image 
I tried with a selenium click and running java script to perform the click action for the link that is supposed to open a new tab but it doesnt open 

Im using chromedriver 2.3 and google chrome stable 61 and google chrome unstable 63 still doesnt work 

can you give me any suggestions how can I get it work ?

**Comment by cyrus-and** [comment]
@skaliber if it's ChromeDriver-related then you may want to take a look at #265, otherwise please file a new issue with all the details.
